"""Release-governance gate owner constants."""

from __future__ import annotations

DISTRIBUTION_CREDIBILITY_GATE_ID = "distribution-credibility"
PACKAGING_CHANNELS_GATE_ID = "packaging-channels"
PUBLIC_CONFORMANCE_REPORTING_GATE_ID = "public-conformance-reporting"
RELEASE_FOUNDATION_GATE_ID = "release-foundation"
RELEASE_OPERATIONS_GATE_ID = "release-operations"
SECURITY_HARDENING_GATE_ID = "security-hardening"

RELEASE_GATE_IDS: tuple[str, ...] = (
    RELEASE_FOUNDATION_GATE_ID,
    PACKAGING_CHANNELS_GATE_ID,
    RELEASE_OPERATIONS_GATE_ID,
    PUBLIC_CONFORMANCE_REPORTING_GATE_ID,
    DISTRIBUTION_CREDIBILITY_GATE_ID,
    SECURITY_HARDENING_GATE_ID,
)

__all__ = [
    "DISTRIBUTION_CREDIBILITY_GATE_ID",
    "PACKAGING_CHANNELS_GATE_ID",
    "PUBLIC_CONFORMANCE_REPORTING_GATE_ID",
    "RELEASE_FOUNDATION_GATE_ID",
    "RELEASE_GATE_IDS",
    "RELEASE_OPERATIONS_GATE_ID",
    "SECURITY_HARDENING_GATE_ID",
]
