             surface.deterministic_type_boundary_summary_readiness_record &&
         IsReadyObjc3SemaTypeBoundarySummaryReadinessRecord(
             surface.type_boundary_summary_readiness_record) &&
         surface.deterministic_module_type_abi_summary_readiness_record &&
         IsReadyObjc3SemaModuleTypeAbiSummaryReadinessRecord(
             surface.module_type_abi_summary_readiness_record) &&
         surface.deterministic_module_boundary_summary_readiness_record &&
         IsReadyObjc3SemaModuleBoundarySummaryReadinessRecord(
             surface.module_boundary_summary_readiness_record) &&
         surface.deterministic_intermodule_flow_summary_readiness_record &&
         IsReadyObjc3SemaIntermoduleFlowSummaryReadinessRecord(
             surface.intermodule_flow_summary_readiness_record) &&
         surface.deterministic_concurrency_parity_publication_readiness_record &&
         IsReadyObjc3SemaConcurrencyParityPublicationReadinessRecord(
             surface.concurrency_parity_publication_readiness_record) &&
         surface.deterministic_unsafe_error_parity_validation_readiness_record &&
         IsReadyObjc3SemaUnsafeErrorParityValidationReadinessRecord(
             surface.unsafe_error_parity_validation_readiness_record) &&
         surface.deterministic_control_binding_parity_validation_readiness_record &&
         IsReadyObjc3SemaControlBindingParityValidationReadinessRecord(
             surface.control_binding_parity_validation_readiness_record) &&
         surface.await_lowering_suspension_state_lowering_summary
                 .await_suspension_sites ==
             surface.await_lowering_suspension_state_lowering_sites_total &&
         surface.await_lowering_suspension_state_lowering_summary
                 .await_keyword_sites ==
             surface
                 .await_lowering_suspension_state_lowering_await_keyword_sites_total &&
         surface.await_lowering_suspension_state_lowering_summary
                 .await_suspension_point_sites ==
             surface.await_lowering_suspension_state_lowering_await_suspension_point_sites_total &&
         surface.await_lowering_suspension_state_lowering_summary
                 .await_resume_sites ==
             surface.await_lowering_suspension_state_lowering_await_resume_sites_total &&
         surface.await_lowering_suspension_state_lowering_summary
                 .await_state_machine_sites ==
             surface.await_lowering_suspension_state_lowering_await_state_machine_sites_total &&
         surface.await_lowering_suspension_state_lowering_summary
                 .await_continuation_sites ==
             surface.await_lowering_suspension_state_lowering_await_continuation_sites_total &&
         surface.await_lowering_suspension_state_lowering_summary
                 .normalized_sites ==
             surface.await_lowering_suspension_state_lowering_normalized_sites_total &&
         surface.await_lowering_suspension_state_lowering_summary
                 .gate_blocked_sites ==
             surface.await_lowering_suspension_state_lowering_gate_blocked_sites_total &&
         surface.await_lowering_suspension_state_lowering_summary
                 .contract_violation_sites ==
             surface.await_lowering_suspension_state_lowering_contract_violation_sites_total &&
         surface.await_lowering_suspension_state_lowering_summary
                 .await_keyword_sites <=
             surface.await_lowering_suspension_state_lowering_summary
                 .await_suspension_sites &&
         surface.await_lowering_suspension_state_lowering_summary
                 .await_suspension_point_sites <=
             surface.await_lowering_suspension_state_lowering_summary
                 .await_suspension_sites &&
         surface.await_lowering_suspension_state_lowering_summary
                 .await_resume_sites <=
             surface.await_lowering_suspension_state_lowering_summary
                 .await_suspension_sites &&
         surface.await_lowering_suspension_state_lowering_summary
                 .await_state_machine_sites <=
             surface.await_lowering_suspension_state_lowering_summary
                 .await_suspension_point_sites &&
         surface.await_lowering_suspension_state_lowering_summary
                 .await_continuation_sites <=
             surface.await_lowering_suspension_state_lowering_summary
                 .await_suspension_point_sites &&
         surface.await_lowering_suspension_state_lowering_summary
                 .normalized_sites <=
             surface.await_lowering_suspension_state_lowering_summary
                 .await_suspension_sites &&
         surface.await_lowering_suspension_state_lowering_summary
                 .gate_blocked_sites <=
             surface.await_lowering_suspension_state_lowering_summary
                 .await_suspension_sites &&
         surface.await_lowering_suspension_state_lowering_summary
                 .contract_violation_sites <=
             surface.await_lowering_suspension_state_lowering_summary
                 .await_suspension_sites &&
         surface.await_lowering_suspension_state_lowering_summary
                 .normalized_sites +
                 surface.await_lowering_suspension_state_lowering_summary
                     .gate_blocked_sites ==
             surface.await_lowering_suspension_state_lowering_summary
                 .await_suspension_sites &&
         surface.await_lowering_suspension_state_lowering_summary.deterministic &&
         surface.deterministic_await_lowering_suspension_state_lowering_handoff &&
         surface.block_literal_capture_semantics_summary.block_literal_sites ==
             surface.block_literal_capture_semantics_sites_total &&
         surface.block_literal_capture_semantics_summary.block_parameter_entries ==
             surface.block_literal_capture_semantics_parameter_entries_total &&
         surface.block_literal_capture_semantics_summary.block_capture_entries ==
             surface.block_literal_capture_semantics_capture_entries_total &&
         surface.block_literal_capture_semantics_summary.block_body_statement_entries ==
             surface.block_literal_capture_semantics_body_statement_entries_total &&
         surface.block_literal_capture_semantics_summary.block_empty_capture_sites ==
             surface.block_literal_capture_semantics_empty_capture_sites_total &&
         surface.block_literal_capture_semantics_summary.block_nondeterministic_capture_sites ==
             surface.block_literal_capture_semantics_nondeterministic_capture_sites_total &&
         surface.block_literal_capture_semantics_summary.block_non_normalized_sites ==
             surface.block_literal_capture_semantics_non_normalized_sites_total &&
         surface.block_literal_capture_semantics_summary.contract_violation_sites ==
             surface.block_literal_capture_semantics_contract_violation_sites_total &&
         surface.block_literal_capture_semantics_summary.block_empty_capture_sites <=
             surface.block_literal_capture_semantics_summary.block_literal_sites &&
         surface.block_literal_capture_semantics_summary.block_nondeterministic_capture_sites <=
             surface.block_literal_capture_semantics_summary.block_literal_sites &&
         surface.block_literal_capture_semantics_summary.block_non_normalized_sites <=
             surface.block_literal_capture_semantics_summary.block_literal_sites &&
         surface.block_literal_capture_semantics_summary.contract_violation_sites <=
             surface.block_literal_capture_semantics_summary.block_literal_sites &&
         surface.block_literal_capture_semantics_summary.deterministic &&
         surface.deterministic_block_literal_capture_semantics_handoff &&
         surface.block_abi_invoke_trampoline_semantics_summary.block_literal_sites ==
             surface.block_abi_invoke_trampoline_sites_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.invoke_argument_slots_total ==
             surface.block_abi_invoke_trampoline_invoke_argument_slots_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.capture_word_count_total ==
             surface.block_abi_invoke_trampoline_capture_word_count_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.parameter_entries_total ==
             surface.block_abi_invoke_trampoline_parameter_entries_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.capture_entries_total ==
             surface.block_abi_invoke_trampoline_capture_entries_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.body_statement_entries_total ==
             surface.block_abi_invoke_trampoline_body_statement_entries_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.descriptor_symbolized_sites ==
             surface.block_abi_invoke_trampoline_descriptor_symbolized_sites_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.invoke_trampoline_symbolized_sites ==
             surface.block_abi_invoke_trampoline_invoke_symbolized_sites_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.missing_invoke_trampoline_sites ==
             surface.block_abi_invoke_trampoline_missing_invoke_sites_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.non_normalized_layout_sites ==
             surface.block_abi_invoke_trampoline_non_normalized_layout_sites_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.contract_violation_sites ==
             surface.block_abi_invoke_trampoline_contract_violation_sites_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.descriptor_symbolized_sites <=
             surface.block_abi_invoke_trampoline_semantics_summary.block_literal_sites &&
         surface.block_abi_invoke_trampoline_semantics_summary.invoke_trampoline_symbolized_sites <=
             surface.block_abi_invoke_trampoline_semantics_summary.block_literal_sites &&
         surface.block_abi_invoke_trampoline_semantics_summary.missing_invoke_trampoline_sites <=
             surface.block_abi_invoke_trampoline_semantics_summary.block_literal_sites &&
         surface.block_abi_invoke_trampoline_semantics_summary.non_normalized_layout_sites <=
             surface.block_abi_invoke_trampoline_semantics_summary.block_literal_sites &&
         surface.block_abi_invoke_trampoline_semantics_summary.contract_violation_sites <=
             surface.block_abi_invoke_trampoline_semantics_summary.block_literal_sites &&
         surface.block_abi_invoke_trampoline_semantics_summary.invoke_trampoline_symbolized_sites +
                 surface.block_abi_invoke_trampoline_semantics_summary.missing_invoke_trampoline_sites ==
             surface.block_abi_invoke_trampoline_semantics_summary.block_literal_sites &&
         surface.block_abi_invoke_trampoline_semantics_summary.invoke_argument_slots_total ==
             surface.block_abi_invoke_trampoline_semantics_summary.parameter_entries_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.capture_word_count_total ==
             surface.block_abi_invoke_trampoline_semantics_summary.capture_entries_total &&
         surface.block_abi_invoke_trampoline_semantics_summary.deterministic &&
         surface.deterministic_block_abi_invoke_trampoline_handoff &&
         surface.block_storage_escape_semantics_summary.block_literal_sites ==
             surface.block_storage_escape_sites_total &&
         surface.block_storage_escape_semantics_summary.mutable_capture_count_total ==
             surface.block_storage_escape_mutable_capture_count_total &&
         surface.block_storage_escape_semantics_summary.byref_slot_count_total ==
             surface.block_storage_escape_byref_slot_count_total &&
         surface.block_storage_escape_semantics_summary.parameter_entries_total ==
             surface.block_storage_escape_parameter_entries_total &&
         surface.block_storage_escape_semantics_summary.capture_entries_total ==
             surface.block_storage_escape_capture_entries_total &&
         surface.block_storage_escape_semantics_summary.body_statement_entries_total ==
             surface.block_storage_escape_body_statement_entries_total &&
         surface.block_storage_escape_semantics_summary.requires_byref_cells_sites ==
             surface.block_storage_escape_requires_byref_cells_sites_total &&
         surface.block_storage_escape_semantics_summary.escape_analysis_enabled_sites ==
             surface.block_storage_escape_escape_analysis_enabled_sites_total &&
         surface.block_storage_escape_semantics_summary.escape_to_heap_sites ==
             surface.block_storage_escape_escape_to_heap_sites_total &&
         surface.block_storage_escape_semantics_summary.escape_profile_normalized_sites ==
             surface.block_storage_escape_escape_profile_normalized_sites_total &&
         surface.block_storage_escape_semantics_summary.byref_layout_symbolized_sites ==
             surface.block_storage_escape_byref_layout_symbolized_sites_total &&
         surface.block_storage_escape_semantics_summary.contract_violation_sites ==
             surface.block_storage_escape_contract_violation_sites_total &&
         surface.block_storage_escape_semantics_summary.requires_byref_cells_sites <=
             surface.block_storage_escape_semantics_summary.block_literal_sites &&
         surface.block_storage_escape_semantics_summary.escape_analysis_enabled_sites <=
             surface.block_storage_escape_semantics_summary.block_literal_sites &&
         surface.block_storage_escape_semantics_summary.escape_to_heap_sites <=
             surface.block_storage_escape_semantics_summary.block_literal_sites &&
         surface.block_storage_escape_semantics_summary.escape_profile_normalized_sites <=
             surface.block_storage_escape_semantics_summary.block_literal_sites &&
         surface.block_storage_escape_semantics_summary.byref_layout_symbolized_sites <=
             surface.block_storage_escape_semantics_summary.block_literal_sites &&
         surface.block_storage_escape_semantics_summary.contract_violation_sites <=
             surface.block_storage_escape_semantics_summary.block_literal_sites &&
         surface.block_storage_escape_semantics_summary.mutable_capture_count_total <=
             surface.block_storage_escape_semantics_summary.capture_entries_total &&
         surface.block_storage_escape_semantics_summary.byref_slot_count_total <=
             surface.block_storage_escape_semantics_summary.mutable_capture_count_total &&
         surface.block_storage_escape_semantics_summary.escape_analysis_enabled_sites ==
             surface.block_storage_escape_semantics_summary.block_literal_sites &&
         surface.block_storage_escape_semantics_summary.deterministic &&
         surface.deterministic_block_storage_escape_handoff &&
         surface.block_copy_dispose_semantics_summary.block_literal_sites ==
             surface.block_copy_dispose_sites_total &&
         surface.block_copy_dispose_semantics_summary.mutable_capture_count_total ==
             surface.block_copy_dispose_mutable_capture_count_total &&
         surface.block_copy_dispose_semantics_summary.byref_slot_count_total ==
             surface.block_copy_dispose_byref_slot_count_total &&
         surface.block_copy_dispose_semantics_summary.parameter_entries_total ==
             surface.block_copy_dispose_parameter_entries_total &&
         surface.block_copy_dispose_semantics_summary.capture_entries_total ==
             surface.block_copy_dispose_capture_entries_total &&
         surface.block_copy_dispose_semantics_summary.body_statement_entries_total ==
             surface.block_copy_dispose_body_statement_entries_total &&
         surface.block_copy_dispose_semantics_summary.copy_helper_required_sites ==
             surface.block_copy_dispose_copy_helper_required_sites_total &&
         surface.block_copy_dispose_semantics_summary.dispose_helper_required_sites ==
             surface.block_copy_dispose_dispose_helper_required_sites_total &&
         surface.block_copy_dispose_semantics_summary.profile_normalized_sites ==
             surface.block_copy_dispose_profile_normalized_sites_total &&
         surface.block_copy_dispose_semantics_summary.copy_helper_symbolized_sites ==
             surface.block_copy_dispose_copy_helper_symbolized_sites_total &&
         surface.block_copy_dispose_semantics_summary.dispose_helper_symbolized_sites ==
             surface.block_copy_dispose_dispose_helper_symbolized_sites_total &&
         surface.block_copy_dispose_semantics_summary.contract_violation_sites ==
             surface.block_copy_dispose_contract_violation_sites_total &&
         surface.block_copy_dispose_semantics_summary.copy_helper_required_sites <=
             surface.block_copy_dispose_semantics_summary.block_literal_sites &&
         surface.block_copy_dispose_semantics_summary.dispose_helper_required_sites <=
             surface.block_copy_dispose_semantics_summary.block_literal_sites &&
         surface.block_copy_dispose_semantics_summary.profile_normalized_sites <=
             surface.block_copy_dispose_semantics_summary.block_literal_sites &&
         surface.block_copy_dispose_semantics_summary.copy_helper_symbolized_sites <=
             surface.block_copy_dispose_semantics_summary.block_literal_sites &&
         surface.block_copy_dispose_semantics_summary.dispose_helper_symbolized_sites <=
             surface.block_copy_dispose_semantics_summary.block_literal_sites &&
         surface.block_copy_dispose_semantics_summary.contract_violation_sites <=
             surface.block_copy_dispose_semantics_summary.block_literal_sites &&
         surface.block_copy_dispose_semantics_summary.mutable_capture_count_total <=
             surface.block_copy_dispose_semantics_summary.capture_entries_total &&
         surface.block_copy_dispose_semantics_summary.byref_slot_count_total <=
             surface.block_copy_dispose_semantics_summary.mutable_capture_count_total &&
         surface.block_copy_dispose_semantics_summary.copy_helper_required_sites <=
             surface.block_copy_dispose_semantics_summary.dispose_helper_required_sites &&
         surface.block_copy_dispose_semantics_summary.deterministic &&
         surface.deterministic_block_copy_dispose_handoff &&
         surface.block_determinism_perf_baseline_summary.block_literal_sites ==
             surface.block_determinism_perf_baseline_sites_total &&
         surface.block_determinism_perf_baseline_summary.baseline_weight_total ==
             surface.block_determinism_perf_baseline_weight_total &&
         surface.block_determinism_perf_baseline_summary.parameter_entries_total ==
             surface.block_determinism_perf_baseline_parameter_entries_total &&
         surface.block_determinism_perf_baseline_summary.capture_entries_total ==
             surface.block_determinism_perf_baseline_capture_entries_total &&
         surface.block_determinism_perf_baseline_summary.body_statement_entries_total ==
             surface.block_determinism_perf_baseline_body_statement_entries_total &&
         surface.block_determinism_perf_baseline_summary.deterministic_capture_sites ==
             surface.block_determinism_perf_baseline_deterministic_capture_sites_total &&
         surface.block_determinism_perf_baseline_summary.heavy_tier_sites ==
             surface.block_determinism_perf_baseline_heavy_tier_sites_total &&
         surface.block_determinism_perf_baseline_summary.normalized_profile_sites ==
             surface.block_determinism_perf_baseline_normalized_profile_sites_total &&
         surface.block_determinism_perf_baseline_summary.contract_violation_sites ==
             surface.block_determinism_perf_baseline_contract_violation_sites_total &&
         surface.block_determinism_perf_baseline_summary.deterministic_capture_sites <=
             surface.block_determinism_perf_baseline_summary.block_literal_sites &&
         surface.block_determinism_perf_baseline_summary.heavy_tier_sites <=
             surface.block_determinism_perf_baseline_summary.block_literal_sites &&
         surface.block_determinism_perf_baseline_summary.normalized_profile_sites <=
             surface.block_determinism_perf_baseline_summary.block_literal_sites &&
         surface.block_determinism_perf_baseline_summary.contract_violation_sites <=
             surface.block_determinism_perf_baseline_summary.block_literal_sites &&
         surface.block_determinism_perf_baseline_summary.deterministic &&
         surface.deterministic_block_determinism_perf_baseline_handoff &&
         surface.message_send_selector_lowering_summary.message_send_sites ==
             surface.message_send_selector_lowering_sites_total &&
         surface.message_send_selector_lowering_summary.unary_form_sites ==
             surface.message_send_selector_lowering_unary_form_sites_total &&
         surface.message_send_selector_lowering_summary.keyword_form_sites ==
             surface.message_send_selector_lowering_keyword_form_sites_total &&
         surface.message_send_selector_lowering_summary.selector_lowering_symbol_sites ==
             surface.message_send_selector_lowering_symbol_sites_total &&
         surface.message_send_selector_lowering_summary.selector_lowering_piece_entries ==
             surface.message_send_selector_lowering_piece_entries_total &&
         surface.message_send_selector_lowering_summary.selector_lowering_argument_piece_entries ==
             surface.message_send_selector_lowering_argument_piece_entries_total &&
         surface.message_send_selector_lowering_summary.selector_lowering_normalized_sites ==
             surface.message_send_selector_lowering_normalized_sites_total &&
         surface.message_send_selector_lowering_summary.selector_lowering_form_mismatch_sites ==
             surface.message_send_selector_lowering_form_mismatch_sites_total &&
         surface.message_send_selector_lowering_summary.selector_lowering_arity_mismatch_sites ==
             surface.message_send_selector_lowering_arity_mismatch_sites_total &&
         surface.message_send_selector_lowering_summary.selector_lowering_symbol_mismatch_sites ==
             surface.message_send_selector_lowering_symbol_mismatch_sites_total &&
         surface.message_send_selector_lowering_summary.selector_lowering_missing_symbol_sites ==
             surface.message_send_selector_lowering_missing_symbol_sites_total &&
         surface.message_send_selector_lowering_summary.selector_lowering_contract_violation_sites ==
             surface.message_send_selector_lowering_contract_violation_sites_total &&
         surface.message_send_selector_lowering_summary.unary_form_sites +
                 surface.message_send_selector_lowering_summary.keyword_form_sites ==
             surface.message_send_selector_lowering_summary.message_send_sites &&
         surface.message_send_selector_lowering_summary.selector_lowering_symbol_sites <=
             surface.message_send_selector_lowering_summary.message_send_sites &&
         surface.message_send_selector_lowering_summary.selector_lowering_piece_entries >=
             surface.message_send_selector_lowering_summary.selector_lowering_argument_piece_entries &&
         surface.message_send_selector_lowering_summary.selector_lowering_normalized_sites <=
             surface.message_send_selector_lowering_summary.selector_lowering_symbol_sites &&
         surface.message_send_selector_lowering_summary.selector_lowering_form_mismatch_sites <=
             surface.message_send_selector_lowering_summary.message_send_sites &&
         surface.message_send_selector_lowering_summary.selector_lowering_arity_mismatch_sites <=
             surface.message_send_selector_lowering_summary.message_send_sites &&
         surface.message_send_selector_lowering_summary.selector_lowering_symbol_mismatch_sites <=
             surface.message_send_selector_lowering_summary.message_send_sites &&
         surface.message_send_selector_lowering_summary.selector_lowering_missing_symbol_sites <=
             surface.message_send_selector_lowering_summary.message_send_sites &&
         surface.message_send_selector_lowering_summary.selector_lowering_contract_violation_sites <=
             surface.message_send_selector_lowering_summary.message_send_sites &&
         surface.message_send_selector_lowering_summary.deterministic &&
         surface.deterministic_message_send_selector_lowering_handoff &&
         surface.dispatch_abi_marshalling_summary.message_send_sites ==
             surface.dispatch_abi_marshalling_sites_total &&
         surface.dispatch_abi_marshalling_summary.receiver_slots ==
             surface.dispatch_abi_marshalling_receiver_slots_total &&
         surface.dispatch_abi_marshalling_summary.selector_symbol_slots ==
             surface.dispatch_abi_marshalling_selector_symbol_slots_total &&
         surface.dispatch_abi_marshalling_summary.argument_slots ==
             surface.dispatch_abi_marshalling_argument_slots_total &&
         surface.dispatch_abi_marshalling_summary.keyword_argument_slots ==
             surface.dispatch_abi_marshalling_keyword_argument_slots_total &&
         surface.dispatch_abi_marshalling_summary.unary_argument_slots ==
             surface.dispatch_abi_marshalling_unary_argument_slots_total &&
         surface.dispatch_abi_marshalling_summary.arity_mismatch_sites ==
             surface.dispatch_abi_marshalling_arity_mismatch_sites_total &&
         surface.dispatch_abi_marshalling_summary.missing_selector_symbol_sites ==
             surface.dispatch_abi_marshalling_missing_selector_symbol_sites_total &&
         surface.dispatch_abi_marshalling_summary.contract_violation_sites ==
             surface.dispatch_abi_marshalling_contract_violation_sites_total &&
         surface.dispatch_abi_marshalling_summary.receiver_slots ==
             surface.dispatch_abi_marshalling_summary.message_send_sites &&
         surface.dispatch_abi_marshalling_summary.selector_symbol_slots +
                 surface.dispatch_abi_marshalling_summary.missing_selector_symbol_sites ==
             surface.dispatch_abi_marshalling_summary.message_send_sites &&
         surface.dispatch_abi_marshalling_summary.keyword_argument_slots +
                 surface.dispatch_abi_marshalling_summary.unary_argument_slots ==
             surface.dispatch_abi_marshalling_summary.argument_slots &&
         surface.dispatch_abi_marshalling_summary.keyword_argument_slots <=
             surface.dispatch_abi_marshalling_summary.argument_slots &&
         surface.dispatch_abi_marshalling_summary.unary_argument_slots <=
             surface.dispatch_abi_marshalling_summary.argument_slots &&
         surface.dispatch_abi_marshalling_summary.selector_symbol_slots <=
             surface.dispatch_abi_marshalling_summary.message_send_sites &&
         surface.dispatch_abi_marshalling_summary.missing_selector_symbol_sites <=
             surface.dispatch_abi_marshalling_summary.message_send_sites &&
         surface.dispatch_abi_marshalling_summary.arity_mismatch_sites <=
             surface.dispatch_abi_marshalling_summary.message_send_sites &&
         surface.dispatch_abi_marshalling_summary.contract_violation_sites <=
             surface.dispatch_abi_marshalling_summary.message_send_sites &&
         surface.dispatch_abi_marshalling_summary.deterministic &&
         surface.deterministic_dispatch_abi_marshalling_handoff &&
         surface.nil_receiver_semantics_foldability_summary.message_send_sites ==
             surface.nil_receiver_semantics_foldability_sites_total &&
         surface.nil_receiver_semantics_foldability_summary.receiver_nil_literal_sites ==
             surface.nil_receiver_semantics_foldability_receiver_nil_literal_sites_total &&
         surface.nil_receiver_semantics_foldability_summary.nil_receiver_semantics_enabled_sites ==
             surface.nil_receiver_semantics_foldability_enabled_sites_total &&
         surface.nil_receiver_semantics_foldability_summary.nil_receiver_foldable_sites ==
             surface.nil_receiver_semantics_foldability_foldable_sites_total &&
         surface.nil_receiver_semantics_foldability_summary.nil_receiver_runtime_dispatch_required_sites ==
             surface.nil_receiver_semantics_foldability_runtime_dispatch_required_sites_total &&
         surface.nil_receiver_semantics_foldability_summary.non_nil_receiver_sites ==
             surface.nil_receiver_semantics_foldability_non_nil_receiver_sites_total &&
         surface.nil_receiver_semantics_foldability_summary.contract_violation_sites ==
             surface.nil_receiver_semantics_foldability_contract_violation_sites_total &&
         surface.nil_receiver_semantics_foldability_summary.receiver_nil_literal_sites ==
             surface.nil_receiver_semantics_foldability_summary.nil_receiver_semantics_enabled_sites &&
         surface.nil_receiver_semantics_foldability_summary.nil_receiver_foldable_sites <=
             surface.nil_receiver_semantics_foldability_summary.nil_receiver_semantics_enabled_sites &&
         surface.nil_receiver_semantics_foldability_summary.nil_receiver_runtime_dispatch_required_sites +
                 surface.nil_receiver_semantics_foldability_summary.nil_receiver_foldable_sites ==
             surface.nil_receiver_semantics_foldability_summary.message_send_sites &&
         surface.nil_receiver_semantics_foldability_summary.nil_receiver_semantics_enabled_sites +
                 surface.nil_receiver_semantics_foldability_summary.non_nil_receiver_sites ==
             surface.nil_receiver_semantics_foldability_summary.message_send_sites &&
         surface.nil_receiver_semantics_foldability_summary.contract_violation_sites <=
             surface.nil_receiver_semantics_foldability_summary.message_send_sites &&
         surface.nil_receiver_semantics_foldability_summary.deterministic &&
         surface.deterministic_nil_receiver_semantics_foldability_handoff &&
         surface.super_dispatch_method_family_summary.message_send_sites ==
             surface.super_dispatch_method_family_sites_total &&
         surface.super_dispatch_method_family_summary.receiver_super_identifier_sites ==
             surface.super_dispatch_method_family_receiver_super_identifier_sites_total &&
         surface.super_dispatch_method_family_summary.super_dispatch_enabled_sites ==
             surface.super_dispatch_method_family_enabled_sites_total &&
         surface.super_dispatch_method_family_summary.super_dispatch_requires_class_context_sites ==
             surface.super_dispatch_method_family_requires_class_context_sites_total &&
         surface.super_dispatch_method_family_summary.method_family_init_sites ==
             surface.super_dispatch_method_family_init_sites_total &&
         surface.super_dispatch_method_family_summary.method_family_copy_sites ==
             surface.super_dispatch_method_family_copy_sites_total &&
         surface.super_dispatch_method_family_summary.method_family_mutable_copy_sites ==
             surface.super_dispatch_method_family_mutable_copy_sites_total &&
         surface.super_dispatch_method_family_summary.method_family_new_sites ==
             surface.super_dispatch_method_family_new_sites_total &&
         surface.super_dispatch_method_family_summary.method_family_none_sites ==
             surface.super_dispatch_method_family_none_sites_total &&
         surface.super_dispatch_method_family_summary.method_family_returns_retained_result_sites ==
             surface.super_dispatch_method_family_returns_retained_result_sites_total &&
         surface.super_dispatch_method_family_summary.method_family_returns_related_result_sites ==
             surface.super_dispatch_method_family_returns_related_result_sites_total &&
         surface.super_dispatch_method_family_summary.contract_violation_sites ==
             surface.super_dispatch_method_family_contract_violation_sites_total &&
         surface.super_dispatch_method_family_summary.receiver_super_identifier_sites ==
             surface.super_dispatch_method_family_summary.super_dispatch_enabled_sites &&
         surface.super_dispatch_method_family_summary.super_dispatch_requires_class_context_sites ==
             surface.super_dispatch_method_family_summary.super_dispatch_enabled_sites &&
         surface.super_dispatch_method_family_summary.method_family_init_sites +
                 surface.super_dispatch_method_family_summary.method_family_copy_sites +
                 surface.super_dispatch_method_family_summary.method_family_mutable_copy_sites +
                 surface.super_dispatch_method_family_summary.method_family_new_sites +
                 surface.super_dispatch_method_family_summary.method_family_none_sites ==
             surface.super_dispatch_method_family_summary.message_send_sites &&
         surface.super_dispatch_method_family_summary.method_family_returns_related_result_sites <=
             surface.super_dispatch_method_family_summary.method_family_init_sites &&
         surface.super_dispatch_method_family_summary.method_family_returns_retained_result_sites <=
             surface.super_dispatch_method_family_summary.message_send_sites &&
         surface.super_dispatch_method_family_summary.contract_violation_sites <=
             surface.super_dispatch_method_family_summary.message_send_sites &&
         surface.super_dispatch_method_family_summary.deterministic &&
         surface.deterministic_super_dispatch_method_family_handoff &&
         surface.runtime_link_host_link_summary.message_send_sites ==
             surface.runtime_link_host_link_message_send_sites_total &&
         surface.runtime_link_host_link_summary.runtime_link_required_sites ==
             surface.runtime_link_host_link_required_sites_total &&
         surface.runtime_link_host_link_summary.runtime_link_elided_sites ==
             surface.runtime_link_host_link_elided_sites_total &&
         surface.runtime_link_host_link_summary.runtime_dispatch_arg_slots ==
             surface.runtime_link_host_link_runtime_dispatch_arg_slots_total &&
         surface.runtime_link_host_link_summary.runtime_dispatch_declaration_parameter_count ==
             surface.runtime_link_host_link_runtime_dispatch_declaration_parameter_count_total &&
         surface.runtime_link_host_link_summary.contract_violation_sites ==
             surface.runtime_link_host_link_contract_violation_sites_total &&
         surface.runtime_link_host_link_summary.runtime_dispatch_symbol ==
             surface.runtime_link_host_link_runtime_dispatch_symbol &&
         surface.runtime_link_host_link_summary.default_runtime_dispatch_symbol_binding ==
             surface.runtime_link_host_link_default_runtime_dispatch_symbol_binding &&
         surface.runtime_link_host_link_summary.runtime_link_required_sites +
                 surface.runtime_link_host_link_summary.runtime_link_elided_sites ==
             surface.runtime_link_host_link_summary.message_send_sites &&
         surface.runtime_link_host_link_summary.contract_violation_sites <=
             surface.runtime_link_host_link_summary.message_send_sites &&
         (surface.runtime_link_host_link_summary.message_send_sites == 0 ||
          surface.runtime_link_host_link_summary.runtime_dispatch_declaration_parameter_count ==
              surface.runtime_link_host_link_summary.runtime_dispatch_arg_slots + 2u) &&
         (surface.runtime_link_host_link_summary.default_runtime_dispatch_symbol_binding ==
          (surface.runtime_link_host_link_summary.runtime_dispatch_symbol ==
           kObjc3RuntimeLinkHostLinkDefaultDispatchSymbol)) &&
         surface.runtime_link_host_link_summary.deterministic &&
         surface.deterministic_runtime_link_host_link_handoff &&
         surface.retain_release_operation_summary.ownership_qualified_sites ==
             surface.retain_release_operation_ownership_qualified_sites_total &&
         surface.retain_release_operation_summary.retain_insertion_sites ==
             surface.retain_release_operation_retain_insertion_sites_total &&
         surface.retain_release_operation_summary.release_insertion_sites ==
             surface.retain_release_operation_release_insertion_sites_total &&
         surface.retain_release_operation_summary.autorelease_insertion_sites ==
             surface.retain_release_operation_autorelease_insertion_sites_total &&
         surface.retain_release_operation_summary.contract_violation_sites ==
             surface.retain_release_operation_contract_violation_sites_total &&
         surface.retain_release_operation_summary.retain_insertion_sites <=
             surface.retain_release_operation_summary.ownership_qualified_sites +
                 surface.retain_release_operation_summary.contract_violation_sites &&
         surface.retain_release_operation_summary.release_insertion_sites <=
             surface.retain_release_operation_summary.ownership_qualified_sites +
                 surface.retain_release_operation_summary.contract_violation_sites &&
         surface.retain_release_operation_summary.autorelease_insertion_sites <=
             surface.retain_release_operation_summary.ownership_qualified_sites +
                 surface.retain_release_operation_summary.contract_violation_sites &&
         surface.retain_release_operation_summary.deterministic &&
         surface.deterministic_retain_release_operation_handoff &&
         surface.weak_unowned_semantics_summary.ownership_candidate_sites ==
             surface.weak_unowned_semantics_ownership_candidate_sites_total &&
         surface.weak_unowned_semantics_summary.weak_reference_sites ==
             surface.weak_unowned_semantics_weak_reference_sites_total &&
         surface.weak_unowned_semantics_summary.unowned_reference_sites ==
             surface.weak_unowned_semantics_unowned_reference_sites_total &&
         surface.weak_unowned_semantics_summary.unowned_safe_reference_sites ==
             surface.weak_unowned_semantics_unowned_safe_reference_sites_total &&
         surface.weak_unowned_semantics_summary.weak_unowned_conflict_sites ==
             surface.weak_unowned_semantics_conflict_sites_total &&
         surface.weak_unowned_semantics_summary.contract_violation_sites ==
             surface.weak_unowned_semantics_contract_violation_sites_total &&
         surface.weak_unowned_semantics_summary.unowned_safe_reference_sites <=
             surface.weak_unowned_semantics_summary.unowned_reference_sites &&
         surface.weak_unowned_semantics_summary.weak_unowned_conflict_sites <=
             surface.weak_unowned_semantics_summary.ownership_candidate_sites &&
         surface.weak_unowned_semantics_summary.contract_violation_sites <=
             surface.weak_unowned_semantics_summary.ownership_candidate_sites +
                 surface.weak_unowned_semantics_summary.weak_unowned_conflict_sites &&
         surface.weak_unowned_semantics_summary.deterministic &&
         surface.deterministic_weak_unowned_semantics_handoff &&
         surface.arc_diagnostics_fixit_summary.ownership_arc_diagnostic_candidate_sites ==
             surface.ownership_arc_diagnostic_candidate_sites_total &&
         surface.arc_diagnostics_fixit_summary.ownership_arc_fixit_available_sites ==
             surface.ownership_arc_fixit_available_sites_total &&
         surface.arc_diagnostics_fixit_summary.ownership_arc_profiled_sites ==
             surface.ownership_arc_profiled_sites_total &&
         surface.arc_diagnostics_fixit_summary.ownership_arc_weak_unowned_conflict_diagnostic_sites ==
             surface.ownership_arc_weak_unowned_conflict_diagnostic_sites_total &&
         surface.arc_diagnostics_fixit_summary.ownership_arc_empty_fixit_hint_sites ==
             surface.ownership_arc_empty_fixit_hint_sites_total &&
         surface.arc_diagnostics_fixit_summary.contract_violation_sites ==
             surface.ownership_arc_contract_violation_sites_total &&
         surface.arc_diagnostics_fixit_summary.ownership_arc_fixit_available_sites <=
             surface.arc_diagnostics_fixit_summary.ownership_arc_diagnostic_candidate_sites +
                 surface.arc_diagnostics_fixit_summary.contract_violation_sites &&
         surface.arc_diagnostics_fixit_summary.ownership_arc_profiled_sites <=
             surface.arc_diagnostics_fixit_summary.ownership_arc_diagnostic_candidate_sites +
                 surface.arc_diagnostics_fixit_summary.contract_violation_sites &&
         surface.arc_diagnostics_fixit_summary.ownership_arc_weak_unowned_conflict_diagnostic_sites <=
             surface.arc_diagnostics_fixit_summary.ownership_arc_diagnostic_candidate_sites +
                 surface.arc_diagnostics_fixit_summary.contract_violation_sites &&
         surface.arc_diagnostics_fixit_summary.ownership_arc_empty_fixit_hint_sites <=
             surface.arc_diagnostics_fixit_summary.ownership_arc_fixit_available_sites +
                 surface.arc_diagnostics_fixit_summary.contract_violation_sites &&
         surface.arc_diagnostics_fixit_summary.deterministic &&
         surface.deterministic_arc_diagnostics_fixit_handoff &&
         surface.autoreleasepool_scope_summary.scope_sites == surface.autoreleasepool_scope_sites_total &&
         surface.autoreleasepool_scope_summary.scope_symbolized_sites ==
             surface.autoreleasepool_scope_symbolized_sites_total &&
         surface.autoreleasepool_scope_summary.contract_violation_sites ==
             surface.autoreleasepool_scope_contract_violation_sites_total &&
         surface.autoreleasepool_scope_summary.max_scope_depth == surface.autoreleasepool_scope_max_depth_total &&
         surface.autoreleasepool_scope_summary.scope_symbolized_sites <=
             surface.autoreleasepool_scope_summary.scope_sites &&
         surface.autoreleasepool_scope_summary.contract_violation_sites <=
             surface.autoreleasepool_scope_summary.scope_sites &&
         (surface.autoreleasepool_scope_summary.scope_sites > 0u ||
          surface.autoreleasepool_scope_summary.max_scope_depth == 0u) &&
         surface.autoreleasepool_scope_summary.max_scope_depth <=
             static_cast<unsigned>(surface.autoreleasepool_scope_summary.scope_sites) &&
         surface.autoreleasepool_scope_summary.deterministic &&
         surface.deterministic_autoreleasepool_scope_handoff;
}

struct Objc3SemaPassManagerResult {
  Objc3ParserContractSnapshot parser_contract_snapshot;
  bool deterministic_parser_sema_handoff = false;
  Objc3ParserSemaConformanceMatrix parser_sema_conformance_matrix;
  bool deterministic_parser_sema_conformance_matrix = false;
  Objc3ParserSemaConformanceCorpus parser_sema_conformance_corpus;
  bool deterministic_parser_sema_conformance_corpus = false;
  Objc3ParserSemaPerformanceQualityGuardrails parser_sema_performance_quality_guardrails;
  bool deterministic_parser_sema_performance_quality_guardrails = false;
  Objc3ParserSemaCrossLaneIntegrationSync parser_sema_cross_lane_integration_sync;
  bool deterministic_parser_sema_cross_lane_integration_sync = false;
