#pragma once

#include "sema/objc3_parser_sema_handoff_scaffold_parts/objc3_parser_sema_handoff_scaffold_part_001.inc"
#include "sema/objc3_parser_sema_handoff_scaffold_parts/objc3_parser_sema_handoff_scaffold_part_002.inc"
