"""Shared concurrency runtime probe payload assertions."""

from __future__ import annotations

from collections.abc import Mapping

from objc3c_runtime_acceptance.expectation_matching import expect

EXPECTED_RUNTIME_ABI_PAYLOADS = {
    "continuation": {
        "handle": 1,
        "mismatched_handoff": 0,
        "mismatched_handoff_failure_code": 12,
        "handed_off": 1,
        "resumed": 77,
        "double_resumed": 0,
        "double_resume_failure_code": 4,
        "unhandedoff_handle": 65537,
        "unhandedoff_resume": 0,
        "unhandedoff_resume_failure_code": 11,
        "unhandedoff_cancel": 65537,
        "missing_payload_handle": 131073,
        "missing_payload_handed_off": 131073,
        "missing_payload_resumed": 0,
        "missing_payload_failure_code": 6,
        "cancelled_handle": 196609,
        "cancelled": 196609,
        "resume_after_cancel": 0,
        "resume_after_cancel_failure_code": 5,
        "recycled_handle": 262145,
        "stale_generation_resume": 0,
        "stale_generation_failure_code": 3,
        "malformed_resume": 0,
        "malformed_failure_code": 1,
        "unknown_resume": 0,
        "unknown_failure_code": 2,
        "invalid_allocation": 0,
        "invalid_allocation_failure_code": 7,
        "copy_status": 0,
        "allocation_call_count": 6,
        "handoff_call_count": 3,
        "resume_call_count": 8,
        "cancel_call_count": 2,
        "rejected_operation_count": 9,
        "live_continuation_handle_count": 1,
        "completed_continuation_count": 1,
        "cancelled_continuation_count": 2,
        "failed_continuation_count": 1,
        "last_allocated_continuation_handle": 0,
        "last_allocated_continuation_slot": 0,
        "last_allocated_continuation_generation": 0,
        "last_allocated_resume_entry_tag": 0,
        "last_allocated_executor_tag": 9,
        "last_handoff_continuation_handle": 131073,
        "last_handoff_executor_tag": 9,
        "last_resume_continuation_handle": 2,
        "last_resume_result_value": 102,
        "last_resume_return_value": 0,
        "last_cancel_continuation_handle": 196609,
        "last_cancel_return_value": 196609,
        "last_operation_failure_code": 7,
        "last_observed_continuation_slot": 2,
        "last_observed_continuation_generation": 0,
    },
    "task": {
        "spawn_group": 111,
        "scope": 1,
        "add_task": 1,
        "add_second_task": 1,
        "cancelled": 0,
        "wait_next": 23,
        "wait_second_next": 24,
        "hop": 23,
        "cancel_all": 31,
        "on_cancel": 41,
        "spawn_detached": 121,
        "copy_status": 0,
        "after_add_copy_status": 0,
        "after_add_last_queue_depth": 1,
        "after_add_scheduler_enqueue_count": 1,
        "after_add_scheduler_dequeue_count": 0,
        "after_add_last_scheduled_task_handle": 23,
        "after_add_last_scheduled_executor_tag": 2,
        "after_add_last_executor_queue_depth": 1,
        "after_add_max_executor_queue_depth": 1,
        "after_add_scheduler_sequence": 1,
        "after_add_deadlock_guard_passed": 1,
        "after_add_race_guard_passed": 1,
        "after_second_add_copy_status": 0,
        "after_second_add_last_queue_depth": 2,
        "after_second_add_scheduler_enqueue_count": 2,
        "after_second_add_scheduler_dequeue_count": 0,
        "after_second_add_last_scheduled_task_handle": 24,
        "after_second_add_last_scheduled_executor_tag": 2,
        "after_second_add_last_executor_queue_depth": 2,
        "after_second_add_max_executor_queue_depth": 2,
        "after_second_add_scheduler_sequence": 2,
        "after_second_add_deadlock_guard_passed": 1,
        "after_second_add_race_guard_passed": 1,
        "after_wait_copy_status": 0,
        "after_wait_last_queue_depth": 1,
        "after_wait_last_queue_drain_result": 23,
        "after_wait_scheduler_enqueue_count": 2,
        "after_wait_scheduler_dequeue_count": 1,
        "after_wait_last_scheduled_task_handle": 24,
        "after_wait_last_scheduled_executor_tag": 2,
        "after_wait_last_dequeued_task_handle": 23,
        "after_wait_last_dequeued_executor_tag": 2,
        "after_wait_last_executor_queue_depth": 1,
        "after_wait_max_executor_queue_depth": 2,
        "after_wait_scheduler_sequence": 3,
        "after_wait_deadlock_guard_passed": 1,
        "after_wait_race_guard_passed": 1,
        "after_second_wait_copy_status": 0,
        "after_second_wait_last_queue_depth": 0,
        "after_second_wait_last_queue_drain_result": 24,
        "after_second_wait_scheduler_enqueue_count": 2,
        "after_second_wait_scheduler_dequeue_count": 2,
        "after_second_wait_last_scheduled_task_handle": 24,
        "after_second_wait_last_scheduled_executor_tag": 2,
        "after_second_wait_last_dequeued_task_handle": 24,
        "after_second_wait_last_dequeued_executor_tag": 2,
        "after_second_wait_last_executor_queue_depth": 0,
        "after_second_wait_max_executor_queue_depth": 2,
        "after_second_wait_scheduler_sequence": 4,
        "after_second_wait_deadlock_guard_passed": 1,
        "after_second_wait_race_guard_passed": 1,
        "spawn_call_count": 2,
        "scope_call_count": 1,
        "add_task_call_count": 2,
        "wait_next_call_count": 2,
        "cancel_all_call_count": 1,
        "cancellation_poll_call_count": 1,
        "on_cancel_call_count": 1,
        "executor_hop_call_count": 1,
        "last_spawn_kind": 2,
        "last_spawn_executor_tag": 3,
        "last_wait_next_result": 24,
        "last_executor_hop_executor_tag": 2,
        "last_executor_hop_value": 23,
        "last_failure_reason": 0,
        "lifecycle_state": 1,
        "selected_executor_tag": 3,
        "active_group_executor_tag": 2,
        "active_group_task_count": 2,
        "pending_group_task_count": 0,
        "completed_group_task_count": 2,
        "cancelled_group_task_count": 0,
        "group_cancelled": 1,
        "cancellation_generation": 1,
        "observed_cancellation_generation": 1,
        "last_queue_depth": 0,
        "last_queue_drain_result": 24,
        "scheduler_enqueue_count": 3,
        "scheduler_dequeue_count": 2,
        "scheduler_cancelled_count": 0,
        "last_scheduled_task_handle": 121,
        "last_scheduled_executor_tag": 3,
        "last_dequeued_task_handle": 24,
        "last_dequeued_executor_tag": 2,
        "last_cancelled_task_handle": 0,
        "last_cancelled_executor_tag": 0,
        "last_executor_queue_depth": 1,
        "max_executor_queue_depth": 2,
        "scheduler_sequence": 5,
        "deadlock_guard_passed": 1,
        "race_guard_passed": 1,
        "cancel_drain_scope": 1,
        "cancel_drain_add_task": 1,
        "cancel_drain_add_second_task": 1,
        "cancel_drain_cancel_all": 31,
        "cancel_drain_copy_task_status": 0,
        "cancel_drain_scope_call_count": 1,
        "cancel_drain_add_task_call_count": 2,
        "cancel_drain_cancel_all_call_count": 1,
        "cancel_drain_last_cancel_all_result": 31,
        "cancel_drain_last_failure_reason": 0,
        "cancel_drain_lifecycle_state": 4,
        "cancel_drain_selected_executor_tag": 6,
        "cancel_drain_active_group_executor_tag": 6,
        "cancel_drain_active_group_task_count": 2,
        "cancel_drain_pending_group_task_count": 0,
        "cancel_drain_completed_group_task_count": 0,
        "cancel_drain_cancelled_group_task_count": 2,
        "cancel_drain_group_cancelled": 1,
        "cancel_drain_cancellation_generation": 1,
        "cancel_drain_last_queue_depth": 0,
        "cancel_drain_last_queue_drain_result": 28,
        "cancel_drain_scheduler_enqueue_count": 2,
        "cancel_drain_scheduler_dequeue_count": 0,
        "cancel_drain_scheduler_cancelled_count": 2,
        "cancel_drain_last_scheduled_task_handle": 28,
        "cancel_drain_last_scheduled_executor_tag": 6,
        "cancel_drain_last_cancelled_task_handle": 28,
        "cancel_drain_last_cancelled_executor_tag": 6,
        "cancel_drain_last_executor_queue_depth": 0,
        "cancel_drain_max_executor_queue_depth": 2,
        "cancel_drain_scheduler_sequence": 4,
        "cancel_drain_deadlock_guard_passed": 1,
        "cancel_drain_race_guard_passed": 1,
        "cancel_drain_replay_equal": 1,
    },
    "actor": {
        "copy_status": 0,
        "replay": 1,
        "guard": 1,
        "isolation": 1,
        "nonisolated": 5,
        "hopped": 17,
        "replay_proof_call_count": 1,
        "race_guard_call_count": 1,
        "isolation_thunk_call_count": 1,
        "nonisolated_entry_call_count": 1,
        "hop_to_executor_call_count": 1,
        "failed_operation_count": 0,
        "last_replay_proof_executor_tag": 1,
        "last_race_guard_executor_tag": 1,
        "last_isolation_executor_tag": 1,
        "last_nonisolated_value": 5,
        "last_nonisolated_executor_tag": 0,
        "last_hop_value": 17,
        "last_hop_executor_tag": 1,
        "last_hop_result": 17,
        "last_operation_succeeded": 1,
        "last_failure_code": 0,
    },
}

EXPECTED_LIVE_RUNTIME_PAYLOADS = {
    "continuation": {
        "runTask": 7,
        "loadValue": 7,
        "copy_status": 0,
        "allocation_call_count": 4,
        "handoff_call_count": 4,
        "resume_call_count": 4,
        "cancel_call_count": 0,
        "rejected_operation_count": 0,
        "live_continuation_handle_count": 0,
        "completed_continuation_count": 4,
        "cancelled_continuation_count": 0,
        "failed_continuation_count": 0,
        "last_allocated_continuation_slot": 1,
        "last_allocated_continuation_generation": 3,
        "last_handoff_executor_tag": 1,
        "last_resume_return_value": 7,
        "last_operation_failure_code": 0,
    },
    "task": EXPECTED_RUNTIME_ABI_PAYLOADS["task"],
    "actor": {
        "copy_status": 0,
        "replay": 1,
        "guard": 1,
        "isolation": 1,
        "bound": 1,
        "enqueued": 23,
        "drained": 23,
        "replay_proof_call_count": 1,
        "race_guard_call_count": 1,
        "isolation_thunk_call_count": 1,
        "bind_executor_call_count": 1,
        "mailbox_enqueue_call_count": 1,
        "mailbox_drain_call_count": 1,
        "failed_operation_count": 0,
        "actor_executor_binding_count": 1,
        "last_replay_proof_executor_tag": 1,
        "last_race_guard_executor_tag": 1,
        "last_isolation_executor_tag": 1,
        "last_bound_actor_handle": 41,
        "last_bound_executor_tag": 1,
        "last_mailbox_actor_handle": 41,
        "last_mailbox_enqueued_value": 23,
        "last_mailbox_executor_tag": 1,
        "last_mailbox_depth": 0,
        "last_mailbox_drained_value": 23,
        "last_expected_executor_tag": 1,
        "mailbox_identity_guard_passed": 1,
        "executor_binding_guard_passed": 1,
        "last_operation_succeeded": 1,
        "last_failure_code": 0,
        "failure_copy_status": 0,
        "invalid_executor": 0,
        "invalid_actor": 0,
        "unbound_actor": 0,
        "executor_mismatch": 0,
        "empty_drain": 0,
        "failure_failed_operation_count": 5,
        "failure_last_operation_succeeded": 0,
        "failure_last_failure_code": 3,
        "failure_actor_executor_binding_count": 1,
        "failure_last_expected_executor_tag": 1,
        "failure_mailbox_identity_guard_passed": 1,
        "failure_executor_binding_guard_passed": 1,
    },
}


def expect_probe_payload_fields(
    payload: Mapping[str, object],
    expected_payload: Mapping[str, object],
    probe_description: str,
) -> None:
    for field_name, expected_value in expected_payload.items():
        expect(
            payload.get(field_name) == expected_value,
            f"expected {probe_description} to preserve {field_name}",
        )


__all__ = [
    "EXPECTED_LIVE_RUNTIME_PAYLOADS",
    "EXPECTED_RUNTIME_ABI_PAYLOADS",
    "expect_probe_payload_fields",
]
