#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

struct Objc3CrossModuleRuntimeLinkPlanImportedInput {
  std::string module_name;
  std::string import_surface_artifact_path;
  std::string registration_manifest_artifact_path;
  std::string object_artifact_path;
  std::string discovery_artifact_path;
  std::string linker_response_artifact_path;
  std::string translation_unit_identity_model;
  std::string translation_unit_identity_key;
  std::string object_format;
  std::string runtime_support_library_archive_relative_path;
  std::uint64_t translation_unit_registration_order_ordinal = 0;
  std::size_t class_descriptor_count = 0;
  std::size_t protocol_descriptor_count = 0;
  std::size_t category_descriptor_count = 0;
  std::size_t property_descriptor_count = 0;
  std::size_t ivar_descriptor_count = 0;
  std::size_t total_descriptor_count = 0;
  std::vector<std::string> driver_linker_flags;
  bool ready_for_live_registration_discovery_replay = false;
  bool ready_for_live_restart_hardening = false;
  std::string bootstrap_live_registration_contract_id;
  std::string bootstrap_live_restart_hardening_contract_id;
  std::string bootstrap_live_replay_registered_images_symbol;
  std::string bootstrap_live_reset_replay_state_snapshot_symbol;
  std::string bootstrap_live_restart_reset_for_testing_symbol;
  std::string bootstrap_live_restart_replay_registered_images_symbol;
  std::string bootstrap_live_restart_reset_replay_state_snapshot_symbol;
  bool error_handling_result_and_bridging_artifact_replay_present = false;
  bool error_handling_binary_artifact_replay_ready = false;
  bool error_handling_runtime_import_artifact_ready = false;
  bool error_handling_separate_compilation_replay_ready = false;
  bool error_handling_deterministic = false;
  std::string error_handling_contract_id;
  std::string error_handling_source_contract_id;
  std::string error_handling_result_and_bridging_artifact_replay_key;
  std::string error_handling_error_handling_replay_key;
  std::string error_handling_throws_replay_key;
  std::string error_handling_result_like_replay_key;
  std::string error_handling_ns_error_replay_key;
  std::string error_handling_unwind_replay_key;
  bool concurrency_actor_mailbox_runtime_import_present = false;
  std::size_t concurrency_actor_interface_sites = 0;
  std::size_t concurrency_actor_method_sites = 0;
  std::size_t concurrency_actor_metadata_record_sites = 0;
  std::size_t concurrency_actor_nonisolated_entry_sites = 0;
  std::size_t concurrency_actor_executor_affinity_sites = 0;
  std::size_t concurrency_actor_hop_artifact_sites = 0;
  std::size_t concurrency_actor_isolation_thunk_sites = 0;
  std::size_t concurrency_actor_replay_proof_dependency_sites = 0;
  std::size_t concurrency_actor_race_guard_dependency_sites = 0;
  std::size_t concurrency_actor_task_handoff_sites = 0;
  std::size_t concurrency_actor_guard_blocked_sites = 0;
  std::size_t concurrency_actor_contract_violation_sites = 0;
  bool concurrency_actor_mailbox_runtime_ready = false;
  bool concurrency_actor_mailbox_runtime_deterministic = false;
  std::string concurrency_actor_contract_id;
  std::string concurrency_actor_source_contract_id;
  std::string concurrency_actor_mailbox_runtime_replay_key;
  std::string concurrency_actor_lowering_replay_key;
  std::string concurrency_actor_isolation_lowering_replay_key;
  bool interop_ffi_metadata_interface_preservation_present = false;
  bool interop_ffi_runtime_import_artifact_ready = false;
  bool interop_ffi_separate_compilation_preservation_ready = false;
  bool interop_ffi_deterministic = false;
  std::string interop_ffi_contract_id;
  std::string interop_ffi_source_contract_id;
  std::string interop_ffi_preservation_contract_id;
  std::string interop_ffi_replay_key;
  std::string interop_ffi_lowering_replay_key;
  std::string interop_ffi_preservation_replay_key;
  std::size_t interop_ffi_local_foreign_callable_count = 0;
  std::size_t interop_ffi_local_metadata_preservation_sites = 0;
  std::size_t interop_ffi_local_interface_annotation_sites = 0;
  bool interop_header_module_bridge_generation_present = false;
  bool interop_header_module_bridge_runtime_generation_ready = false;
  bool interop_header_module_bridge_cross_module_packaging_ready = false;
  bool interop_header_module_bridge_deterministic = false;
  std::string interop_header_module_bridge_contract_id;
  std::string interop_header_module_bridge_source_contract_id;
  std::string interop_header_module_bridge_preservation_contract_id;
  std::string interop_header_module_bridge_replay_key;
  std::string interop_header_module_bridge_preservation_replay_key;
  std::string interop_bridge_header_artifact_relative_path;
  std::string interop_bridge_module_artifact_relative_path;
  std::string interop_bridge_artifact_relative_path;
  std::size_t interop_header_module_bridge_local_foreign_callable_count = 0;
  bool metaprogramming_macro_host_process_cache_runtime_integration_present = false;
  bool metaprogramming_macro_host_process_cache_runtime_ready = false;
  bool metaprogramming_macro_host_process_cache_separate_compilation_ready = false;
  bool metaprogramming_macro_host_process_cache_deterministic = false;
  std::string metaprogramming_macro_host_process_cache_contract_id;
  std::string metaprogramming_macro_host_process_cache_source_contract_id;
  std::string metaprogramming_macro_host_process_cache_replay_key;
  std::string metaprogramming_macro_host_process_cache_host_executable_relative_path;
  std::string metaprogramming_macro_host_process_cache_root_relative_path;
  bool block_ownership_artifact_preservation_present = false;
  bool block_ownership_runtime_import_artifact_ready = false;
  bool block_ownership_separate_compilation_preservation_ready = false;
  bool block_ownership_runtime_support_library_link_wiring_ready = false;
  bool block_ownership_deterministic = false;
  std::string block_ownership_contract_id;
  std::string block_ownership_source_contract_id;
  std::string block_ownership_object_invoke_thunk_lowering_contract_id;
  std::string block_ownership_byref_helper_lowering_contract_id;
  std::string block_ownership_escape_runtime_hook_lowering_contract_id;
  std::string block_ownership_runtime_support_library_link_wiring_contract_id;
  std::string block_ownership_retain_release_operation_lowering_contract_id;
  std::string block_ownership_autoreleasepool_scope_lowering_contract_id;
  std::string block_ownership_replay_key;
  std::string block_ownership_retain_release_operation_lowering_replay_key;
  std::string block_ownership_autoreleasepool_scope_lowering_replay_key;
  std::size_t block_ownership_local_block_literal_sites = 0;
  std::size_t block_ownership_local_invoke_trampoline_symbolized_sites = 0;
  std::size_t block_ownership_local_copy_helper_required_sites = 0;
  std::size_t block_ownership_local_dispose_helper_required_sites = 0;
  std::size_t block_ownership_local_copy_helper_symbolized_sites = 0;
  std::size_t block_ownership_local_dispose_helper_symbolized_sites = 0;
  std::size_t block_ownership_local_escape_to_heap_sites = 0;
  std::size_t block_ownership_local_byref_layout_symbolized_sites = 0;
  std::size_t block_ownership_local_arc_ownership_qualified_sites = 0;
  std::size_t block_ownership_local_arc_retain_insertion_sites = 0;
  std::size_t block_ownership_local_arc_release_insertion_sites = 0;
  std::size_t block_ownership_local_arc_autorelease_insertion_sites = 0;
  std::size_t block_ownership_local_arc_contract_violation_sites = 0;
  std::size_t block_ownership_local_autoreleasepool_scope_sites = 0;
  std::size_t block_ownership_local_autoreleasepool_scope_symbolized_sites = 0;
  unsigned block_ownership_local_autoreleasepool_max_scope_depth = 0;
  std::size_t
      block_ownership_local_autoreleasepool_scope_entry_transition_sites = 0;
  std::size_t
      block_ownership_local_autoreleasepool_scope_exit_transition_sites = 0;
  std::size_t block_ownership_local_autoreleasepool_contract_violation_sites =
      0;
  bool block_ownership_arc_cleanup_preservation_ready = false;
  bool storage_reflection_artifact_preservation_present = false;
  bool storage_reflection_runtime_import_artifact_ready = false;
  bool storage_reflection_separate_compilation_preservation_ready = false;
  bool storage_reflection_deterministic = false;
  std::string storage_reflection_contract_id;
  std::string storage_reflection_source_contract_id;
  std::string
      storage_reflection_dispatch_and_synthesized_accessor_lowering_surface_contract_id;
  std::string
      storage_reflection_executable_property_accessor_layout_lowering_contract_id;
  std::string storage_reflection_executable_ivar_layout_emission_contract_id;
  std::string
      storage_reflection_executable_synthesized_accessor_property_lowering_contract_id;
  std::string storage_reflection_replay_key;
  std::size_t storage_reflection_local_property_descriptor_count = 0;
  std::size_t storage_reflection_local_ivar_descriptor_count = 0;
  std::size_t storage_reflection_implementation_owned_property_entries = 0;
  std::size_t storage_reflection_synthesized_accessor_owner_entries = 0;
  std::size_t storage_reflection_synthesized_getter_entries = 0;
  std::size_t storage_reflection_synthesized_setter_entries = 0;
  std::size_t storage_reflection_synthesized_accessor_entries = 0;
  std::size_t storage_reflection_current_property_read_entries = 0;
  std::size_t storage_reflection_current_property_write_entries = 0;
  std::size_t storage_reflection_current_property_exchange_entries = 0;
  std::size_t storage_reflection_weak_current_property_load_entries = 0;
  std::size_t storage_reflection_weak_current_property_store_entries = 0;
  std::size_t storage_reflection_ivar_layout_entries = 0;
  std::size_t storage_reflection_ivar_layout_owner_entries = 0;
};

struct Objc3CrossModuleRuntimeLinkPlanArtifactInputs {
  std::string contract_id;
  std::string source_orchestration_contract_id;
  std::string import_surface_contract_id;
  std::string registration_manifest_contract_id;
  std::string payload_model;
  std::string artifact_relative_path;
  std::string linker_response_artifact_relative_path;
  std::string authority_model;
  std::string packaging_model;
  std::string registration_scope_model;
  std::string link_object_order_model;
  std::string local_module_name;
  std::string local_import_surface_artifact_relative_path;
  std::string local_registration_manifest_artifact_relative_path;
  std::string local_object_artifact_relative_path;
  std::string runtime_support_library_archive_relative_path;
  std::string object_format;
  std::string local_translation_unit_identity_model;
  std::string local_translation_unit_identity_key;
  std::uint64_t local_translation_unit_registration_order_ordinal = 0;
  std::size_t local_class_descriptor_count = 0;
  std::size_t local_protocol_descriptor_count = 0;
  std::size_t local_category_descriptor_count = 0;
  std::size_t local_property_descriptor_count = 0;
  std::size_t local_ivar_descriptor_count = 0;
  std::size_t local_total_descriptor_count = 0;
  std::size_t local_block_ownership_block_literal_sites = 0;
  std::size_t local_block_ownership_invoke_trampoline_symbolized_sites = 0;
  std::size_t local_block_ownership_copy_helper_required_sites = 0;
  std::size_t local_block_ownership_dispose_helper_required_sites = 0;
  std::size_t local_block_ownership_copy_helper_symbolized_sites = 0;
  std::size_t local_block_ownership_dispose_helper_symbolized_sites = 0;
  std::size_t local_block_ownership_escape_to_heap_sites = 0;
  std::size_t local_block_ownership_byref_layout_symbolized_sites = 0;
  std::size_t local_storage_reflection_implementation_owned_property_entries = 0;
  std::size_t local_storage_reflection_synthesized_accessor_owner_entries = 0;
  std::size_t local_storage_reflection_synthesized_getter_entries = 0;
  std::size_t local_storage_reflection_synthesized_setter_entries = 0;
  std::size_t local_storage_reflection_synthesized_accessor_entries = 0;
  std::size_t local_storage_reflection_current_property_read_entries = 0;
  std::size_t local_storage_reflection_current_property_write_entries = 0;
  std::size_t local_storage_reflection_current_property_exchange_entries = 0;
  std::size_t local_storage_reflection_weak_current_property_load_entries = 0;
  std::size_t local_storage_reflection_weak_current_property_store_entries = 0;
  std::size_t local_storage_reflection_ivar_layout_entries = 0;
  std::size_t local_storage_reflection_ivar_layout_owner_entries = 0;
  std::vector<std::string> local_driver_linker_flags;
  std::string expected_error_handling_contract_id;
  std::string expected_error_handling_source_contract_id;
  std::string expected_concurrency_actor_contract_id;
  std::string expected_concurrency_actor_source_contract_id;
  std::string expected_interop_ffi_contract_id;
  std::string expected_interop_ffi_source_contract_id;
  std::string expected_interop_ffi_preservation_contract_id;
  std::string expected_interop_header_module_bridge_contract_id;
  std::string expected_interop_header_module_bridge_source_contract_id;
  std::string expected_interop_header_module_bridge_preservation_contract_id;
  std::string expected_interop_bridge_header_artifact_relative_path;
  std::string expected_interop_bridge_module_artifact_relative_path;
  std::string expected_interop_bridge_artifact_relative_path;
  std::string expected_metaprogramming_host_cache_contract_id;
  std::string expected_metaprogramming_host_cache_source_contract_id;
  std::string expected_metaprogramming_host_cache_executable_relative_path;
  std::string expected_metaprogramming_host_cache_root_relative_path;
  std::string expected_block_ownership_contract_id;
  std::string expected_block_ownership_source_contract_id;
  std::string expected_block_ownership_object_invoke_thunk_lowering_contract_id;
  std::string expected_block_ownership_byref_helper_lowering_contract_id;
  std::string expected_block_ownership_escape_runtime_hook_lowering_contract_id;
  std::string expected_block_ownership_runtime_support_library_link_wiring_contract_id;
  std::string expected_block_ownership_retain_release_operation_lowering_contract_id;
  std::string expected_block_ownership_autoreleasepool_scope_lowering_contract_id;
  std::string expected_storage_reflection_contract_id;
  std::string expected_storage_reflection_source_contract_id;
  std::string
      expected_storage_reflection_dispatch_and_synthesized_accessor_lowering_surface_contract_id;
  std::string
      expected_storage_reflection_executable_property_accessor_layout_lowering_contract_id;
  std::string expected_storage_reflection_executable_ivar_layout_emission_contract_id;
  std::string
      expected_storage_reflection_executable_synthesized_accessor_property_lowering_contract_id;
  std::string expected_bootstrap_live_registration_contract_id;
  std::string expected_bootstrap_live_restart_hardening_contract_id;
  std::string expected_bootstrap_replay_registered_images_symbol;
  std::string expected_bootstrap_reset_replay_state_snapshot_symbol;
  std::string expected_bootstrap_reset_for_testing_symbol;
  std::vector<std::string> direct_import_surface_artifact_paths;
  std::vector<Objc3CrossModuleRuntimeLinkPlanImportedInput> imported_inputs;
};

bool TryBuildObjc3CrossModuleRuntimeLinkPlanArtifact(
    const Objc3CrossModuleRuntimeLinkPlanArtifactInputs &inputs,
    std::string &plan_json,
    std::string &linker_response_payload,
    std::string &error);
