from __future__ import annotations

from .evidence_links import boundary_inventory_path, owner_contract
from .models import EvidenceFamily


SECURITY_HARDENING = "security_hardening"
OBJECT_MODEL_CLOSURE = "object_model_closure"
RUNTIME_CORRECTIVE = "runtime_corrective"
METAPROGRAMMING_INTEROP_CLOSURE = "metaprogramming_interop_closure"


EVIDENCE_FAMILIES: dict[str, EvidenceFamily] = {
    SECURITY_HARDENING: EvidenceFamily(
        boundary_inventory=boundary_inventory_path(SECURITY_HARDENING),
        owners=(
            owner_contract(
                SECURITY_HARDENING,
                "security_response_owner",
                "security_response_disclosure_policy.json",
                supporting_contracts=("response_drill_contract.json",),
                summary_script="build_security_hardening_response_policy_summary.py",
                check_scripts=("check_security_hardening_response_drill.py",),
            ),
            owner_contract(
                SECURITY_HARDENING,
                "release_key_owner",
                "installer_update_release_key_hardening_policy.json",
                summary_script="build_security_hardening_release_key_policy_summary.py",
            ),
            owner_contract(
                SECURITY_HARDENING,
                "supply_chain_owner",
                "macro_package_provenance_trust_policy.json",
                supporting_contracts=(
                    "supply_chain_audit_contract.json",
                    "source_surface.json",
                    "schema_surface.json",
                ),
                summary_script="build_security_hardening_macro_trust_policy_summary.py",
                check_scripts=(
                    "check_security_hardening_supply_chain_audit.py",
                    "check_security_hardening_source_surface.py",
                    "check_security_hardening_schema_surface.py",
                ),
            ),
            owner_contract(
                SECURITY_HARDENING,
                "runtime_hardening_owner",
                "runtime_hardening_contract.json",
                summary_script="build_security_hardening_artifact_contract_summary.py",
                check_scripts=(
                    "check_security_hardening_runtime_hardening.py",
                    "check_objc3c_security_hardening_integration.py",
                    "check_objc3c_security_hardening_end_to_end.py",
                ),
            ),
        ),
    ),
    OBJECT_MODEL_CLOSURE: EvidenceFamily(
        boundary_inventory=boundary_inventory_path(OBJECT_MODEL_CLOSURE),
        owners=(
            owner_contract(
                OBJECT_MODEL_CLOSURE,
                "object_model_semantic_owner",
                "realized_object_graph_reflection_semantic_model.json",
                summary_script="build_object_model_closure_semantic_summary.py",
                check_scripts=(
                    "check_object_model_closure_live_property_reflection.py",
                ),
            ),
            owner_contract(
                OBJECT_MODEL_CLOSURE,
                "object_model_runtime_owner",
                "realized_object_graph_runtime_implementation_contract.json",
                summary_script=(
                    "build_object_model_closure_runtime_implementation_summary.py"
                ),
                check_scripts=(
                    "check_object_model_closure_live_runtime.py",
                    "check_object_model_closure_realization_lowering.py",
                ),
            ),
            owner_contract(
                OBJECT_MODEL_CLOSURE,
                "object_model_artifact_owner",
                "object_model_reflection_artifact_runtime_registration_contract.json",
                summary_script=(
                    "build_object_model_closure_artifact_registration_summary.py"
                ),
                check_scripts=(
                    "check_object_model_closure_property_reflection_artifact.py",
                ),
            ),
            owner_contract(
                OBJECT_MODEL_CLOSURE,
                "object_model_workload_owner",
                "loader_category_protocol_workload_map.json",
                summary_script="build_object_model_closure_workload_summary.py",
            ),
            owner_contract(
                OBJECT_MODEL_CLOSURE,
                "object_model_executable_proof_owner",
                "executable_proof_abi_contract.json",
                summary_script=(
                    "build_object_model_closure_executable_proof_summary.py"
                ),
            ),
        ),
    ),
    RUNTIME_CORRECTIVE: EvidenceFamily(
        boundary_inventory=boundary_inventory_path(RUNTIME_CORRECTIVE),
        owners=(
            owner_contract(
                RUNTIME_CORRECTIVE,
                "runtime_corrective_dispatch_owner",
                "realized_dispatch_semantic_model.json",
                supporting_contracts=(
                    "dispatch_lowering_implementation_contract.json",
                ),
                summary_script="build_runtime_corrective_dispatch_summary.py",
                check_scripts=(
                    "check_runtime_corrective_live_dispatch_runtime.py",
                    "check_runtime_corrective_dispatch_lowering.py",
                ),
            ),
            owner_contract(
                RUNTIME_CORRECTIVE,
                "runtime_corrective_native_output_owner",
                "native_output_truth_policy.json",
                summary_script=(
                    "build_runtime_corrective_native_output_truth_summary.py"
                ),
            ),
            owner_contract(
                RUNTIME_CORRECTIVE,
                "runtime_corrective_lowering_provenance_owner",
                "lowering_provenance_artifact_contract.json",
                summary_script=(
                    "build_runtime_corrective_lowering_provenance_summary.py"
                ),
                check_scripts=(
                    "check_runtime_corrective_dispatch_lowering.py",
                    "check_runtime_corrective_synthesized_accessor_lowering.py",
                ),
            ),
            owner_contract(
                RUNTIME_CORRECTIVE,
                "runtime_corrective_accessor_owner",
                "synthesized_accessor_semantic_model.json",
                supporting_contracts=(
                    "synthesized_accessor_lowering_implementation_contract.json",
                ),
                summary_script=(
                    "build_runtime_corrective_synthesized_accessor_summary.py"
                ),
                check_scripts=(
                    "check_runtime_corrective_synthesized_accessor_runtime.py",
                    "check_runtime_corrective_synthesized_accessor_lowering.py",
                ),
            ),
            owner_contract(
                RUNTIME_CORRECTIVE,
                "runtime_corrective_executable_proof_owner",
                "executable_proof_abi_contract.json",
                summary_script=(
                    "build_runtime_corrective_executable_proof_summary.py"
                ),
                check_scripts=("check_runtime_corrective_closeout_gate.py",),
            ),
        ),
    ),
    METAPROGRAMMING_INTEROP_CLOSURE: EvidenceFamily(
        boundary_inventory=boundary_inventory_path(METAPROGRAMMING_INTEROP_CLOSURE),
        owners=(
            owner_contract(
                METAPROGRAMMING_INTEROP_CLOSURE,
                "metaprogramming_runtime_owner",
                "metaprogramming_runtime_semantic_model.json",
                summary_script=(
                    "build_metaprogramming_interop_closure_semantic_summary.py"
                ),
                check_scripts=(
                    "check_metaprogramming_interop_closure_live_metaprogramming_runtime.py",
                ),
            ),
            owner_contract(
                METAPROGRAMMING_INTEROP_CLOSURE,
                "property_behavior_owner",
                "property_behavior_runtime_materialization_policy.json",
                supporting_contracts=(
                    "property_behavior_macro_runtime_materialization_implementation_contract.json",
                ),
                summary_script=(
                    "build_metaprogramming_interop_closure_property_behavior_policy_summary.py"
                ),
            ),
            owner_contract(
                METAPROGRAMMING_INTEROP_CLOSURE,
                "interop_runtime_owner",
                "interop_runtime_ownership_abi_policy.json",
                supporting_contracts=(
                    "interop_bridge_cross_module_artifact_implementation_contract.json",
                ),
                summary_script=(
                    "build_metaprogramming_interop_closure_interop_policy_summary.py"
                ),
                check_scripts=(
                    "check_metaprogramming_interop_closure_live_interop_runtime.py",
                    "check_metaprogramming_interop_closure_interop_lowering.py",
                ),
            ),
            owner_contract(
                METAPROGRAMMING_INTEROP_CLOSURE,
                "metaprogramming_lowering_owner",
                "lowering_runtime_artifact_contract.json",
                summary_script=(
                    "build_metaprogramming_interop_closure_artifact_summary.py"
                ),
                check_scripts=(
                    "check_metaprogramming_interop_closure_metaprogramming_lowering.py",
                ),
            ),
            owner_contract(
                METAPROGRAMMING_INTEROP_CLOSURE,
                "runtime_abi_packaged_proof_owner",
                "executable_proof_abi_contract.json",
                supporting_contracts=("packaged_interop_proof_contract.json",),
                summary_script=(
                    "build_metaprogramming_interop_closure_executable_proof_summary.py"
                ),
                check_scripts=(
                    "check_metaprogramming_interop_closure_packaged_interop_proof.py",
                ),
            ),
        ),
    ),
}


__all__ = [
    "EVIDENCE_FAMILIES",
    "METAPROGRAMMING_INTEROP_CLOSURE",
    "OBJECT_MODEL_CLOSURE",
    "RUNTIME_CORRECTIVE",
    "SECURITY_HARDENING",
]
