from objc3c_parser_sema_integration_support import (
    PASS_MANAGER_CONTRACT,
    SEMA_HANDOFF_SCAFFOLD,
    SEMA_PASS_MANAGER,
    assert_contains_all,
    read_source,
)

PARSER_SEMA_STRUCT_SNIPPETS = (
    "struct Objc3ParserSemaConformanceMatrix {",
    "struct Objc3ParserSemaConformanceCorpus {",
    "struct Objc3ParserSemaPerformanceQualityGuardrails {",
    "struct Objc3ParserSemaCrossLaneIntegrationSync {",
    "struct Objc3ParserSemaDocsRunbookSync {",
    "struct Objc3ParserSemaReleaseCandidateReplayDryRun {",
    "struct Objc3ParserSemaAdvancedCoreShard1 {",
    "struct Objc3ParserSemaAdvancedEdgeCompatibilityShard1 {",
    "struct Objc3ParserSemaAdvancedDiagnosticsShard1 {",
    "struct Objc3ParserSemaAdvancedConformanceShard1 {",
    "struct Objc3ParserSemaAdvancedIntegrationShard1 {",
    "struct Objc3ParserSemaAdvancedPerformanceShard1 {",
    "struct Objc3ParserSemaAdvancedCoreShard2 {",
    "struct Objc3ParserSemaAdvancedEdgeCompatibilityShard2 {",
    "struct Objc3ParserSemaAdvancedDiagnosticsShard2 {",
    "struct Objc3ParserSemaIntegrationCloseoutSignoff {",
)
PARSER_SEMA_FIELD_SNIPPETS = (
    "Objc3ParserSemaConformanceMatrix parser_sema_conformance_matrix;",
    "Objc3ParserSemaConformanceCorpus parser_sema_conformance_corpus;",
    "Objc3ParserSemaPerformanceQualityGuardrails parser_sema_performance_quality_guardrails;",
    "Objc3ParserSemaCrossLaneIntegrationSync parser_sema_cross_lane_integration_sync;",
    "Objc3ParserSemaDocsRunbookSync parser_sema_docs_runbook_sync;",
    "Objc3ParserSemaReleaseCandidateReplayDryRun parser_sema_release_candidate_replay_dry_run;",
    "Objc3ParserSemaAdvancedCoreShard1 parser_sema_advanced_core_shard1;",
    "Objc3ParserSemaAdvancedEdgeCompatibilityShard1 parser_sema_advanced_edge_compatibility_shard1;",
    "Objc3ParserSemaAdvancedDiagnosticsShard1 parser_sema_advanced_diagnostics_shard1;",
    "Objc3ParserSemaAdvancedConformanceShard1 parser_sema_advanced_conformance_shard1;",
    "Objc3ParserSemaAdvancedIntegrationShard1 parser_sema_advanced_integration_shard1;",
    "Objc3ParserSemaAdvancedPerformanceShard1 parser_sema_advanced_performance_shard1;",
    "Objc3ParserSemaAdvancedCoreShard2 parser_sema_advanced_core_shard2;",
    "Objc3ParserSemaAdvancedEdgeCompatibilityShard2 parser_sema_advanced_edge_compatibility_shard2;",
    "Objc3ParserSemaAdvancedDiagnosticsShard2 parser_sema_advanced_diagnostics_shard2;",
    "Objc3ParserSemaIntegrationCloseoutSignoff parser_sema_integration_closeout_signoff;",
)
PARSER_SEMA_DETERMINISM_FIELDS = (
    "bool deterministic_parser_sema_conformance_matrix = false;",
    "bool deterministic_parser_sema_conformance_corpus = false;",
    "bool deterministic_parser_sema_performance_quality_guardrails = false;",
    "bool deterministic_parser_sema_cross_lane_integration_sync = false;",
    "bool deterministic_parser_sema_docs_runbook_sync = false;",
    "bool deterministic_parser_sema_release_candidate_replay_dry_run = false;",
    "bool deterministic_parser_sema_advanced_core_shard1 = false;",
    "bool deterministic_parser_sema_advanced_edge_compatibility_shard1 = false;",
    "bool deterministic_parser_sema_advanced_diagnostics_shard1 = false;",
    "bool deterministic_parser_sema_advanced_conformance_shard1 = false;",
    "bool deterministic_parser_sema_advanced_integration_shard1 = false;",
    "bool deterministic_parser_sema_advanced_performance_shard1 = false;",
    "bool deterministic_parser_sema_advanced_core_shard2 = false;",
    "bool deterministic_parser_sema_advanced_edge_compatibility_shard2 = false;",
    "bool deterministic_parser_sema_advanced_diagnostics_shard2 = false;",
    "bool deterministic_parser_sema_integration_closeout_signoff = false;",
)
HANDOFF_BUILDERS = (
    "BuildObjc3ParserSemaConformanceMatrix(",
    "BuildObjc3ParserSemaConformanceCorpus(",
    "BuildObjc3ParserSemaPerformanceQualityGuardrails(",
    "BuildObjc3ParserSemaCrossLaneIntegrationSync(",
    "BuildObjc3ParserSemaDocsRunbookSync(",
    "BuildObjc3ParserSemaReleaseCandidateReplayDryRun(",
    "BuildObjc3ParserSemaAdvancedCoreShard1(",
    "BuildObjc3ParserSemaAdvancedEdgeCompatibilityShard1(",
    "BuildObjc3ParserSemaAdvancedDiagnosticsShard1(",
    "BuildObjc3ParserSemaAdvancedConformanceShard1(",
    "BuildObjc3ParserSemaAdvancedIntegrationShard1(",
    "BuildObjc3ParserSemaAdvancedPerformanceShard1(",
    "BuildObjc3ParserSemaAdvancedCoreShard2(",
    "BuildObjc3ParserSemaAdvancedEdgeCompatibilityShard2(",
    "BuildObjc3ParserSemaAdvancedDiagnosticsShard2(",
    "BuildObjc3ParserSemaIntegrationCloseoutSignoff(",
)
HANDOFF_ASSIGNMENTS = (
    "scaffold.parser_sema_conformance_matrix = BuildObjc3ParserSemaConformanceMatrix(",
    "scaffold.parser_sema_conformance_corpus =",
    "scaffold.parser_sema_performance_quality_guardrails =",
    "scaffold.parser_sema_cross_lane_integration_sync =",
    "scaffold.parser_sema_docs_runbook_sync =",
    "scaffold.parser_sema_release_candidate_replay_dry_run =",
    "scaffold.parser_sema_advanced_core_shard1 =",
    "scaffold.parser_sema_advanced_edge_compatibility_shard1 =",
    "scaffold.parser_sema_advanced_diagnostics_shard1 =",
    "scaffold.parser_sema_advanced_conformance_shard1 =",
    "scaffold.parser_sema_advanced_integration_shard1 =",
    "scaffold.parser_sema_advanced_performance_shard1 =",
    "scaffold.parser_sema_advanced_core_shard2 =",
    "scaffold.parser_sema_advanced_edge_compatibility_shard2 =",
    "scaffold.parser_sema_advanced_diagnostics_shard2 =",
    "scaffold.parser_sema_integration_closeout_signoff =",
)
PASS_MANAGER_RESULT_ASSIGNMENTS = (
    "result.parser_sema_conformance_matrix = handoff.parser_sema_conformance_matrix;",
    "result.parser_sema_conformance_corpus = handoff.parser_sema_conformance_corpus;",
    "result.parser_sema_performance_quality_guardrails =",
    "result.parser_sema_cross_lane_integration_sync =",
    "result.parser_sema_docs_runbook_sync =",
    "result.parser_sema_release_candidate_replay_dry_run =",
    "result.parser_sema_advanced_core_shard1 =",
    "result.parser_sema_advanced_edge_compatibility_shard1 =",
    "result.parser_sema_advanced_diagnostics_shard1 =",
    "result.parser_sema_advanced_conformance_shard1 =",
    "result.parser_sema_advanced_integration_shard1 =",
    "result.parser_sema_advanced_performance_shard1 =",
    "result.parser_sema_advanced_core_shard2 =",
    "result.parser_sema_advanced_edge_compatibility_shard2 =",
    "result.parser_sema_advanced_diagnostics_shard2 =",
    "result.parser_sema_integration_closeout_signoff =",
)
PASS_MANAGER_DETERMINISM_ASSIGNMENTS = (
    "result.deterministic_parser_sema_conformance_matrix =",
    "result.deterministic_parser_sema_conformance_corpus =",
    "result.deterministic_parser_sema_performance_quality_guardrails =",
    "result.deterministic_parser_sema_cross_lane_integration_sync =",
    "result.deterministic_parser_sema_docs_runbook_sync =",
    "result.deterministic_parser_sema_release_candidate_replay_dry_run =",
    "result.deterministic_parser_sema_advanced_core_shard1 =",
    "result.deterministic_parser_sema_advanced_edge_compatibility_shard1 =",
    "result.deterministic_parser_sema_advanced_diagnostics_shard1 =",
    "result.deterministic_parser_sema_advanced_conformance_shard1 =",
    "result.deterministic_parser_sema_advanced_integration_shard1 =",
    "result.deterministic_parser_sema_advanced_performance_shard1 =",
    "result.deterministic_parser_sema_advanced_core_shard2 =",
    "result.deterministic_parser_sema_advanced_edge_compatibility_shard2 =",
    "result.deterministic_parser_sema_advanced_diagnostics_shard2 =",
    "result.deterministic_parser_sema_integration_closeout_signoff =",
)
FAIL_CLOSED_CHECKS = (
    "if (!result.deterministic_parser_sema_conformance_matrix) {",
    "if (!result.deterministic_parser_sema_conformance_corpus) {",
    "if (!result.deterministic_parser_sema_performance_quality_guardrails) {",
    "if (!result.deterministic_parser_sema_cross_lane_integration_sync) {",
    "if (!result.deterministic_parser_sema_docs_runbook_sync) {",
    "if (!result.deterministic_parser_sema_release_candidate_replay_dry_run) {",
    "if (!result.deterministic_parser_sema_advanced_core_shard1) {",
    "if (!result.deterministic_parser_sema_advanced_edge_compatibility_shard1) {",
    "if (!result.deterministic_parser_sema_advanced_diagnostics_shard1) {",
    "if (!result.deterministic_parser_sema_advanced_conformance_shard1) {",
    "if (!result.deterministic_parser_sema_advanced_integration_shard1) {",
    "if (!result.deterministic_parser_sema_advanced_performance_shard1) {",
    "if (!result.deterministic_parser_sema_advanced_core_shard2) {",
    "if (!result.deterministic_parser_sema_advanced_edge_compatibility_shard2) {",
    "if (!result.deterministic_parser_sema_advanced_diagnostics_shard2) {",
    "if (!result.deterministic_parser_sema_integration_closeout_signoff) {",
)
PARITY_SURFACE_ASSIGNMENTS = (
    "result.parity_surface.deterministic_parser_sema_conformance_matrix =",
    "result.parity_surface.deterministic_parser_sema_conformance_corpus =",
    "result.parity_surface.deterministic_parser_sema_performance_quality_guardrails =",
    "result.parity_surface.deterministic_parser_sema_cross_lane_integration_sync =",
    "result.parity_surface.deterministic_parser_sema_docs_runbook_sync =",
    "result.parity_surface.deterministic_parser_sema_release_candidate_replay_dry_run =",
    "result.parity_surface.deterministic_parser_sema_advanced_core_shard1 =",
    "result.parity_surface.deterministic_parser_sema_advanced_edge_compatibility_shard1 =",
    "result.parity_surface.deterministic_parser_sema_advanced_diagnostics_shard1 =",
    "result.parity_surface.deterministic_parser_sema_advanced_conformance_shard1 =",
    "result.parity_surface.deterministic_parser_sema_advanced_integration_shard1 =",
    "result.parity_surface.deterministic_parser_sema_advanced_performance_shard1 =",
    "result.parity_surface.deterministic_parser_sema_advanced_core_shard2 =",
    "result.parity_surface.deterministic_parser_sema_advanced_edge_compatibility_shard2 =",
    "result.parity_surface.deterministic_parser_sema_advanced_diagnostics_shard2 =",
    "result.parity_surface.deterministic_parser_sema_integration_closeout_signoff =",
)
CONTRACT_READINESS_GATES = (
    "surface.deterministic_parser_sema_conformance_matrix &&",
    "surface.deterministic_parser_sema_conformance_corpus &&",
    "surface.deterministic_parser_sema_performance_quality_guardrails &&",
    "surface.deterministic_parser_sema_cross_lane_integration_sync &&",
    "surface.deterministic_parser_sema_docs_runbook_sync &&",
    "surface.deterministic_parser_sema_release_candidate_replay_dry_run &&",
    "surface.deterministic_parser_sema_advanced_core_shard1 &&",
    "surface.deterministic_parser_sema_advanced_edge_compatibility_shard1 &&",
    "surface.deterministic_parser_sema_advanced_diagnostics_shard1 &&",
    "surface.deterministic_parser_sema_advanced_conformance_shard1 &&",
    "surface.deterministic_parser_sema_advanced_integration_shard1 &&",
    "surface.deterministic_parser_sema_advanced_performance_shard1 &&",
    "surface.deterministic_parser_sema_advanced_core_shard2 &&",
    "surface.deterministic_parser_sema_advanced_edge_compatibility_shard2 &&",
    "surface.deterministic_parser_sema_advanced_diagnostics_shard2 &&",
    "surface.deterministic_parser_sema_integration_closeout_signoff &&",
    "surface.parser_sema_conformance_matrix.parser_subset_count_consistent &&",
    "surface.parser_sema_conformance_corpus.required_case_count == 5u &&",
    "surface.parser_sema_performance_quality_guardrails.required_guardrail_count == 7u &&",
    "surface.parser_sema_cross_lane_integration_sync.required_sync_count == 4u &&",
    "surface.parser_sema_docs_runbook_sync.required_sync_count == 3u &&",
    "surface.parser_sema_release_candidate_replay_dry_run.required_sync_count ==",
    "surface.parser_sema_advanced_core_shard1.required_sync_count == 3u &&",
    "surface.parser_sema_advanced_edge_compatibility_shard1.required_sync_count == 3u &&",
    "surface.parser_sema_advanced_diagnostics_shard1.required_sync_count == 3u &&",
    "surface.parser_sema_advanced_conformance_shard1.required_sync_count == 3u &&",
    "surface.parser_sema_advanced_integration_shard1.required_sync_count == 3u &&",
    "surface.parser_sema_advanced_performance_shard1.required_sync_count == 3u &&",
    "surface.parser_sema_advanced_core_shard2.required_sync_count == 3u &&",
    "surface.parser_sema_advanced_edge_compatibility_shard2.required_sync_count == 3u &&",
    "surface.parser_sema_advanced_diagnostics_shard2.required_sync_count == 3u &&",
    "surface.parser_sema_integration_closeout_signoff.required_sync_count == 3u &&",
)


def test_parser_to_sema_conformance_matrix_hardening_gate_is_explicit() -> None:
    sema_handoff = read_source(SEMA_HANDOFF_SCAFFOLD)
    sema_pass_manager = read_source(SEMA_PASS_MANAGER)
    pass_manager_contract = read_source(PASS_MANAGER_CONTRACT)

    assert_contains_all(
        pass_manager_contract,
        PARSER_SEMA_STRUCT_SNIPPETS
        + PARSER_SEMA_FIELD_SNIPPETS
        + PARSER_SEMA_DETERMINISM_FIELDS
        + CONTRACT_READINESS_GATES,
    )
    assert_contains_all(sema_handoff, HANDOFF_BUILDERS + HANDOFF_ASSIGNMENTS)
    assert_contains_all(
        sema_pass_manager,
        PASS_MANAGER_RESULT_ASSIGNMENTS
        + PASS_MANAGER_DETERMINISM_ASSIGNMENTS
        + FAIL_CLOSED_CHECKS
        + PARITY_SURFACE_ASSIGNMENTS,
    )
