name: Conformance Execution Task
description: Track conformance/tooling work with test and evidence requirements.
title: "[CONFORMANCE] <short objective>"
labels:
  - priority:P1
  - area:conformance
  - type:tooling
body:
  - type: markdown
    attributes:
      value: |
        Use this template for conformance schemas, generators, checklists, and release gates.
        Include evidence and test requirements up front.
  - type: input
    id: objective
    attributes:
      label: Objective
      description: One sentence describing the expected conformance outcome.
      placeholder: Define machine-readable conformance evidence bundle schema.
    validations:
      required: true
  - type: textarea
    id: artifacts
    attributes:
      label: Required Artifacts
      description: Files to add or update.
      placeholder: |
        - schemas/<bundle>.schema.json
        - reports/conformance/<sample>.json
        - spec/conformance/<guidance>.md
    validations:
      required: true
  - type: textarea
    id: required_keys
    attributes:
      label: Required Keys / Enums
      description: Required fields, enum values, and constraints.
      placeholder: |
        - schema_id, release_id, profiles, manifests, tests, known_deviations
        - enum: core|strict|strict-concurrency|strict-system
    validations:
      required: true
  - type: textarea
    id: test_plan
    attributes:
      label: Validation and Test Plan
      description: Commands and expected pass criteria.
      placeholder: |
        - python scripts/<tool>.py --help
        - python -c "<schema validation command>"
        - npm run check:task-hygiene
    validations:
      required: true
  - type: textarea
    id: done_criteria
    attributes:
      label: Done Criteria
      description: Explicit acceptance conditions.
      placeholder: |
        - Schema validates sample payload.
        - Output is deterministic and CI-consumable.
        - Conformance docs link to artifacts.
    validations:
      required: true
  - type: input
    id: parent_epic
    attributes:
      label: Parent Epic
      description: Epic issue number.
      placeholder: "#112"
    validations:
      required: true
