#pragma once

struct Objc3IRFrontendMetadata;

struct Objc3RuntimeMetadataObjectInspectionHarnessSummary;

struct Objc3OwnershipAwareLoweringBehaviorScaffold;
struct Objc3IREmissionCompletenessScaffold;
struct Objc3LoweringPipelinePassGraphCoreFeatureSurface;
struct Objc3IREmissionCoreFeatureImplementationSurface;

struct Objc3RuntimeBootstrapLoweringSummary;
struct Objc3RuntimeRegistrationDescriptorFrontendClosureSummary;
struct Objc3RuntimeTranslationUnitRegistrationManifestSummary;

struct Objc3RuntimeMetadataSourceOwnershipBoundary;
struct Objc3RuntimeExportLegalityBoundary;
struct Objc3RuntimeExportEnforcementSummary;
struct Objc3RuntimeMetadataSectionAbiFreezeSummary;
struct Objc3RuntimeMetadataSectionPublicationSummary;
struct Objc3ExecutableMetadataTypedLoweringHandoff;

struct Objc3RuntimeSupportLibraryContractSummary;
struct Objc3RuntimeSupportLibraryCoreFeatureSummary;
struct Objc3RuntimeSupportLibraryLinkWiringSummary;

struct Objc3LightweightGenericsConstraintLoweringContract;
struct Objc3NullabilityFlowWarningPrecisionLoweringContract;
struct Objc3ProtocolQualifiedObjectTypeLoweringContract;
struct Objc3VarianceBridgeCastLoweringContract;
struct Objc3GenericMetadataAbiLoweringContract;

struct Objc3OwnershipQualifierLoweringContract;
struct Objc3RetainReleaseOperationLoweringContract;
struct Objc3AutoreleasePoolScopeLoweringContract;
struct Objc3WeakUnownedSemanticsLoweringContract;
struct Objc3ArcDiagnosticsFixitLoweringContract;
struct Objc3OwnershipSystemExtensionLoweringContract;
struct Objc3FrontendOwnershipSystemExtensionSourceClosureSummary;
struct Objc3FrontendOwnershipRetainableCFamilySourceCompletionSummary;

struct Objc3BlockLiteralCaptureLoweringContract;
struct Objc3BlockSourceModelCompletionContract;
struct Objc3BlockSourceStorageAnnotationContract;
struct Objc3BlockAbiInvokeTrampolineLoweringContract;
struct Objc3BlockStorageEscapeLoweringContract;
struct Objc3BlockCopyDisposeLoweringContract;
struct Objc3BlockDeterminismPerfBaselineLoweringContract;

struct Objc3AsyncContinuationLoweringContract;
struct Objc3AwaitLoweringSuspensionStateLoweringContract;
struct Objc3ActorIsolationSendabilityLoweringContract;
struct Objc3ActorLoweringMetadataContract;
struct Objc3TaskRuntimeInteropCancellationLoweringContract;
struct Objc3ConcurrencyReplayRaceGuardLoweringContract;

struct Objc3ExecutableMetadataDebugProjectionSummary;

struct Objc3ThrowsPropagationLoweringContract;
struct Objc3ResultLikeLoweringContract;
struct Objc3NSErrorBridgingLoweringContract;
struct Objc3UnwindCleanupLoweringContract;

struct Objc3InteropInteropLoweringContract;
struct Objc3InteropForeignCallLifetimeLoweringContract;
struct Objc3InteropFfiMetadataInterfacePreservationContract;
struct Objc3InteropHeaderModuleBridgeGenerationSummary;

struct Objc3MetaprogrammingExpansionLoweringContract;
struct Objc3MetaprogrammingSynthesizedArtifactEmissionContract;
struct Objc3IRMetaprogrammingDerivedMethodBundle;
struct Objc3IRMetaprogrammingMacroArtifactBundle;
struct Objc3IRMetaprogrammingPropertyBehaviorArtifactBundle;
struct Objc3MetaprogrammingModuleInterfaceReplayPreservationSurfaceSummary;

struct Objc3ModuleImportGraphLoweringContract;
struct Objc3NamespaceCollisionShadowingLoweringContract;
struct Objc3PublicPrivateApiPartitionLoweringContract;
struct Objc3IncrementalModuleCacheInvalidationLoweringContract;
struct Objc3CrossModuleConformanceLoweringContract;

namespace objc3::artifacts::evidence {

struct ErrorHandlingResultAndBridgingArtifactReplayEvidence;

}  // namespace objc3::artifacts::evidence
