#pragma once

#include "ir/objc3_ir_frontend_metadata_publication_error_safety_lowering_error_handling.h"
#include "ir/objc3_ir_frontend_metadata_publication_error_safety_lowering_safety_concurrency.h"
#include "ir/objc3_ir_frontend_metadata_publication_error_safety_lowering_async_diagnostic.h"
