#include "ir/objc3_ir_frontend_core_metadata_nodes.h"

#include <sstream>

#include "ir/objc3_ir_c_string.h"

std::string BuildObjc3IRFrontendNamedMetadataTable() {
  return
      "!objc3.frontend = !{!0}\n"
      "!objc3.objc_interface_implementation = !{!1}\n"
      "!objc3.objc_protocol_category = !{!2}\n"
      "!objc3.objc_class_protocol_category_linking = !{!7}\n"
      "!objc3.objc_selector_normalization = !{!3}\n"
      "!objc3.objc_property_attribute = !{!4}\n"
      "!objc3.objc_runtime_metadata_source_ownership = !{!45}\n"
      "!objc3.objc_runtime_export_legality = !{!46}\n"
      "!objc3.objc_runtime_export_enforcement = !{!47}\n"
      "!objc3.objc_runtime_metadata_section_abi = !{!48}\n"
      "!objc3.objc_runtime_metadata_section_publication = !{!49}\n"
      "!objc3.objc_runtime_metadata_layout_policy = !{!55}\n"
      "!objc3.objc_runtime_class_metaclass_emission = !{!56}\n"
      "!objc3.objc_runtime_protocol_category_emission = !{!57}\n"
      "!objc3.objc_runtime_member_table_emission = !{!58}\n"
      "!objc3.objc_runtime_selector_string_pool_emission = !{!59}\n"
      "!objc3.objc_runtime_binary_inspection_harness = !{!60}\n"
      "!objc3.objc_runtime_object_packaging_retention = !{!61}\n"
      "!objc3.objc_runtime_linker_retention = !{!62}\n"
      "!objc3.objc_runtime_archive_static_link_discovery = !{!63}\n"
      "!objc3.objc_runtime_metadata_emission_gate = !{!64}\n"
      "!objc3.objc_runtime_metadata_object_emission_closeout = !{!65}\n"
      "!objc3.objc_runtime_metadata_object_inspection = !{!50}\n"
      "!objc3.objc_runtime_support_library = !{!51}\n"
      "!objc3.objc_runtime_support_library_core_feature = !{!52}\n"
      "!objc3.objc_runtime_support_library_link_wiring = !{!53}\n"
      "!objc3.objc_executable_metadata_debug_projection = !{!54}\n"
      "!objc3.objc_object_pointer_nullability_generics = !{!5}\n"
      "!objc3.objc_symbol_graph_scope_resolution = !{!6}\n"
      "!objc3.objc_id_class_sel_object_pointer_typecheck = !{!8}\n"
      "!objc3.objc_dispatch_surface_classification = !{!66}\n"
      "!objc3.objc_executable_ivar_layout_emission = !{!67}\n"
      "!objc3.objc_executable_synthesized_accessor_property_lowering = !{!68}\n"
      "!objc3.objc_runtime_ownership_hook_emission = !{!69}\n"
      "!objc3.objc_runtime_memory_management_api = !{!70}\n"
      "!objc3.objc_runtime_memory_management_implementation = !{!71}\n"
      "!objc3.objc_ownership_runtime_gate = !{!72}\n"
      "!objc3.objc_runnable_block_runtime_gate = !{!73}\n"
      "!objc3.objc_runnable_block_execution_matrix = !{!74}\n"
      "!objc3.objc_arc_source_mode_boundary = !{!75}\n"
      "!objc3.objc_arc_mode_handling = !{!76}\n"
      "!objc3.objc_arc_semantic_rules = !{!77}\n"
      "!objc3.objc_arc_inference_lifetime = !{!78}\n"
      "!objc3.objc_arc_interaction_semantics = !{!79}\n"
      "!objc3.objc_arc_automatic_insertions = !{!80}\n"
      "!objc3.objc_arc_cleanup_weak_lifetime_hooks = !{!81}\n"
      "!objc3.objc_arc_block_autorelease_return_lowering = !{!82}\n"
      "!objc3.objc_runtime_arc_helper_api_surface = !{!83}\n"
      "!objc3.objc_runtime_arc_helper_runtime_support = !{!84}\n"
      "!objc3.objc_runtime_arc_debug_instrumentation = !{!85}\n"
      "!objc3.objc_runnable_arc_runtime_gate = !{!86}\n"
      "!objc3.objc_message_send_selector_lowering = !{!9}\n"
      "!objc3.objc_dispatch_abi_marshalling = !{!10}\n"
      "!objc3.objc_nil_receiver_semantics_foldability = !{!11}\n"
      "!objc3.objc_super_dispatch_method_family = !{!12}\n"
      "!objc3.objc_runtime_link_host_link = !{!13}\n"
      "!objc3.objc_ownership_qualifier_lowering = !{!14}\n"
      "!objc3.objc_retain_release_operation_lowering = !{!15}\n"
      "!objc3.objc_autoreleasepool_scope_lowering = !{!16}\n"
      "!objc3.objc_weak_unowned_semantics_lowering = !{!17}\n"
      "!objc3.objc_arc_diagnostics_fixit_lowering = !{!18}\n"
      "!objc3.objc_block_literal_capture_lowering = !{!19}\n"
      "!objc3.objc_block_abi_invoke_trampoline_lowering = !{!20}\n"
      "!objc3.objc_block_storage_escape_lowering = !{!21}\n"
      "!objc3.objc_block_copy_dispose_lowering = !{!22}\n"
      "!objc3.objc_block_determinism_perf_baseline_lowering = !{!23}\n"
      "!objc3.objc_lightweight_generic_constraint_lowering = !{!24}\n"
      "!objc3.objc_nullability_flow_warning_precision_lowering = !{!25}\n"
      "!objc3.objc_protocol_qualified_object_type_lowering = !{!26}\n"
      "!objc3.objc_variance_bridge_cast_lowering = !{!27}\n"
      "!objc3.objc_generic_metadata_abi_lowering = !{!28}\n"
      "!objc3.objc_module_import_graph_lowering = !{!29}\n"
      "!objc3.objc_namespace_collision_shadowing_lowering = !{!30}\n"
      "!objc3.objc_public_private_api_partition_lowering = !{!31}\n"
      "!objc3.objc_incremental_module_cache_invalidation_lowering = !{!32}\n"
      "!objc3.objc_cross_module_conformance_lowering = !{!33}\n"
      "!objc3.objc_error_handling_throws_abi_propagation_lowering = !{!87}\n"
      "!objc3.objc_error_handling_result_and_bridging_artifact_replay = !{!88}\n"
      "!objc3.objc_error_handling_error_runtime_bridge_helper = !{!89}\n"
      "!objc3.objc_error_handling_live_error_runtime_integration = !{!90}\n"
      "!objc3.objc_concurrency_continuation_runtime_helper = !{!91}\n"
      "!objc3.objc_concurrency_live_continuation_runtime_integration = !{!92}\n"
      "!objc3.objc_concurrency_task_runtime_abi_completion = !{!93}\n"
      "!objc3.objc_concurrency_scheduler_executor_runtime_contract = !{!94}\n"
      "!objc3.objc_concurrency_live_task_runtime_integration = !{!95}\n"
      "!objc3.objc_concurrency_task_runtime_hardening = !{!96}\n"
      "!objc3.objc_concurrency_actor_lowering_and_metadata = !{!97}\n"
      "!objc3.objc_dispatch_dispatch_control_lowering_contract = !{!102}\n"
      "!objc3.objc_interop_interop_lowering_and_abi_contract = !{!108}\n"
      "!objc3.objc_interop_foreign_call_and_lifetime_lowering = !{!109}\n"
      "!objc3.objc_interop_ffi_metadata_and_interface_preservation = !{!110}\n"
      "!objc3.objc_interop_bridge_packaging_and_toolchain_contract = !{!111}\n"
      "!objc3.objc_interop_header_module_and_bridge_generation = !{!112}\n"
      "!objc3.objc_metaprogramming_expansion_and_lowering_contract = !{!104}\n"
      "!objc3.objc_metaprogramming_synthesized_ast_and_ir_emission = !{!105}\n"
      "!objc3.objc_metaprogramming_module_interface_and_replay_preservation = !{!106}\n"
      "!objc3.objc_metaprogramming_expansion_host_and_runtime_boundary = !{!107}\n"
      "!objc3.objc_dispatch_dispatch_metadata_and_interface_preservation = !{!103}\n"
      "!objc3.objc_ownership_system_extension_lowering_contract = !{!98}\n"
      "!objc3.objc_ownership_borrowed_pointer_and_retainable_family_abi_completion = !{!99}\n"
      "!objc3.objc_ownership_system_helper_runtime_contract = !{!100}\n"
      "!objc3.objc_ownership_live_cleanup_retainable_runtime_integration = !{!101}\n"
      "!objc3.objc_throws_propagation_lowering = !{!34}\n"
      "!objc3.objc_unwind_cleanup_lowering = !{!35}\n"
      "!objc3.objc_ns_error_bridging_lowering = !{!36}\n"
      "!objc3.objc_unsafe_pointer_extension_lowering = !{!37}\n"
      "!objc3.objc_inline_asm_intrinsic_governance_lowering = !{!38}\n"
      "!objc3.objc_concurrency_replay_race_guard_lowering = !{!39}\n"
      "!objc3.objc_task_runtime_interop_cancellation_lowering = !{!40}\n"
      "!objc3.objc_actor_isolation_sendability_lowering = !{!41}\n"
      "!objc3.objc_await_lowering_suspension_state_lowering = !{!42}\n"
      "!objc3.objc_async_continuation_lowering = !{!43}\n"
      "!objc3.objc_error_diagnostics_recovery_lowering = !{!44}\n";
}

std::string BuildObjc3IRFrontendMetadataNode(
    const Objc3IRFrontendMetadata &metadata) {
  std::ostringstream out;
  out << "!0 = !{i32 " << static_cast<unsigned>(metadata.language_version)
      << ", !\"" << EscapeCStringLiteral(metadata.language_profile)
      << "\", i64 "
      << static_cast<unsigned long long>(
             metadata.canonical_literal_yes_rejection_sites)
      << ", i64 "
      << static_cast<unsigned long long>(
             metadata.canonical_literal_no_rejection_sites)
      << ", i64 "
      << static_cast<unsigned long long>(
             metadata.canonical_literal_null_rejection_sites)
      << ", i64 "
      << static_cast<unsigned long long>(
             metadata.canonical_literal_rejection_total())
      << "}";
  return out.str();
}
