#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "lower/objc3_lowering_contract.h"
// Historical extraction contract marker:
// #include "parse/objc3_parser_contract.h"

struct Objc3Program;

struct Objc3IRRuntimeMetadataClassMetaclassBundle {
  std::string class_name;
  std::string owner_identity;
  std::string super_bundle_owner_identity;
  bool has_super = false;
  std::size_t instance_method_count = 0;
  std::size_t class_method_count = 0;
};

struct Objc3IRRuntimeMetadataProtocolBundle {
  std::string protocol_name;
  std::string owner_identity;
  std::vector<std::string> inherited_protocol_owner_identities_lexicographic;
  std::size_t property_count = 0;
  std::size_t method_count = 0;
  bool is_forward_declaration = false;
};

struct Objc3IRRuntimeMetadataCategoryBundle {
  std::string record_kind;
  std::string class_name;
  std::string category_name;
  std::string owner_identity;
  std::string category_owner_identity;
  std::string class_owner_identity;
  std::vector<std::string> adopted_protocol_owner_identities_lexicographic;
  std::size_t property_count = 0;
  std::size_t instance_method_count = 0;
  std::size_t class_method_count = 0;
};

struct Objc3IRFrontendMetadata {
  std::uint8_t language_version = 3u;
  std::string compatibility_mode = "canonical";
  bool migration_assist = false;
  std::size_t migration_legacy_yes = 0;
  std::size_t migration_legacy_no = 0;
  std::size_t migration_legacy_null = 0;
  std::size_t declared_interfaces = 0;
  std::size_t declared_implementations = 0;
  std::size_t resolved_interface_symbols = 0;
  std::size_t resolved_implementation_symbols = 0;
  std::size_t interface_method_symbols = 0;
  std::size_t implementation_method_symbols = 0;
  std::size_t linked_implementation_symbols = 0;
  bool deterministic_interface_implementation_handoff = false;
  std::size_t declared_protocols = 0;
  std::size_t declared_categories = 0;
  std::size_t resolved_protocol_symbols = 0;
  std::size_t resolved_category_symbols = 0;
  std::size_t protocol_method_symbols = 0;
  std::size_t category_method_symbols = 0;
  std::size_t linked_category_symbols = 0;
  bool deterministic_protocol_category_handoff = false;
  std::size_t declared_class_interfaces = 0;
  std::size_t declared_class_implementations = 0;
  std::size_t resolved_class_interfaces = 0;
  std::size_t resolved_class_implementations = 0;
  std::size_t linked_class_method_symbols = 0;
  std::size_t linked_category_method_symbols = 0;
  std::size_t protocol_composition_sites = 0;
  std::size_t protocol_composition_symbols = 0;
  std::size_t category_composition_sites = 0;
  std::size_t category_composition_symbols = 0;
  std::size_t invalid_protocol_composition_sites = 0;
  bool deterministic_class_protocol_category_linking_handoff = false;
  std::size_t selector_method_declaration_entries = 0;
  std::size_t selector_normalized_method_declarations = 0;
  std::size_t selector_piece_entries = 0;
  std::size_t selector_piece_parameter_links = 0;
  bool deterministic_selector_normalization_handoff = false;
  std::size_t property_declaration_entries = 0;
  std::size_t property_attribute_entries = 0;
  std::size_t property_attribute_value_entries = 0;
  std::size_t property_accessor_modifier_entries = 0;
  std::size_t property_getter_selector_entries = 0;
  std::size_t property_setter_selector_entries = 0;
  bool deterministic_property_attribute_handoff = false;
  std::string runtime_metadata_source_ownership_contract_id;
  std::string runtime_metadata_source_schema;
  std::string runtime_metadata_ivar_source_model;
  std::size_t runtime_metadata_class_record_count = 0;
  std::size_t runtime_metadata_protocol_record_count = 0;
  std::size_t runtime_metadata_category_interface_record_count = 0;
  std::size_t runtime_metadata_category_implementation_record_count = 0;
  std::size_t runtime_metadata_property_record_count = 0;
  std::size_t runtime_metadata_method_record_count = 0;
  std::size_t runtime_metadata_ivar_record_count = 0;
  bool frontend_owns_runtime_metadata_source_records = false;
  bool runtime_metadata_source_records_ready_for_lowering = false;
  bool native_runtime_library_present = false;
  bool runtime_metadata_source_boundary_fail_closed = false;
  bool runtime_shim_test_only = true;
  bool deterministic_runtime_metadata_source_schema = false;
  std::string runtime_export_legality_contract_id;
  bool runtime_export_semantic_boundary_frozen = false;
  bool runtime_export_metadata_export_enforcement_ready = false;
  bool runtime_export_fail_closed = false;
  bool runtime_export_duplicate_runtime_identity_enforcement_pending = true;
  bool runtime_export_incomplete_declaration_export_blocking_pending = true;
  bool runtime_export_illegal_redeclaration_mix_export_blocking_pending = true;
  std::size_t runtime_export_class_record_count = 0;
  std::size_t runtime_export_protocol_record_count = 0;
  std::size_t runtime_export_category_record_count = 0;
  std::size_t runtime_export_property_record_count = 0;
  std::size_t runtime_export_method_record_count = 0;
  std::size_t runtime_export_ivar_record_count = 0;
  std::size_t runtime_export_invalid_protocol_composition_sites = 0;
  std::size_t runtime_export_property_attribute_invalid_entries = 0;
  std::size_t runtime_export_property_attribute_contract_violations = 0;
  std::size_t runtime_export_invalid_type_annotation_sites = 0;
  std::size_t runtime_export_property_ivar_binding_missing = 0;
  std::size_t runtime_export_property_ivar_binding_conflicts = 0;
  std::size_t runtime_export_implementation_resolution_misses = 0;
  std::size_t runtime_export_method_resolution_misses = 0;
  bool runtime_export_boundary_ready = false;
  std::string runtime_export_enforcement_contract_id;
  bool runtime_export_metadata_completeness_enforced = false;
  bool runtime_export_duplicate_runtime_identity_suppression_enforced = false;
  bool runtime_export_illegal_redeclaration_mix_blocking_enforced = false;
  bool runtime_export_metadata_shape_drift_blocking_enforced = false;
  bool runtime_export_enforcement_fail_closed = false;
  bool runtime_export_ready_for_runtime_export = false;
  std::size_t runtime_export_duplicate_runtime_identity_sites = 0;
  std::size_t runtime_export_incomplete_declaration_sites = 0;
  std::size_t runtime_export_illegal_redeclaration_mix_sites = 0;
  std::size_t runtime_export_metadata_shape_drift_sites = 0;
  std::string runtime_metadata_section_abi_contract_id;
  bool runtime_metadata_section_boundary_frozen = false;
  bool runtime_metadata_section_fail_closed = false;
  bool runtime_metadata_section_object_file_inventory_frozen = false;
  bool runtime_metadata_section_symbol_policy_frozen = false;
  bool runtime_metadata_section_visibility_model_frozen = false;
  bool runtime_metadata_section_retention_policy_frozen = false;
  bool runtime_metadata_section_ready_for_scaffold = false;
  std::string runtime_metadata_section_logical_image_info_section;
  std::string runtime_metadata_section_logical_class_descriptor_section;
  std::string runtime_metadata_section_logical_protocol_descriptor_section;
  std::string runtime_metadata_section_logical_category_descriptor_section;
  std::string runtime_metadata_section_logical_property_descriptor_section;
  std::string runtime_metadata_section_logical_ivar_descriptor_section;
  std::string runtime_metadata_section_descriptor_symbol_prefix;
  std::string runtime_metadata_section_aggregate_symbol_prefix;
  std::string runtime_metadata_section_image_info_symbol;
  std::string runtime_metadata_section_descriptor_linkage;
  std::string runtime_metadata_section_aggregate_linkage;
  std::string runtime_metadata_section_visibility;
  std::string runtime_metadata_section_retention_root;
  std::string runtime_metadata_section_scaffold_contract_id;
  std::string runtime_metadata_section_scaffold_abi_contract_id;
  bool runtime_metadata_section_scaffold_emitted = false;
  bool runtime_metadata_section_scaffold_fail_closed = false;
  bool runtime_metadata_section_scaffold_uses_llvm_used = false;
  bool runtime_metadata_section_scaffold_image_info_emitted = false;
  std::size_t runtime_metadata_section_scaffold_class_descriptor_count = 0;
  std::size_t runtime_metadata_section_scaffold_protocol_descriptor_count = 0;
  std::size_t runtime_metadata_section_scaffold_category_descriptor_count = 0;
  std::size_t runtime_metadata_section_scaffold_property_descriptor_count = 0;
  std::size_t runtime_metadata_section_scaffold_ivar_descriptor_count = 0;
  std::size_t runtime_metadata_section_scaffold_total_descriptor_count = 0;
  std::size_t runtime_metadata_section_scaffold_total_retained_global_count = 0;
  std::string runtime_metadata_section_scaffold_image_info_symbol;
  std::string runtime_metadata_section_scaffold_class_aggregate_symbol;
  std::string runtime_metadata_section_scaffold_protocol_aggregate_symbol;
  std::string runtime_metadata_section_scaffold_category_aggregate_symbol;
  std::string runtime_metadata_section_scaffold_property_aggregate_symbol;
  std::string runtime_metadata_section_scaffold_ivar_aggregate_symbol;
  std::string runtime_metadata_class_metaclass_emission_contract_id;
  std::string runtime_metadata_class_metaclass_payload_model;
  std::string runtime_metadata_class_metaclass_name_model;
  std::string runtime_metadata_class_metaclass_super_link_model;
  std::string runtime_metadata_class_metaclass_method_list_reference_model;
  bool runtime_metadata_class_metaclass_emission_ready = false;
  bool runtime_metadata_class_metaclass_emission_fail_closed = false;
  std::string runtime_metadata_class_metaclass_typed_handoff_replay_key;
  std::vector<Objc3IRRuntimeMetadataClassMetaclassBundle>
      runtime_metadata_class_metaclass_bundles_lexicographic;
  std::string runtime_metadata_protocol_category_emission_contract_id;
  std::string runtime_metadata_protocol_emission_payload_model;
  std::string runtime_metadata_category_emission_payload_model;
  std::string runtime_metadata_protocol_reference_model;
  std::string runtime_metadata_category_attachment_model;
  bool runtime_metadata_protocol_category_emission_ready = false;
  bool runtime_metadata_protocol_category_emission_fail_closed = false;
  std::string runtime_metadata_protocol_category_typed_handoff_replay_key;
  std::vector<Objc3IRRuntimeMetadataProtocolBundle>
      runtime_metadata_protocol_bundles_lexicographic;
  std::vector<Objc3IRRuntimeMetadataCategoryBundle>
      runtime_metadata_category_bundles_lexicographic;
  std::string runtime_metadata_object_inspection_contract_id;
  std::string runtime_metadata_object_inspection_scaffold_contract_id;
  bool runtime_metadata_object_inspection_matrix_published = false;
  bool runtime_metadata_object_inspection_fail_closed = false;
  bool runtime_metadata_object_inspection_uses_llvm_readobj = false;
  bool runtime_metadata_object_inspection_uses_llvm_objdump = false;
  std::size_t runtime_metadata_object_inspection_matrix_row_count = 0;
  std::string runtime_metadata_object_inspection_fixture_path;
  std::string runtime_metadata_object_inspection_emit_prefix;
  std::string runtime_metadata_object_inspection_object_relative_path;
  std::string runtime_metadata_object_inspection_section_inventory_row_key;
  std::string runtime_metadata_object_inspection_section_inventory_command;
  std::string runtime_metadata_object_inspection_symbol_inventory_row_key;
  std::string runtime_metadata_object_inspection_symbol_inventory_command;
  std::string executable_metadata_debug_projection_contract_id;
  std::string executable_metadata_debug_projection_typed_handoff_contract_id;
  std::string executable_metadata_debug_projection_source_graph_contract_id;
  std::string executable_metadata_debug_projection_named_metadata_name;
  std::string executable_metadata_debug_projection_manifest_surface_path;
  std::string executable_metadata_debug_projection_typed_handoff_surface_path;
  std::string executable_metadata_debug_projection_source_graph_surface_path;
  bool executable_metadata_debug_projection_matrix_published = false;
  bool executable_metadata_debug_projection_fail_closed = false;
  bool executable_metadata_debug_projection_manifest_debug_surface_published =
      false;
  bool executable_metadata_debug_projection_ir_named_metadata_published = false;
  bool executable_metadata_debug_projection_replay_anchor_deterministic = false;
  bool executable_metadata_debug_projection_active_typed_handoff_ready = false;
  std::size_t executable_metadata_debug_projection_matrix_row_count = 0;
  std::string executable_metadata_debug_projection_replay_key;
  std::string executable_metadata_debug_projection_active_typed_handoff_replay_key;
  std::string executable_metadata_debug_projection_row0_descriptor;
  std::string executable_metadata_debug_projection_row1_descriptor;
  std::string executable_metadata_debug_projection_row2_descriptor;
  std::string runtime_support_library_contract_id;
  std::string runtime_support_library_metadata_scaffold_contract_id;
  bool runtime_support_library_boundary_frozen = false;
  bool runtime_support_library_fail_closed = false;
  bool runtime_support_library_target_name_frozen = false;
  bool runtime_support_library_exported_entrypoints_frozen = false;
  bool runtime_support_library_ownership_boundaries_frozen = false;
  bool runtime_support_library_build_constraints_frozen = false;
  bool runtime_support_library_shim_remains_test_only = false;
  bool runtime_support_library_native_library_present = false;
  bool runtime_support_library_driver_link_wiring_pending = false;
  bool runtime_support_library_ready_for_skeleton = false;
  std::string runtime_support_library_target_name;
  std::string runtime_support_library_public_header_path;
  std::string runtime_support_library_source_root;
  std::string runtime_support_library_library_kind;
  std::string runtime_support_library_archive_basename;
  std::string runtime_support_library_register_image_symbol;
  std::string runtime_support_library_lookup_selector_symbol;
  std::string runtime_support_library_dispatch_i32_symbol;
  std::string runtime_support_library_reset_for_testing_symbol;
  std::string runtime_support_library_driver_link_mode;
  std::string runtime_support_library_compiler_ownership_boundary;
  std::string runtime_support_library_runtime_ownership_boundary;
  std::string runtime_support_library_core_feature_contract_id;
  std::string runtime_support_library_core_feature_support_library_contract_id;
  std::string runtime_support_library_core_feature_metadata_scaffold_contract_id;
  bool runtime_support_library_core_feature_fail_closed = false;
  bool runtime_support_library_core_feature_sources_present = false;
  bool runtime_support_library_core_feature_header_present = false;
  bool runtime_support_library_core_feature_archive_build_enabled = false;
  bool runtime_support_library_core_feature_entrypoints_implemented = false;
  bool runtime_support_library_core_feature_selector_lookup_stateful = false;
  bool runtime_support_library_core_feature_dispatch_formula_matches_test_shim =
      false;
  bool runtime_support_library_core_feature_reset_for_testing_supported = false;
  bool runtime_support_library_core_feature_shim_remains_test_only = false;
  bool runtime_support_library_core_feature_driver_link_wiring_pending = false;
  bool runtime_support_library_core_feature_ready_for_driver_link_wiring = false;
  std::string runtime_support_library_core_feature_target_name;
  std::string runtime_support_library_core_feature_public_header_path;
  std::string runtime_support_library_core_feature_source_root;
  std::string runtime_support_library_core_feature_implementation_source_path;
  std::string runtime_support_library_core_feature_library_kind;
  std::string runtime_support_library_core_feature_archive_basename;
  std::string runtime_support_library_core_feature_archive_relative_path;
  std::string runtime_support_library_core_feature_probe_source_path;
  std::string runtime_support_library_core_feature_register_image_symbol;
  std::string runtime_support_library_core_feature_lookup_selector_symbol;
  std::string runtime_support_library_core_feature_dispatch_i32_symbol;
  std::string runtime_support_library_core_feature_reset_for_testing_symbol;
  std::string runtime_support_library_core_feature_driver_link_mode;
  std::string runtime_support_library_link_wiring_contract_id;
  std::string runtime_support_library_link_wiring_core_feature_contract_id;
  bool runtime_support_library_link_wiring_fail_closed = false;
  bool runtime_support_library_link_wiring_archive_available = false;
  bool runtime_support_library_link_wiring_compatibility_dispatch_alias_exported =
      false;
  bool runtime_support_library_link_wiring_driver_emits_runtime_link_contract =
      false;
  bool runtime_support_library_link_wiring_execution_smoke_consumes_runtime_library =
      false;
  bool runtime_support_library_link_wiring_shim_remains_test_only = false;
  bool runtime_support_library_link_wiring_ready_for_runtime_library_consumption =
      false;
  std::string runtime_support_library_link_wiring_archive_relative_path;
  std::string runtime_support_library_link_wiring_compatibility_dispatch_symbol;
  std::string runtime_support_library_link_wiring_runtime_dispatch_symbol;
  std::string runtime_support_library_link_wiring_execution_smoke_script_path;
  std::string runtime_support_library_link_wiring_driver_link_mode;
  std::string lowering_property_synthesis_ivar_binding_replay_key;
  std::string lowering_id_class_sel_object_pointer_typecheck_replay_key;
  std::size_t id_typecheck_sites = 0;
  std::size_t class_typecheck_sites = 0;
  std::size_t sel_typecheck_sites = 0;
  std::size_t object_pointer_typecheck_sites = 0;
  std::size_t id_class_sel_object_pointer_typecheck_sites_total = 0;
  bool deterministic_id_class_sel_object_pointer_typecheck_handoff = false;
  std::string lowering_message_send_selector_lowering_replay_key;
  std::size_t message_send_selector_lowering_sites = 0;
  std::size_t message_send_selector_lowering_unary_sites = 0;
  std::size_t message_send_selector_lowering_keyword_sites = 0;
  std::size_t message_send_selector_lowering_selector_piece_sites = 0;
  std::size_t message_send_selector_lowering_argument_expression_sites = 0;
  std::size_t message_send_selector_lowering_receiver_sites = 0;
  std::size_t message_send_selector_lowering_selector_literal_entries = 0;
  std::size_t message_send_selector_lowering_selector_literal_characters = 0;
  bool deterministic_message_send_selector_lowering_handoff = false;
  std::string lowering_dispatch_abi_marshalling_replay_key;
  std::size_t dispatch_abi_marshalling_message_send_sites = 0;
  std::size_t dispatch_abi_marshalling_receiver_slots_marshaled = 0;
  std::size_t dispatch_abi_marshalling_selector_slots_marshaled = 0;
  std::size_t dispatch_abi_marshalling_argument_value_slots_marshaled = 0;
  std::size_t dispatch_abi_marshalling_argument_padding_slots_marshaled = 0;
  std::size_t dispatch_abi_marshalling_argument_total_slots_marshaled = 0;
  std::size_t dispatch_abi_marshalling_total_marshaled_slots = 0;
  std::size_t dispatch_abi_marshalling_runtime_dispatch_arg_slots = 0;
  bool deterministic_dispatch_abi_marshalling_handoff = false;
  std::string lowering_nil_receiver_semantics_foldability_replay_key;
  std::size_t nil_receiver_semantics_foldability_message_send_sites = 0;
  std::size_t nil_receiver_semantics_foldability_receiver_nil_literal_sites = 0;
  std::size_t nil_receiver_semantics_foldability_enabled_sites = 0;
  std::size_t nil_receiver_semantics_foldability_foldable_sites = 0;
  std::size_t nil_receiver_semantics_foldability_runtime_dispatch_required_sites = 0;
  std::size_t nil_receiver_semantics_foldability_non_nil_receiver_sites = 0;
  std::size_t nil_receiver_semantics_foldability_contract_violation_sites = 0;
  bool deterministic_nil_receiver_semantics_foldability_handoff = false;
  std::string lowering_super_dispatch_method_family_replay_key;
  std::size_t super_dispatch_method_family_message_send_sites = 0;
  std::size_t super_dispatch_method_family_receiver_super_identifier_sites = 0;
  std::size_t super_dispatch_method_family_enabled_sites = 0;
  std::size_t super_dispatch_method_family_requires_class_context_sites = 0;
  std::size_t super_dispatch_method_family_init_sites = 0;
  std::size_t super_dispatch_method_family_copy_sites = 0;
  std::size_t super_dispatch_method_family_mutable_copy_sites = 0;
  std::size_t super_dispatch_method_family_new_sites = 0;
  std::size_t super_dispatch_method_family_none_sites = 0;
  std::size_t super_dispatch_method_family_returns_retained_result_sites = 0;
  std::size_t super_dispatch_method_family_returns_related_result_sites = 0;
  std::size_t super_dispatch_method_family_contract_violation_sites = 0;
  bool deterministic_super_dispatch_method_family_handoff = false;
  std::string lowering_runtime_shim_host_link_replay_key;
  std::size_t runtime_shim_host_link_message_send_sites = 0;
  std::size_t runtime_shim_host_link_required_sites = 0;
  std::size_t runtime_shim_host_link_elided_sites = 0;
  std::size_t runtime_shim_host_link_runtime_dispatch_arg_slots = 0;
  std::size_t runtime_shim_host_link_runtime_dispatch_declaration_parameter_count = 0;
  std::size_t runtime_shim_host_link_contract_violation_sites = 0;
  std::string runtime_shim_host_link_runtime_dispatch_symbol;
  bool runtime_shim_host_link_default_runtime_dispatch_symbol_binding = true;
  bool deterministic_runtime_shim_host_link_handoff = false;
  std::string lowering_ownership_qualifier_replay_key;
  std::size_t ownership_qualifier_lowering_ownership_qualifier_sites = 0;
  std::size_t ownership_qualifier_lowering_invalid_ownership_qualifier_sites = 0;
  std::size_t ownership_qualifier_lowering_object_pointer_type_annotation_sites = 0;
  bool deterministic_ownership_qualifier_lowering_handoff = false;
  std::string lowering_retain_release_operation_replay_key;
  std::size_t retain_release_operation_lowering_ownership_qualified_sites = 0;
  std::size_t retain_release_operation_lowering_retain_insertion_sites = 0;
  std::size_t retain_release_operation_lowering_release_insertion_sites = 0;
  std::size_t retain_release_operation_lowering_autorelease_insertion_sites = 0;
  std::size_t retain_release_operation_lowering_contract_violation_sites = 0;
  bool deterministic_retain_release_operation_lowering_handoff = false;
  std::string lowering_autoreleasepool_scope_replay_key;
  std::size_t autoreleasepool_scope_lowering_scope_sites = 0;
  std::size_t autoreleasepool_scope_lowering_scope_symbolized_sites = 0;
  unsigned autoreleasepool_scope_lowering_max_scope_depth = 0;
  std::size_t autoreleasepool_scope_lowering_scope_entry_transition_sites = 0;
  std::size_t autoreleasepool_scope_lowering_scope_exit_transition_sites = 0;
  std::size_t autoreleasepool_scope_lowering_contract_violation_sites = 0;
  bool deterministic_autoreleasepool_scope_lowering_handoff = false;
  std::string lowering_weak_unowned_semantics_replay_key;
  std::size_t weak_unowned_semantics_lowering_ownership_candidate_sites = 0;
  std::size_t weak_unowned_semantics_lowering_weak_reference_sites = 0;
  std::size_t weak_unowned_semantics_lowering_unowned_reference_sites = 0;
  std::size_t weak_unowned_semantics_lowering_unowned_safe_reference_sites = 0;
  std::size_t weak_unowned_semantics_lowering_conflict_sites = 0;
  std::size_t weak_unowned_semantics_lowering_contract_violation_sites = 0;
  bool deterministic_weak_unowned_semantics_lowering_handoff = false;
  std::string lowering_arc_diagnostics_fixit_replay_key;
  std::size_t arc_diagnostics_fixit_lowering_ownership_arc_diagnostic_candidate_sites = 0;
  std::size_t arc_diagnostics_fixit_lowering_ownership_arc_fixit_available_sites = 0;
  std::size_t arc_diagnostics_fixit_lowering_ownership_arc_profiled_sites = 0;
  std::size_t arc_diagnostics_fixit_lowering_ownership_arc_weak_unowned_conflict_diagnostic_sites = 0;
  std::size_t arc_diagnostics_fixit_lowering_ownership_arc_empty_fixit_hint_sites = 0;
  std::size_t arc_diagnostics_fixit_lowering_contract_violation_sites = 0;
  bool deterministic_arc_diagnostics_fixit_lowering_handoff = false;
  std::string lowering_block_literal_capture_replay_key;
  std::size_t block_literal_capture_lowering_block_literal_sites = 0;
  std::size_t block_literal_capture_lowering_block_parameter_entries = 0;
  std::size_t block_literal_capture_lowering_block_capture_entries = 0;
  std::size_t block_literal_capture_lowering_block_body_statement_entries = 0;
  std::size_t block_literal_capture_lowering_block_empty_capture_sites = 0;
  std::size_t block_literal_capture_lowering_block_nondeterministic_capture_sites = 0;
  std::size_t block_literal_capture_lowering_block_non_normalized_sites = 0;
  std::size_t block_literal_capture_lowering_contract_violation_sites = 0;
  bool deterministic_block_literal_capture_lowering_handoff = false;
  std::string lowering_block_abi_invoke_trampoline_replay_key;
  std::size_t block_abi_invoke_trampoline_lowering_block_literal_sites = 0;
  std::size_t block_abi_invoke_trampoline_lowering_invoke_argument_slots_total = 0;
  std::size_t block_abi_invoke_trampoline_lowering_capture_word_count_total = 0;
  std::size_t block_abi_invoke_trampoline_lowering_parameter_entries_total = 0;
  std::size_t block_abi_invoke_trampoline_lowering_capture_entries_total = 0;
  std::size_t block_abi_invoke_trampoline_lowering_body_statement_entries_total = 0;
  std::size_t block_abi_invoke_trampoline_lowering_descriptor_symbolized_sites = 0;
  std::size_t block_abi_invoke_trampoline_lowering_invoke_symbolized_sites = 0;
  std::size_t block_abi_invoke_trampoline_lowering_missing_invoke_sites = 0;
  std::size_t block_abi_invoke_trampoline_lowering_non_normalized_layout_sites = 0;
  std::size_t block_abi_invoke_trampoline_lowering_contract_violation_sites = 0;
  bool deterministic_block_abi_invoke_trampoline_lowering_handoff = false;
  std::string lowering_block_storage_escape_replay_key;
  std::size_t block_storage_escape_lowering_block_literal_sites = 0;
  std::size_t block_storage_escape_lowering_mutable_capture_count_total = 0;
  std::size_t block_storage_escape_lowering_byref_slot_count_total = 0;
  std::size_t block_storage_escape_lowering_parameter_entries_total = 0;
  std::size_t block_storage_escape_lowering_capture_entries_total = 0;
  std::size_t block_storage_escape_lowering_body_statement_entries_total = 0;
  std::size_t block_storage_escape_lowering_requires_byref_cells_sites = 0;
  std::size_t block_storage_escape_lowering_escape_analysis_enabled_sites = 0;
  std::size_t block_storage_escape_lowering_escape_to_heap_sites = 0;
  std::size_t block_storage_escape_lowering_escape_profile_normalized_sites = 0;
  std::size_t block_storage_escape_lowering_byref_layout_symbolized_sites = 0;
  std::size_t block_storage_escape_lowering_contract_violation_sites = 0;
  bool deterministic_block_storage_escape_lowering_handoff = false;
  std::string lowering_block_copy_dispose_replay_key;
  std::size_t block_copy_dispose_lowering_block_literal_sites = 0;
  std::size_t block_copy_dispose_lowering_mutable_capture_count_total = 0;
  std::size_t block_copy_dispose_lowering_byref_slot_count_total = 0;
  std::size_t block_copy_dispose_lowering_parameter_entries_total = 0;
  std::size_t block_copy_dispose_lowering_capture_entries_total = 0;
  std::size_t block_copy_dispose_lowering_body_statement_entries_total = 0;
  std::size_t block_copy_dispose_lowering_copy_helper_required_sites = 0;
  std::size_t block_copy_dispose_lowering_dispose_helper_required_sites = 0;
  std::size_t block_copy_dispose_lowering_profile_normalized_sites = 0;
  std::size_t block_copy_dispose_lowering_copy_helper_symbolized_sites = 0;
  std::size_t block_copy_dispose_lowering_dispose_helper_symbolized_sites = 0;
  std::size_t block_copy_dispose_lowering_contract_violation_sites = 0;
  bool deterministic_block_copy_dispose_lowering_handoff = false;
  std::string lowering_block_determinism_perf_baseline_replay_key;
  std::size_t block_determinism_perf_baseline_lowering_block_literal_sites = 0;
  std::size_t block_determinism_perf_baseline_lowering_baseline_weight_total = 0;
  std::size_t block_determinism_perf_baseline_lowering_parameter_entries_total = 0;
  std::size_t block_determinism_perf_baseline_lowering_capture_entries_total = 0;
  std::size_t block_determinism_perf_baseline_lowering_body_statement_entries_total = 0;
  std::size_t block_determinism_perf_baseline_lowering_deterministic_capture_sites = 0;
  std::size_t block_determinism_perf_baseline_lowering_heavy_tier_sites = 0;
  std::size_t block_determinism_perf_baseline_lowering_normalized_profile_sites = 0;
  std::size_t block_determinism_perf_baseline_lowering_contract_violation_sites = 0;
  bool deterministic_block_determinism_perf_baseline_lowering_handoff = false;
  std::string lowering_lightweight_generic_constraint_replay_key;
  std::size_t lightweight_generic_constraint_lowering_generic_constraint_sites = 0;
  std::size_t lightweight_generic_constraint_lowering_generic_suffix_sites = 0;
  std::size_t lightweight_generic_constraint_lowering_object_pointer_type_sites = 0;
  std::size_t lightweight_generic_constraint_lowering_terminated_generic_suffix_sites = 0;
  std::size_t lightweight_generic_constraint_lowering_pointer_declarator_sites = 0;
  std::size_t lightweight_generic_constraint_lowering_normalized_constraint_sites = 0;
  std::size_t lightweight_generic_constraint_lowering_contract_violation_sites = 0;
  bool deterministic_lightweight_generic_constraint_lowering_handoff = false;
  std::string lowering_nullability_flow_warning_precision_replay_key;
  std::size_t nullability_flow_warning_precision_lowering_sites = 0;
  std::size_t nullability_flow_warning_precision_lowering_object_pointer_type_sites = 0;
  std::size_t nullability_flow_warning_precision_lowering_nullability_suffix_sites = 0;
  std::size_t nullability_flow_warning_precision_lowering_nullable_suffix_sites = 0;
  std::size_t nullability_flow_warning_precision_lowering_nonnull_suffix_sites = 0;
  std::size_t nullability_flow_warning_precision_lowering_normalized_sites = 0;
  std::size_t nullability_flow_warning_precision_lowering_contract_violation_sites = 0;
  bool deterministic_nullability_flow_warning_precision_lowering_handoff = false;
  std::string lowering_protocol_qualified_object_type_replay_key;
  std::size_t protocol_qualified_object_type_lowering_sites = 0;
  std::size_t protocol_qualified_object_type_lowering_protocol_composition_sites = 0;
  std::size_t protocol_qualified_object_type_lowering_object_pointer_type_sites = 0;
  std::size_t protocol_qualified_object_type_lowering_terminated_protocol_composition_sites = 0;
  std::size_t protocol_qualified_object_type_lowering_pointer_declarator_sites = 0;
  std::size_t protocol_qualified_object_type_lowering_normalized_protocol_composition_sites = 0;
  std::size_t protocol_qualified_object_type_lowering_contract_violation_sites = 0;
  bool deterministic_protocol_qualified_object_type_lowering_handoff = false;
  std::string lowering_variance_bridge_cast_replay_key;
  std::size_t variance_bridge_cast_lowering_sites = 0;
  std::size_t variance_bridge_cast_lowering_protocol_composition_sites = 0;
  std::size_t variance_bridge_cast_lowering_ownership_qualifier_sites = 0;
  std::size_t variance_bridge_cast_lowering_object_pointer_type_sites = 0;
  std::size_t variance_bridge_cast_lowering_pointer_declarator_sites = 0;
  std::size_t variance_bridge_cast_lowering_normalized_sites = 0;
  std::size_t variance_bridge_cast_lowering_contract_violation_sites = 0;
  bool deterministic_variance_bridge_cast_lowering_handoff = false;
  std::string lowering_generic_metadata_abi_replay_key;
  std::size_t generic_metadata_abi_lowering_sites = 0;
  std::size_t generic_metadata_abi_lowering_generic_suffix_sites = 0;
  std::size_t generic_metadata_abi_lowering_protocol_composition_sites = 0;
  std::size_t generic_metadata_abi_lowering_ownership_qualifier_sites = 0;
  std::size_t generic_metadata_abi_lowering_object_pointer_type_sites = 0;
  std::size_t generic_metadata_abi_lowering_pointer_declarator_sites = 0;
  std::size_t generic_metadata_abi_lowering_normalized_sites = 0;
  std::size_t generic_metadata_abi_lowering_contract_violation_sites = 0;
  bool deterministic_generic_metadata_abi_lowering_handoff = false;
  std::string lowering_module_import_graph_replay_key;
  std::size_t module_import_graph_lowering_sites = 0;
  std::size_t module_import_graph_lowering_import_edge_candidate_sites = 0;
  std::size_t module_import_graph_lowering_namespace_segment_sites = 0;
  std::size_t module_import_graph_lowering_object_pointer_type_sites = 0;
  std::size_t module_import_graph_lowering_pointer_declarator_sites = 0;
  std::size_t module_import_graph_lowering_normalized_sites = 0;
  std::size_t module_import_graph_lowering_contract_violation_sites = 0;
  bool deterministic_module_import_graph_lowering_handoff = false;
  std::string lowering_namespace_collision_shadowing_replay_key;
  std::size_t namespace_collision_shadowing_lowering_sites = 0;
  std::size_t namespace_collision_shadowing_lowering_namespace_segment_sites = 0;
  std::size_t namespace_collision_shadowing_lowering_import_edge_candidate_sites = 0;
  std::size_t namespace_collision_shadowing_lowering_object_pointer_type_sites = 0;
  std::size_t namespace_collision_shadowing_lowering_pointer_declarator_sites = 0;
  std::size_t namespace_collision_shadowing_lowering_normalized_sites = 0;
  std::size_t namespace_collision_shadowing_lowering_contract_violation_sites = 0;
  bool deterministic_namespace_collision_shadowing_lowering_handoff = false;
  std::string lowering_public_private_api_partition_replay_key;
  std::size_t public_private_api_partition_lowering_sites = 0;
  std::size_t public_private_api_partition_lowering_namespace_segment_sites = 0;
  std::size_t public_private_api_partition_lowering_import_edge_candidate_sites = 0;
  std::size_t public_private_api_partition_lowering_object_pointer_type_sites = 0;
  std::size_t public_private_api_partition_lowering_pointer_declarator_sites = 0;
  std::size_t public_private_api_partition_lowering_normalized_sites = 0;
  std::size_t public_private_api_partition_lowering_contract_violation_sites = 0;
  bool deterministic_public_private_api_partition_lowering_handoff = false;
  std::string lowering_incremental_module_cache_invalidation_replay_key;
  std::size_t incremental_module_cache_invalidation_lowering_sites = 0;
  std::size_t incremental_module_cache_invalidation_lowering_namespace_segment_sites = 0;
  std::size_t incremental_module_cache_invalidation_lowering_import_edge_candidate_sites = 0;
  std::size_t incremental_module_cache_invalidation_lowering_object_pointer_type_sites = 0;
  std::size_t incremental_module_cache_invalidation_lowering_pointer_declarator_sites = 0;
  std::size_t incremental_module_cache_invalidation_lowering_normalized_sites = 0;
  std::size_t incremental_module_cache_invalidation_lowering_cache_invalidation_candidate_sites = 0;
  std::size_t incremental_module_cache_invalidation_lowering_contract_violation_sites = 0;
  bool deterministic_incremental_module_cache_invalidation_lowering_handoff = false;
  std::string lowering_cross_module_conformance_replay_key;
  std::size_t cross_module_conformance_lowering_sites = 0;
  std::size_t cross_module_conformance_lowering_namespace_segment_sites = 0;
  std::size_t cross_module_conformance_lowering_import_edge_candidate_sites = 0;
  std::size_t cross_module_conformance_lowering_object_pointer_type_sites = 0;
  std::size_t cross_module_conformance_lowering_pointer_declarator_sites = 0;
  std::size_t cross_module_conformance_lowering_normalized_sites = 0;
  std::size_t cross_module_conformance_lowering_cache_invalidation_candidate_sites = 0;
  std::size_t cross_module_conformance_lowering_contract_violation_sites = 0;
  bool deterministic_cross_module_conformance_lowering_handoff = false;
  std::string lowering_throws_propagation_replay_key;
  std::size_t throws_propagation_lowering_sites = 0;
  std::size_t throws_propagation_lowering_namespace_segment_sites = 0;
  std::size_t throws_propagation_lowering_import_edge_candidate_sites = 0;
  std::size_t throws_propagation_lowering_object_pointer_type_sites = 0;
  std::size_t throws_propagation_lowering_pointer_declarator_sites = 0;
  std::size_t throws_propagation_lowering_normalized_sites = 0;
  std::size_t throws_propagation_lowering_cache_invalidation_candidate_sites = 0;
  std::size_t throws_propagation_lowering_contract_violation_sites = 0;
  bool deterministic_throws_propagation_lowering_handoff = false;
  std::string lowering_ns_error_bridging_replay_key;
  std::size_t ns_error_bridging_lowering_sites = 0;
  std::size_t ns_error_bridging_lowering_ns_error_parameter_sites = 0;
  std::size_t ns_error_bridging_lowering_ns_error_out_parameter_sites = 0;
  std::size_t ns_error_bridging_lowering_ns_error_bridge_path_sites = 0;
  std::size_t ns_error_bridging_lowering_failable_call_sites = 0;
  std::size_t ns_error_bridging_lowering_normalized_sites = 0;
  std::size_t ns_error_bridging_lowering_bridge_boundary_sites = 0;
  std::size_t ns_error_bridging_lowering_contract_violation_sites = 0;
  bool deterministic_ns_error_bridging_lowering_handoff = false;
  std::string lowering_unwind_cleanup_replay_key;
  std::size_t unwind_cleanup_lowering_sites = 0;
  std::size_t unwind_cleanup_lowering_unwind_edge_sites = 0;
  std::size_t unwind_cleanup_lowering_cleanup_scope_sites = 0;
  std::size_t unwind_cleanup_lowering_cleanup_emit_sites = 0;
  std::size_t unwind_cleanup_lowering_landing_pad_sites = 0;
  std::size_t unwind_cleanup_lowering_cleanup_resume_sites = 0;
  std::size_t unwind_cleanup_lowering_normalized_sites = 0;
  std::size_t unwind_cleanup_lowering_guard_blocked_sites = 0;
  std::size_t unwind_cleanup_lowering_contract_violation_sites = 0;
  bool deterministic_unwind_cleanup_lowering_handoff = false;
  std::string lowering_error_diagnostics_recovery_replay_key;
  std::size_t error_diagnostics_recovery_lowering_sites = 0;
  std::size_t
      error_diagnostics_recovery_lowering_parser_diagnostic_sites = 0;
  std::size_t
      error_diagnostics_recovery_lowering_semantic_diagnostic_sites = 0;
  std::size_t error_diagnostics_recovery_lowering_fixit_hint_sites = 0;
  std::size_t
      error_diagnostics_recovery_lowering_recovery_candidate_sites = 0;
  std::size_t
      error_diagnostics_recovery_lowering_recovery_applied_sites = 0;
  std::size_t error_diagnostics_recovery_lowering_normalized_sites = 0;
  std::size_t error_diagnostics_recovery_lowering_guard_blocked_sites = 0;
  std::size_t
      error_diagnostics_recovery_lowering_contract_violation_sites = 0;
  bool deterministic_error_diagnostics_recovery_lowering_handoff = false;
  std::string lowering_async_continuation_replay_key;
  std::size_t async_continuation_lowering_sites = 0;
  std::size_t async_continuation_lowering_async_keyword_sites = 0;
  std::size_t async_continuation_lowering_async_function_sites = 0;
  std::size_t async_continuation_lowering_continuation_allocation_sites = 0;
  std::size_t async_continuation_lowering_continuation_resume_sites = 0;
  std::size_t async_continuation_lowering_continuation_suspend_sites = 0;
  std::size_t async_continuation_lowering_async_state_machine_sites = 0;
  std::size_t async_continuation_lowering_normalized_sites = 0;
  std::size_t async_continuation_lowering_gate_blocked_sites = 0;
  std::size_t async_continuation_lowering_contract_violation_sites = 0;
  bool deterministic_async_continuation_lowering_handoff = false;
  std::string lowering_await_lowering_suspension_state_replay_key;
  std::size_t await_lowering_suspension_state_lowering_sites = 0;
  std::size_t
      await_lowering_suspension_state_lowering_await_keyword_sites = 0;
  std::size_t
      await_lowering_suspension_state_lowering_await_suspension_point_sites =
          0;
  std::size_t await_lowering_suspension_state_lowering_await_resume_sites = 0;
  std::size_t
      await_lowering_suspension_state_lowering_await_state_machine_sites = 0;
  std::size_t
      await_lowering_suspension_state_lowering_await_continuation_sites = 0;
  std::size_t await_lowering_suspension_state_lowering_normalized_sites = 0;
  std::size_t await_lowering_suspension_state_lowering_gate_blocked_sites = 0;
  std::size_t
      await_lowering_suspension_state_lowering_contract_violation_sites = 0;
  bool deterministic_await_lowering_suspension_state_lowering_handoff = false;
  std::string lowering_actor_isolation_sendability_replay_key;
  std::size_t actor_isolation_sendability_lowering_sites = 0;
  std::size_t actor_isolation_sendability_lowering_sendability_check_sites = 0;
  std::size_t actor_isolation_sendability_lowering_cross_actor_hop_sites = 0;
  std::size_t actor_isolation_sendability_lowering_non_sendable_capture_sites =
      0;
  std::size_t actor_isolation_sendability_lowering_sendable_transfer_sites = 0;
  std::size_t actor_isolation_sendability_lowering_isolation_boundary_sites = 0;
  std::size_t actor_isolation_sendability_lowering_guard_blocked_sites = 0;
  std::size_t actor_isolation_sendability_lowering_contract_violation_sites = 0;
  bool deterministic_actor_isolation_sendability_lowering_handoff = false;
  std::string lowering_task_runtime_interop_cancellation_replay_key;
  std::size_t task_runtime_interop_cancellation_lowering_sites = 0;
  std::size_t task_runtime_interop_cancellation_lowering_runtime_interop_sites =
      0;
  std::size_t
      task_runtime_interop_cancellation_lowering_cancellation_probe_sites = 0;
  std::size_t
      task_runtime_interop_cancellation_lowering_cancellation_handler_sites = 0;
  std::size_t task_runtime_interop_cancellation_lowering_runtime_resume_sites =
      0;
  std::size_t task_runtime_interop_cancellation_lowering_runtime_cancel_sites =
      0;
  std::size_t task_runtime_interop_cancellation_lowering_normalized_sites = 0;
  std::size_t task_runtime_interop_cancellation_lowering_guard_blocked_sites =
      0;
  std::size_t
      task_runtime_interop_cancellation_lowering_contract_violation_sites = 0;
  bool deterministic_task_runtime_interop_cancellation_lowering_handoff =
      false;
  std::string lowering_concurrency_replay_race_guard_replay_key;
  std::size_t concurrency_replay_race_guard_lowering_sites = 0;
  std::size_t concurrency_replay_race_guard_lowering_replay_proof_sites = 0;
  std::size_t concurrency_replay_race_guard_lowering_race_guard_sites = 0;
  std::size_t concurrency_replay_race_guard_lowering_task_handoff_sites = 0;
  std::size_t concurrency_replay_race_guard_lowering_actor_isolation_sites = 0;
  std::size_t concurrency_replay_race_guard_lowering_deterministic_schedule_sites = 0;
  std::size_t concurrency_replay_race_guard_lowering_guard_blocked_sites = 0;
  std::size_t concurrency_replay_race_guard_lowering_contract_violation_sites = 0;
  bool deterministic_concurrency_replay_race_guard_lowering_handoff = false;
  std::string lowering_unsafe_pointer_extension_replay_key;
  std::size_t unsafe_pointer_extension_lowering_sites = 0;
  std::size_t unsafe_pointer_extension_lowering_unsafe_keyword_sites = 0;
  std::size_t unsafe_pointer_extension_lowering_pointer_arithmetic_sites = 0;
  std::size_t unsafe_pointer_extension_lowering_raw_pointer_type_sites = 0;
  std::size_t unsafe_pointer_extension_lowering_unsafe_operation_sites = 0;
  std::size_t unsafe_pointer_extension_lowering_normalized_sites = 0;
  std::size_t unsafe_pointer_extension_lowering_gate_blocked_sites = 0;
  std::size_t unsafe_pointer_extension_lowering_contract_violation_sites = 0;
  bool deterministic_unsafe_pointer_extension_lowering_handoff = false;
  std::string lowering_inline_asm_intrinsic_governance_replay_key;
  std::size_t inline_asm_intrinsic_governance_lowering_sites = 0;
  std::size_t inline_asm_intrinsic_governance_lowering_inline_asm_sites = 0;
  std::size_t inline_asm_intrinsic_governance_lowering_intrinsic_sites = 0;
  std::size_t inline_asm_intrinsic_governance_lowering_governed_intrinsic_sites =
      0;
  std::size_t
      inline_asm_intrinsic_governance_lowering_privileged_intrinsic_sites = 0;
  std::size_t inline_asm_intrinsic_governance_lowering_normalized_sites = 0;
  std::size_t inline_asm_intrinsic_governance_lowering_gate_blocked_sites = 0;
  std::size_t
      inline_asm_intrinsic_governance_lowering_contract_violation_sites = 0;
  bool deterministic_inline_asm_intrinsic_governance_lowering_handoff = false;
  std::size_t object_pointer_type_spellings = 0;
  std::size_t pointer_declarator_entries = 0;
  std::size_t pointer_declarator_depth_total = 0;
  std::size_t pointer_declarator_token_entries = 0;
  std::size_t nullability_suffix_entries = 0;
  std::size_t generic_suffix_entries = 0;
  std::size_t terminated_generic_suffix_entries = 0;
  std::size_t unterminated_generic_suffix_entries = 0;
  bool deterministic_object_pointer_nullability_generics_handoff = false;
  std::size_t global_symbol_nodes = 0;
  std::size_t function_symbol_nodes = 0;
  std::size_t interface_symbol_nodes = 0;
  std::size_t implementation_symbol_nodes = 0;
  std::size_t interface_property_symbol_nodes = 0;
  std::size_t implementation_property_symbol_nodes = 0;
  std::size_t interface_method_symbol_nodes = 0;
  std::size_t implementation_method_symbol_nodes = 0;
  std::size_t top_level_scope_symbols = 0;
  std::size_t nested_scope_symbols = 0;
  std::size_t scope_frames_total = 0;
  std::size_t implementation_interface_resolution_sites = 0;
  std::size_t implementation_interface_resolution_hits = 0;
  std::size_t implementation_interface_resolution_misses = 0;
  std::size_t method_resolution_sites = 0;
  std::size_t method_resolution_hits = 0;
  std::size_t method_resolution_misses = 0;
  bool deterministic_symbol_graph_handoff = false;
  bool deterministic_scope_resolution_handoff = false;
  std::string deterministic_symbol_graph_scope_resolution_handoff_key;
  bool ownership_aware_lowering_core_feature_expansion_ready = false;
  std::string ownership_aware_lowering_core_feature_expansion_key;
  bool ownership_aware_lowering_performance_quality_guardrails_ready = false;
  std::string ownership_aware_lowering_performance_quality_guardrails_key;
  bool ownership_aware_lowering_cross_lane_integration_ready = false;
  std::string ownership_aware_lowering_cross_lane_integration_key;
  bool lowering_pass_graph_core_feature_ready = false;
  std::string lowering_pass_graph_core_feature_key;
  bool lowering_pass_graph_core_feature_expansion_ready = false;
  std::string lowering_pass_graph_core_feature_expansion_key;
  bool lowering_pass_graph_edge_case_compatibility_ready = false;
  std::string lowering_pass_graph_edge_case_compatibility_key;
  bool lowering_pass_graph_edge_case_robustness_ready = false;
  std::string lowering_pass_graph_edge_case_robustness_key;
  bool lowering_pass_graph_diagnostics_hardening_ready = false;
  std::string lowering_pass_graph_diagnostics_hardening_key;
  bool lowering_pass_graph_recovery_determinism_ready = false;
  std::string lowering_pass_graph_recovery_determinism_key;
  bool lowering_pass_graph_conformance_matrix_ready = false;
  std::string lowering_pass_graph_conformance_matrix_key;
  bool lowering_pass_graph_conformance_corpus_ready = false;
  std::string lowering_pass_graph_conformance_corpus_key;
  bool lowering_pass_graph_performance_quality_guardrails_ready = false;
  std::string lowering_pass_graph_performance_quality_guardrails_key;
  bool ir_emission_completeness_modular_split_ready = false;
  std::string ir_emission_completeness_modular_split_key;
  bool ir_emission_core_feature_impl_ready = false;
  std::string ir_emission_core_feature_impl_key;
  bool ir_emission_core_feature_expansion_ready = false;
  std::string ir_emission_core_feature_expansion_key;
  bool ir_emission_core_feature_edge_case_compatibility_ready = false;
  std::string ir_emission_core_feature_edge_case_compatibility_key;
  bool ir_emission_core_feature_edge_case_robustness_ready = false;
  std::string ir_emission_core_feature_edge_case_robustness_key;
  bool ir_emission_core_feature_diagnostics_hardening_ready = false;
  std::string ir_emission_core_feature_diagnostics_hardening_key;
  bool ir_emission_core_feature_recovery_determinism_ready = false;
  std::string ir_emission_core_feature_recovery_determinism_key;
  bool ir_emission_core_feature_conformance_matrix_ready = false;
  std::string ir_emission_core_feature_conformance_matrix_key;
  bool ir_emission_core_feature_conformance_corpus_ready = false;
  std::string ir_emission_core_feature_conformance_corpus_key;
  bool ir_emission_core_feature_performance_quality_guardrails_ready = false;
  std::string ir_emission_core_feature_performance_quality_guardrails_key;
  bool ir_emission_core_feature_cross_lane_integration_sync_ready = false;
  std::string ir_emission_core_feature_cross_lane_integration_sync_key;
  bool ir_emission_core_feature_advanced_core_shard1_ready = false;
  std::string ir_emission_core_feature_advanced_core_shard1_key;
  bool ir_emission_core_feature_advanced_edge_compatibility_shard1_ready = false;
  std::string ir_emission_core_feature_advanced_edge_compatibility_shard1_key;
  bool ir_emission_core_feature_advanced_diagnostics_shard1_ready = false;
  std::string ir_emission_core_feature_advanced_diagnostics_shard1_key;
  bool ir_emission_core_feature_advanced_conformance_shard1_ready = false;
  std::string ir_emission_core_feature_advanced_conformance_shard1_key;
  bool ir_emission_core_feature_advanced_integration_shard1_ready = false;
  std::string ir_emission_core_feature_advanced_integration_shard1_key;

  std::size_t migration_legacy_total() const { return migration_legacy_yes + migration_legacy_no + migration_legacy_null; }
};

bool EmitObjc3IRText(const Objc3Program &program,
                     const Objc3LoweringContract &lowering_contract,
                     const Objc3IRFrontendMetadata &frontend_metadata,
                     std::string &ir,
                     std::string &error);
