#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum objc3_runtime_dispatch_status_code {
  OBJC3_RUNTIME_DISPATCH_STATUS_OK = 0,
  OBJC3_RUNTIME_DISPATCH_STATUS_NIL_RECEIVER = 1,
  OBJC3_RUNTIME_DISPATCH_STATUS_UNKNOWN_SELECTOR = -1,
  OBJC3_RUNTIME_DISPATCH_STATUS_UNKNOWN_RECEIVER_CLASS = -2,
  OBJC3_RUNTIME_DISPATCH_STATUS_MISSING_CLASS_GRAPH = -3,
  OBJC3_RUNTIME_DISPATCH_STATUS_MALFORMED_METADATA = -4,
  OBJC3_RUNTIME_DISPATCH_STATUS_UNSUPPORTED_RETURN_TYPE = -5,
  OBJC3_RUNTIME_DISPATCH_STATUS_UNSUPPORTED_ARGUMENT_LAYOUT = -6,
  OBJC3_RUNTIME_DISPATCH_STATUS_CATEGORY_CONFLICT = -7
} objc3_runtime_dispatch_status_code;

#ifdef __cplusplus
}
#endif
