#include "artifacts/interop/interop_bridge_artifacts.h"

#include <algorithm>
#include <sstream>
#include <vector>

#include "io/objc3_json.h"

namespace objc3::artifacts::interop {
namespace {

using objc3::io::EscapeJsonString;

std::string BuildInteropBridgeCType(ValueType type, unsigned pointer_depth,
                                    bool object_pointer_type_spelling) {
  std::string base;
  switch (type) {
    case ValueType::I32:
      base = "int32_t";
      break;
    case ValueType::Bool:
      base = "bool";
      break;
    case ValueType::Void:
      base = "void";
      break;
    case ValueType::ObjCId:
    case ValueType::ObjCClass:
    case ValueType::ObjCSel:
    case ValueType::ObjCProtocol:
    case ValueType::ObjCInstancetype:
    case ValueType::ObjCObjectPtr:
    case ValueType::Function:
    default:
      base = "void";
      pointer_depth = std::max(pointer_depth, 1u);
      break;
  }
  if (object_pointer_type_spelling) {
    base = "void";
    pointer_depth = std::max(pointer_depth, 1u);
  }
  for (unsigned i = 0; i < pointer_depth; ++i) {
    base += "*";
  }
  return base;
}

std::string BuildInteropBridgeReturnType(const FunctionDecl &function) {
  return BuildInteropBridgeCType(function.return_type,
                                function.has_return_pointer_declarator
                                    ? function.return_pointer_declarator_depth
                                    : 0u,
                                function.return_object_pointer_type_spelling);
}

std::string BuildInteropBridgeParameterType(const FuncParam &param) {
  return BuildInteropBridgeCType(param.type,
                                param.has_pointer_declarator
                                    ? param.pointer_declarator_depth
                                    : 0u,
                                param.object_pointer_type_spelling);
}

std::vector<const FunctionDecl *> BuildSortedForeignFunctions(
    const Objc3Program &program) {
  std::vector<const FunctionDecl *> foreign_functions;
  for (const auto &function : program.functions) {
    if (function.objc_foreign_declared) {
      foreign_functions.push_back(&function);
    }
  }
  std::sort(foreign_functions.begin(), foreign_functions.end(),
            [](const FunctionDecl *lhs, const FunctionDecl *rhs) {
              return lhs->name < rhs->name;
            });
  return foreign_functions;
}

}  // namespace

std::string BuildInteropBridgeHeaderArtifactText(
    const Objc3Program &program,
    const Objc3RuntimeAwareImportModuleFrontendClosureSummary &summary,
    const Objc3InteropHeaderModuleBridgeGenerationSummary &bridge_summary) {
  const std::vector<const FunctionDecl *> foreign_functions =
      BuildSortedForeignFunctions(program);

  std::ostringstream out;
  out << "/* Part 11 bridge header: generated by objc3c-native. */\n"
      << "#pragma once\n"
      << "#include <stdbool.h>\n"
      << "#include <stdint.h>\n\n"
      << "/* module: " << summary.module_name << " */\n"
      << "/* replay: " << bridge_summary.replay_key << " */\n";
  for (const auto &module_name :
       bridge_summary.local_import_module_names_lexicographic) {
    out << "/* objc_import_module: " << module_name << " */\n";
  }
  if (!bridge_summary.local_import_module_names_lexicographic.empty()) {
    out << "\n";
  }
  for (const FunctionDecl *function : foreign_functions) {
    out << "/* objc_foreign";
    if (function->objc_header_name_declared &&
        !function->objc_header_name.empty()) {
      out << " header_name=" << function->objc_header_name;
    }
    if (function->objc_cxx_name_declared && !function->objc_cxx_name.empty()) {
      out << " cxx_name=" << function->objc_cxx_name;
    }
    if (function->objc_swift_name_declared &&
        !function->objc_swift_name.empty()) {
      out << " swift_name=" << function->objc_swift_name;
    }
    if (function->objc_import_module_declared &&
        !function->objc_import_module_name.empty()) {
      out << " import_module=" << function->objc_import_module_name;
    }
    if (function->objc_export_header_declared &&
        !function->objc_export_header_name.empty()) {
      out << " export_header=" << function->objc_export_header_name;
    }
    if (function->objc_abi_align_declared) {
      out << " abi_align=" << function->objc_abi_alignment_bytes;
    }
    if (function->objc_foreign_type_declared &&
        !function->objc_foreign_type_name.empty()) {
      out << " foreign_type=" << function->objc_foreign_type_name;
    }
    if (function->objc_mixed_image_declared &&
        !function->objc_mixed_image_name.empty()) {
      out << " mixed_image=" << function->objc_mixed_image_name;
    }
    if (function->objc_package_entry_declared &&
        !function->objc_package_entry_name.empty()) {
      out << " package_entry=" << function->objc_package_entry_name;
    }
    out << " */\n";
    out << BuildInteropBridgeReturnType(*function) << " " << function->name
        << "(";
    for (std::size_t index = 0; index < function->params.size(); ++index) {
      const auto &param = function->params[index];
      out << BuildInteropBridgeParameterType(param) << " " << param.name;
      if (index + 1 != function->params.size()) {
        out << ", ";
      }
    }
    if (function->params.empty()) {
      out << "void";
    }
    out << ");\n\n";
  }
  return out.str();
}

std::string BuildInteropBridgeModuleArtifactText(
    const Objc3RuntimeAwareImportModuleFrontendClosureSummary &summary,
    const Objc3InteropHeaderModuleBridgeGenerationSummary &bridge_summary) {
  std::ostringstream out;
  out << "module " << summary.module_name << "_objc3_interop_bridge {\n"
      << "  header \"" << bridge_summary.header_artifact_relative_path
      << "\"\n"
      << "  export *\n"
      << "}\n";
  return out.str();
}

std::string BuildInteropBridgeArtifactJson(
    const Objc3Program &program,
    const Objc3RuntimeAwareImportModuleFrontendClosureSummary &summary,
    const Objc3InteropHeaderModuleBridgeGenerationSummary &bridge_summary) {
  const std::vector<const FunctionDecl *> foreign_functions =
      BuildSortedForeignFunctions(program);

  std::ostringstream callables;
  callables << "[";
  for (std::size_t index = 0; index < foreign_functions.size(); ++index) {
    const FunctionDecl &function = *foreign_functions[index];
    callables << "{"
              << "\"name\":\"" << EscapeJsonString(function.name) << "\""
              << ",\"return_type\":\""
              << EscapeJsonString(BuildInteropBridgeReturnType(function)) << "\""
              << ",\"parameter_count\":" << function.params.size()
              << ",\"objc_import_module_name\":\""
              << EscapeJsonString(function.objc_import_module_name) << "\""
              << ",\"objc_header_name\":\""
              << EscapeJsonString(function.objc_header_name) << "\""
              << ",\"objc_cxx_name\":\""
              << EscapeJsonString(function.objc_cxx_name) << "\""
              << ",\"objc_swift_name\":\""
              << EscapeJsonString(function.objc_swift_name) << "\""
              << ",\"objc_export_header_name\":\""
              << EscapeJsonString(function.objc_export_header_name) << "\""
              << ",\"objc_abi_alignment_bytes\":"
              << function.objc_abi_alignment_bytes
              << ",\"objc_foreign_type_name\":\""
              << EscapeJsonString(function.objc_foreign_type_name) << "\""
              << ",\"objc_mixed_image_name\":\""
              << EscapeJsonString(function.objc_mixed_image_name) << "\""
              << ",\"objc_package_entry_name\":\""
              << EscapeJsonString(function.objc_package_entry_name) << "\""
              << "}";
    if (index + 1 != foreign_functions.size()) {
      callables << ",";
    }
  }
  callables << "]";

  std::ostringstream out;
  out << "{\n"
      << "  \"contract_id\": \""
      << EscapeJsonString(bridge_summary.contract_id) << "\",\n"
      << "  \"module_name\": \"" << EscapeJsonString(summary.module_name)
      << "\",\n"
      << "  \"header_artifact_relative_path\": \""
      << EscapeJsonString(bridge_summary.header_artifact_relative_path)
      << "\",\n"
      << "  \"module_artifact_relative_path\": \""
      << EscapeJsonString(bridge_summary.module_artifact_relative_path)
      << "\",\n"
      << "  \"bridge_artifact_relative_path\": \""
      << EscapeJsonString(bridge_summary.bridge_artifact_relative_path)
      << "\",\n"
      << "  \"runtime_generation_ready\": "
      << (bridge_summary.runtime_generation_ready ? "true" : "false")
      << ",\n"
      << "  \"cross_module_packaging_ready\": "
      << (bridge_summary.cross_module_packaging_ready ? "true" : "false")
      << ",\n"
      << "  \"deterministic\": "
      << (bridge_summary.deterministic ? "true" : "false") << ",\n"
      << "  \"replay_key\": \""
      << EscapeJsonString(bridge_summary.replay_key) << "\",\n"
      << "  \"foreign_callables\": " << callables.str() << "\n"
      << "}\n";
  return out.str();
}

}  // namespace objc3::artifacts::interop
