"""Core repo/build surface fields for the repo superclean checker."""

from __future__ import annotations

from .model import SurfaceField


CORE_SURFACE_FIELDS = (
    SurfaceField(
        "contract_id",
        "objc3c-repo-superclean-source-of-truth/build-wrapper-generated-surface-v1",
        "unexpected contract_id",
    ),
    SurfaceField("schema_version", 1, "unexpected schema_version"),
    SurfaceField(
        "surface_kind",
        "native-build-wrapper-generated-source-of-truth",
        "unexpected surface_kind",
    ),
    SurfaceField(
        "implementation_roots",
        ["native/objc3c", "scripts", "tests"],
        "implementation_roots drifted",
    ),
    SurfaceField(
        "checked_in_doc_sources",
        [
            "README.md",
            "CONTRIBUTING.md",
            "showcase",
            "stdlib",
            "site/src",
            "docs/objc3c-native/src",
            "docs/runbooks",
            "package.json",
        ],
        "checked_in_doc_sources drifted",
    ),
    SurfaceField(
        "generated_checked_in_outputs",
        [
            "site/index.md",
            "docs/objc3c-native.md",
            "docs/runbooks/objc3c_public_command_surface.md",
        ],
        "generated_checked_in_outputs drifted",
    ),
    SurfaceField(
        "maintainer_runbooks",
        [
            "docs/runbooks/objc3c_maintainer_workflows.md",
            "docs/runbooks/objc3c_developer_tooling.md",
            "docs/runbooks/objc3c_bonus_experiences.md",
            "docs/runbooks/objc3c_distribution_credibility.md",
            "docs/runbooks/objc3c_performance.md",
            "docs/runbooks/objc3c_performance_governance.md",
            "docs/runbooks/objc3c_packaging_channels.md",
            "docs/runbooks/objc3c_release_operations.md",
            "docs/runbooks/objc3c_release_foundation.md",
            "docs/runbooks/objc3c_runtime_performance.md",
            "docs/runbooks/objc3c_stress_validation.md",
            "docs/runbooks/objc3c_stdlib_foundation.md",
            "docs/runbooks/objc3c_stdlib_core.md",
            "docs/runbooks/objc3c_stdlib_advanced.md",
        ],
        "maintainer_runbooks drifted",
    ),
    SurfaceField(
        "machine_owned_output_roots",
        ["tmp", "artifacts"],
        "machine_owned_output_roots drifted",
    ),
    SurfaceField(
        "package_entrypoints",
        {
            "build_native": "build:objc3c-native",
            "build_contracts": "build:objc3c-native:contracts",
            "build_full": "build:objc3c-native:full",
            "build_reconfigure": "build:objc3c-native:reconfigure",
            "build_site": "build:site",
            "check_site": "check:site",
            "build_native_docs": "build:docs:native",
            "build_public_command_surface": "build:docs:commands",
            "build_stdlib": "build:objc3c:stdlib",
            "check_stdlib_surface": "check:stdlib:surface",
            "inspect_performance_dashboard": "inspect:objc3c:performance-dashboard",
            "publish_performance_report": "publish:objc3c:performance-report",
            "test_performance_governance": "test:objc3c:performance-governance",
            "inspect_release_manifest": "inspect:objc3c:release-manifest",
            "publish_release_provenance": "publish:objc3c:release-provenance",
            "test_release_foundation": "test:objc3c:release-foundation",
            "package_channels": "package:objc3c:channels",
            "check_packaging_channels_surface": "check:objc3c:packaging-channels:surface",
            "check_packaging_channels_schemas": "check:objc3c:packaging-channels:schemas",
            "test_packaging_channels": "test:objc3c:packaging-channels",
            "test_packaging_channels_e2e": "test:objc3c:packaging-channels:e2e",
            "check_release_operations_surface": "check:objc3c:release-operations:surface",
            "check_release_operations_schemas": "check:objc3c:release-operations:schemas",
            "inspect_update_manifest": "inspect:objc3c:update-manifest",
            "publish_release_operations": "publish:objc3c:release-operations",
            "test_release_operations": "test:objc3c:release-operations",
            "test_release_operations_e2e": "test:objc3c:release-operations:e2e",
            "check_distribution_credibility_surface": "check:objc3c:distribution-credibility:surface",
            "check_distribution_credibility_schemas": "check:objc3c:distribution-credibility:schemas",
            "inspect_distribution_credibility": "inspect:objc3c:distribution-credibility",
            "publish_distribution_credibility": "publish:objc3c:distribution-credibility",
            "test_distribution_credibility": "test:objc3c:distribution-credibility",
            "test_distribution_credibility_e2e": "test:objc3c:distribution-credibility:e2e",
            "inspect_runtime_performance": "inspect:objc3c:runtime-performance",
            "test_runtime_performance": "test:objc3c:runtime-performance",
            "test_runtime_performance_e2e": "test:objc3c:runnable-runtime-performance",
            "test_stdlib": "test:stdlib",
            "test_stdlib_e2e": "test:stdlib:e2e",
            "test_smoke": "test:smoke",
            "test_ci": "test:ci",
            "test_docs": "test:docs",
        },
        "package_entrypoints drifted",
    ),
    SurfaceField(
        "native_build_outputs",
        {
            "native_executable": "artifacts/bin/objc3c-native.exe",
            "frontend_c_api_runner": "artifacts/bin/objc3c-frontend-c-api-runner.exe",
            "runtime_library": "artifacts/lib/objc3_runtime.lib",
            "compile_commands": "tmp/build-objc3c-native/compile_commands.json",
        },
        "native_build_outputs drifted",
    ),
)
