  std::unique_ptr<Stmt> ParseStatement() {
#include "parse/objc3_parser_core_statement_parser_block_empty_qualifiers.inc"

#include "parse/objc3_parser_core_statement_local_binding_parsing.inc"

#include "parse/objc3_parser_core_statement_parser_return_statement.inc"

#include "parse/objc3_parser_core_statement_if_guard_parsing.inc"

#include "parse/objc3_parser_core_statement_parser_defer_throw.inc"

#include "parse/objc3_parser_core_statement_do_for_parsing.inc"

#include "parse/objc3_parser_core_statement_switch_parsing.inc"

#include "parse/objc3_parser_core_statement_tail_parsing.inc"
  }
