"""Storage/reflection source-surface case catalog data."""

from __future__ import annotations


ACCESSOR_STORAGE_LOWERING_METADATA_SURFACE_CASE_ID = (
    "accessor-storage-lowering-metadata-surface"
)
PROPERTY_IVAR_ORDERING_SEMANTICS_CASE_ID = "property-ivar-ordering-semantics"
PROPERTY_REFLECTION_ACCESSOR_COMPATIBILITY_DIAGNOSTICS_CASE_ID = (
    "property-reflection-accessor-compatibility-diagnostics"
)
PROPERTY_SYNTHESIS_STORAGE_BINDING_SEMANTICS_CASE_ID = (
    "property-synthesis-storage-binding-semantics"
)
STORAGE_LEGALITY_SEMANTICS_CASE_ID = "storage-legality-semantics"
SYNTHESIZED_ACCESSOR_CODEGEN_CASE_ID = "synthesized-accessor-codegen"
SYNTHESIZED_ACCESSOR_RUNTIME_CASE_ID = "synthesized-accessor-runtime"
PROPERTY_LAYOUT_CASE_ID = "property-layout"
INSTANCE_ALLOCATION_LAYOUT_RUNTIME_CASE_ID = "instance-allocation-layout-runtime"
PROPERTY_EXECUTION_CASE_ID = "property-execution"
PROPERTY_REFLECTION_CASE_ID = "property-reflection"
STORAGE_OWNERSHIP_REFLECTION_CASE_ID = "storage-ownership-reflection"
ARC_PROPERTY_HELPER_ABI_CASE_ID = "arc-property-helper-abi"


PROPERTY_IVAR_STORAGE_ACCESSOR_CASE_IDS = frozenset(
    {
        ACCESSOR_STORAGE_LOWERING_METADATA_SURFACE_CASE_ID,
        PROPERTY_IVAR_ORDERING_SEMANTICS_CASE_ID,
        PROPERTY_REFLECTION_ACCESSOR_COMPATIBILITY_DIAGNOSTICS_CASE_ID,
        PROPERTY_SYNTHESIS_STORAGE_BINDING_SEMANTICS_CASE_ID,
        STORAGE_LEGALITY_SEMANTICS_CASE_ID,
        SYNTHESIZED_ACCESSOR_CODEGEN_CASE_ID,
        SYNTHESIZED_ACCESSOR_RUNTIME_CASE_ID,
        PROPERTY_LAYOUT_CASE_ID,
        INSTANCE_ALLOCATION_LAYOUT_RUNTIME_CASE_ID,
        PROPERTY_EXECUTION_CASE_ID,
        PROPERTY_REFLECTION_CASE_ID,
        STORAGE_OWNERSHIP_REFLECTION_CASE_ID,
        ARC_PROPERTY_HELPER_ABI_CASE_ID,
    }
)

PROPERTY_ATOMICITY_SYNTHESIS_REFLECTION_CASE_IDS = frozenset(
    {
        PROPERTY_REFLECTION_ACCESSOR_COMPATIBILITY_DIAGNOSTICS_CASE_ID,
        STORAGE_LEGALITY_SEMANTICS_CASE_ID,
        PROPERTY_REFLECTION_CASE_ID,
        PROPERTY_EXECUTION_CASE_ID,
        STORAGE_OWNERSHIP_REFLECTION_CASE_ID,
        ARC_PROPERTY_HELPER_ABI_CASE_ID,
    }
)


__all__ = [
    "ACCESSOR_STORAGE_LOWERING_METADATA_SURFACE_CASE_ID",
    "ARC_PROPERTY_HELPER_ABI_CASE_ID",
    "INSTANCE_ALLOCATION_LAYOUT_RUNTIME_CASE_ID",
    "PROPERTY_ATOMICITY_SYNTHESIS_REFLECTION_CASE_IDS",
    "PROPERTY_EXECUTION_CASE_ID",
    "PROPERTY_IVAR_ORDERING_SEMANTICS_CASE_ID",
    "PROPERTY_IVAR_STORAGE_ACCESSOR_CASE_IDS",
    "PROPERTY_LAYOUT_CASE_ID",
    "PROPERTY_REFLECTION_ACCESSOR_COMPATIBILITY_DIAGNOSTICS_CASE_ID",
    "PROPERTY_REFLECTION_CASE_ID",
    "PROPERTY_SYNTHESIS_STORAGE_BINDING_SEMANTICS_CASE_ID",
    "STORAGE_LEGALITY_SEMANTICS_CASE_ID",
    "STORAGE_OWNERSHIP_REFLECTION_CASE_ID",
    "SYNTHESIZED_ACCESSOR_CODEGEN_CASE_ID",
    "SYNTHESIZED_ACCESSOR_RUNTIME_CASE_ID",
]
