"""Developer-experience runbook source catalog rows."""

from __future__ import annotations

from documentation_surface import paths as docs_paths

from .runbook_source_types import RunbookSourceSpec


def developer_runbook_source_specs() -> tuple[RunbookSourceSpec, ...]:
    return (
        RunbookSourceSpec(
            docs_paths.DEVELOPER_TOOLING_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Developer Tooling Boundary",
                "## Working Boundary",
                "## Exact Live Implementation Paths",
                "native/objc3c/src/tools/objc3c_frontend_c_api_runner.cpp",
                "native/objc3c/src/io/objc3_cli_reporting_output_contract_scaffold.h",
                "scripts/build_objc3c_native.ps1",
                "scripts.objc3c_workflow",
                "native/objc3c/src/runtime/objc3_runtime.cpp",
                "scripts/check_objc3c_library_cli_parity.py",
                "scripts/check_objc3c_runtime_acceptance.py",
                "tests/tooling/runtime/arc_debug_instrumentation_probe.cpp",
                "## Explainability And Introspection Surface",
                "## Exact Live Artifact And Output Paths",
                "artifacts/bin/objc3c-frontend-c-api-runner.exe",
                "tmp/build-objc3c-native/repo_superclean_source_of_truth.json",
                "tmp/artifacts/compilation/objc3c-native/",
                "tmp/reports/objc3c-public-workflow/compile-observability.json",
                "tmp/reports/objc3c-public-workflow/runtime-inspector.json",
                "tmp/reports/objc3c-public-workflow/capability-explorer.json",
                "capability_demo_compatibility",
                "stdlib/program_surface.json",
                "showcase/portfolio.json",
                "tmp/reports/objc3c-public-workflow/runtime-debug-trace.json",
                "tmp/reports/objc3c-public-workflow/compile-stage-trace.json",
                "## Exact Live Commands",
                "npm run objc3c -- build-native-contracts",
                "artifacts/bin/objc3c-frontend-c-api-runner.exe tests/tooling/fixtures/native/hello.objc3",
                "npm run objc3c -- inspect-compile-observability",
                "npm run objc3c -- inspect-compile-observability",
                "npm run objc3c -- inspect-runtime-inspector",
                "npm run objc3c -- inspect-runtime-inspector",
                "npm run objc3c -- inspect-capability-explorer",
                "npm run objc3c -- inspect-capability-explorer",
                "npm run objc3c -- trace-runtime-debug",
                "npm run objc3c -- trace-runtime-debug",
                "npm run objc3c -- trace-compile-stages",
                "npm run objc3c -- trace-compile-stages",
                "npm run objc3c -- validate-developer-tooling",
                "npm run objc3c -- validate-developer-tooling",
                "## Runtime Introspection Primitives",
                "objc3_runtime_copy_arc_debug_state_for_testing",
                "runtime_metadata_object_inspection_uses_llvm_objdump",
                "## Explicit Non-Goals",
            ),
        ),
        RunbookSourceSpec(
            docs_paths.BONUS_EXPERIENCES_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Bonus Experiences Boundary",
                "## Working Boundary",
                "interactive playground flows",
                "visual runtime inspection and capability-explorer flows",
                "starter-template and project-generator flows",
                "## Current Truthful Portfolio",
                "scripts.objc3c_workflow",
                "package.json",
                "native/objc3c/src/tools/objc3c_frontend_c_api_runner.cpp",
                "scripts/build_objc3c_native.ps1",
                "scripts/package_objc3c_runnable_toolchain.ps1",
                "showcase/portfolio.json",
                "showcase/auroraBoard/main.objc3",
                "docs/tutorials/getting_started.md",
                "docs/runbooks/objc3c_developer_tooling.md",
                "scripts/check_showcase_integration.py",
                "scripts/check_getting_started_integration.py",
                "## Exact Playground Inspector And Template Paths",
                "tests/tooling/fixtures/native/hello.objc3",
                "showcase/tutorial_walkthrough.json",
                "tests/tooling/runtime/arc_debug_instrumentation_probe.cpp",
                "## Exact Live Artifact And Output Paths",
                "artifacts/bin/objc3c-frontend-c-api-runner.exe",
                "tmp/artifacts/showcase/",
                "tmp/reports/developer-tooling/integration-summary.json",
                "npm run objc3c -- inspect-capability-explorer",
                "npm run objc3c -- inspect-capability-explorer",
                "tmp/reports/tutorials/",
                "artifacts/package/objc3c-runnable-toolchain-package.json",
                "## Exact Live Commands",
                "npm run objc3c -- compile-objc3c showcase/auroraBoard/main.objc3",
                "npm run objc3c -- compile-objc3c showcase/auroraBoard/main.objc3",
                "npm run objc3c -- package-runnable-toolchain",
                "npm run objc3c -- package-runnable-toolchain",
                "npm run objc3c -- validate-showcase",
                "npm run objc3c -- validate-runnable-showcase",
                "npm run objc3c -- validate-getting-started",
                "## Feasibility And Working Model",
                "## Working Rules For Downstream Issues",
                "## Explicit Non-Goals",
            ),
        ),
    )


__all__ = ("developer_runbook_source_specs",)
