"""Performance runbook source catalog rows."""

from __future__ import annotations

from documentation_surface import paths as docs_paths

from .runbook_source_types import RunbookSourceSpec


def performance_runbook_source_specs() -> tuple[RunbookSourceSpec, ...]:
    return (
        RunbookSourceSpec(
            docs_paths.PERFORMANCE_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Performance Benchmark Boundary",
                "## Working Boundary",
                "compiler compile-latency benchmark flows",
                "comparative baseline workloads for ObjC2, Swift, and C++",
                "telemetry packets, normalization logic, and benchmark claim output",
                "## Benchmark Taxonomy And Claim Classes",
                "local-measurement",
                "toolchain-comparison",
                "availability-limited",
                "non-portable",
                "## Exact Live Implementation Paths",
                "scripts.objc3c_workflow",
                "scripts/build_objc3c_native.ps1",
                "scripts/package_objc3c_runnable_toolchain.ps1",
                "showcase/portfolio.json",
                "docs/tutorials/objc2_swift_cpp_comparison.md",
                "tests/tooling/fixtures/performance/benchmark_portfolio.json",
                "## Exact Live Artifact And Output Paths",
                "tmp/artifacts/performance/",
                "tmp/reports/performance/",
                "tmp/pkg/objc3c-native-runnable-toolchain/",
                "## Exact Live Commands",
                "npm run objc3c -- build-native-binaries",
                "npm run objc3c -- benchmark-performance",
                "npm run objc3c -- benchmark-performance",
                "npm run objc3c -- benchmark-comparative-baselines",
                "npm run objc3c -- benchmark-comparative-baselines",
                "npm run objc3c -- validate-runnable-performance",
                "npm run objc3c -- validate-runnable-performance",
                "npm run objc3c -- validate-performance-foundation",
                "npm run objc3c -- validate-performance-foundation",
                "npm run objc3c -- package-runnable-toolchain",
                "## Exact Live Paths For Downstream Work",
                "docs/runbooks/objc3c_performance.md",
                "## Explicit Non-Goals",
            ),
        ),
        RunbookSourceSpec(
            docs_paths.RUNTIME_PERFORMANCE_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Runtime Performance Boundary",
                "## Working Boundary",
                "startup registration and replay costs",
                "selector lookup and dispatch cache behavior",
                "property/reflection query hot paths",
                "runtime performance summaries, regression artifacts, and packaged validation",
                "## Runtime Hot-Path Taxonomy",
                "startup-installation",
                "dispatch-cache",
                "reflection-query",
                "ownership-helpers",
                "runtime-counter-snapshot",
                "## Exact Live Implementation Paths",
                "native/objc3c/src/runtime/objc3_runtime.cpp",
                "native/objc3c/src/runtime/objc3_runtime_bootstrap_internal.h",
                "scripts/check_objc3c_runtime_acceptance.py",
                "scripts/benchmark_objc3c_runtime_performance.py",
                "scripts/check_objc3c_runtime_performance_integration.py",
                "scripts/check_objc3c_runnable_runtime_performance_end_to_end.py",
                "tests/tooling/fixtures/runtime_performance/source_surface.json",
                "## Exact Live Artifact And Output Paths",
                "tmp/artifacts/runtime-performance/",
                "tmp/reports/runtime-performance/",
                "## Exact Live Commands",
                "npm run objc3c -- benchmark-runtime-performance",
                "npm run objc3c -- benchmark-runtime-performance",
                "npm run objc3c -- validate-runtime-performance",
                "npm run objc3c -- validate-runtime-performance",
                "npm run objc3c -- validate-runnable-runtime-performance",
                "npm run objc3c -- validate-runnable-runtime-performance",
                "## Explicit Non-Goals",
            ),
        ),
        RunbookSourceSpec(
            docs_paths.COMPILER_THROUGHPUT_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Compiler Throughput Boundary",
                "## Working Boundary",
                "incremental build cache reuse and invalidation behavior",
                "macro-host cache publication and compile-coupled docs generation cost",
                "heavyweight validation-tier ownership and duplicate compile removal",
                "## Throughput Taxonomy",
                "compile-cold",
                "compile-cache-hit",
                "incremental-invalidation",
                "macro-host-runtime-boundary",
                "docs-generation",
                "validation-tier-overlap",
                "## Exact Live Implementation Paths",
                "scripts/check_objc3c_native_perf_budget.ps1",
                "scripts/check_objc3c_compiler_throughput_integration.py",
                "tests/tooling/fixtures/compiler_throughput/source_surface.json",
                "tests/tooling/fixtures/compiler_throughput/workload_manifest.json",
                "tests/tooling/fixtures/compiler_throughput/validation_tier_map.json",
                "tests/tooling/fixtures/compiler_throughput/optimization_policy.json",
                "tests/tooling/fixtures/compiler_throughput/artifact_surface.json",
                "schemas/objc3c-compiler-throughput-summary-v1.schema.json",
                "## Exact Live Artifact And Output Paths",
                "tmp/artifacts/objc3c-native/perf-budget/",
                "tmp/reports/compiler-throughput/",
                "## Exact Live Commands",
                "npm run objc3c -- benchmark-compiler-throughput",
                "## Explicit Non-Goals",
            ),
        ),
    )


__all__ = ("performance_runbook_source_specs",)
