"""Runbook and site documentation sources for the documentation surface model."""

from __future__ import annotations

from documentation_surface import paths as docs_paths
from documentation_surface.model import DocumentationSurfaceSource

from .source_factory import _source


def runbook_documentation_sources() -> tuple[DocumentationSurfaceSource, ...]:
    return (
        _source(
            docs_paths.SITE_BODY_PATH,
            required_tokens=(
                "## At a Glance {#toc-status-scope-note}",
                "## Quick Routes {#toc-quick-routes}",
                "## Reader Promises {#toc-reader-promises}",
                "## Specification Map {#toc-front-matter}",
                "## Language Parts {#toc-parts}",
                "[README.md](../README.md)",
                "[docs/tutorials/README.md](../docs/tutorials/README.md)",
                "[docs/tutorials/getting_started.md](../docs/tutorials/getting_started.md)",
                "[docs/tutorials/build_run_verify.md](../docs/tutorials/build_run_verify.md)",
                "[docs/tutorials/guided_walkthrough.md](../docs/tutorials/guided_walkthrough.md)",
                "[docs/tutorials/objc2_to_objc3_migration.md](../docs/tutorials/objc2_to_objc3_migration.md)",
                "[docs/tutorials/objc2_swift_cpp_comparison.md](../docs/tutorials/objc2_swift_cpp_comparison.md)",
                "[docs/objc3c-native.md](../docs/objc3c-native.md)",
                "[capability matrix](../docs/support/capability_matrix.md)",
                "[evidence map](../docs/support/evidence_map.md)",
            ),
            forbidden_tokens=(
                "[archived spec index](../docs/reference/legacy_spec_anchor_index.md#legacy-files)",
            ),
        ),
        _source(
            docs_paths.SITE_POLICY_PATH,
            required_tokens=(
                "## Tone and Accessibility Rules",
            ),
        ),
        _source(
            docs_paths.NATIVE_OWNERSHIP_PATH,
            required_tokens=(
                "## Public Doc Style And Accessibility Rules",
            ),
        ),
        _source(
            docs_paths.NATIVE_FRAGMENT_README_PATH,
            required_tokens=(
                "## Canonical Naming And Path Rules",
                "user-facing package entrypoints come from `package.json`",
                "transient outputs stay under `tmp/`",
                "published binaries and libraries stay under `artifacts/`",
            ),
        ),
        _source(
            docs_paths.MAINTAINER_WORKFLOW_PATH,
            required_tokens=(
                "## Superclean Working Boundary",
                "implementation roots:",
                "generated checked-in outputs:",
                "docs/tutorials/",
                "CONTRIBUTING.md",
                "showcase/",
                "docs/runbooks/objc3c_developer_tooling.md",
                "docs/runbooks/objc3c_bonus_experiences.md",
                "docs/runbooks/objc3c_performance.md",
                "docs/runbooks/objc3c_runtime_performance.md",
                "docs/runbooks/objc3c_compiler_throughput.md",
                "Do not add milestone-specific wrappers, sidecar compatibility files, or",
            ),
        ),
        _source(
            docs_paths.DEVELOPER_TOOLING_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Developer Tooling Boundary",
                "## Working Boundary",
                "## Exact Live Implementation Paths",
                "native/objc3c/src/tools/objc3c_frontend_c_api_runner.cpp",
                "native/objc3c/src/io/objc3_cli_reporting_output_contract_scaffold.h",
                "scripts/build_objc3c_native.ps1",
                "scripts.objc3c_workflow",
                "native/objc3c/src/runtime/objc3_runtime.cpp",
                "scripts/check_objc3c_library_cli_parity.py",
                "scripts/check_objc3c_runtime_acceptance.py",
                "tests/tooling/runtime/arc_debug_instrumentation_probe.cpp",
                "## Explainability And Introspection Surface",
                "## Exact Live Artifact And Output Paths",
                "artifacts/bin/objc3c-frontend-c-api-runner.exe",
                "tmp/artifacts/objc3c-native/repo_superclean_source_of_truth.json",
                "tmp/artifacts/compilation/objc3c-native/",
                "tmp/reports/objc3c-public-workflow/compile-observability.json",
                "tmp/reports/objc3c-public-workflow/runtime-inspector.json",
                "tmp/reports/objc3c-public-workflow/capability-explorer.json",
                "capability_demo_compatibility",
                "stdlib/program_surface.json",
                "showcase/portfolio.json",
                "tmp/reports/objc3c-public-workflow/compile-stage-trace.json",
                "## Exact Live Commands",
                "npm run objc3c -- build-native-contracts",
                "artifacts/bin/objc3c-frontend-c-api-runner.exe tests/tooling/fixtures/native/hello.objc3",
                "npm run objc3c -- inspect-compile-observability",
                "npm run objc3c -- inspect-compile-observability",
                "npm run objc3c -- inspect-runtime-inspector",
                "npm run objc3c -- inspect-runtime-inspector",
                "npm run objc3c -- inspect-capability-explorer",
                "npm run objc3c -- inspect-capability-explorer",
                "npm run objc3c -- trace-compile-stages",
                "npm run objc3c -- trace-compile-stages",
                "npm run objc3c -- validate-developer-tooling",
                "npm run objc3c -- validate-developer-tooling",
                "## Runtime Introspection Primitives",
                "objc3_runtime_copy_arc_debug_state_for_testing",
                "runtime_metadata_object_inspection_uses_llvm_objdump",
                "## Explicit Non-Goals",
            ),
        ),
        _source(
            docs_paths.BONUS_EXPERIENCES_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Bonus Experiences Boundary",
                "## Working Boundary",
                "interactive playground flows",
                "visual runtime inspection and capability-explorer flows",
                "starter-template and project-generator flows",
                "## Current Truthful Portfolio",
                "scripts.objc3c_workflow",
                "package.json",
                "native/objc3c/src/tools/objc3c_frontend_c_api_runner.cpp",
                "scripts/build_objc3c_native.ps1",
                "scripts/package_objc3c_runnable_toolchain.ps1",
                "showcase/portfolio.json",
                "showcase/auroraBoard/main.objc3",
                "docs/tutorials/getting_started.md",
                "docs/runbooks/objc3c_developer_tooling.md",
                "scripts/check_showcase_integration.py",
                "scripts/check_getting_started_integration.py",
                "## Exact Playground Inspector And Template Paths",
                "tests/tooling/fixtures/native/hello.objc3",
                "showcase/tutorial_walkthrough.json",
                "tests/tooling/runtime/arc_debug_instrumentation_probe.cpp",
                "## Exact Live Artifact And Output Paths",
                "artifacts/bin/objc3c-frontend-c-api-runner.exe",
                "tmp/artifacts/showcase/",
                "tmp/reports/developer-tooling/integration-summary.json",
                "npm run objc3c -- inspect-capability-explorer",
                "npm run objc3c -- inspect-capability-explorer",
                "tmp/reports/tutorials/",
                "artifacts/package/objc3c-runnable-toolchain-package.json",
                "## Exact Live Commands",
                "npm run objc3c -- compile-objc3c showcase/auroraBoard/main.objc3",
                "npm run objc3c -- compile-objc3c showcase/auroraBoard/main.objc3",
                "npm run objc3c -- package-runnable-toolchain",
                "npm run objc3c -- package-runnable-toolchain",
                "npm run objc3c -- validate-showcase",
                "npm run objc3c -- validate-runnable-showcase",
                "npm run objc3c -- validate-getting-started",
                "## Feasibility And Working Model",
                "## Working Rules For Downstream Issues",
                "## Explicit Non-Goals",
            ),
        ),
        _source(
            docs_paths.PERFORMANCE_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Performance Benchmark Boundary",
                "## Working Boundary",
                "compiler compile-latency benchmark flows",
                "comparative baseline workloads for ObjC2, Swift, and C++",
                "telemetry packets, normalization logic, and benchmark claim output",
                "## Benchmark Taxonomy And Claim Classes",
                "local-measurement",
                "toolchain-comparison",
                "availability-limited",
                "non-portable",
                "## Exact Live Implementation Paths",
                "scripts.objc3c_workflow",
                "scripts/build_objc3c_native.ps1",
                "scripts/package_objc3c_runnable_toolchain.ps1",
                "showcase/portfolio.json",
                "docs/tutorials/objc2_swift_cpp_comparison.md",
                "tests/tooling/fixtures/performance/benchmark_portfolio.json",
                "## Exact Live Artifact And Output Paths",
                "tmp/artifacts/performance/",
                "tmp/reports/performance/",
                "tmp/pkg/objc3c-native-runnable-toolchain/",
                "## Exact Live Commands",
                "npm run objc3c -- build-native-binaries",
                "npm run objc3c -- benchmark-performance",
                "npm run objc3c -- benchmark-performance",
                "npm run objc3c -- benchmark-comparative-baselines",
                "npm run objc3c -- benchmark-comparative-baselines",
                "npm run objc3c -- validate-runnable-performance",
                "npm run objc3c -- validate-runnable-performance",
                "npm run objc3c -- validate-performance-foundation",
                "npm run objc3c -- validate-performance-foundation",
                "npm run objc3c -- package-runnable-toolchain",
                "## Exact Live Paths For Downstream Work",
                "docs/runbooks/objc3c_performance.md",
                "## Explicit Non-Goals",
            ),
        ),
        _source(
            docs_paths.RUNTIME_PERFORMANCE_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Runtime Performance Boundary",
                "## Working Boundary",
                "startup registration and replay costs",
                "selector lookup and dispatch cache behavior",
                "property/reflection query hot paths",
                "runtime performance summaries, regression artifacts, and packaged validation",
                "## Runtime Hot-Path Taxonomy",
                "startup-installation",
                "dispatch-cache",
                "reflection-query",
                "ownership-helpers",
                "runtime-counter-snapshot",
                "## Exact Live Implementation Paths",
                "native/objc3c/src/runtime/objc3_runtime.cpp",
                "native/objc3c/src/runtime/objc3_runtime_bootstrap_internal.h",
                "scripts/check_objc3c_runtime_acceptance.py",
                "scripts/benchmark_objc3c_runtime_performance.py",
                "scripts/check_objc3c_runtime_performance_integration.py",
                "scripts/check_objc3c_runnable_runtime_performance_end_to_end.py",
                "tests/tooling/fixtures/runtime_performance/source_surface.json",
                "## Exact Live Artifact And Output Paths",
                "tmp/artifacts/runtime-performance/",
                "tmp/reports/runtime-performance/",
                "## Exact Live Commands",
                "npm run objc3c -- benchmark-runtime-performance",
                "npm run objc3c -- benchmark-runtime-performance",
                "npm run objc3c -- validate-runtime-performance",
                "npm run objc3c -- validate-runtime-performance",
                "npm run objc3c -- validate-runnable-runtime-performance",
                "npm run objc3c -- validate-runnable-runtime-performance",
                "## Explicit Non-Goals",
            ),
        ),
        _source(
            docs_paths.COMPILER_THROUGHPUT_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Compiler Throughput Boundary",
                "## Working Boundary",
                "incremental build cache reuse and invalidation behavior",
                "macro-host cache publication and compile-coupled docs generation cost",
                "heavyweight validation-tier ownership and duplicate compile removal",
                "## Throughput Taxonomy",
                "compile-cold",
                "compile-cache-hit",
                "incremental-invalidation",
                "macro-host-runtime-boundary",
                "docs-generation",
                "validation-tier-overlap",
                "## Exact Live Implementation Paths",
                "scripts/check_objc3c_native_perf_budget.ps1",
                "scripts/check_objc3c_compiler_throughput_integration.py",
                "tests/tooling/fixtures/compiler_throughput/source_surface.json",
                "tests/tooling/fixtures/compiler_throughput/workload_manifest.json",
                "tests/tooling/fixtures/compiler_throughput/validation_tier_map.json",
                "tests/tooling/fixtures/compiler_throughput/optimization_policy.json",
                "tests/tooling/fixtures/compiler_throughput/artifact_surface.json",
                "schemas/objc3c-compiler-throughput-summary-v1.schema.json",
                "## Exact Live Artifact And Output Paths",
                "tmp/artifacts/objc3c-native/perf-budget/",
                "tmp/reports/compiler-throughput/",
                "## Exact Live Commands",
                "npm run objc3c -- benchmark-compiler-throughput",
                "## Explicit Non-Goals",
            ),
        ),
        _source(
            docs_paths.PUBLIC_COMMAND_SURFACE_PATH,
            required_tokens=(
                "operator-facing appendix",
                "## Operator Notes",
                "Treat this file as a generated machine-facing appendix",
                "Canonical user-facing command names come from `package.json`",
                "`native/objc3c/`, `scripts/`, and `tests/` are the live implementation roots",
            ),
        ),
    )


__all__ = ("runbook_documentation_sources",)
