"""Stdlib documentation sources for the documentation surface model."""

from __future__ import annotations

from documentation_surface import paths as docs_paths
from documentation_surface.model import DocumentationSurfaceSource

from .source_factory import _source


def stdlib_documentation_sources() -> tuple[DocumentationSurfaceSource, ...]:
    return (
        _source(
            docs_paths.STDLIB_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Standard Library Foundation",
                "## Working boundary",
                "stdlib/",
                "tmp/artifacts/stdlib/",
                "tmp/reports/stdlib/",
                "## Non-goals",
                "## Expected end state",
                "## Lowering And Import Artifact Surface",
                "## Exact Live Implementation Paths",
                "scripts/check_objc3c_stdlib_foundation_integration.py",
                "scripts/check_objc3c_runnable_stdlib_foundation_end_to_end.py",
                "## Exact Live Artifact And Output Paths",
                "tmp/reports/stdlib/runnable-end-to-end-summary.json",
                "## Exact Live Commands",
                "npm run objc3c -- validate-runnable-stdlib-foundation",
                "npm run objc3c -- package-runnable-toolchain",
                "## Public actions",
                "npm run objc3c -- validate-runnable-stdlib-foundation",
                "stdlib/core_architecture.json",
                "stdlib/advanced_architecture.json",
                "stdlib/lowering_import_surface.json",
                "stdlib/advanced_helper_package_surface.json",
                "stdlib/program_surface.json",
                "module.runtime-registration-manifest.json",
                "identifier-safe implementation module declarations",
                "docs/runbooks/objc3c_stdlib_core.md",
                "docs/runbooks/objc3c_stdlib_advanced.md",
                "docs/runbooks/objc3c_stdlib_program.md",
            ),
        ),
        _source(
            docs_paths.STDLIB_README_PATH,
            required_tokens=(
                "# objc3c Standard Library",
                "## Boundary",
                "stdlib/workspace.json",
                "stdlib/module_inventory.json",
                "stdlib/stability_policy.json",
                "stdlib/package_surface.json",
                "stdlib/core_architecture.json",
                "stdlib/advanced_architecture.json",
                "stdlib/semantic_policy.json",
                "stdlib/lowering_import_surface.json",
                "stdlib/advanced_helper_package_surface.json",
                "stdlib/program_surface.json",
                "docs/runbooks/objc3c_stdlib_program.md",
                "docs/tutorials/",
                "showcase/",
                "site/src/index.body.md",
                "docs/runbooks/objc3c_stdlib_advanced.md",
                "machine-owned lowering roots",
                "## Working model",
            ),
        ),
        _source(
            docs_paths.STDLIB_CORE_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Core Stdlib Surface",
                "## Working boundary",
                "stdlib/core_architecture.json",
                "stdlib/modules/objc3.core/",
                "stdlib/modules/objc3.errors/",
                "stdlib/modules/objc3.keypath/",
                "stdlib/semantic_policy.json",
                "## Core family split",
                "`objc3.core` owns:",
                "`objc3.errors` owns:",
                "`objc3.keypath` remains in scope",
                "## Expected shipped API families",
                "profile-revision",
                "result-shape",
                "typed-keypath-text-compatibility",
                "## Exact checked-in source surface",
                "objc3_core_string_view_length",
                "objc3_core_string_view_prefix_units",
                "objc3_errors_text_data_compatibility_score",
                "objc3_errors_result_unwrap_or",
                "objc3_errors_result_bridge_diagnostic",
                "objc3_keypath_text_compatibility_diagnostic",
                "objc3_keypath_text_compatibility_score",
                "## Semantic guarantees",
                "presence or result tag says it is valid",
                "stable mismatch code `30601`",
                "stable mismatch codes `30602` and `30603`",
                "result_err_tag` stays `2`",
                "module semver metadata stays `1.0.0`",
                "## Explicit non-goals",
            ),
        ),
        _source(
            docs_paths.STDLIB_ADVANCED_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Advanced Stdlib Helper Surface",
                "## Working boundary",
                "stdlib/advanced_architecture.json",
                "stdlib/advanced_helper_package_surface.json",
                "stdlib/modules/objc3.concurrency/",
                "stdlib/modules/objc3.keypath/",
                "stdlib/modules/objc3.system/",
                "## Advanced family split",
                "`objc3.concurrency` owns:",
                "`objc3.keypath` owns:",
                "`objc3.system` owns:",
                "## Expected shipped API families",
                "structured-child-spawn",
                "reflection-interop",
                "runtime-composition-hook",
                "## Exact checked-in source surface",
                "objc3_concurrency_spawn_token",
                "objc3_keypath_component_count",
                "objc3_system_resource_token",
                "## Layering rules",
                "## Explicit non-goals",
            ),
        ),
        _source(
            docs_paths.STDLIB_PROGRAM_RUNBOOK_PATH,
            required_tokens=(
                "# objc3c Stdlib Program Surface",
                "## Working Boundary",
                "stdlib/program_surface.json",
                "docs/tutorials/getting_started.md",
                "docs/tutorials/objc2_swift_cpp_comparison.md",
                "showcase/README.md",
                "showcase/portfolio.json",
                "## Onboarding And Capability-Story Policy",
                "runnable-now stories",
                "actor-shaped comparison or",
                "stdlib/README.md",
                "objc3.core",
                "objc3.concurrency",
                "objc3.keypath",
                "objc3.system",
                "showcase/tutorial_walkthrough.json",
                "site/src/index.body.md",
                "## Current Truthful Portfolio",
                "## Exact Live Implementation Paths",
                "scripts/check_stdlib_surface.py",
                "scripts/check_documentation_surface.py",
                "scripts/check_showcase_surface.py",
                "scripts/check_showcase_integration.py",
                "scripts/check_getting_started_integration.py",
                "## Exact Capability Demo Paths",
                "showcase/auroraBoard/main.objc3",
                "showcase/signalMesh/main.objc3",
                "showcase/patchKit/main.objc3",
                "## Exact Live Artifact And Output Paths",
                "tmp/artifacts/showcase/",
                "tmp/reports/showcase/",
                "## Publish And Package Surface",
                "publish_inputs",
                "staged_manifest_fields",
                "stdlib_program_surface",
                "stdlib_program_publish_inputs",
                "tmp/pkg/objc3c-native-runnable-toolchain/",
                "## Live Workflow Surface",
                "validate-stdlib-foundation",
                "validate-runnable-stdlib-foundation",
                "validate-stdlib-program",
                "validate-runnable-stdlib-program",
                "npm run objc3c -- validate-stdlib-program",
                "npm run objc3c -- validate-runnable-stdlib-program",
                "tmp/reports/tutorials/",
                "## Exact Live Commands",
                "npm run objc3c -- validate-showcase",
                "npm run objc3c -- validate-runnable-showcase",
                "npm run objc3c -- inspect-capability-explorer",
                "npm run objc3c -- inspect-capability-explorer",
                "## Working Rules For Downstream Issues",
                "## Explicit Non-Goals",
            ),
            forbidden_tokens=(
                "for actors, status bridging, and runtime",
            ),
        ),
    )


__all__ = ("stdlib_documentation_sources",)
