"""Tutorial documentation sources for the documentation surface model."""

from __future__ import annotations

from documentation_surface import paths as docs_paths
from documentation_surface.model import DocumentationSurfaceSource

from .source_factory import _source


def tutorial_documentation_sources() -> tuple[DocumentationSurfaceSource, ...]:
    return (
        _source(
            docs_paths.TUTORIAL_README_PATH,
            required_tokens=(
                "# Tutorials And Canonicalization Guides",
                "## Learning Paths",
                "## Start Here By Goal",
                "## Capability-Backed Routes",
                "## Canonical Inputs",
                "docs/tutorials/",
                "showcase/README.md",
                "showcase/portfolio.json",
                "actor-shaped messaging",
                "stdlib/README.md",
                "objc3.core",
                "objc3.concurrency",
                "objc3.keypath",
                "objc3.system",
                "## Exact Live Paths For Downstream Work",
                "scripts/check_documentation_surface.py",
                "## Explicit Non-Goals",
            ),
            forbidden_tokens=(
                "use it for actors, status bridging, and runtime messaging",
            ),
        ),
        _source(
            docs_paths.GETTING_STARTED_PATH,
            required_tokens=(
                "# Getting Started With The Runnable Subset",
                "## What This Tutorial Proves",
                "## Teaching Model",
                "## Step 1 Verify The Toolchain",
                "npm run objc3c -- build-native-binaries",
                "npm run objc3c -- test-smoke",
                "## Step 2 Compile One Runnable Example",
                "showcase/auroraBoard/main.objc3",
                "## Step 3 Use The Showcase Surface As The Tutorial Backbone",
                "npm run objc3c -- check-showcase-surface",
                "npm run objc3c -- validate-showcase",
                "## Step 4 Choose The Next Learning Path",
                "docs/runbooks/objc3c_public_command_surface.md",
                "actor-shaped messaging",
                "stdlib/README.md",
                "objc3.concurrency",
                "objc3.system",
                "## Canonical Inputs",
                "## Exact Live Paths For Downstream Work",
                "scripts/check_documentation_surface.py",
                "## Explicit Non-Goals",
            ),
            forbidden_tokens=(
                "`signalMesh` for actors, status bridging, and runtime messaging",
            ),
        ),
        _source(
            docs_paths.BUILD_RUN_VERIFY_PATH,
            required_tokens=(
                "# Tutorial Build Run And Verify Surface",
                "## Workflow Boundary",
                "## Build",
                "npm run objc3c -- build-native-binaries",
                "## Run The First Compile",
                "npm run objc3c -- compile-objc3c showcase/auroraBoard/main.objc3",
                "## Verify The Portfolio Surface",
                "npm run objc3c -- check-showcase-surface",
                "npm run objc3c -- validate-showcase",
                "npm run objc3c -- validate-runnable-showcase",
                "## Validation Surface",
                "scripts/check_getting_started_surface.py",
                "scripts/check_getting_started_integration.py",
                "npm run objc3c -- validate-getting-started",
                "## Artifact And Report Expectations",
                "tmp/artifacts/showcase/<example-id>/",
                "tmp/reports/showcase/",
                "## Canonical Inputs",
                "## Exact Live Paths For Downstream Work",
                "scripts.objc3c_workflow",
                "## Explicit Non-Goals",
            ),
        ),
        _source(
            docs_paths.GUIDED_WALKTHROUGH_PATH,
            required_tokens=(
                "# Guided Showcase Walkthrough",
                "## Walkthrough Boundary",
                "## Walkthrough Steps",
                "npm run objc3c -- build-native-binaries",
                "npm run objc3c -- compile-objc3c showcase/auroraBoard/main.objc3",
                "npm run objc3c -- compile-objc3c showcase/signalMesh/main.objc3",
                "npm run objc3c -- compile-objc3c showcase/patchKit/main.objc3",
                "npm run objc3c -- check-showcase-surface",
                "npm run objc3c -- validate-showcase",
                "## Walkthrough Assets",
                "showcase/tutorial_walkthrough.json",
                "scripts/check_getting_started_surface.py",
                "scripts/check_getting_started_integration.py",
                "npm run objc3c -- validate-getting-started",
                "## Canonical Inputs",
                "## Exact Live Paths For Downstream Work",
                "scripts/check_showcase_surface.py",
                "## Explicit Non-Goals",
            ),
        ),
        _source(
            docs_paths.MIGRATION_GUIDE_PATH,
            required_tokens=(
                "# ObjC2 To ObjC3 Canonicalization Guide",
                "## Canonicalization Boundary",
                "## Step 1 Keep The Familiar ObjC Shape, Drop The Implicit Assumptions",
                "showcase/auroraBoard/main.objc3",
                "## Step 3 Treat Swift-Facing Async And Imported Hooks As Explicit Interop Contracts",
                "showcase/signalMesh/main.objc3",
                "showcase/patchKit/main.objc3",
                "npm run objc3c -- check-showcase-surface",
                "npm run objc3c -- validate-showcase",
                "## Recommended Reading Order",
                "## Canonical Inputs",
                "## Exact Live Paths For Downstream Work",
                "scripts/check_documentation_surface.py",
                "## Explicit Non-Goals",
            ),
        ),
        _source(
            docs_paths.COMPARISON_README_PATH,
            required_tokens=(
                "# ObjC2 Swift And C++ Comparison Surface",
                "## Start With The Capability That Matches The Question",
                "## Comparison Boundary",
                "## Current Truthful Comparison Shape",
                "## Canonical Inputs",
                "showcase/patchKit/main.objc3",
                "showcase/signalMesh/main.objc3",
                "actor-shaped workflow",
                "stdlib/README.md",
                "objc3.concurrency",
                "objc3.system",
                "objc3.keypath",
                "## Exact Live Paths For Downstream Work",
                "scripts/check_documentation_surface.py",
                "## Explicit Non-Goals",
            ),
        ),
    )


__all__ = ("tutorial_documentation_sources",)
