#ifndef OBJC3C_LIBOBJC3C_FRONTEND_OBJC3C_FRONTEND_ARTIFACT_H_
#define OBJC3C_LIBOBJC3C_FRONTEND_OBJC3C_FRONTEND_ARTIFACT_H_

typedef enum objc3c_frontend_artifact_kind {
  OBJC3C_FRONTEND_ARTIFACT_DIAGNOSTICS = 0,
  OBJC3C_FRONTEND_ARTIFACT_MANIFEST = 1,
  OBJC3C_FRONTEND_ARTIFACT_IR = 2,
  OBJC3C_FRONTEND_ARTIFACT_OBJECT = 3
} objc3c_frontend_artifact_kind_t;

#endif  // OBJC3C_LIBOBJC3C_FRONTEND_OBJC3C_FRONTEND_ARTIFACT_H_
