#pragma once

struct Objc3SemanticDiagnosticTaxonomyAndFixitSynthesisScaffold {
  bool sema_pass_flow_summary_present = false;
  bool sema_pass_flow_summary_ready = false;
  bool sema_parity_surface_present = false;
  bool sema_parity_surface_ready = false;
  bool diagnostics_taxonomy_consistent = false;
  bool arc_diagnostics_fixit_summary_deterministic = false;
  bool arc_diagnostics_fixit_handoff_deterministic = false;
  bool typed_sema_handoff_deterministic = false;
  bool modular_split_ready = false;
  std::string sema_pass_flow_handoff_key;
  std::string typed_handoff_key;
  std::string scaffold_key;
  std::string failure_reason;
};
struct Objc3SemanticDiagnosticTaxonomyAndFixitSynthesisCoreFeatureImplementationSurface {
  bool sema_pass_flow_summary_ready = false;
  bool sema_parity_surface_ready = false;
  bool diagnostics_taxonomy_consistent = false;
  bool arc_diagnostics_fixit_summary_deterministic = false;
  bool arc_diagnostics_fixit_handoff_deterministic = false;
  bool typed_sema_handoff_deterministic = false;
  bool modular_split_ready = false;
  bool diagnostics_case_accounting_consistent = false;
  bool arc_diagnostics_fixit_case_accounting_consistent = false;
  bool replay_keys_ready = false;
  bool core_feature_impl_ready = false;
  std::size_t diagnostics_total = 0;
  std::size_t diagnostics_after_pass_final = 0;
  std::size_t diagnostics_emitted_total = 0;
  std::size_t ownership_arc_diagnostic_candidate_sites = 0;
  std::size_t ownership_arc_fixit_available_sites = 0;
  std::size_t ownership_arc_profiled_sites = 0;
  std::size_t ownership_arc_weak_unowned_conflict_diagnostic_sites = 0;
  std::size_t ownership_arc_empty_fixit_hint_sites = 0;
  std::size_t ownership_arc_contract_violation_sites = 0;
  std::string sema_pass_flow_handoff_key;
  std::string typed_handoff_key;
  std::string recovery_replay_key;
  std::string arc_diagnostics_fixit_replay_key;
  std::string core_feature_key;
  std::string failure_reason;
};
struct Objc3SemanticDiagnosticTaxonomyAndFixitSynthesisCoreFeatureExpansionSurface {
  bool core_feature_impl_ready = false;
  bool modular_split_ready = false;
  bool typed_handoff_key_consistent = false;
  bool arc_diagnostics_fixit_replay_key_consistent = false;
  bool diagnostics_fixit_payload_accounting_consistent = false;
  bool expansion_replay_keys_ready = false;
  bool core_feature_expansion_ready = false;
  std::size_t ownership_arc_diagnostic_candidate_sites = 0;
  std::size_t ownership_arc_fixit_available_sites = 0;
  std::size_t ownership_arc_profiled_sites = 0;
  std::size_t ownership_arc_weak_unowned_conflict_diagnostic_sites = 0;
  std::size_t ownership_arc_empty_fixit_hint_sites = 0;
  std::size_t ownership_arc_contract_violation_sites = 0;
  std::string sema_pass_flow_handoff_key;
  std::string typed_handoff_key;
  std::string recovery_replay_key;
  std::string arc_diagnostics_fixit_replay_key;
  std::string core_feature_key;
  std::string expansion_key;
  std::string failure_reason;
};
struct Objc3SemanticDiagnosticTaxonomyAndFixitSynthesisEdgeCaseCompatibilitySurface {
  bool core_feature_expansion_ready = false;
  bool typed_handoff_key_consistent = false;
  bool compatibility_handoff_consistent = false;
  bool language_version_pragma_coordinate_order_consistent = false;
  bool parse_artifact_edge_case_robustness_consistent = false;
  bool parse_artifact_replay_key_deterministic = false;
  bool parse_recovery_determinism_hardening_consistent = false;
  bool edge_case_compatibility_consistent = false;
  bool edge_case_compatibility_ready = false;
  std::size_t ownership_arc_diagnostic_candidate_sites = 0;
  std::size_t ownership_arc_fixit_available_sites = 0;
  std::size_t ownership_arc_profiled_sites = 0;
  std::size_t ownership_arc_weak_unowned_conflict_diagnostic_sites = 0;
  std::size_t ownership_arc_empty_fixit_hint_sites = 0;
  std::size_t ownership_arc_contract_violation_sites = 0;
  std::string typed_handoff_key;
  std::string compatibility_handoff_key;
  std::string parse_artifact_edge_robustness_key;
  std::string parse_recovery_determinism_hardening_key;
  std::string expansion_key;
  std::string edge_case_compatibility_key;
  std::string failure_reason;
};
struct Objc3SemanticDiagnosticTaxonomyAndFixitSynthesisEdgeCaseExpansionAndRobustnessSurface {
  bool core_feature_expansion_ready = false;
  bool edge_case_compatibility_consistent = false;
  bool edge_case_compatibility_ready = false;
  bool edge_case_expansion_consistent = false;
  bool edge_case_robustness_ready = false;
  std::size_t ownership_arc_diagnostic_candidate_sites = 0;
  std::size_t ownership_arc_fixit_available_sites = 0;
  std::size_t ownership_arc_profiled_sites = 0;
  std::size_t ownership_arc_weak_unowned_conflict_diagnostic_sites = 0;
  std::size_t ownership_arc_empty_fixit_hint_sites = 0;
  std::size_t ownership_arc_contract_violation_sites = 0;
  std::string typed_handoff_key;
  std::string compatibility_handoff_key;
  std::string parse_artifact_edge_robustness_key;
  std::string long_tail_grammar_edge_case_robustness_key;
  std::string parse_recovery_determinism_hardening_key;
  std::string edge_case_compatibility_key;
  std::string edge_case_robustness_key;
  std::string failure_reason;
};
struct Objc3SemanticDiagnosticTaxonomyAndFixitSynthesisDiagnosticsHardeningSurface {
  bool edge_case_robustness_ready = false;
  bool edge_case_expansion_consistent = false;
  bool parser_diagnostic_surface_consistent = false;
  bool parser_diagnostic_code_surface_deterministic = false;
  bool parse_artifact_diagnostics_hardening_consistent = false;
  bool long_tail_grammar_diagnostics_hardening_consistent = false;
  bool long_tail_grammar_diagnostics_hardening_ready = false;
  bool semantic_diagnostics_deterministic = false;
  bool diagnostics_hardening_consistent = false;
  bool diagnostics_hardening_ready = false;
  std::size_t parser_diagnostic_code_count = 0;
  std::size_t parser_diagnostic_grammar_hook_code_count = 0;
  std::size_t parser_diagnostic_coordinate_tagged_count = 0;
  std::string edge_case_robustness_key;
  std::string parse_artifact_diagnostics_hardening_key;
  std::string long_tail_grammar_diagnostics_hardening_key;
  std::string typed_handoff_key;
  std::string diagnostics_hardening_key;
  std::string failure_reason;
};
struct Objc3SemanticDiagnosticTaxonomyAndFixitSynthesisRecoveryDeterminismHardeningSurface {
  bool diagnostics_hardening_consistent = false;
  bool diagnostics_hardening_ready = false;
  bool parse_recovery_determinism_hardening_consistent = false;
  bool long_tail_grammar_recovery_determinism_consistent = false;
  bool long_tail_grammar_recovery_determinism_ready = false;
  bool parser_recovery_replay_ready = false;
  bool recovery_determinism_consistent = false;
  bool recovery_determinism_ready = false;
  std::size_t parser_diagnostic_code_count = 0;
  std::size_t parser_diagnostic_grammar_hook_code_count = 0;
  std::size_t parser_diagnostic_coordinate_tagged_count = 0;
  std::string edge_case_robustness_key;
  std::string parse_artifact_diagnostics_hardening_key;
  std::string typed_handoff_key;
  std::string diagnostics_hardening_key;
  std::string parse_recovery_determinism_hardening_key;
  std::string long_tail_grammar_recovery_determinism_key;
  std::string recovery_determinism_key;
  std::string failure_reason;
};
struct Objc3SemanticDiagnosticTaxonomyAndFixitSynthesisConformanceMatrixImplementationSurface {
  bool recovery_determinism_consistent = false;
  bool recovery_determinism_ready = false;
  bool parse_lowering_conformance_matrix_consistent = false;
  bool long_tail_grammar_conformance_matrix_consistent = false;
  bool long_tail_grammar_conformance_matrix_ready = false;
  bool conformance_matrix_consistent = false;
  bool conformance_matrix_ready = false;
  std::size_t parse_lowering_conformance_matrix_case_count = 0;
  std::string recovery_determinism_key;
  std::string parse_lowering_conformance_matrix_key;
  std::string long_tail_grammar_conformance_matrix_key;
  std::string conformance_matrix_key;
  std::string failure_reason;
};
struct Objc3SemanticDiagnosticTaxonomyAndFixitSynthesisConformanceCorpusExpansionSurface {
  bool conformance_matrix_consistent = false;
  bool conformance_matrix_ready = false;
  bool parse_lowering_conformance_corpus_consistent = false;
  bool conformance_corpus_consistent = false;
  bool conformance_corpus_ready = false;
  std::size_t parse_lowering_conformance_corpus_case_count = 0;
  std::size_t parse_lowering_conformance_corpus_passed_case_count = 0;
  std::size_t parse_lowering_conformance_corpus_failed_case_count = 0;
  std::string conformance_matrix_key;
  std::string parse_lowering_conformance_corpus_key;
  std::string conformance_corpus_key;
  std::string failure_reason;
};
struct Objc3SemanticDiagnosticTaxonomyAndFixitSynthesisPerformanceQualityGuardrailsSurface {
  bool conformance_corpus_consistent = false;
  bool conformance_corpus_ready = false;
  bool parse_lowering_performance_quality_guardrails_consistent = false;
  bool performance_quality_guardrails_consistent = false;
  bool performance_quality_guardrails_ready = false;
  std::size_t parse_lowering_performance_quality_guardrails_case_count = 0;
  std::size_t parse_lowering_performance_quality_guardrails_passed_case_count = 0;
  std::size_t parse_lowering_performance_quality_guardrails_failed_case_count = 0;
  std::string conformance_corpus_key;
  std::string parse_lowering_performance_quality_guardrails_key;
  std::string performance_quality_guardrails_key;
  std::string failure_reason;
};
