"""Objective-C 3.0 package manager model helpers."""

from __future__ import annotations

from .model import (
    LOCAL_PACKAGE_ABI_IDENTITY,
    LOCAL_PACKAGE_LANGUAGE_VERSION,
    LOCAL_PACKAGE_TRUST_KEY_ID,
    PACKAGE_MANIFEST_CONTRACT_ID,
    PACKAGE_MANAGER_TAMPER_CODE,
    PackageManagerPaths,
    build_lock_components,
    cache_payload_from_mirror_package,
    collect_lock_model_failures,
    default_trust_policy_payload,
    file_digest,
    package_resolution_plan,
    package_manifest_paths,
    stable_digest,
)
from .operations import (
    PACKAGE_OPERATION_PLAN_CONTRACT_ID,
    PACKAGE_OPERATION_RECEIPT_CONTRACT_ID,
    PackageOperationError,
    PackageOperationRequest,
    collect_package_operation_failures,
    package_operation_plan,
    package_operation_receipt,
)
from .trust import (
    LOCAL_PACKAGE_SIGNING_BACKEND,
    LOCAL_PACKAGE_TRUST_ROOT_ID,
    PACKAGE_TRUST_CONTRACT_ID,
    SIGNATURE_ENVELOPE_CONTRACT_ID,
    collect_manifest_trust_failures,
    collect_signature_envelope_failures,
    collect_trust_policy_failures,
    production_signing_reserved_diagnostic,
    sign_manifest_trust_envelope,
)

__all__ = [
    "LOCAL_PACKAGE_ABI_IDENTITY",
    "LOCAL_PACKAGE_LANGUAGE_VERSION",
    "LOCAL_PACKAGE_TRUST_KEY_ID",
    "PACKAGE_MANAGER_TAMPER_CODE",
    "PACKAGE_MANIFEST_CONTRACT_ID",
    "PACKAGE_OPERATION_PLAN_CONTRACT_ID",
    "PACKAGE_OPERATION_RECEIPT_CONTRACT_ID",
    "PackageManagerPaths",
    "PackageOperationError",
    "PackageOperationRequest",
    "build_lock_components",
    "cache_payload_from_mirror_package",
    "collect_lock_model_failures",
    "collect_manifest_trust_failures",
    "collect_package_operation_failures",
    "collect_signature_envelope_failures",
    "collect_trust_policy_failures",
    "default_trust_policy_payload",
    "file_digest",
    "LOCAL_PACKAGE_SIGNING_BACKEND",
    "LOCAL_PACKAGE_TRUST_ROOT_ID",
    "package_resolution_plan",
    "package_manifest_paths",
    "package_operation_plan",
    "package_operation_receipt",
    "PACKAGE_TRUST_CONTRACT_ID",
    "production_signing_reserved_diagnostic",
    "sign_manifest_trust_envelope",
    "SIGNATURE_ENVELOPE_CONTRACT_ID",
    "stable_digest",
]
