#pragma once

#include "pipeline/objc3_typed_sema_to_lowering_contract_surface_parts/objc3_typed_sema_to_lowering_contract_surface_part_001.inc"
#include "pipeline/objc3_typed_sema_to_lowering_contract_surface_parts/objc3_typed_sema_to_lowering_contract_surface_part_002.inc"
