#pragma once

#include "pipeline/objc3_parse_lowering_readiness_surface_parts/objc3_parse_lowering_readiness_surface_part_001.inc"
#include "pipeline/objc3_parse_lowering_readiness_surface_parts/objc3_parse_lowering_readiness_surface_part_002.inc"
#include "pipeline/objc3_parse_lowering_readiness_surface_parts/objc3_parse_lowering_readiness_surface_part_003.inc"
#include "pipeline/objc3_parse_lowering_readiness_surface_parts/objc3_parse_lowering_readiness_surface_part_004.inc"
