#pragma once

#include "pipeline/objc3_final_readiness_gate_core_feature_implementation_surface_parts/objc3_final_readiness_gate_core_feature_implementation_surface_part_001.inc"
#include "pipeline/objc3_final_readiness_gate_core_feature_implementation_surface_parts/objc3_final_readiness_gate_core_feature_implementation_surface_part_002.inc"
