#pragma once

#include "pipeline/objc3_ir_emission_core_feature_implementation_surface_parts/objc3_ir_emission_core_feature_implementation_surface_part_001.inc"
#include "pipeline/objc3_ir_emission_core_feature_implementation_surface_parts/objc3_ir_emission_core_feature_implementation_surface_part_002.inc"
