#include "pipeline/objc3_ownership_aware_lowering_behavior_scaffold_owners.h"

Objc3OwnershipAwareLoweringBehaviorScaffold BuildObjc3OwnershipAwareLoweringBehaviorScaffold(
    const Objc3OwnershipQualifierLoweringContract &ownership_qualifier_contract,
    const std::string &ownership_qualifier_replay_key,
    const Objc3RetainReleaseOperationLoweringContract &retain_release_contract,
    const std::string &retain_release_replay_key,
    const Objc3AutoreleasePoolScopeLoweringContract &autoreleasepool_scope_contract,
    const std::string &autoreleasepool_scope_replay_key,
    const Objc3WeakUnownedSemanticsLoweringContract &weak_unowned_semantics_contract,
    const std::string &weak_unowned_semantics_replay_key,
    const Objc3ArcDiagnosticsFixitLoweringContract &arc_diagnostics_fixit_contract,
    const std::string &arc_diagnostics_fixit_replay_key,
    bool compatibility_handoff_consistent,
    bool language_version_pragma_coordinate_order_consistent,
    bool parse_artifact_edge_case_robustness_consistent,
    bool parse_artifact_replay_key_deterministic,
    const std::string &compatibility_handoff_key,
    const std::string &parse_artifact_edge_robustness_key,
    bool parse_recovery_determinism_hardening_consistent,
    const std::string &parse_recovery_determinism_hardening_key,
    bool parse_lowering_conformance_matrix_consistent,
    const std::string &parse_lowering_conformance_matrix_key,
    bool parse_lowering_conformance_corpus_consistent,
    std::size_t parse_lowering_conformance_corpus_case_count,
    const std::string &parse_lowering_conformance_corpus_key,
    bool parse_lowering_performance_quality_guardrails_consistent,
    std::size_t parse_lowering_performance_quality_guardrails_case_count,
    std::size_t parse_lowering_performance_quality_guardrails_passed_case_count,
    std::size_t parse_lowering_performance_quality_guardrails_failed_case_count,
    const std::string &parse_lowering_performance_quality_guardrails_key,
    bool lowering_pass_graph_conformance_corpus_ready,
    const std::string &lowering_pass_graph_conformance_corpus_key,
    bool lowering_pass_graph_performance_quality_guardrails_ready,
    const std::string &lowering_pass_graph_performance_quality_guardrails_key) {
  Objc3OwnershipAwareLoweringBehaviorScaffold scaffold;
  objc3_ownership_aware_lowering_behavior_scaffold::PopulateEvidence(
      scaffold,
      ownership_qualifier_contract,
      ownership_qualifier_replay_key,
      retain_release_contract,
      retain_release_replay_key,
      autoreleasepool_scope_contract,
      autoreleasepool_scope_replay_key,
      weak_unowned_semantics_contract,
      weak_unowned_semantics_replay_key,
      arc_diagnostics_fixit_contract,
      arc_diagnostics_fixit_replay_key,
      compatibility_handoff_consistent,
      language_version_pragma_coordinate_order_consistent,
      parse_artifact_edge_case_robustness_consistent,
      parse_artifact_replay_key_deterministic,
      compatibility_handoff_key,
      parse_artifact_edge_robustness_key,
      parse_recovery_determinism_hardening_consistent,
      parse_recovery_determinism_hardening_key,
      parse_lowering_conformance_matrix_consistent,
      parse_lowering_conformance_matrix_key,
      parse_lowering_conformance_corpus_consistent,
      parse_lowering_conformance_corpus_case_count,
      parse_lowering_conformance_corpus_key,
      parse_lowering_performance_quality_guardrails_consistent,
      parse_lowering_performance_quality_guardrails_case_count,
      parse_lowering_performance_quality_guardrails_passed_case_count,
      parse_lowering_performance_quality_guardrails_failed_case_count,
      parse_lowering_performance_quality_guardrails_key,
      lowering_pass_graph_conformance_corpus_ready,
      lowering_pass_graph_conformance_corpus_key,
      lowering_pass_graph_performance_quality_guardrails_ready,
      lowering_pass_graph_performance_quality_guardrails_key);
  objc3_ownership_aware_lowering_behavior_scaffold::PublishReadiness(
      scaffold,
      ownership_qualifier_contract,
      retain_release_contract,
      weak_unowned_semantics_contract,
      arc_diagnostics_fixit_contract);
  objc3_ownership_aware_lowering_behavior_scaffold::PublishFailureReason(
      scaffold);
  return scaffold;
}
