from __future__ import annotations

CONTRACT_ID = "objc3c.parser.draft-syntax-surface.v1"

REQUIRED_AST_FIELDS = [
    "struct Objc3DraftSyntaxSurfaceSummary",
    "block_literal_sites",
    "block_explicit_capture_list_sites",
    "block_explicit_capture_byref_sites",
    "block_byref_capture_sites",
    "block_heap_escape_candidate_sites",
    "try_expression_sites",
    "throw_statement_sites",
    "do_catch_sites",
    "error_catch_clause_sites",
    "error_catch_binding_sites",
    "error_catch_all_sites",
    "error_bridge_payload_sites",
    "error_foreign_boundary_annotation_sites",
    "error_nested_cleanup_marker_sites",
    "throws_callable_sites",
    "async_callable_sites",
    "await_expression_sites",
    "actor_interface_sites",
    "actor_nonisolated_callable_sites",
    "actor_isolation_marker_sites",
    "actor_sendable_annotation_sites",
    "task_runtime_construct_sites",
    "task_cancellation_check_sites",
    "task_suspension_point_sites",
    "macro_attribute_sites",
    "macro_package_sites",
    "macro_provenance_sites",
    "macro_cache_key_sites",
    "macro_sandbox_policy_sites",
    "property_behavior_sites",
    "property_attribute_sites",
    "property_accessor_selector_sites",
    "property_synthesis_metadata_sites",
    "property_reflection_input_sites",
    "property_ownership_nullability_sites",
    "interop_attribute_sites",
    "interop_import_module_sites",
    "interop_swift_annotation_sites",
    "interop_cxx_annotation_sites",
    "interop_header_import_sites",
    "interop_header_export_sites",
    "interop_abi_alignment_sites",
    "interop_foreign_type_sites",
    "interop_mixed_image_sites",
    "interop_package_entry_sites",
    "interop_error_bridge_sites",
    "draft_syntax_surface_sites",
    "draft_syntax_surface_summary",
]

REQUIRED_PARSER_ANCHORS = [
    "BuildObjc3DraftSyntaxSurfaceSummary",
    "BuildObjc3DraftSyntaxSurfaceReplayKey",
    "CountDraftSyntaxExpr",
    "CountDraftSyntaxCallable",
    "ParseBlockLiteralExpression",
    "block_explicit_capture_byref_count",
    "block_storage_requires_byref_cells",
    "ParseOptionalThrowsClause",
    "ParseOptionalAsyncClause",
    "ParseObjcActorInterfaceDecl",
    "objc_nonisolated",
    "task_runtime_construct_sites",
    "actor_sendable_annotation_sites",
    "objc_macro_package",
    "objc_macro_provenance",
    "objc_macro_cache_key",
    "objc_macro_sandbox",
    "property_behavior_declared",
    "objc_import_module",
    "objc_export_header",
    "objc_abi_align",
    "objc_foreign_type",
    "objc_mixed_image",
    "objc_package_entry",
    "objc_status_code",
]

REQUIRED_CONTRACT_ANCHORS = [
    "draft_syntax_surface_count",
    "draft_syntax_surface_fingerprint",
    "draft_syntax_surface_handoff_key",
    "draft_syntax_surface_handoff_deterministic",
    "BuildObjc3DraftSyntaxSurfaceFingerprint",
]

REQUIRED_ARTIFACT_FIELDS = [
    "draft_syntax_surface_count",
    "draft_syntax_surface_fingerprint",
    "draft_syntax_surface_handoff_key",
    "draft_syntax_surface_deterministic",
]

POSITIVE_TOKENS = [
    "let callback = ^[__block scratch] (i32 value)",
    "scratch = scratch + value;",
    "return seed + scratch;",
    "fn risky(value: i32) throws -> i32",
    "throw 7;",
    "let direct = try risky(0);",
    "let bridged = try? bridgeStatus(1, 0);",
    "do {",
    "catch (NSError* error)",
    "objc_foreign, objc_status_code(success: 0, error_type: NSError, mapping: mapStatus)",
    "defer {",
    "produce();",
    "async fn runTask()",
    "async fn taskGroupEntry()",
    "async fn detachedTaskEntry()",
    "task_spawn_child();",
    "with_task_group_scope();",
    "task_group_add_task();",
    "task_runtime_cancelled_value()",
    "task_group_cancel_all();",
    "task_runtime_on_cancel();",
    "return await task_group_wait_next();",
    "return await produce();",
    "actor class SyntaxActor",
    "objc_nonisolated",
    "sendable_transfer_marker();",
    "objc_executor(named(\"parser.actor\"))",
    "objc_macro(named(\"Trace\"))",
    "objc_macro_package(named(\"std.metaprogramming.trace\"))",
    "objc_macro_provenance(named(\"sha256:abc123\"))",
    "objc_macro_cache_key(named(\"Trace:v1:parser\"))",
    "objc_macro_sandbox(named(\"deterministic\"))",
    "behavior=Observed",
    "@property (retain, nullable, direct, behavior=Observed",
    "@property (unsafe_unretained, null_resettable, class, behavior=Observed",
    "getter=currentValue",
    "setter=setCurrentValue:",
    "objc_foreign",
    "objc_import_module(named(\"ParserKit\"))",
    "objc_swift_name(named(\"ParserKit.foreignEntry()\"))",
    "objc_swift_private",
    "objc_cxx_name(named(\"ParserKit::foreignEntry\"))",
    "objc_header_name(named(\"ParserKit/ForeignEntry.h\"))",
    "objc_export_header(named(\"ParserKit/ParserKit.h\"))",
    "objc_abi_align(bytes: 16)",
    "objc_foreign_type(named(\"ParserKit.ForeignEntry\"))",
    "objc_mixed_image(named(\"ParserKitCore\"))",
    "objc_package_entry(named(\"ParserKit.foreignEntry\"))",
    "objc_status_code(success: 0, error_type: NSError, mapping: mapStatus)",
]

VALIDATION_COMMANDS = [
    "npm run objc3c -- test-fixture-matrix",
    "npm run objc3c -- test-negative-expectations",
    "npm run objc3c -- test-execution-replay",
]
