Set-StrictMode -Version Latest

Import-Module (Join-Path $PSScriptRoot "..\..\objc3c_native_cmake.psm1") -Force -DisableNameChecking

function Get-ManifestProvenanceCoreToolchainFiles {
  $coreArtifacts = Get-Objc3cNativePackageArtifactRelativePaths
  return @(
    "package.json",
    $coreArtifacts.NativeExecutable,
    $coreArtifacts.CapiRunnerExecutable,
    $coreArtifacts.RuntimeLibrary,
    "scripts/__init__.py",
    "scripts/build_objc3c_native.ps1",
    "scripts/objc3c_native_compile.ps1",
    "scripts/objc3c_shared/__init__.py",
    "scripts/objc3c_shared/json_io.py",
    "scripts/objc3c_shared/report_model.py",
    "scripts/objc3c_shared/schema_registry.py",
    "scripts/objc3c_native_compile_arguments.ps1",
    "scripts/objc3c_native_compile_arguments/usage.psm1",
    "scripts/objc3c_native_compile_arguments/boolean_values.psm1",
    "scripts/objc3c_native_compile_arguments/wrapper_flags.psm1",
    "scripts/objc3c_native_compile_arguments/parsing.psm1",
    "scripts/objc3c_native_compile_arguments/out_dir_filter.psm1",
    "scripts/objc3c_native_compile_io.psm1",
    "scripts/objc3c_native_compile_io/path_normalization.psm1",
    "scripts/objc3c_native_compile_io/command_context.psm1",
    "scripts/objc3c_native_compile_io/cache_io.psm1",
    "scripts/objc3c_native_compile_io/artifact_io.psm1",
    "scripts/objc3c_native_compile_io/result_parsing.psm1",
    "scripts/objc3c_native_compile_toolchain.psm1",
    "scripts/objc3c_native_compile_toolchain/artifacts.psm1",
    "scripts/objc3c_native_compile_toolchain/commands.psm1",
    "scripts/objc3c_native_compile_toolchain/results.psm1",
    "scripts/objc3c_native_compile_toolchain/processes.psm1",
    "scripts/objc3c_native_compile_toolchain/readiness.psm1",
    "scripts/objc3c_native_compile_toolchain/availability.psm1",
    "scripts/objc3c_native_compile_toolchain/artifact_resolution/build_results.psm1",
    "scripts/objc3c_native_compile_toolchain/artifact_resolution/definitions.psm1",
    "scripts/objc3c_native_compile_toolchain/artifact_resolution/native_executable.psm1",
    "scripts/objc3c_native_compile_toolchain/artifact_resolution/resolution.psm1",
    "scripts/objc3c_native_compile_toolchain/readiness/artifacts_ready.psm1",
    "scripts/objc3c_native_compile_toolchain/readiness/build_inputs.psm1",
    "scripts/objc3c_native_compile_toolchain/readiness/freshness.psm1",
    "scripts/objc3c_native_compile_toolchain/readiness/frontend_lock.psm1",
    "scripts/objc3c_native_compile_toolchain/results/artifact_prefixes.psm1",
    "scripts/objc3c_native_compile_toolchain/results/conversion.psm1",
    "scripts/objc3c_native_compile_frontend_guards.psm1",
    "scripts/objc3c_native_compile_frontend_guards/dependencies.psm1",
    "scripts/objc3c_native_compile_frontend_guards/orchestration.psm1",
    "scripts/objc3c_native_compile_frontend_artifact_guards.psm1",
    "scripts/objc3c_native_compile_frontend_feature_guards.psm1",
    "scripts/objc3c_native_compile_frontend_hardening_guards.psm1",
    "scripts/objc3c_native_compile_frontend_conformance_guards.psm1",
    "scripts/objc3c_native_compile_command.psm1",
    "scripts/objc3c_runtime_launch_contract.ps1",
    "scripts/objc3c_native_compile_provenance.ps1",
    "scripts/objc3c_native_compile_provenance/hash_io.psm1",
    "scripts/objc3c_native_compile_provenance/path_config.psm1",
    "scripts/objc3c_native_compile_provenance/text_analysis.psm1",
    "scripts/objc3c_native_compile_provenance/truthfulness.psm1",
    "scripts/objc3c_native_compile_provenance/artifact_inventory.psm1",
    "scripts/objc3c_native_compile_provenance/report_shaping.psm1",
    "scripts/objc3c_native_compile_provenance/provenance_capture.psm1",
    "scripts/objc3c_native_compile_wrapper.psm1",
    "scripts/objc3c_native_compile_wrapper/success_provenance.psm1",
    "scripts/objc3c_native_compile_wrapper/cache_flow.psm1",
    "scripts/objc3c_native_compile_wrapper/orchestration.psm1",
    "scripts/objc3c_workflow/__init__.py",
    "scripts/objc3c_workflow/__main__.py"
  )
}

Export-ModuleMember -Function @("Get-ManifestProvenanceCoreToolchainFiles")
