#!/usr/bin/env python3
from __future__ import annotations

from scripts.validation_surface_inventory import (
    ACCEPTANCE_HARNESS,
    CHECK_ROOTS,
    JSON_OUT,
    MD_OUT,
    PACKAGE_JSON,
    REPORT_DIR,
    ROOT,
    STATIC_GUARD_OVERRIDES,
    TASK_HYGIENE_GATE,
    acceptance_harness_catalog,
    all_check_py_files,
    all_test_check_py_files,
    all_validation_ps1_files,
    build_inventory_entries,
    build_parser,
    build_report,
    classify_check_py,
    main,
    migration_map,
    non_goals,
    package_scripts,
    parse_args,
    referenced_by,
    render_markdown,
    retained_static_guards,
    run,
    run_json,
    unreferenced_check_surfaces,
    workflow_backend_text,
    write_report,
)

__all__ = [
    "ACCEPTANCE_HARNESS",
    "CHECK_ROOTS",
    "JSON_OUT",
    "MD_OUT",
    "PACKAGE_JSON",
    "REPORT_DIR",
    "ROOT",
    "STATIC_GUARD_OVERRIDES",
    "TASK_HYGIENE_GATE",
    "acceptance_harness_catalog",
    "all_check_py_files",
    "all_test_check_py_files",
    "all_validation_ps1_files",
    "build_inventory_entries",
    "build_parser",
    "build_report",
    "classify_check_py",
    "main",
    "migration_map",
    "non_goals",
    "package_scripts",
    "parse_args",
    "referenced_by",
    "render_markdown",
    "retained_static_guards",
    "run",
    "run_json",
    "unreferenced_check_surfaces",
    "workflow_backend_text",
    "write_report",
]


if __name__ == "__main__":
    raise SystemExit(main())
