#!/usr/bin/env python3
"""Run mixed-module and import/export differential stress validation."""

from __future__ import annotations

try:
    from run_objc3c_mixed_module_differential import (
        CASE_RUNNERS,
        MANIFEST_PATH,
        ROOT,
        SUMMARY_CONTRACT_ID,
        SUMMARY_PATH,
        SURFACE_BUILDERS,
        CaseCommand,
        CaseRunner,
        CaseSummary,
        ClangCase,
        FixtureGroup,
        NativeToolResolver,
        NoClangCase,
        RunnerConfig,
        SurfaceBuilder,
        build_arg_parser,
        build_summary_payload,
        build_surfaces,
        emit_result,
        load_manifest,
        main,
        parse_args,
        prepare_run_root,
        render_console_summary,
        run_cases,
        run_mixed_module_differential,
        run_no_clang,
        run_with_clang,
        write_json,
    )
except ModuleNotFoundError:
    from scripts.run_objc3c_mixed_module_differential import (
        CASE_RUNNERS,
        MANIFEST_PATH,
        ROOT,
        SUMMARY_CONTRACT_ID,
        SUMMARY_PATH,
        SURFACE_BUILDERS,
        CaseCommand,
        CaseRunner,
        CaseSummary,
        ClangCase,
        FixtureGroup,
        NativeToolResolver,
        NoClangCase,
        RunnerConfig,
        SurfaceBuilder,
        build_arg_parser,
        build_summary_payload,
        build_surfaces,
        emit_result,
        load_manifest,
        main,
        parse_args,
        prepare_run_root,
        render_console_summary,
        run_cases,
        run_mixed_module_differential,
        run_no_clang,
        run_with_clang,
        write_json,
    )

__all__ = [
    "CASE_RUNNERS",
    "MANIFEST_PATH",
    "ROOT",
    "SUMMARY_CONTRACT_ID",
    "SUMMARY_PATH",
    "SURFACE_BUILDERS",
    "CaseCommand",
    "CaseRunner",
    "CaseSummary",
    "ClangCase",
    "FixtureGroup",
    "NativeToolResolver",
    "NoClangCase",
    "RunnerConfig",
    "SurfaceBuilder",
    "build_arg_parser",
    "build_summary_payload",
    "build_surfaces",
    "emit_result",
    "load_manifest",
    "main",
    "parse_args",
    "prepare_run_root",
    "render_console_summary",
    "run_cases",
    "run_mixed_module_differential",
    "run_no_clang",
    "run_with_clang",
    "write_json",
]


if __name__ == "__main__":
    raise SystemExit(main())
