#!/usr/bin/env python3
"""Reduce failing checked-in stress seeds into machine-owned replay capsules."""

from __future__ import annotations

try:
    from objc3c_stress_minimization import (
        ARTIFACT_SURFACE_PATH,
        COMPILER,
        MANIFEST_PATH,
        ROOT,
        SUMMARY_CONTRACT_ID,
        SUMMARY_PATH,
        MinCase,
        build_arg_parser,
        build_failure_summary,
        build_invocation_payload,
        build_reduced_summary,
        build_reducer_plan,
        build_summary_payload,
        count_subsystems,
        compile_source,
        emit_result,
        json_text,
        load_manifest,
        main,
        materialize_case,
        parse_args,
        reduce_source,
        render_console_summary,
        run_stress_minimization,
        run_runtime_or_execution_source,
        validate_artifact_surface,
        write_json,
    )
except ModuleNotFoundError:
    from scripts.objc3c_stress_minimization import (
        ARTIFACT_SURFACE_PATH,
        COMPILER,
        MANIFEST_PATH,
        ROOT,
        SUMMARY_CONTRACT_ID,
        SUMMARY_PATH,
        MinCase,
        build_arg_parser,
        build_failure_summary,
        build_invocation_payload,
        build_reduced_summary,
        build_reducer_plan,
        build_summary_payload,
        count_subsystems,
        compile_source,
        emit_result,
        json_text,
        load_manifest,
        main,
        materialize_case,
        parse_args,
        reduce_source,
        render_console_summary,
        run_stress_minimization,
        run_runtime_or_execution_source,
        validate_artifact_surface,
        write_json,
    )

__all__ = [
    "ARTIFACT_SURFACE_PATH",
    "COMPILER",
    "MANIFEST_PATH",
    "ROOT",
    "SUMMARY_CONTRACT_ID",
    "SUMMARY_PATH",
    "MinCase",
    "build_arg_parser",
    "build_failure_summary",
    "build_invocation_payload",
    "build_reduced_summary",
    "build_reducer_plan",
    "build_summary_payload",
    "count_subsystems",
    "compile_source",
    "emit_result",
    "json_text",
    "load_manifest",
    "main",
    "materialize_case",
    "parse_args",
    "reduce_source",
    "render_console_summary",
    "run_stress_minimization",
    "run_runtime_or_execution_source",
    "validate_artifact_surface",
    "write_json",
]


if __name__ == "__main__":
    raise SystemExit(main())
