#pragma once

#ifndef OBJC3_AST_EXPR_NODE_MEMBERS_IN_EXPR
#error "objc3_ast_expr_block_members.h must be included inside struct Expr"
#endif

  std::vector<std::string> block_parameter_names_lexicographic;
  std::size_t block_parameter_count = 0;
  std::vector<std::string> block_parameter_signature_entries_lexicographic;
  std::vector<ValueType> block_parameter_types_source_order;
  std::vector<BlockParameter> block_parameters_source_order;
  std::size_t block_explicit_typed_parameter_count = 0;
  std::size_t block_implicit_parameter_count = 0;
  std::string block_signature_profile;
  std::vector<std::string> block_capture_names_lexicographic;
  std::size_t block_capture_count = 0;
  std::vector<std::string> block_capture_inventory_entries_lexicographic;
  std::size_t block_byvalue_readonly_capture_count = 0;
  std::string block_capture_inventory_profile;
  bool block_has_explicit_capture_list = false;
  std::vector<ExplicitBlockCaptureItem> block_explicit_capture_items_source_order;
  std::vector<std::string> block_explicit_capture_names_lexicographic;
  std::size_t block_explicit_capture_count = 0;
  std::size_t block_explicit_capture_move_count = 0;
  std::size_t block_explicit_capture_weak_count = 0;
  std::size_t block_explicit_capture_unowned_count = 0;
  std::size_t block_explicit_capture_byref_count = 0;
  std::size_t block_explicit_capture_plain_count = 0;
  std::string block_explicit_capture_profile;
  std::vector<std::string> block_mutated_capture_names_lexicographic;
  std::size_t block_mutated_capture_count = 0;
  std::vector<std::string> block_byref_capture_names_lexicographic;
  std::size_t block_byref_capture_count = 0;
  std::size_t block_body_statement_count = 0;
  std::string block_capture_profile;
  bool block_capture_set_deterministic = false;
  bool block_literal_is_normalized = false;
  std::size_t block_abi_invoke_argument_slots = 0;
  std::size_t block_abi_capture_word_count = 0;
  std::vector<std::string> block_invoke_surface_entries_lexicographic;
  std::string block_invoke_surface_profile;
  std::string block_source_model_replay_key;
  bool block_source_model_is_normalized = false;
  std::string block_abi_layout_profile;
  std::string block_abi_descriptor_symbol;
  std::string block_invoke_trampoline_symbol;
  bool block_abi_has_invoke_trampoline = false;
  bool block_abi_layout_is_normalized = false;
  std::size_t block_storage_mutable_capture_count = 0;
  std::size_t block_storage_byref_slot_count = 0;
  bool block_storage_requires_byref_cells = false;
  bool block_storage_escape_analysis_enabled = false;
  bool block_storage_escape_to_heap = false;
  bool block_storage_escape_profile_is_normalized = false;
  std::string block_storage_escape_profile;
  std::string block_storage_byref_layout_symbol;
  bool block_copy_helper_required = false;
  bool block_dispose_helper_required = false;
  bool block_copy_dispose_profile_is_normalized = false;
  std::string block_copy_dispose_profile;
  std::string block_copy_helper_symbol;
  std::string block_dispose_helper_symbol;
  bool block_copy_helper_intent_required = false;
  bool block_dispose_helper_intent_required = false;
  bool block_escape_shape_promotes_to_heap_candidate = false;
  bool block_source_storage_annotations_are_normalized = false;
  std::string block_helper_intent_profile;
  std::string block_escape_shape_symbol;
  std::string block_escape_shape_profile;
  std::size_t block_runtime_owned_object_capture_count = 0;
  std::size_t block_runtime_weak_object_capture_count = 0;
  std::size_t block_runtime_unowned_object_capture_count = 0;
  std::vector<std::string> block_runtime_owned_object_capture_names_lexicographic;
  std::vector<std::string> block_runtime_weak_object_capture_names_lexicographic;
  std::vector<std::string> block_runtime_unowned_object_capture_names_lexicographic;
  bool block_runtime_copy_helper_required = false;
  bool block_runtime_dispose_helper_required = false;
  bool block_runtime_capture_ownership_is_normalized = false;
  std::string block_runtime_capture_ownership_profile;
  std::size_t block_determinism_perf_baseline_weight = 0;
  bool block_determinism_perf_baseline_profile_is_normalized = false;
  std::string block_determinism_perf_baseline_profile;
