#pragma once

#include <cstddef>
#include <memory>
#include <string>
#include <vector>

#include "ast/objc3_ast_core.h"
#include "ast/objc3_ast_generic_param_decl_nodes.h"
#include "token/objc3_token_contract.h"

struct FunctionDecl {
  std::string name;
  std::string scope_owner_symbol;
  std::vector<std::string> scope_path_lexicographic;
  std::vector<Objc3GenericParamDecl> generic_params;
  bool generic_callable_reification_marker_declared = false;
  unsigned generic_callable_reification_marker_line = 1;
  unsigned generic_callable_reification_marker_column = 1;
  std::vector<FuncParam> params;
  ValueType return_type = ValueType::I32;
  bool return_vector_spelling = false;
  std::string return_vector_base_spelling;
  unsigned return_vector_lane_count = 1;
  bool return_id_spelling = false;
  bool return_class_spelling = false;
  bool return_sel_spelling = false;
  bool return_instancetype_spelling = false;
  bool return_object_pointer_type_spelling = false;
  std::string return_object_pointer_type_name;
  std::string return_typecheck_family_symbol;
  bool has_return_generic_suffix = false;
  bool return_generic_suffix_terminated = true;
  std::string return_generic_suffix_text;
  unsigned return_generic_line = 1;
  unsigned return_generic_column = 1;
  bool return_lightweight_generic_constraint_profile_is_normalized = false;
  std::string return_lightweight_generic_constraint_profile;
  bool return_nullability_flow_profile_is_normalized = false;
  std::string return_nullability_flow_profile;
  bool return_protocol_qualified_object_type_profile_is_normalized = false;
  std::string return_protocol_qualified_object_type_profile;
  bool return_variance_bridge_cast_profile_is_normalized = false;
  std::string return_variance_bridge_cast_profile;
  bool return_generic_metadata_abi_profile_is_normalized = false;
  std::string return_generic_metadata_abi_profile;
  bool return_module_import_graph_profile_is_normalized = false;
  std::string return_module_import_graph_profile;
  bool return_namespace_collision_shadowing_profile_is_normalized = false;
  std::string return_namespace_collision_shadowing_profile;
  bool return_public_private_api_partition_profile_is_normalized = false;
  std::string return_public_private_api_partition_profile;
  bool return_incremental_module_cache_invalidation_profile_is_normalized = false;
  std::string return_incremental_module_cache_invalidation_profile;
  bool return_cross_module_conformance_profile_is_normalized = false;
  std::string return_cross_module_conformance_profile;
  bool has_return_pointer_declarator = false;
  unsigned return_pointer_declarator_depth = 0;
  std::vector<Objc3SemaTokenMetadata> return_pointer_declarator_tokens;
  std::vector<Objc3SemaTokenMetadata> return_nullability_suffix_tokens;
  bool has_return_ownership_qualifier = false;
  std::string return_ownership_qualifier_spelling;
  std::string return_ownership_qualifier_symbol;
  std::vector<Objc3SemaTokenMetadata> return_ownership_qualifier_tokens;
  bool return_ownership_insert_retain = false;
  bool return_ownership_insert_release = false;
  bool return_ownership_insert_autorelease = false;
  std::string return_ownership_operation_profile;
  bool return_ownership_is_weak_reference = false;
  bool return_ownership_is_unowned_reference = false;
  bool return_ownership_is_unowned_safe_reference = false;
  std::string return_ownership_lifetime_profile;
  std::string return_ownership_runtime_hook_profile;
  bool return_ownership_arc_diagnostic_candidate = false;
  bool return_ownership_arc_fixit_available = false;
  std::string return_ownership_arc_diagnostic_profile;
  std::string return_ownership_arc_fixit_hint;
  bool async_declared = false;
  bool objc_nonisolated_declared = false;
  bool executor_affinity_declared = false;
  bool executor_affinity_named = false;
  std::string executor_affinity_kind;
  std::string executor_affinity_name;
  bool objc_macro_declared = false;
  std::string objc_macro_name;
  bool objc_macro_package_declared = false;
  std::string objc_macro_package_name;
  bool objc_macro_provenance_declared = false;
  std::string objc_macro_provenance_name;
  bool objc_macro_cache_key_declared = false;
  std::string objc_macro_cache_key_name;
  bool objc_macro_sandbox_declared = false;
  std::string objc_macro_sandbox_name;
  bool objc_foreign_declared = false;
  bool objc_import_module_declared = false;
  std::string objc_import_module_name;
  bool objc_swift_name_declared = false;
  std::string objc_swift_name;
  bool objc_swift_private_declared = false;
  bool objc_cxx_name_declared = false;
  std::string objc_cxx_name;
  bool objc_header_name_declared = false;
  std::string objc_header_name;
  bool objc_export_header_declared = false;
  std::string objc_export_header_name;
  bool objc_abi_align_declared = false;
  std::size_t objc_abi_alignment_bytes = 0;
  bool objc_foreign_type_declared = false;
  std::string objc_foreign_type_name;
  bool objc_mixed_image_declared = false;
  std::string objc_mixed_image_name;
  bool objc_package_entry_declared = false;
  std::string objc_package_entry_name;
  bool objc_direct_declared = false;
  bool objc_final_declared = false;
  bool objc_dynamic_declared = false;
  bool objc_returns_borrowed_declared = false;
  std::size_t objc_returns_borrowed_owner_index = 0;
  bool return_borrowed_pointer_qualified = false;
  std::string returns_borrowed_profile;
  std::vector<std::string> retainable_c_family_callable_attributes;
  std::vector<std::string> retainable_c_family_names;
  bool retainable_c_family_profile_is_normalized = false;
  std::string retainable_c_family_profile;
  bool throws_declared = false;
  bool throws_declaration_profile_is_normalized = false;
  std::string throws_declaration_profile;
  bool result_like_profile_is_normalized = false;
  bool deterministic_result_like_lowering_handoff = false;
  std::size_t result_like_sites = 0;
  std::size_t result_success_sites = 0;
  std::size_t result_failure_sites = 0;
  std::size_t result_branch_sites = 0;
  std::size_t result_payload_sites = 0;
  std::size_t result_normalized_sites = 0;
  std::size_t result_branch_merge_sites = 0;
  std::size_t result_contract_violation_sites = 0;
  std::string result_like_profile;
  bool ns_error_bridging_profile_is_normalized = false;
  bool deterministic_ns_error_bridging_lowering_handoff = false;
  std::size_t ns_error_bridging_sites = 0;
  std::size_t ns_error_parameter_sites = 0;
  std::size_t ns_error_out_parameter_sites = 0;
  std::size_t ns_error_bridge_path_sites = 0;
  std::size_t failable_call_sites = 0;
  std::size_t ns_error_bridging_normalized_sites = 0;
  std::size_t ns_error_bridge_boundary_sites = 0;
  std::size_t ns_error_bridging_contract_violation_sites = 0;
  std::string ns_error_bridging_profile;
  bool objc_nserror_declared = false;
  bool objc_status_code_declared = false;
  bool error_bridge_marker_profile_is_normalized = false;
  std::size_t objc_nserror_attribute_sites = 0;
  std::size_t objc_status_code_attribute_sites = 0;
  std::size_t status_code_success_clause_sites = 0;
  std::size_t status_code_error_type_clause_sites = 0;
  std::size_t status_code_mapping_clause_sites = 0;
  std::size_t error_bridge_marker_contract_violation_sites = 0;
  std::string objc_status_code_success_literal;
  std::string objc_status_code_error_type_spelling;
  std::string objc_status_code_mapping_symbol;
  std::string error_bridge_marker_profile;
  bool unwind_cleanup_profile_is_normalized = false;
  bool deterministic_unwind_cleanup_handoff = false;
  std::size_t unwind_cleanup_sites = 0;
  std::size_t exceptional_exit_sites = 0;
  std::size_t cleanup_action_sites = 0;
  std::size_t cleanup_scope_sites = 0;
  std::size_t cleanup_resume_sites = 0;
  std::size_t unwind_cleanup_normalized_sites = 0;
  std::size_t unwind_cleanup_fail_closed_sites = 0;
  std::size_t unwind_cleanup_contract_violation_sites = 0;
  std::string unwind_cleanup_profile;
  bool error_diagnostics_recovery_profile_is_normalized = false;
  bool deterministic_error_diagnostics_recovery_handoff = false;
  std::size_t error_diagnostics_recovery_sites = 0;
  std::size_t diagnostic_emit_sites = 0;
  std::size_t recovery_anchor_sites = 0;
  std::size_t recovery_boundary_sites = 0;
  std::size_t fail_closed_diagnostic_sites = 0;
  std::size_t error_diagnostics_recovery_normalized_sites = 0;
  std::size_t error_diagnostics_recovery_gate_blocked_sites = 0;
  std::size_t error_diagnostics_recovery_contract_violation_sites = 0;
  std::string error_diagnostics_recovery_profile;
  bool async_continuation_profile_is_normalized = false;
  bool deterministic_async_continuation_handoff = false;
  std::size_t async_continuation_sites = 0;
  std::size_t async_keyword_sites = 0;
  std::size_t async_function_sites = 0;
  std::size_t continuation_allocation_sites = 0;
  std::size_t continuation_resume_sites = 0;
  std::size_t continuation_suspend_sites = 0;
  std::size_t async_state_machine_sites = 0;
  std::size_t async_continuation_normalized_sites = 0;
  std::size_t async_continuation_gate_blocked_sites = 0;
  std::size_t async_continuation_contract_violation_sites = 0;
  std::string async_continuation_profile;
  bool await_suspension_profile_is_normalized = false;
  bool deterministic_await_suspension_handoff = false;
  std::size_t await_suspension_sites = 0;
  std::size_t await_keyword_sites = 0;
  std::size_t await_suspension_point_sites = 0;
  std::size_t await_resume_sites = 0;
  std::size_t await_state_machine_sites = 0;
  std::size_t await_continuation_sites = 0;
  std::size_t await_suspension_normalized_sites = 0;
  std::size_t await_suspension_gate_blocked_sites = 0;
  std::size_t await_suspension_contract_violation_sites = 0;
  std::string await_suspension_profile;
  bool actor_isolation_sendability_profile_is_normalized = false;
  bool deterministic_actor_isolation_sendability_handoff = false;
  std::size_t actor_isolation_sendability_sites = 0;
  std::size_t actor_isolation_decl_sites = 0;
  std::size_t actor_hop_sites = 0;
  std::size_t sendable_annotation_sites = 0;
  std::size_t non_sendable_crossing_sites = 0;
  std::size_t isolation_boundary_sites = 0;
  std::size_t actor_isolation_sendability_normalized_sites = 0;
  std::size_t actor_isolation_sendability_gate_blocked_sites = 0;
  std::size_t actor_isolation_sendability_contract_violation_sites = 0;
  std::string actor_isolation_sendability_profile;
  bool task_runtime_cancellation_profile_is_normalized = false;
  bool deterministic_task_runtime_cancellation_handoff = false;
  std::size_t task_runtime_interop_sites = 0;
  std::size_t runtime_hook_sites = 0;
  std::size_t cancellation_check_sites = 0;
  std::size_t cancellation_handler_sites = 0;
  std::size_t suspension_point_sites = 0;
  std::size_t cancellation_propagation_sites = 0;
  std::size_t task_runtime_normalized_sites = 0;
  std::size_t task_runtime_gate_blocked_sites = 0;
  std::size_t task_runtime_contract_violation_sites = 0;
  std::size_t task_runtime_cancellation_normalized_sites = 0;
  std::size_t task_runtime_cancellation_gate_blocked_sites = 0;
  std::size_t task_runtime_cancellation_contract_violation_sites = 0;
  std::string task_runtime_cancellation_profile;
  bool concurrency_replay_race_guard_profile_is_normalized = false;
  bool deterministic_concurrency_replay_race_guard_handoff = false;
  std::size_t concurrency_replay_race_guard_sites = 0;
  std::size_t concurrency_replay_sites = 0;
  std::size_t replay_proof_sites = 0;
  std::size_t race_guard_sites = 0;
  std::size_t task_handoff_sites = 0;
  std::size_t actor_isolation_sites = 0;
  std::size_t deterministic_schedule_sites = 0;
  std::size_t concurrency_replay_guard_blocked_sites = 0;
  std::size_t concurrency_replay_contract_violation_sites = 0;
  std::string concurrency_replay_race_guard_profile;
  bool unsafe_pointer_extension_profile_is_normalized = false;
  bool deterministic_unsafe_pointer_extension_handoff = false;
  std::size_t unsafe_pointer_extension_sites = 0;
  std::size_t unsafe_keyword_sites = 0;
  std::size_t pointer_arithmetic_sites = 0;
  std::size_t raw_pointer_type_sites = 0;
  std::size_t unsafe_operation_sites = 0;
  std::size_t unsafe_pointer_extension_normalized_sites = 0;
  std::size_t unsafe_pointer_extension_gate_blocked_sites = 0;
  std::size_t unsafe_pointer_extension_contract_violation_sites = 0;
  std::string unsafe_pointer_extension_profile;
  bool inline_asm_intrinsic_governance_profile_is_normalized = false;
  bool deterministic_inline_asm_intrinsic_governance_handoff = false;
  std::size_t inline_asm_intrinsic_sites = 0;
  std::size_t inline_asm_sites = 0;
  std::size_t intrinsic_sites = 0;
  std::size_t governed_intrinsic_sites = 0;
  std::size_t privileged_intrinsic_sites = 0;
  std::size_t inline_asm_intrinsic_normalized_sites = 0;
  std::size_t inline_asm_intrinsic_gate_blocked_sites = 0;
  std::size_t inline_asm_intrinsic_contract_violation_sites = 0;
  std::string inline_asm_intrinsic_governance_profile;
  bool is_prototype = false;
  bool is_pure = false;
  std::vector<std::unique_ptr<Stmt>> body;
  unsigned line = 1;
  unsigned column = 1;
};
