#pragma once

#include <memory>
#include <string>
#include <vector>

#include "token/objc3_token_contract.h"

struct SymbolRow {
  std::string kind;
  std::string name;
  unsigned line;
  unsigned column;
};

struct SymbolContext {
  std::vector<SymbolRow> rows;
};

enum class ValueType { Unknown, I32, Bool, Void, Function };

struct Expr {
  enum class Kind {
    Number,
    BoolLiteral,
    NilLiteral,
    Identifier,
    Binary,
    Conditional,
    Call,
    MessageSend,
    BlockLiteral
  };
  enum class MessageSendForm { None, Unary, Keyword };
  struct MessageSendSelectorPiece {
    std::string keyword;
    bool has_argument = false;
    unsigned line = 1;
    unsigned column = 1;
  };
  Kind kind = Kind::Number;
  int number = 0;
  bool bool_value = false;
  std::string ident;
  std::string selector;
  MessageSendForm message_send_form = MessageSendForm::None;
  std::string message_send_form_symbol;
  std::vector<MessageSendSelectorPiece> selector_lowering_pieces;
  std::string selector_lowering_symbol;
  bool selector_lowering_is_normalized = false;
  unsigned dispatch_abi_receiver_slots_marshaled = 0;
  unsigned dispatch_abi_selector_slots_marshaled = 0;
  unsigned dispatch_abi_argument_value_slots_marshaled = 0;
  unsigned dispatch_abi_argument_padding_slots_marshaled = 0;
  unsigned dispatch_abi_argument_total_slots_marshaled = 0;
  unsigned dispatch_abi_total_slots_marshaled = 0;
  unsigned dispatch_abi_runtime_arg_slots = 0;
  std::string dispatch_abi_marshalling_symbol;
  bool dispatch_abi_marshalling_is_normalized = false;
  bool nil_receiver_semantics_enabled = false;
  bool nil_receiver_foldable = false;
  bool nil_receiver_requires_runtime_dispatch = true;
  std::string nil_receiver_folding_symbol;
  bool nil_receiver_semantics_is_normalized = false;
  bool super_dispatch_enabled = false;
  bool super_dispatch_requires_class_context = false;
  std::string super_dispatch_symbol;
  bool super_dispatch_semantics_is_normalized = false;
  std::string method_family_name;
  bool method_family_returns_retained_result = false;
  bool method_family_returns_related_result = false;
  std::string method_family_semantics_symbol;
  bool method_family_semantics_is_normalized = false;
  bool runtime_shim_host_link_required = true;
  bool runtime_shim_host_link_elided = false;
  unsigned runtime_shim_host_link_declaration_parameter_count = 0;
  std::string runtime_dispatch_bridge_symbol;
  std::string runtime_shim_host_link_symbol;
  bool runtime_shim_host_link_is_normalized = false;
  std::vector<std::string> block_parameter_names_lexicographic;
  std::size_t block_parameter_count = 0;
  std::vector<std::string> block_capture_names_lexicographic;
  std::size_t block_capture_count = 0;
  std::size_t block_body_statement_count = 0;
  std::string block_capture_profile;
  bool block_capture_set_deterministic = false;
  bool block_literal_is_normalized = false;
  std::size_t block_abi_invoke_argument_slots = 0;
  std::size_t block_abi_capture_word_count = 0;
  std::string block_abi_layout_profile;
  std::string block_abi_descriptor_symbol;
  std::string block_invoke_trampoline_symbol;
  bool block_abi_has_invoke_trampoline = false;
  bool block_abi_layout_is_normalized = false;
  std::size_t block_storage_mutable_capture_count = 0;
  std::size_t block_storage_byref_slot_count = 0;
  bool block_storage_requires_byref_cells = false;
  bool block_storage_escape_analysis_enabled = false;
  bool block_storage_escape_to_heap = false;
  bool block_storage_escape_profile_is_normalized = false;
  std::string block_storage_escape_profile;
  std::string block_storage_byref_layout_symbol;
  bool block_copy_helper_required = false;
  bool block_dispose_helper_required = false;
  bool block_copy_dispose_profile_is_normalized = false;
  std::string block_copy_dispose_profile;
  std::string block_copy_helper_symbol;
  std::string block_dispose_helper_symbol;
  std::size_t block_determinism_perf_baseline_weight = 0;
  bool block_determinism_perf_baseline_profile_is_normalized = false;
  std::string block_determinism_perf_baseline_profile;
  std::string op = "+";
  std::unique_ptr<Expr> receiver;
  std::unique_ptr<Expr> left;
  std::unique_ptr<Expr> right;
  std::unique_ptr<Expr> third;
  std::vector<std::unique_ptr<Expr>> args;
  unsigned line = 1;
  unsigned column = 1;
};

struct LetStmt;
struct AssignStmt;
struct ReturnStmt;
struct IfStmt;
struct DoWhileStmt;
struct ForStmt;
struct SwitchStmt;
struct WhileStmt;
struct BlockStmt;
struct ExprStmt;

struct Stmt {
  enum class Kind { Let, Assign, Return, If, DoWhile, For, Switch, While, Break, Continue, Empty, Block, Expr };
  Kind kind = Kind::Expr;
  std::unique_ptr<LetStmt> let_stmt;
  std::unique_ptr<AssignStmt> assign_stmt;
  std::unique_ptr<ReturnStmt> return_stmt;
  std::unique_ptr<IfStmt> if_stmt;
  std::unique_ptr<DoWhileStmt> do_while_stmt;
  std::unique_ptr<ForStmt> for_stmt;
  std::unique_ptr<SwitchStmt> switch_stmt;
  std::unique_ptr<WhileStmt> while_stmt;
  std::unique_ptr<BlockStmt> block_stmt;
  std::unique_ptr<ExprStmt> expr_stmt;
  unsigned line = 1;
  unsigned column = 1;
};

struct LetStmt {
  std::string name;
  std::unique_ptr<Expr> value;
  unsigned line = 1;
  unsigned column = 1;
};

struct AssignStmt {
  std::string name;
  std::string op = "=";
  std::unique_ptr<Expr> value;
  unsigned line = 1;
  unsigned column = 1;
};

struct ReturnStmt {
  std::unique_ptr<Expr> value;
  unsigned line = 1;
  unsigned column = 1;
};

struct IfStmt {
  std::unique_ptr<Expr> condition;
  std::vector<std::unique_ptr<Stmt>> then_body;
  std::vector<std::unique_ptr<Stmt>> else_body;
  unsigned line = 1;
  unsigned column = 1;
};

struct DoWhileStmt {
  std::vector<std::unique_ptr<Stmt>> body;
  std::unique_ptr<Expr> condition;
  unsigned line = 1;
  unsigned column = 1;
};

struct ForClause {
  enum class Kind { None, Let, Assign, Expr };
  Kind kind = Kind::None;
  std::string name;
  std::string op = "=";
  std::unique_ptr<Expr> value;
  unsigned line = 1;
  unsigned column = 1;
};

struct ForStmt {
  ForClause init;
  std::unique_ptr<Expr> condition;
  ForClause step;
  std::vector<std::unique_ptr<Stmt>> body;
  unsigned line = 1;
  unsigned column = 1;
};

struct SwitchCase {
  bool is_default = false;
  int value = 0;
  unsigned value_line = 1;
  unsigned value_column = 1;
  std::vector<std::unique_ptr<Stmt>> body;
  unsigned line = 1;
  unsigned column = 1;
};

struct SwitchStmt {
  std::unique_ptr<Expr> condition;
  std::vector<SwitchCase> cases;
  unsigned line = 1;
  unsigned column = 1;
};

struct WhileStmt {
  std::unique_ptr<Expr> condition;
  std::vector<std::unique_ptr<Stmt>> body;
  unsigned line = 1;
  unsigned column = 1;
};

struct BlockStmt {
  std::vector<std::unique_ptr<Stmt>> body;
  bool is_autoreleasepool_scope = false;
  std::string autoreleasepool_scope_symbol;
  unsigned autoreleasepool_scope_depth = 0;
  unsigned line = 1;
  unsigned column = 1;
};

struct ExprStmt {
  std::unique_ptr<Expr> value;
  unsigned line = 1;
  unsigned column = 1;
};

struct FuncParam {
  std::string name;
  ValueType type = ValueType::I32;
  bool vector_spelling = false;
  std::string vector_base_spelling;
  unsigned vector_lane_count = 1;
  bool id_spelling = false;
  bool class_spelling = false;
  bool sel_spelling = false;
  bool instancetype_spelling = false;
  bool object_pointer_type_spelling = false;
  std::string object_pointer_type_name;
  std::string typecheck_family_symbol;
  bool has_generic_suffix = false;
  bool generic_suffix_terminated = true;
  std::string generic_suffix_text;
  unsigned generic_line = 1;
  unsigned generic_column = 1;
  bool lightweight_generic_constraint_profile_is_normalized = false;
  std::string lightweight_generic_constraint_profile;
  bool nullability_flow_profile_is_normalized = false;
  std::string nullability_flow_profile;
  bool protocol_qualified_object_type_profile_is_normalized = false;
  std::string protocol_qualified_object_type_profile;
  bool variance_bridge_cast_profile_is_normalized = false;
  std::string variance_bridge_cast_profile;
  bool generic_metadata_abi_profile_is_normalized = false;
  std::string generic_metadata_abi_profile;
  bool module_import_graph_profile_is_normalized = false;
  std::string module_import_graph_profile;
  bool namespace_collision_shadowing_profile_is_normalized = false;
  std::string namespace_collision_shadowing_profile;
  bool public_private_api_partition_profile_is_normalized = false;
  std::string public_private_api_partition_profile;
  bool incremental_module_cache_invalidation_profile_is_normalized = false;
  std::string incremental_module_cache_invalidation_profile;
  bool cross_module_conformance_profile_is_normalized = false;
  std::string cross_module_conformance_profile;
  bool has_pointer_declarator = false;
  unsigned pointer_declarator_depth = 0;
  std::vector<Objc3SemaTokenMetadata> pointer_declarator_tokens;
  std::vector<Objc3SemaTokenMetadata> nullability_suffix_tokens;
  bool has_ownership_qualifier = false;
  std::string ownership_qualifier_spelling;
  std::string ownership_qualifier_symbol;
  std::vector<Objc3SemaTokenMetadata> ownership_qualifier_tokens;
  bool ownership_insert_retain = false;
  bool ownership_insert_release = false;
  bool ownership_insert_autorelease = false;
  std::string ownership_operation_profile;
  bool ownership_is_weak_reference = false;
  bool ownership_is_unowned_reference = false;
  bool ownership_is_unowned_safe_reference = false;
  std::string ownership_lifetime_profile;
  std::string ownership_runtime_hook_profile;
  bool ownership_arc_diagnostic_candidate = false;
  bool ownership_arc_fixit_available = false;
  std::string ownership_arc_diagnostic_profile;
  std::string ownership_arc_fixit_hint;
  unsigned line = 1;
  unsigned column = 1;
};

struct Objc3MethodDecl {
  struct SelectorPiece {
    std::string keyword;
    std::string parameter_name;
    bool has_parameter = false;
    unsigned line = 1;
    unsigned column = 1;
  };

  std::string selector;
  std::vector<SelectorPiece> selector_pieces;
  bool selector_is_normalized = false;
  std::vector<FuncParam> params;
  ValueType return_type = ValueType::I32;
  bool return_vector_spelling = false;
  std::string return_vector_base_spelling;
  unsigned return_vector_lane_count = 1;
  bool return_id_spelling = false;
  bool return_class_spelling = false;
  bool return_sel_spelling = false;
  bool return_instancetype_spelling = false;
  bool return_object_pointer_type_spelling = false;
  std::string return_object_pointer_type_name;
  std::string return_typecheck_family_symbol;
  bool has_return_generic_suffix = false;
  bool return_generic_suffix_terminated = true;
  std::string return_generic_suffix_text;
  unsigned return_generic_line = 1;
  unsigned return_generic_column = 1;
  bool return_lightweight_generic_constraint_profile_is_normalized = false;
  std::string return_lightweight_generic_constraint_profile;
  bool return_nullability_flow_profile_is_normalized = false;
  std::string return_nullability_flow_profile;
  bool return_protocol_qualified_object_type_profile_is_normalized = false;
  std::string return_protocol_qualified_object_type_profile;
  bool return_variance_bridge_cast_profile_is_normalized = false;
  std::string return_variance_bridge_cast_profile;
  bool return_generic_metadata_abi_profile_is_normalized = false;
  std::string return_generic_metadata_abi_profile;
  bool return_module_import_graph_profile_is_normalized = false;
  std::string return_module_import_graph_profile;
  bool return_namespace_collision_shadowing_profile_is_normalized = false;
  std::string return_namespace_collision_shadowing_profile;
  bool return_public_private_api_partition_profile_is_normalized = false;
  std::string return_public_private_api_partition_profile;
  bool return_incremental_module_cache_invalidation_profile_is_normalized = false;
  std::string return_incremental_module_cache_invalidation_profile;
  bool return_cross_module_conformance_profile_is_normalized = false;
  std::string return_cross_module_conformance_profile;
  bool has_return_pointer_declarator = false;
  unsigned return_pointer_declarator_depth = 0;
  std::vector<Objc3SemaTokenMetadata> return_pointer_declarator_tokens;
  std::vector<Objc3SemaTokenMetadata> return_nullability_suffix_tokens;
  bool has_return_ownership_qualifier = false;
  std::string return_ownership_qualifier_spelling;
  std::string return_ownership_qualifier_symbol;
  std::vector<Objc3SemaTokenMetadata> return_ownership_qualifier_tokens;
  bool return_ownership_insert_retain = false;
  bool return_ownership_insert_release = false;
  bool return_ownership_insert_autorelease = false;
  std::string return_ownership_operation_profile;
  bool return_ownership_is_weak_reference = false;
  bool return_ownership_is_unowned_reference = false;
  bool return_ownership_is_unowned_safe_reference = false;
  std::string return_ownership_lifetime_profile;
  std::string return_ownership_runtime_hook_profile;
  bool return_ownership_arc_diagnostic_candidate = false;
  bool return_ownership_arc_fixit_available = false;
  std::string return_ownership_arc_diagnostic_profile;
  std::string return_ownership_arc_fixit_hint;
  std::string scope_owner_symbol;
  std::string scope_path_symbol;
  std::string method_lookup_symbol;
  std::string override_lookup_symbol;
  std::string conflict_lookup_symbol;
  bool throws_declared = false;
  bool throws_declaration_profile_is_normalized = false;
  std::string throws_declaration_profile;
  bool result_like_profile_is_normalized = false;
  bool deterministic_result_like_lowering_handoff = false;
  std::size_t result_like_sites = 0;
  std::size_t result_success_sites = 0;
  std::size_t result_failure_sites = 0;
  std::size_t result_branch_sites = 0;
  std::size_t result_payload_sites = 0;
  std::size_t result_normalized_sites = 0;
  std::size_t result_branch_merge_sites = 0;
  std::size_t result_contract_violation_sites = 0;
  std::string result_like_profile;
  bool ns_error_bridging_profile_is_normalized = false;
  bool deterministic_ns_error_bridging_lowering_handoff = false;
  std::size_t ns_error_bridging_sites = 0;
  std::size_t ns_error_parameter_sites = 0;
  std::size_t ns_error_out_parameter_sites = 0;
  std::size_t ns_error_bridge_path_sites = 0;
  std::size_t failable_call_sites = 0;
  std::size_t ns_error_bridging_normalized_sites = 0;
  std::size_t ns_error_bridge_boundary_sites = 0;
  std::size_t ns_error_bridging_contract_violation_sites = 0;
  std::string ns_error_bridging_profile;
  bool await_suspension_profile_is_normalized = false;
  bool deterministic_await_suspension_handoff = false;
  std::size_t await_suspension_sites = 0;
  std::size_t await_keyword_sites = 0;
  std::size_t await_suspension_point_sites = 0;
  std::size_t await_resume_sites = 0;
  std::size_t await_state_machine_sites = 0;
  std::size_t await_continuation_sites = 0;
  std::size_t await_suspension_normalized_sites = 0;
  std::size_t await_suspension_gate_blocked_sites = 0;
  std::size_t await_suspension_contract_violation_sites = 0;
  std::string await_suspension_profile;
  bool actor_isolation_sendability_profile_is_normalized = false;
  bool deterministic_actor_isolation_sendability_handoff = false;
  std::size_t actor_isolation_sendability_sites = 0;
  std::size_t actor_isolation_decl_sites = 0;
  std::size_t actor_hop_sites = 0;
  std::size_t sendable_annotation_sites = 0;
  std::size_t non_sendable_crossing_sites = 0;
  std::size_t isolation_boundary_sites = 0;
  std::size_t actor_isolation_sendability_normalized_sites = 0;
  std::size_t actor_isolation_sendability_gate_blocked_sites = 0;
  std::size_t actor_isolation_sendability_contract_violation_sites = 0;
  std::string actor_isolation_sendability_profile;
  bool task_runtime_cancellation_profile_is_normalized = false;
  bool deterministic_task_runtime_cancellation_handoff = false;
  std::size_t task_runtime_interop_sites = 0;
  std::size_t runtime_hook_sites = 0;
  std::size_t cancellation_check_sites = 0;
  std::size_t cancellation_handler_sites = 0;
  std::size_t suspension_point_sites = 0;
  std::size_t cancellation_propagation_sites = 0;
  std::size_t task_runtime_normalized_sites = 0;
  std::size_t task_runtime_gate_blocked_sites = 0;
  std::size_t task_runtime_contract_violation_sites = 0;
  std::string task_runtime_cancellation_profile;
  bool concurrency_replay_race_guard_profile_is_normalized = false;
  bool deterministic_concurrency_replay_race_guard_handoff = false;
  std::size_t concurrency_replay_race_guard_sites = 0;
  std::size_t concurrency_replay_sites = 0;
  std::size_t replay_proof_sites = 0;
  std::size_t race_guard_sites = 0;
  std::size_t task_handoff_sites = 0;
  std::size_t actor_isolation_sites = 0;
  std::size_t deterministic_schedule_sites = 0;
  std::size_t concurrency_replay_guard_blocked_sites = 0;
  std::size_t concurrency_replay_contract_violation_sites = 0;
  std::string concurrency_replay_race_guard_profile;
  bool unsafe_pointer_extension_profile_is_normalized = false;
  bool deterministic_unsafe_pointer_extension_handoff = false;
  std::size_t unsafe_pointer_extension_sites = 0;
  std::size_t unsafe_keyword_sites = 0;
  std::size_t pointer_arithmetic_sites = 0;
  std::size_t raw_pointer_type_sites = 0;
  std::size_t unsafe_operation_sites = 0;
  std::size_t unsafe_pointer_extension_normalized_sites = 0;
  std::size_t unsafe_pointer_extension_gate_blocked_sites = 0;
  std::size_t unsafe_pointer_extension_contract_violation_sites = 0;
  std::string unsafe_pointer_extension_profile;
  bool inline_asm_intrinsic_governance_profile_is_normalized = false;
  bool deterministic_inline_asm_intrinsic_governance_handoff = false;
  std::size_t inline_asm_intrinsic_sites = 0;
  std::size_t inline_asm_sites = 0;
  std::size_t intrinsic_sites = 0;
  std::size_t governed_intrinsic_sites = 0;
  std::size_t privileged_intrinsic_sites = 0;
  std::size_t inline_asm_intrinsic_normalized_sites = 0;
  std::size_t inline_asm_intrinsic_gate_blocked_sites = 0;
  std::size_t inline_asm_intrinsic_contract_violation_sites = 0;
  std::string inline_asm_intrinsic_governance_profile;
  bool is_class_method = false;
  bool has_body = false;
  unsigned line = 1;
  unsigned column = 1;
};

struct Objc3PropertyAttributeDecl {
  std::string name;
  std::string value;
  bool has_value = false;
  unsigned line = 1;
  unsigned column = 1;
};

struct Objc3PropertyDecl {
  std::string name;
  ValueType type = ValueType::Unknown;
  bool vector_spelling = false;
  std::string vector_base_spelling;
  unsigned vector_lane_count = 1;
  bool id_spelling = false;
  bool class_spelling = false;
  bool sel_spelling = false;
  bool instancetype_spelling = false;
  bool object_pointer_type_spelling = false;
  std::string object_pointer_type_name;
  std::string typecheck_family_symbol;
  bool has_generic_suffix = false;
  bool generic_suffix_terminated = true;
  std::string generic_suffix_text;
  unsigned generic_line = 1;
  unsigned generic_column = 1;
  bool lightweight_generic_constraint_profile_is_normalized = false;
  std::string lightweight_generic_constraint_profile;
  bool nullability_flow_profile_is_normalized = false;
  std::string nullability_flow_profile;
  bool protocol_qualified_object_type_profile_is_normalized = false;
  std::string protocol_qualified_object_type_profile;
  bool variance_bridge_cast_profile_is_normalized = false;
  std::string variance_bridge_cast_profile;
  bool generic_metadata_abi_profile_is_normalized = false;
  std::string generic_metadata_abi_profile;
  bool module_import_graph_profile_is_normalized = false;
  std::string module_import_graph_profile;
  bool namespace_collision_shadowing_profile_is_normalized = false;
  std::string namespace_collision_shadowing_profile;
  bool public_private_api_partition_profile_is_normalized = false;
  std::string public_private_api_partition_profile;
  bool incremental_module_cache_invalidation_profile_is_normalized = false;
  std::string incremental_module_cache_invalidation_profile;
  bool cross_module_conformance_profile_is_normalized = false;
  std::string cross_module_conformance_profile;
  bool has_pointer_declarator = false;
  unsigned pointer_declarator_depth = 0;
  std::vector<Objc3SemaTokenMetadata> pointer_declarator_tokens;
  std::vector<Objc3SemaTokenMetadata> nullability_suffix_tokens;
  bool has_ownership_qualifier = false;
  std::string ownership_qualifier_spelling;
  std::string ownership_qualifier_symbol;
  std::vector<Objc3SemaTokenMetadata> ownership_qualifier_tokens;
  bool ownership_insert_retain = false;
  bool ownership_insert_release = false;
  bool ownership_insert_autorelease = false;
  std::string ownership_operation_profile;
  std::vector<Objc3PropertyAttributeDecl> attributes;
  bool is_readonly = false;
  bool is_readwrite = false;
  bool is_atomic = false;
  bool is_nonatomic = false;
  bool is_copy = false;
  bool is_strong = false;
  bool is_weak = false;
  bool is_unowned = false;
  bool is_assign = false;
  bool has_weak_unowned_conflict = false;
  bool ownership_is_weak_reference = false;
  bool ownership_is_unowned_reference = false;
  bool ownership_is_unowned_safe_reference = false;
  std::string ownership_lifetime_profile;
  std::string ownership_runtime_hook_profile;
  bool ownership_arc_diagnostic_candidate = false;
  bool ownership_arc_fixit_available = false;
  std::string ownership_arc_diagnostic_profile;
  std::string ownership_arc_fixit_hint;
  bool has_getter = false;
  bool has_setter = false;
  std::string getter_selector;
  std::string setter_selector;
  std::string scope_owner_symbol;
  std::string scope_path_symbol;
  std::string property_synthesis_symbol;
  std::string ivar_binding_symbol;
  unsigned line = 1;
  unsigned column = 1;
};

struct Objc3ProtocolDecl {
  std::string name;
  std::string scope_owner_symbol;
  std::vector<std::string> scope_path_lexicographic;
  std::vector<std::string> inherited_protocols;
  std::vector<std::string> inherited_protocols_lexicographic;
  std::string semantic_link_symbol;
  std::vector<std::string> method_lookup_symbols_lexicographic;
  std::vector<std::string> override_lookup_symbols_lexicographic;
  std::vector<std::string> conflict_lookup_symbols_lexicographic;
  std::vector<Objc3PropertyDecl> properties;
  std::vector<Objc3MethodDecl> methods;
  bool is_forward_declaration = false;
  unsigned line = 1;
  unsigned column = 1;
};

struct Objc3InterfaceDecl {
  std::string name;
  std::string super_name;
  std::string category_name;
  bool has_category = false;
  std::string scope_owner_symbol;
  std::vector<std::string> scope_path_lexicographic;
  std::vector<std::string> adopted_protocols;
  std::vector<std::string> adopted_protocols_lexicographic;
  std::string semantic_link_symbol;
  std::string semantic_link_super_symbol;
  std::string semantic_link_category_symbol;
  std::vector<std::string> method_lookup_symbols_lexicographic;
  std::vector<std::string> override_lookup_symbols_lexicographic;
  std::vector<std::string> conflict_lookup_symbols_lexicographic;
  std::vector<Objc3PropertyDecl> properties;
  std::vector<Objc3MethodDecl> methods;
  unsigned line = 1;
  unsigned column = 1;
};

struct Objc3ImplementationDecl {
  std::string name;
  std::string category_name;
  bool has_category = false;
  std::string scope_owner_symbol;
  std::vector<std::string> scope_path_lexicographic;
  std::string semantic_link_symbol;
  std::string semantic_link_interface_symbol;
  std::string semantic_link_category_symbol;
  std::vector<std::string> property_synthesis_symbols_lexicographic;
  std::vector<std::string> ivar_binding_symbols_lexicographic;
  std::vector<std::string> method_lookup_symbols_lexicographic;
  std::vector<std::string> override_lookup_symbols_lexicographic;
  std::vector<std::string> conflict_lookup_symbols_lexicographic;
  std::vector<Objc3PropertyDecl> properties;
  std::vector<Objc3MethodDecl> methods;
  unsigned line = 1;
  unsigned column = 1;
};

struct FunctionDecl {
  std::string name;
  std::string scope_owner_symbol;
  std::vector<std::string> scope_path_lexicographic;
  std::vector<FuncParam> params;
  ValueType return_type = ValueType::I32;
  bool return_vector_spelling = false;
  std::string return_vector_base_spelling;
  unsigned return_vector_lane_count = 1;
  bool return_id_spelling = false;
  bool return_class_spelling = false;
  bool return_sel_spelling = false;
  bool return_instancetype_spelling = false;
  bool return_object_pointer_type_spelling = false;
  std::string return_object_pointer_type_name;
  std::string return_typecheck_family_symbol;
  bool has_return_generic_suffix = false;
  bool return_generic_suffix_terminated = true;
  std::string return_generic_suffix_text;
  unsigned return_generic_line = 1;
  unsigned return_generic_column = 1;
  bool return_lightweight_generic_constraint_profile_is_normalized = false;
  std::string return_lightweight_generic_constraint_profile;
  bool return_nullability_flow_profile_is_normalized = false;
  std::string return_nullability_flow_profile;
  bool return_protocol_qualified_object_type_profile_is_normalized = false;
  std::string return_protocol_qualified_object_type_profile;
  bool return_variance_bridge_cast_profile_is_normalized = false;
  std::string return_variance_bridge_cast_profile;
  bool return_generic_metadata_abi_profile_is_normalized = false;
  std::string return_generic_metadata_abi_profile;
  bool return_module_import_graph_profile_is_normalized = false;
  std::string return_module_import_graph_profile;
  bool return_namespace_collision_shadowing_profile_is_normalized = false;
  std::string return_namespace_collision_shadowing_profile;
  bool return_public_private_api_partition_profile_is_normalized = false;
  std::string return_public_private_api_partition_profile;
  bool return_incremental_module_cache_invalidation_profile_is_normalized = false;
  std::string return_incremental_module_cache_invalidation_profile;
  bool return_cross_module_conformance_profile_is_normalized = false;
  std::string return_cross_module_conformance_profile;
  bool has_return_pointer_declarator = false;
  unsigned return_pointer_declarator_depth = 0;
  std::vector<Objc3SemaTokenMetadata> return_pointer_declarator_tokens;
  std::vector<Objc3SemaTokenMetadata> return_nullability_suffix_tokens;
  bool has_return_ownership_qualifier = false;
  std::string return_ownership_qualifier_spelling;
  std::string return_ownership_qualifier_symbol;
  std::vector<Objc3SemaTokenMetadata> return_ownership_qualifier_tokens;
  bool return_ownership_insert_retain = false;
  bool return_ownership_insert_release = false;
  bool return_ownership_insert_autorelease = false;
  std::string return_ownership_operation_profile;
  bool return_ownership_is_weak_reference = false;
  bool return_ownership_is_unowned_reference = false;
  bool return_ownership_is_unowned_safe_reference = false;
  std::string return_ownership_lifetime_profile;
  std::string return_ownership_runtime_hook_profile;
  bool return_ownership_arc_diagnostic_candidate = false;
  bool return_ownership_arc_fixit_available = false;
  std::string return_ownership_arc_diagnostic_profile;
  std::string return_ownership_arc_fixit_hint;
  bool throws_declared = false;
  bool throws_declaration_profile_is_normalized = false;
  std::string throws_declaration_profile;
  bool result_like_profile_is_normalized = false;
  bool deterministic_result_like_lowering_handoff = false;
  std::size_t result_like_sites = 0;
  std::size_t result_success_sites = 0;
  std::size_t result_failure_sites = 0;
  std::size_t result_branch_sites = 0;
  std::size_t result_payload_sites = 0;
  std::size_t result_normalized_sites = 0;
  std::size_t result_branch_merge_sites = 0;
  std::size_t result_contract_violation_sites = 0;
  std::string result_like_profile;
  bool ns_error_bridging_profile_is_normalized = false;
  bool deterministic_ns_error_bridging_lowering_handoff = false;
  std::size_t ns_error_bridging_sites = 0;
  std::size_t ns_error_parameter_sites = 0;
  std::size_t ns_error_out_parameter_sites = 0;
  std::size_t ns_error_bridge_path_sites = 0;
  std::size_t failable_call_sites = 0;
  std::size_t ns_error_bridging_normalized_sites = 0;
  std::size_t ns_error_bridge_boundary_sites = 0;
  std::size_t ns_error_bridging_contract_violation_sites = 0;
  std::string ns_error_bridging_profile;
  bool await_suspension_profile_is_normalized = false;
  bool deterministic_await_suspension_handoff = false;
  std::size_t await_suspension_sites = 0;
  std::size_t await_keyword_sites = 0;
  std::size_t await_suspension_point_sites = 0;
  std::size_t await_resume_sites = 0;
  std::size_t await_state_machine_sites = 0;
  std::size_t await_continuation_sites = 0;
  std::size_t await_suspension_normalized_sites = 0;
  std::size_t await_suspension_gate_blocked_sites = 0;
  std::size_t await_suspension_contract_violation_sites = 0;
  std::string await_suspension_profile;
  bool actor_isolation_sendability_profile_is_normalized = false;
  bool deterministic_actor_isolation_sendability_handoff = false;
  std::size_t actor_isolation_sendability_sites = 0;
  std::size_t actor_isolation_decl_sites = 0;
  std::size_t actor_hop_sites = 0;
  std::size_t sendable_annotation_sites = 0;
  std::size_t non_sendable_crossing_sites = 0;
  std::size_t isolation_boundary_sites = 0;
  std::size_t actor_isolation_sendability_normalized_sites = 0;
  std::size_t actor_isolation_sendability_gate_blocked_sites = 0;
  std::size_t actor_isolation_sendability_contract_violation_sites = 0;
  std::string actor_isolation_sendability_profile;
  bool task_runtime_cancellation_profile_is_normalized = false;
  bool deterministic_task_runtime_cancellation_handoff = false;
  std::size_t task_runtime_interop_sites = 0;
  std::size_t runtime_hook_sites = 0;
  std::size_t cancellation_check_sites = 0;
  std::size_t cancellation_handler_sites = 0;
  std::size_t suspension_point_sites = 0;
  std::size_t cancellation_propagation_sites = 0;
  std::size_t task_runtime_normalized_sites = 0;
  std::size_t task_runtime_gate_blocked_sites = 0;
  std::size_t task_runtime_contract_violation_sites = 0;
  std::string task_runtime_cancellation_profile;
  bool concurrency_replay_race_guard_profile_is_normalized = false;
  bool deterministic_concurrency_replay_race_guard_handoff = false;
  std::size_t concurrency_replay_race_guard_sites = 0;
  std::size_t concurrency_replay_sites = 0;
  std::size_t replay_proof_sites = 0;
  std::size_t race_guard_sites = 0;
  std::size_t task_handoff_sites = 0;
  std::size_t actor_isolation_sites = 0;
  std::size_t deterministic_schedule_sites = 0;
  std::size_t concurrency_replay_guard_blocked_sites = 0;
  std::size_t concurrency_replay_contract_violation_sites = 0;
  std::string concurrency_replay_race_guard_profile;
  bool unsafe_pointer_extension_profile_is_normalized = false;
  bool deterministic_unsafe_pointer_extension_handoff = false;
  std::size_t unsafe_pointer_extension_sites = 0;
  std::size_t unsafe_keyword_sites = 0;
  std::size_t pointer_arithmetic_sites = 0;
  std::size_t raw_pointer_type_sites = 0;
  std::size_t unsafe_operation_sites = 0;
  std::size_t unsafe_pointer_extension_normalized_sites = 0;
  std::size_t unsafe_pointer_extension_gate_blocked_sites = 0;
  std::size_t unsafe_pointer_extension_contract_violation_sites = 0;
  std::string unsafe_pointer_extension_profile;
  bool inline_asm_intrinsic_governance_profile_is_normalized = false;
  bool deterministic_inline_asm_intrinsic_governance_handoff = false;
  std::size_t inline_asm_intrinsic_sites = 0;
  std::size_t inline_asm_sites = 0;
  std::size_t intrinsic_sites = 0;
  std::size_t governed_intrinsic_sites = 0;
  std::size_t privileged_intrinsic_sites = 0;
  std::size_t inline_asm_intrinsic_normalized_sites = 0;
  std::size_t inline_asm_intrinsic_gate_blocked_sites = 0;
  std::size_t inline_asm_intrinsic_contract_violation_sites = 0;
  std::string inline_asm_intrinsic_governance_profile;
  bool is_prototype = false;
  bool is_pure = false;
  std::vector<std::unique_ptr<Stmt>> body;
  unsigned line = 1;
  unsigned column = 1;
};

struct GlobalDecl {
  std::string name;
  std::unique_ptr<Expr> value;
  unsigned line = 1;
  unsigned column = 1;
};

struct Objc3Program {
  std::string module_name = "objc3_module";
  std::vector<GlobalDecl> globals;
  std::vector<Objc3ProtocolDecl> protocols;
  std::vector<Objc3InterfaceDecl> interfaces;
  std::vector<Objc3ImplementationDecl> implementations;
  std::vector<FunctionDecl> functions;
  std::vector<std::string> diagnostics;
};
