from __future__ import annotations

from pathlib import Path
from typing import Any

from objc3c_tooling.paths import repo_rel

from capability_docs_validator.constants import (
    CANONICAL_MANIFEST_PATH,
    EVIDENCE_DOC,
    EVIDENCE_MAP_PATH,
    MATRIX_DOC,
    MATRIX_PATH,
    PHASE_OWNER_CONTRACT_PATH,
)
from capability_docs_validator.conformance import _phase_contract_rows
from capability_docs_validator.manifest import _manifest_support_claims
from capability_docs_validator.support_links import _row_support_claims


GENERATED_HEADER = (
    "<!-- Generated by scripts/build_capability_support_docs.py; "
    "edit docs/support/capability_matrix.json, docs/support/evidence_map.json, "
    "tests/fixtures/canonical/manifest.json, or "
    "tests/conformance/hard_cutover_behavior_phase_owner_contracts.json instead. -->"
)


def _code(value: object) -> str:
    text = str(value)
    if not text:
        return ""
    return f"`{text}`"


def _bullet_list(items: list[str], *, indent: str = "- ") -> list[str]:
    if not items:
        return [f"{indent}None"]
    return [f"{indent}{_code(item)}" for item in items]


def _evidence_label(evidence: dict[str, Any]) -> str:
    kind = str(evidence["kind"])
    path = str(evidence["path"])
    command = evidence.get("command")
    if isinstance(command, str) and command:
        return f"{kind}: `{path}` via `{command}`"
    return f"{kind}: `{path}`"


def _claim_to_capability(rows: list[dict[str, Any]]) -> dict[str, str]:
    claims: dict[str, str] = {}
    for row in rows:
        capability_id = str(row["id"])
        for claim in _row_support_claims(row):
            claims[claim] = capability_id
    return claims


def render_capability_matrix_doc(
    *,
    matrix: dict[str, Any],
    rows: list[dict[str, Any]],
    manifest: dict[str, Any],
    phase_owner_contracts: dict[str, Any],
) -> str:
    manifest_claims = _manifest_support_claims(manifest)
    claim_to_capability = _claim_to_capability(rows)

    lines: list[str] = [
        "# Objective-C 3.0 Capability Matrix",
        "",
        GENERATED_HEADER,
        "",
        "This public support matrix is generated from the checked-in support and",
        "conformance manifests. Markdown projections explain the machine-readable",
        "truth, but they do not create support claims.",
        "",
        "Authoritative inputs:",
        f"- `{repo_rel(MATRIX_PATH)}`",
        f"- `{repo_rel(EVIDENCE_MAP_PATH)}`",
        f"- `{repo_rel(CANONICAL_MANIFEST_PATH)}`",
        f"- `{repo_rel(PHASE_OWNER_CONTRACT_PATH)}`",
        "",
        "Support rule: only `implemented` rows with manifest-backed",
        "`objc3c.behavior.*` claims may be described as public Objective-C 3.0",
        "behavior. `rejected`, `reserved`, and `internal` rows are negative,",
        "unavailable, schema, workflow, owner-boundary, or evidence-boundary rows.",
        "",
        "## Support Contract",
        "",
        f"- Matrix version: `{matrix.get('matrix_version', '')}`",
        f"- Matrix schema: `{matrix.get('schema_path', '')}`",
        f"- Evidence map: `{matrix.get('evidence_map_path', '')}`",
        "- Public command surface: `npm run objc3c -- <action>`",
        "- Consumer rule: projections cannot introduce support claims absent from",
        "  the authoritative JSON data and canonical manifests.",
        "",
        "## Support Claim Authority",
        "",
        "| Support claim | Owner phase | Behavior fixture | Command | Matrix capability |",
        "| --- | --- | --- | --- | --- |",
    ]

    for claim_id in sorted(manifest_claims):
        claim = manifest_claims[claim_id]
        lines.append(
            "| "
            f"{_code(claim_id)} | "
            f"{_code(claim['owner_phase'])} | "
            f"{_code(claim['behavior_fixture'])} | "
            f"{_code(claim['executable_command'])} | "
            f"{_code(claim_to_capability.get(claim_id, ''))} |"
        )

    lines.extend(
        [
            "",
            "## Phase Owner Contract",
            "",
            "The conformance phase owner contract is evidence routing, not an",
            "independent support source. Each phase support claim must be backed by",
            "the canonical manifest fixture and public npm command above.",
            "",
        ]
    )
    for contract in _phase_contract_rows(phase_owner_contracts):
        lines.extend(
            [
                f"### {contract['phase']}",
                "",
                f"- Support claim: {_code(contract.get('support_claim', ''))}",
                f"- Fixture root: {_code(contract.get('fixture_root', ''))}",
                "- Canonical positive evidence:",
                *_bullet_list(
                    [str(path) for path in contract.get("canonical_positive_evidence", [])],
                    indent="  - ",
                ),
                "- Retired or negative evidence:",
                *_bullet_list(
                    [str(path) for path in contract.get("retired_surface_evidence", [])],
                    indent="  - ",
                ),
                f"- Generated fixture authority: {_code(str(contract.get('generated_fixture_authority')).lower())}",
                "",
            ]
        )

    lines.extend(["## Capability Rows", ""])
    for row in rows:
        lines.extend(
            [
                f"### {row['title']}",
                "",
                f"- Capability ID: {_code(row['id'])}",
                f"- State: {_code(row['state'])}",
                f"- Support claims: {', '.join(_code(claim) for claim in _row_support_claims(row)) or 'None'}",
                f"- Summary: {row.get('summary', '')}",
                "- Owner modules:",
                *_bullet_list(
                    [str(path) for path in row.get("owner_modules", [])],
                    indent="  - ",
                ),
                "- Evidence:",
                *[
                    f"  - {_evidence_label(evidence)}"
                    for evidence in row.get("evidence", [])
                    if isinstance(evidence, dict)
                ],
                "",
            ]
        )

    lines.extend(
        [
            "## State Meanings",
            "",
            "- `implemented`: the named behavior has manifest-backed executable",
            "  evidence for its owner phase.",
            "- `rejected`: parser, semantic, lowering, runtime, or execution evidence",
            "  is a diagnostic or strict-error case.",
            "- `reserved`: the syntax, feature family, or runtime closure is",
            "  unavailable until a narrower implemented row exists.",
            "- `internal`: the row names implementation, schema, report, workflow, or",
            "  owner boundaries, not public Objective-C 3.0 behavior.",
            "",
        ]
    )
    return "\n".join(lines)


def render_evidence_map_doc(
    *,
    evidence_map: dict[str, Any],
) -> str:
    lines: list[str] = [
        "# Capability Evidence Map",
        "",
        GENERATED_HEADER,
        "",
        "This evidence map is a generated markdown projection of",
        "`docs/support/evidence_map.json`. It is a flattened view of",
        "`docs/support/capability_matrix.json#/capabilities/*/evidence`.",
        "",
        "Rows with commands are replayable public evidence through",
        "`npm run objc3c -- <action>`. Rows without commands are owner, schema,",
        "diagnostic, documentation, or boundary evidence only.",
        "",
        "## Projection Contract",
        "",
    ]
    projection_contract = evidence_map.get("projection_contract", {})
    if isinstance(projection_contract, dict):
        for key in ("source", "owner", "row_key", "drift_rule"):
            lines.append(f"- {key}: {_code(projection_contract.get(key, ''))}")
    lines.extend(["", "## Evidence Policy", ""])
    evidence_policy = evidence_map.get("evidence_policy", {})
    if isinstance(evidence_policy, dict):
        for key in (
            "public_command_surface",
            "command_required_for",
            "command_forbidden_for",
            "row_role_rule",
        ):
            lines.append(f"- {key}: {_code(evidence_policy.get(key, ''))}")

    lines.extend(
        [
            "",
            "## Evidence Rows",
            "",
            "| Capability ID | Support claim | Evidence kind | Path | Command |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for row in evidence_map.get("rows", []):
        if not isinstance(row, dict):
            continue
        lines.append(
            "| "
            f"{_code(row.get('capability_id', ''))} | "
            f"{_code(row.get('support_claim', ''))} | "
            f"{_code(row.get('evidence_kind', ''))} | "
            f"{_code(row.get('path', ''))} | "
            f"{_code(row.get('command', ''))} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_support_docs(
    *,
    matrix: dict[str, Any],
    rows: list[dict[str, Any]],
    evidence_map: dict[str, Any],
    manifest: dict[str, Any],
    phase_owner_contracts: dict[str, Any],
) -> dict[Path, str]:
    return {
        MATRIX_DOC: render_capability_matrix_doc(
            matrix=matrix,
            rows=rows,
            manifest=manifest,
            phase_owner_contracts=phase_owner_contracts,
        ),
        EVIDENCE_DOC: render_evidence_map_doc(evidence_map=evidence_map),
    }


def _validate_generated_docs(rendered_docs: dict[Path, str]) -> None:
    from capability_docs_validator.errors import CapabilityDocsError

    drifted = [
        repo_rel(path)
        for path, expected in rendered_docs.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != expected
    ]
    if drifted:
        raise CapabilityDocsError(
            "generated support docs drifted; run "
            "`python scripts/build_capability_support_docs.py --check` for details "
            "or `python scripts/build_capability_support_docs.py` to regenerate: "
            + ", ".join(drifted)
        )
