"""Manifest/object/IR truth-gate implementation package."""

from __future__ import annotations

from .cli import main
from .compiler_runs import find_llvm_tool, run_compiler
from .manifest_loading import artifact_hashes, read, read_json, sha256
from .paths import (
    COMPILER,
    CONFORMANCE_MANIFEST,
    CONFORMANCE_NEGATIVE,
    CONFORMANCE_POSITIVE,
    CONFORMANCE_README,
    CONTRACT_ID,
    DASHBOARD_BLOCKERS,
    DETERMINISTIC_ARTIFACTS,
    IR_EMITTER,
    ISSUE,
    JSON_OUT,
    LOWERING_CONTRACT_CPP,
    LOWERING_CONTRACT_H,
    MD_OUT,
    NEGATIVE_FIXTURE,
    POSITIVE_FIXTURE,
    PUBLIC_CLAIM_DRIFT,
    REPORT_DIR,
    REQUIRED_ARTIFACTS,
    REQUIRED_IR_TOKENS,
    REQUIRED_MANIFEST_KEYS,
    REQUIRED_OBJECT_SECTIONS,
    REQUIRED_OBJECT_SYMBOLS,
    ROOT,
    SCRATCH,
    SEMA_PASS_MANAGER,
    SEMANTIC_PASSES,
    STATIC_ANALYSIS,
    SUPPORT_CLASSIFICATION,
    rel,
)
from .rendering import render_markdown
from .source_diagnostics import check_conformance, check_source_tokens
from .summary import build_summary
from .truth_models import build_negative_runs, build_positive_runs, inspect_object

__all__ = [
    "COMPILER",
    "CONFORMANCE_MANIFEST",
    "CONFORMANCE_NEGATIVE",
    "CONFORMANCE_POSITIVE",
    "CONFORMANCE_README",
    "CONTRACT_ID",
    "DASHBOARD_BLOCKERS",
    "DETERMINISTIC_ARTIFACTS",
    "IR_EMITTER",
    "ISSUE",
    "JSON_OUT",
    "LOWERING_CONTRACT_CPP",
    "LOWERING_CONTRACT_H",
    "MD_OUT",
    "NEGATIVE_FIXTURE",
    "POSITIVE_FIXTURE",
    "PUBLIC_CLAIM_DRIFT",
    "REPORT_DIR",
    "REQUIRED_ARTIFACTS",
    "REQUIRED_IR_TOKENS",
    "REQUIRED_MANIFEST_KEYS",
    "REQUIRED_OBJECT_SECTIONS",
    "REQUIRED_OBJECT_SYMBOLS",
    "ROOT",
    "SCRATCH",
    "SEMA_PASS_MANAGER",
    "SEMANTIC_PASSES",
    "STATIC_ANALYSIS",
    "SUPPORT_CLASSIFICATION",
    "artifact_hashes",
    "build_negative_runs",
    "build_positive_runs",
    "build_summary",
    "check_conformance",
    "check_source_tokens",
    "find_llvm_tool",
    "inspect_object",
    "main",
    "read",
    "read_json",
    "rel",
    "render_markdown",
    "run_compiler",
    "sha256",
]
