"""Developer-tooling and performance action specs."""

from __future__ import annotations

from .action_spec import ActionSpec

DEVELOPER_AND_PERFORMANCE_ACTION_SPECS: dict[str, ActionSpec] = {
    "inspect-capability-explorer": ActionSpec("inspect-capability-explorer", "probe LLVM and backend-routing capability state through the live capability explorer surface", "python:scripts/probe_objc3c_llvm_capabilities.py", validation_tier="repo", guarantee_owner="capability explorer payloads stay tied to the live LLVM probe and backend-routing contracts", pass_through_args=True),
    "inspect-playground-repro": ActionSpec("inspect-playground-repro", "compile one source through the frontend C API runner and dump the playground and repro object", "runner-internal + artifacts/bin/objc3c-frontend-c-api-runner.exe", validation_tier="repo", guarantee_owner="playground and repro payloads stay tied to the real frontend runner summary, emitted artifacts, and executable replay command", pass_through_args=True),
    "inspect-compile-observability": ActionSpec("inspect-compile-observability", "compile one source through the frontend C API runner and dump the structured observability object", "runner-internal + artifacts/bin/objc3c-frontend-c-api-runner.exe", validation_tier="repo", guarantee_owner="developer-facing compile observability stays tied to the real frontend runner summary and emitted artifacts", pass_through_args=True),
    "inspect-runtime-inspector": ActionSpec("inspect-runtime-inspector", "compile one source through the frontend C API runner and dump the runtime inspector object", "runner-internal + artifacts/bin/objc3c-frontend-c-api-runner.exe", validation_tier="repo", guarantee_owner="developer-facing runtime inspection stays tied to the real emitted object artifact and runtime ABI boundary models", pass_through_args=True),
    "inspect-editor-tooling": ActionSpec("inspect-editor-tooling", "compile one source through the real frontend runner and dump the combined editor tooling surface", "python:scripts/build_objc3c_editor_tooling_surface.py", validation_tier="repo", guarantee_owner="editor-facing diagnostics, language-server capabilities, navigation, formatter output, and preview debug anchors stay tied to the real compile summary, diagnostics JSON, manifest declaration coordinates, and emitted object artifacts", pass_through_args=True),
    "format-objc3c": ActionSpec("format-objc3c", "format one objc3c source through the supported preview formatter subset", "python:scripts/format_objc3c_source.py", validation_tier="repo", guarantee_owner="preview formatter output stays fail-closed outside the supported subset and deterministic within it", pass_through_args=True),
    "benchmark-runtime-inspector": ActionSpec("benchmark-runtime-inspector", "measure the live runtime-inspector and capability-explorer workflow and write a reproducible benchmark report", "python:scripts/benchmark_objc3c_runtime_inspector.py", validation_tier="repo", guarantee_owner="runtime inspector timing and capability comparisons stay tied to executable public actions and real emitted artifacts", pass_through_args=True),
    "benchmark-performance": ActionSpec("benchmark-performance", "measure the checked-in objc3 showcase workloads and write reproducible compile/runtime telemetry packets", "python:scripts/benchmark_objc3c_performance.py", validation_tier="repo", guarantee_owner="objc3 benchmark telemetry stays tied to checked-in showcase workloads and raw sample packets", pass_through_args=True),
    "benchmark-runtime-performance": ActionSpec("benchmark-runtime-performance", "measure the live runtime startup dispatch reflection and ownership hot paths and write reproducible telemetry packets", "python:scripts/benchmark_objc3c_runtime_performance.py", validation_tier="repo", guarantee_owner="runtime hot-path telemetry stays tied to the live runtime acceptance probes and counter snapshots", pass_through_args=True),
    "benchmark-compiler-throughput": ActionSpec("benchmark-compiler-throughput", "measure direct native compile throughput, wrapper cache proof, cache invalidation, macro-host cache publication, and docs-generation cost", "pwsh:scripts/check_objc3c_native_perf_budget.ps1", validation_tier="repo", guarantee_owner="compiler-throughput telemetry stays tied to the live native compiler executable, wrapper cache contract, macro-host artifact path, and checked-in docs generators", pass_through_args=True),
    "validate-compiler-throughput": ActionSpec("validate-compiler-throughput", "run the integrated compiler-throughput benchmark and cache-proof validation flow", "python:scripts/check_objc3c_compiler_throughput_integration.py", validation_tier="repo", guarantee_owner="compiler-throughput benchmark outputs stay executable across the live native compiler, wrapper cache proof, macro-host artifact path, and docs generators"),
    "validate-runnable-compiler-throughput": ActionSpec("validate-runnable-compiler-throughput", "validate the staged runnable compiler-throughput surface end to end from the package root", "python:scripts/check_objc3c_runnable_compiler_throughput_end_to_end.py", validation_tier="full", guarantee_owner="packaged compiler-throughput fixtures, contracts, benchmark script, and command surfaces stay reproducible from the staged runnable toolchain bundle"),
    "validate-runtime-performance": ActionSpec("validate-runtime-performance", "run the integrated runtime hot-path benchmark and packaged validation flow", "python:scripts/check_objc3c_runtime_performance_integration.py", validation_tier="repo", guarantee_owner="runtime hot-path benchmark outputs stay executable across the live runtime probes and the staged runnable bundle"),
    "validate-runnable-runtime-performance": ActionSpec("validate-runnable-runtime-performance", "validate the staged runnable runtime-performance surface end to end from the package root", "python:scripts/check_objc3c_runnable_runtime_performance_end_to_end.py", validation_tier="full", guarantee_owner="packaged runtime-performance fixtures, contracts, and benchmark command surfaces stay reproducible from the staged runnable toolchain bundle"),
    "benchmark-comparative-baselines": ActionSpec("benchmark-comparative-baselines", "measure the checked-in ObjC2 Swift and C++ baseline workloads and write reproducible comparison telemetry packets", "python:scripts/run_objc3c_comparative_baselines.py", validation_tier="repo", guarantee_owner="comparative baseline telemetry stays tied to checked-in language fixtures and recorded availability states", pass_through_args=True),
    "validate-runnable-performance": ActionSpec("validate-runnable-performance", "validate the staged runnable toolchain performance surface end to end from the package root", "python:scripts/check_objc3c_runnable_performance_end_to_end.py", validation_tier="full", guarantee_owner="packaged benchmark fixtures, schemas, and benchmark command surfaces stay reproducible from the staged runnable toolchain bundle"),
    "validate-performance-foundation": ActionSpec("validate-performance-foundation", "run the integrated benchmark and comparative baseline validation flow", "python:scripts/check_objc3c_performance_integration.py", validation_tier="repo", guarantee_owner="benchmark foundations stay executable across live objc3 workloads, comparative baselines, and the staged runnable bundle"),
}
