"""Application, stdlib, package ecosystem, and planning action specs."""

from __future__ import annotations

from .action_spec import ActionSpec

APPLICATION_AND_ECOSYSTEM_ACTION_SPECS: dict[str, ActionSpec] = {
    "materialize-playground-workspace": ActionSpec("materialize-playground-workspace", "compile one source through the live frontend runner and materialize a machine-owned playground workspace contract under tmp", "runner-internal + artifacts/bin/objc3c-frontend-c-api-runner.exe", validation_tier="repo", guarantee_owner="playground workspaces stay machine-owned, compile-coupled, and rooted in tmp outputs with editor/debug drill references instead of shared evidence-only buckets", pass_through_args=True),
    "materialize-stdlib-workspace": ActionSpec("materialize-stdlib-workspace", "copy the checked-in stdlib workspace and lowering/import contracts into a machine-owned artifact root under tmp", "python:scripts/materialize_objc3c_stdlib_workspace.py", validation_tier="repo", guarantee_owner="stdlib workspace materializations stay machine-owned and derived from the checked-in stdlib root plus lowering/import contract surface", pass_through_args=True),
    "materialize-canonical-application-workspace": ActionSpec("materialize-canonical-application-workspace", "materialize the canonical application workspace from the checked-in showcase and stdlib surfaces", "python:scripts/materialize_objc3c_canonical_application_workspace.py", validation_tier="repo", guarantee_owner="canonical application workspace materialization stays derived from the checked-in showcase and stdlib contracts", pass_through_args=True),
    "validate-stdlib-foundation": ActionSpec("validate-stdlib-foundation", "run the integrated stdlib boundary and smoke validation flow", "python:scripts/check_objc3c_stdlib_foundation_integration.py", validation_tier="repo", guarantee_owner="stdlib boundary contracts, lowering/import artifact expectations, workspace materialization, and smoke compilation stay executable on the live public workflow"),
    "validate-stdlib-advanced": ActionSpec("validate-stdlib-advanced", "run the integrated advanced stdlib helper validation flow", "python:scripts/check_objc3c_stdlib_advanced_integration.py", validation_tier="repo", guarantee_owner="advanced stdlib helper module contracts, profile gates, and shared smoke compilation stay executable on the live public workflow"),
    "validate-stdlib-program": ActionSpec("validate-stdlib-program", "run the integrated stdlib program docs, showcase, tutorial, and capability-adoption validation flow", "python:scripts/check_objc3c_stdlib_program_integration.py", validation_tier="repo", guarantee_owner="stdlib publish/adoption docs, capability demos, tutorial routing, and stdlib smoke integration stay executable on the live public workflow"),
    "validate-application-architecture": ActionSpec("validate-application-architecture", "run the integrated template and canonical application workspace validation flow", "python:scripts/check_objc3c_application_architecture_integration.py", validation_tier="repo", guarantee_owner="template harnesses and canonical application workspaces stay derived from live showcase, stdlib, and public workflow surfaces"),
    "validate-runnable-application-architecture": ActionSpec("validate-runnable-application-architecture", "validate packaged canonical application workspace and template surfaces end to end from the staged runnable toolchain bundle", "python:scripts/check_objc3c_runnable_application_architecture_end_to_end.py", validation_tier="full", guarantee_owner="packaged canonical application workspaces and template harness validation stay reproducible from the staged runnable toolchain bundle"),
    "build-package-lock": ActionSpec("build-package-lock", "generate the local package lock from checked-in stdlib and showcase package surfaces", "python:scripts/build_objc3c_package_lock.py", validation_tier="repo", guarantee_owner="package locks stay deterministic, provenance-bearing, and derived from checked-in local package surfaces"),
    "validate-package-authoring": ActionSpec("validate-package-authoring", "validate local package authoring and deterministic lock generation", "python:scripts/check_objc3c_package_authoring_workflow.py", validation_tier="repo", guarantee_owner="package authoring stays replayable through checked-in package surfaces and public workflow commands"),
    "validate-package-mirror": ActionSpec("validate-package-mirror", "validate offline mirror and local registry metadata reproducibility from the generated package lock", "python:scripts/check_objc3c_package_registry_mirror_reproducibility.py", validation_tier="repo", guarantee_owner="offline mirror and local registry metadata stay lock-derived, no-network, and hosted-registry-deferred"),
    "validate-package-ecosystem": ActionSpec("validate-package-ecosystem", "validate the integrated package ecosystem workflow against stdlib program and canonical application surfaces", "python:scripts/check_objc3c_package_ecosystem_integration.py", validation_tier="repo", guarantee_owner="package ecosystem claims stay grounded in deterministic locks, stdlib programs, and canonical application workspaces"),
    "validate-runnable-package-ecosystem": ActionSpec("validate-runnable-package-ecosystem", "validate package authoring and offline mirror workflows from the staged runnable toolchain bundle", "python:scripts/check_objc3c_runnable_package_ecosystem_end_to_end.py", validation_tier="full", guarantee_owner="packaged dependency and offline mirror workflows stay reproducible from the staged runnable toolchain bundle"),
    "validate-long-horizon-operations": ActionSpec("validate-long-horizon-operations", "validate upgrade, rollback, soak, aging, and support-window evidence over the live package and application workflows", "python:scripts/check_objc3c_long_horizon_operations_integration.py", validation_tier="full", guarantee_owner="long-horizon support claims stay backed by generated upgrade, rollback, soak, aging, package, application, performance, and conformance evidence"),
    "publish-long-horizon-operations": ActionSpec("publish-long-horizon-operations", "publish support-window and long-horizon operator metadata from generated evidence", "python:scripts/publish_objc3c_long_horizon_operations_metadata.py", validation_tier="release", guarantee_owner="operator-facing support-window metadata stays generated from long-horizon evidence and blocks when claim audit reports release blockers"),
    "validate-adoption-legibility": ActionSpec("validate-adoption-legibility", "validate adoption, comparison, onboarding, and evaluator evidence over live docs, showcase, package, and support workflows", "python:scripts/check_objc3c_adoption_legibility_integration.py", validation_tier="repo", guarantee_owner="external evaluator and onboarding claims stay backed by generated adoption evidence and checked-in public docs"),
    "publish-adoption-legibility": ActionSpec("publish-adoption-legibility", "publish evaluator-facing adoption and onboarding metadata from generated evidence", "python:scripts/publish_objc3c_adoption_legibility_metadata.py", validation_tier="release", guarantee_owner="evaluator-facing adoption metadata stays generated from adoption evidence and blocks when claim audit reports release blockers"),
    "validate-governance-sustainability": ActionSpec("validate-governance-sustainability", "validate governance budget policy extension review stewardship and artifact evidence on the live public workflow", "python:scripts/check_objc3c_governance_sustainability_integration.py", validation_tier="repo", guarantee_owner="governance and extension-review claims stay executable across checked-in contracts, public workflow entrypoints, and generated evidence"),
    "publish-governance-sustainability": ActionSpec("publish-governance-sustainability", "publish governance stewardship and extension-review metadata from generated evidence", "python:scripts/publish_objc3c_governance_sustainability_metadata.py", validation_tier="release", guarantee_owner="governance publication stays generated from integration evidence and blocks when stewardship or extension-review evidence reports release blockers"),
    "publish-planning-issues": ActionSpec("publish-planning-issues", "publish checked-in Objective-C 3 planning issues to GitHub while preserving GitHub-assigned numbers", "python:scripts/publish_objc3c_planning_issues.py", validation_tier="repo", guarantee_owner="issue publication stays rooted in checked-in planning payloads, durable GitHub number mappings, labels, milestones, and blocker references", pass_through_args=True),
    "check-planning-publication-drift": ActionSpec("check-planning-publication-drift", "audit checked-in Objective-C 3 planning publication references for GitHub mapping drift", "python:scripts/audit_objc3c_planning_publication.py --check", validation_tier="repo", guarantee_owner="planning payloads, markdown reports, durable GitHub mappings, and dependency references stay synchronized with assigned GitHub numbers", pass_through_args=True),
    "validate-runnable-stdlib-advanced": ActionSpec("validate-runnable-stdlib-advanced", "validate runnable advanced stdlib helper packaging and smoke compilation end to end from the package root", "python:scripts/check_objc3c_runnable_stdlib_advanced_end_to_end.py", validation_tier="full", guarantee_owner="packaged advanced stdlib helper contracts, profile gates, and subset smoke compilation stay reproducible from the staged runnable toolchain bundle"),
    "validate-runnable-stdlib-foundation": ActionSpec("validate-runnable-stdlib-foundation", "validate runnable stdlib foundation packaging and smoke compilation end to end from the package root", "python:scripts/check_objc3c_runnable_stdlib_foundation_end_to_end.py", validation_tier="full", guarantee_owner="packaged stdlib boundary contracts, lowering/import artifact metadata, module smoke compilation, and runtime-archive linkage stay reproducible from the staged runnable toolchain bundle"),
    "validate-runnable-stdlib-program": ActionSpec("validate-runnable-stdlib-program", "validate the staged runnable stdlib program docs/example package surface end to end", "python:scripts/check_objc3c_runnable_stdlib_program_end_to_end.py", validation_tier="full", guarantee_owner="packaged stdlib program docs, showcase examples, and publish-input metadata stay reproducible from the staged runnable toolchain bundle"),
    "validate-runnable-developer-tooling": ActionSpec("validate-runnable-developer-tooling", "validate packaged editor, formatter, debug, workspace, and integrated developer-tooling behavior from the staged runnable toolchain bundle", "python:scripts/check_objc3c_runnable_developer_tooling_end_to_end.py", validation_tier="full", guarantee_owner="packaged editor, formatter, debug anchors, workspace drills, and integrated developer-tooling validation stay reproducible from the staged runnable toolchain bundle"),
}
