"""Core codegen optimization policy action specs."""

from __future__ import annotations

from .action_spec import ActionSpec
from .actions.codegen_optimization_policy import (
    CODEGEN_OPTIMIZATION_POLICY_ACTION,
    CODEGEN_OPTIMIZATION_POLICY_BACKEND,
    CODEGEN_OPTIMIZATION_POLICY_GUARANTEE_OWNER,
    CODEGEN_OPTIMIZATION_POLICY_SUMMARY,
    CODEGEN_OPTIMIZATION_POLICY_VALIDATION_TIER,
)
from .actions.semantic_optimization_pipeline import (
    OPTIMIZATION_PROOF_MODEL_ACTION,
    OPTIMIZATION_PROOF_MODEL_BACKEND,
    OPTIMIZATION_PROOF_MODEL_GUARANTEE_OWNER,
    OPTIMIZATION_PROOF_MODEL_SUMMARY,
    OPTIMIZATION_PROOF_MODEL_VALIDATION_TIER,
    SEMANTIC_OPTIMIZATION_PIPELINE_ACTION,
    SEMANTIC_OPTIMIZATION_PIPELINE_BACKEND,
    SEMANTIC_OPTIMIZATION_PIPELINE_GUARANTEE_OWNER,
    SEMANTIC_OPTIMIZATION_PIPELINE_SUMMARY,
    SEMANTIC_OPTIMIZATION_PIPELINE_VALIDATION_TIER,
)

CORE_CODEGEN_ACTION_SPECS: dict[str, ActionSpec] = {
    CODEGEN_OPTIMIZATION_POLICY_ACTION: ActionSpec(
        CODEGEN_OPTIMIZATION_POLICY_ACTION,
        CODEGEN_OPTIMIZATION_POLICY_SUMMARY,
        CODEGEN_OPTIMIZATION_POLICY_BACKEND,
        validation_tier=CODEGEN_OPTIMIZATION_POLICY_VALIDATION_TIER,
        guarantee_owner=CODEGEN_OPTIMIZATION_POLICY_GUARANTEE_OWNER,
    ),
    SEMANTIC_OPTIMIZATION_PIPELINE_ACTION: ActionSpec(
        SEMANTIC_OPTIMIZATION_PIPELINE_ACTION,
        SEMANTIC_OPTIMIZATION_PIPELINE_SUMMARY,
        SEMANTIC_OPTIMIZATION_PIPELINE_BACKEND,
        validation_tier=SEMANTIC_OPTIMIZATION_PIPELINE_VALIDATION_TIER,
        guarantee_owner=SEMANTIC_OPTIMIZATION_PIPELINE_GUARANTEE_OWNER,
    ),
    OPTIMIZATION_PROOF_MODEL_ACTION: ActionSpec(
        OPTIMIZATION_PROOF_MODEL_ACTION,
        OPTIMIZATION_PROOF_MODEL_SUMMARY,
        OPTIMIZATION_PROOF_MODEL_BACKEND,
        validation_tier=OPTIMIZATION_PROOF_MODEL_VALIDATION_TIER,
        guarantee_owner=OPTIMIZATION_PROOF_MODEL_GUARANTEE_OWNER,
    ),
}

__all__ = ["CORE_CODEGEN_ACTION_SPECS"]
