"""Long-horizon operations, adoption, governance, and planning specs."""

from __future__ import annotations

from .action_spec import ActionSpec

ADOPTION_GOVERNANCE_ACTION_SPECS: dict[str, ActionSpec] = {
    "validate-long-horizon-operations": ActionSpec("validate-long-horizon-operations", "validate upgrade, rollback, soak, aging, and support-window evidence over the live package and application workflows", "python:scripts/check_objc3c_long_horizon_operations_integration.py", validation_tier="full", guarantee_owner="long-horizon support claims stay backed by generated upgrade, rollback, soak, aging, package, application, performance, and conformance evidence"),
    "publish-long-horizon-operations": ActionSpec("publish-long-horizon-operations", "publish support-window and long-horizon operator metadata from generated evidence", "python:scripts/publish_objc3c_long_horizon_operations_metadata.py", validation_tier="release", guarantee_owner="operator-facing support-window metadata stays generated from long-horizon evidence and blocks when claim audit reports release blockers"),
    "validate-adoption-legibility": ActionSpec("validate-adoption-legibility", "validate adoption, comparison, onboarding, and evaluator evidence over live docs, showcase, package, and support workflows", "python:scripts/check_objc3c_adoption_legibility_integration.py", validation_tier="repo", guarantee_owner="external evaluator and onboarding claims stay backed by generated adoption evidence and checked-in public docs"),
    "publish-adoption-legibility": ActionSpec("publish-adoption-legibility", "publish evaluator-facing adoption and onboarding metadata from generated evidence", "python:scripts/publish_objc3c_adoption_legibility_metadata.py", validation_tier="release", guarantee_owner="evaluator-facing adoption metadata stays generated from adoption evidence and blocks when claim audit reports release blockers"),
    "validate-governance-sustainability": ActionSpec("validate-governance-sustainability", "validate governance budget policy extension review stewardship and artifact evidence on the live public workflow", "python:scripts/check_objc3c_governance_sustainability_integration.py", validation_tier="repo", guarantee_owner="governance and extension-review claims stay executable across checked-in contracts, public workflow entrypoints, and generated evidence"),
    "publish-governance-sustainability": ActionSpec("publish-governance-sustainability", "publish governance stewardship and extension-review metadata from generated evidence", "python:scripts/publish_objc3c_governance_sustainability_metadata.py", validation_tier="release", guarantee_owner="governance publication stays generated from integration evidence and blocks when stewardship or extension-review evidence reports release blockers"),
    "publish-planning-issues": ActionSpec("publish-planning-issues", "publish checked-in Objective-C 3 planning issues to GitHub while preserving GitHub-assigned numbers", "python:scripts/publish_objc3c_planning_issues.py", validation_tier="repo", guarantee_owner="issue publication stays rooted in checked-in planning payloads, durable GitHub number mappings, labels, milestones, and blocker references", pass_through_args=True),
    "check-planning-publication-drift": ActionSpec("check-planning-publication-drift", "audit checked-in Objective-C 3 planning publication references for GitHub mapping drift", "python:scripts/audit_objc3c_planning_publication.py --check", validation_tier="repo", guarantee_owner="planning payloads, markdown reports, durable GitHub mappings, and dependency references stay synchronized with assigned GitHub numbers", pass_through_args=True),
}
