"""Release foundation, channel, operation, and distribution action specs."""

from __future__ import annotations

from .action_spec import ActionSpec

RELEASE_CHANNEL_ACTION_SPECS: dict[str, ActionSpec] = {
    "check-release-foundation-surface": ActionSpec("check-release-foundation-surface", "validate the checked-in release-foundation source surface", "python:scripts/check_release_foundation_source_surface.py", validation_tier="repo", guarantee_owner="release foundation only publishes from the checked-in release taxonomy, trust, payload, and provenance contracts"),
    "check-release-foundation-schema-surface": ActionSpec("check-release-foundation-schema-surface", "validate the checked-in release-foundation schema surface", "python:scripts/check_release_foundation_schema_surface.py", validation_tier="repo", guarantee_owner="release manifest, sbom, and attestation artifacts stay on checked-in schema contracts"),
    "build-release-manifest": ActionSpec("build-release-manifest", "derive the machine-owned release manifest from repeated runnable package assembly runs", "python:scripts/build_objc3c_release_manifest.py", validation_tier="repo", guarantee_owner="release payload selection and reproducibility proof stay tied to the live runnable package manifest and release-evidence boundary"),
    "publish-release-provenance": ActionSpec("publish-release-provenance", "publish the machine-owned release sbom and attestation artifacts", "python:scripts/publish_objc3c_release_provenance.py", validation_tier="repo", guarantee_owner="release provenance publication stays traceable to the live release manifest, package manifest, and release-evidence index"),
    "validate-release-foundation": ActionSpec("validate-release-foundation", "run the integrated release-foundation workflow", "runner-internal release-foundation child actions", validation_tier="nightly", guarantee_owner="release taxonomy, reproducible package assembly, and provenance publication stay executable on the live runnable package surface"),
    "check-packaging-channels-surface": ActionSpec("check-packaging-channels-surface", "validate the checked-in packaging-channels source surface", "python:scripts/check_packaging_channels_source_surface.py", validation_tier="repo", guarantee_owner="packaging-channel publication stays rooted in checked-in channel, platform, and installer policy contracts"),
    "check-packaging-channels-schema-surface": ActionSpec("check-packaging-channels-schema-surface", "validate the checked-in packaging-channels schema surface", "python:scripts/check_packaging_channels_schema_surface.py", validation_tier="repo", guarantee_owner="packaging-channel and install-receipt artifacts stay on checked-in schema contracts"),
    "build-package-channels": ActionSpec("build-package-channels", "build the portable archive, installer image, and offline bundle channels from the live runnable payload", "python:scripts/build_objc3c_package_channels.py", validation_tier="repo", guarantee_owner="package channels stay derived from the live runnable package and release-foundation artifacts"),
    "validate-packaging-channels": ActionSpec("validate-packaging-channels", "run the integrated packaging-channels workflow", "runner-internal packaging-channel child actions", validation_tier="nightly", guarantee_owner="portable archive installer image and offline bundle generation stay executable on the live release surface"),
    "validate-packaging-channels-end-to-end": ActionSpec("validate-packaging-channels-end-to-end", "validate install bootstrap rollback and offline bundle behavior end to end", "python:scripts/check_objc3c_packaging_channels_end_to_end.py", validation_tier="full", guarantee_owner="packaging-channel artifacts stay installable rollback-safe and offline-bootstrappable under temp-owned roots"),
    "build-platform-support-matrix": ActionSpec("build-platform-support-matrix", "build the machine-owned platform support matrix artifact", "python:scripts/build_objc3c_platform_support_matrix.py", validation_tier="repo", guarantee_owner="the published host and channel support matrix stays machine-owned narrow and aligned with live packaging and release evidence"),
    "validate-platform-hardening": ActionSpec("validate-platform-hardening", "run the integrated platform-hardening workflow", "python:scripts/check_objc3c_platform_hardening_integration.py", validation_tier="nightly", guarantee_owner="supported host package install and release claims stay tiered package-backed and fail-closed outside the checked-in matrix"),
    "validate-platform-hardening-end-to-end": ActionSpec("validate-platform-hardening-end-to-end", "validate packaged platform-hardening publication and smoke behavior from the staged runnable bundle", "python:scripts/check_objc3c_runnable_platform_hardening_end_to_end.py", validation_tier="full", guarantee_owner="packaged platform support inspection and validation remain runnable from the staged toolchain bundle"),
    "check-release-operations-surface": ActionSpec("check-release-operations-surface", "validate the checked-in release-operations source surface", "python:scripts/check_release_operations_source_surface.py", validation_tier="repo", guarantee_owner="release operations only publish from the checked-in versioning, upgrade-warning, rollback, and channel policy contracts"),
    "check-release-operations-schema-surface": ActionSpec("check-release-operations-schema-surface", "validate the checked-in release-operations schema surface", "python:scripts/check_release_operations_schema_surface.py", validation_tier="repo", guarantee_owner="update manifest and release-operations artifacts stay on checked-in schema contracts"),
    "build-update-manifest": ActionSpec("build-update-manifest", "derive the machine-owned update manifest from the live packaging-channel and release-foundation outputs", "python:scripts/build_objc3c_update_manifest.py", validation_tier="repo", guarantee_owner="versioned channel metadata stays tied to the live release and packaging surfaces"),
    "publish-release-operations": ActionSpec("publish-release-operations", "publish the machine-owned release-operations report and channel catalog", "python:scripts/publish_objc3c_release_operations_metadata.py", validation_tier="repo", guarantee_owner="release-operations publication stays traceable to the checked-in upgrade-warning, rollback, and channel policy contracts"),
    "validate-release-operations": ActionSpec("validate-release-operations", "run the integrated release-operations workflow", "runner-internal release-operations child actions", validation_tier="nightly", guarantee_owner="versioning, upgrade warnings, rollback guidance, and update metadata stay executable on the live release surfaces"),
    "validate-release-operations-end-to-end": ActionSpec("validate-release-operations-end-to-end", "validate release-operations entrypoints, generated metadata, and packaged channel references end to end", "python:scripts/check_objc3c_release_operations_end_to_end.py", validation_tier="full", guarantee_owner="release-operations metadata stays coherent with the live package-channel artifacts and rollback paths"),
    "check-distribution-credibility-surface": ActionSpec("check-distribution-credibility-surface", "validate the checked-in distribution-credibility source surface", "python:scripts/check_distribution_credibility_source_surface.py", validation_tier="repo", guarantee_owner="distribution credibility only publishes from the checked-in trust-signal, install-doc, operator, and drill contracts"),
    "check-distribution-credibility-schema-surface": ActionSpec("check-distribution-credibility-schema-surface", "validate the checked-in distribution-credibility schema surface", "python:scripts/check_distribution_credibility_schema_surface.py", validation_tier="repo", guarantee_owner="distribution dashboard and trust-report artifacts stay on checked-in schema contracts"),
    "build-distribution-credibility-dashboard": ActionSpec("build-distribution-credibility-dashboard", "build the machine-owned distribution credibility dashboard from the live release artifacts", "python:scripts/build_objc3c_distribution_credibility_dashboard.py", validation_tier="repo", guarantee_owner="distribution credibility summaries stay tied to the live release-foundation, packaging-channel, release-operations, and release-evidence surfaces"),
    "publish-distribution-credibility": ActionSpec("publish-distribution-credibility", "publish the machine-owned distribution trust report artifacts", "python:scripts/publish_objc3c_distribution_trust_report.py", validation_tier="repo", guarantee_owner="distribution trust reporting stays derived from the live release drill artifacts and checked-in credibility policies"),
    "validate-distribution-credibility": ActionSpec("validate-distribution-credibility", "run the integrated distribution-credibility workflow", "runner-internal distribution-credibility child actions", validation_tier="nightly", guarantee_owner="distribution trust signals and release-drill reporting stay executable on the live shipped release surfaces"),
    "validate-distribution-credibility-end-to-end": ActionSpec("validate-distribution-credibility-end-to-end", "validate distribution trust-report publication and evidence linkage end to end", "python:scripts/check_objc3c_distribution_credibility_end_to_end.py", validation_tier="full", guarantee_owner="distribution credibility artifacts stay coherent with the live package-channel and release-operations evidence paths"),
}
