"""Tooling, ecosystem, runtime, and test action handlers."""

from __future__ import annotations

from scripts.objc3c_workflow.action_handlers_defaults import action_test_default
from scripts.objc3c_workflow.action_spec import ActionHandler
from scripts.objc3c_workflow.actions import (
    application_surfaces,
    developer_tooling,
    ecosystem_publication,
    hygiene,
    native_build,
    runtime_tests,
    test_orchestration,
    validation_timing,
)

TOOLING_ECOSYSTEM_AND_TEST_ACTION_HANDLERS: dict[str, ActionHandler] = {
    "inspect-bonus-tool-integration": developer_tooling.action_inspect_bonus_tool_integration,
    "inspect-validation-timing": validation_timing.action_inspect_validation_timing,
    "materialize-project-template": developer_tooling.action_materialize_project_template,
    "materialize-canonical-application-workspace": application_surfaces.action_materialize_canonical_application_workspace,
    "trace-compile-stages": developer_tooling.action_trace_compile_stages,
    "test-capability-routed-source-parity": developer_tooling.action_test_capability_routed_source_parity,
    "validate-developer-tooling": developer_tooling.action_validate_developer_tooling,
    "validate-runnable-developer-tooling": developer_tooling.action_validate_runnable_developer_tooling,
    "validate-bonus-experiences": developer_tooling.action_validate_bonus_experiences,
    "validate-runnable-bonus-experiences": developer_tooling.action_validate_runnable_bonus_experiences,
    "validate-application-architecture": application_surfaces.action_validate_application_architecture,
    "validate-runnable-application-architecture": application_surfaces.action_validate_runnable_application_architecture,
    "build-package-lock": ecosystem_publication.action_build_package_lock,
    "validate-package-authoring": ecosystem_publication.action_validate_package_authoring,
    "validate-package-mirror": ecosystem_publication.action_validate_package_mirror,
    "validate-package-ecosystem": ecosystem_publication.action_validate_package_ecosystem,
    "validate-runnable-package-ecosystem": ecosystem_publication.action_validate_runnable_package_ecosystem,
    "validate-long-horizon-operations": ecosystem_publication.action_validate_long_horizon_operations,
    "publish-long-horizon-operations": ecosystem_publication.action_publish_long_horizon_operations,
    "validate-adoption-legibility": ecosystem_publication.action_validate_adoption_legibility,
    "publish-adoption-legibility": ecosystem_publication.action_publish_adoption_legibility,
    "validate-governance-sustainability": ecosystem_publication.action_validate_governance_sustainability,
    "publish-governance-sustainability": ecosystem_publication.action_publish_governance_sustainability,
    "publish-planning-issues": ecosystem_publication.action_publish_planning_issues,
    "check-planning-publication-drift": ecosystem_publication.action_check_planning_publication_drift,
    "lint-spec": hygiene.action_lint_spec,
    "test-default": action_test_default,
    "test-behavior-matrix": test_orchestration.action_test_behavior_matrix,
    "test-smoke": test_orchestration.action_test_smoke,
    "test-ci": test_orchestration.action_test_ci,
    "test-recovery": test_orchestration.action_test_recovery,
    "test-compile-wrapper-self-audit": test_orchestration.action_test_compile_wrapper_self_audit,
    "test-llvm-capability-routing": test_orchestration.action_test_llvm_capability_routing,
    "test-execution-smoke": test_orchestration.action_test_execution_smoke,
    "test-execution-replay": test_orchestration.action_test_execution_replay,
    "test-execution-replay-focused": test_orchestration.action_test_execution_replay_focused,
    "test-runtime-acceptance": runtime_tests.action_test_runtime_acceptance,
    "test-runtime-acceptance-fast": runtime_tests.action_test_runtime_acceptance_fast,
    "test-runtime-acceptance-diagnostics": runtime_tests.action_test_runtime_acceptance_diagnostics,
    "test-runtime-acceptance-cross-module": runtime_tests.action_test_runtime_acceptance_cross_module,
    "test-runtime-acceptance-block-arc": runtime_tests.action_test_runtime_acceptance_block_arc,
    "test-runtime-acceptance-concurrency": runtime_tests.action_test_runtime_acceptance_concurrency,
    "proof-runtime-architecture": runtime_tests.action_proof_runtime_architecture,
    "validate-runtime-architecture": runtime_tests.action_validate_runtime_architecture,
    "validate-runnable-bootstrap": runtime_tests.action_validate_runnable_bootstrap,
    "validate-block-arc-conformance": runtime_tests.action_validate_block_arc_conformance,
    "validate-runnable-block-arc": runtime_tests.action_validate_runnable_block_arc,
    "validate-concurrency-conformance": runtime_tests.action_validate_concurrency_conformance,
    "validate-runnable-concurrency": runtime_tests.action_validate_runnable_concurrency,
    "validate-object-model-conformance": runtime_tests.action_validate_object_model_conformance,
    "validate-storage-reflection-conformance": runtime_tests.action_validate_storage_reflection_conformance,
    "validate-runnable-object-model": runtime_tests.action_validate_runnable_object_model,
    "validate-runnable-storage-reflection": runtime_tests.action_validate_runnable_storage_reflection,
    "validate-error-conformance": runtime_tests.action_validate_error_conformance,
    "validate-runnable-error": runtime_tests.action_validate_runnable_error,
    "validate-interop-conformance": runtime_tests.action_validate_interop_conformance,
    "validate-runnable-interop": runtime_tests.action_validate_runnable_interop,
    "validate-metaprogramming-conformance": runtime_tests.action_validate_metaprogramming_conformance,
    "validate-runnable-metaprogramming": runtime_tests.action_validate_runnable_metaprogramming,
    "validate-release-candidate-conformance": runtime_tests.action_validate_release_candidate_conformance,
    "validate-runnable-release-candidate": runtime_tests.action_validate_runnable_release_candidate,
    "test-fixture-matrix": test_orchestration.action_test_fixture_matrix,
    "test-negative-expectations": test_orchestration.action_test_negative_expectations,
    "test-full": test_orchestration.action_test_full,
    "test-nightly": test_orchestration.action_test_nightly,
    "package-runnable-toolchain": native_build.action_package_runnable_toolchain,
    "proof-objc3c": native_build.action_proof_objc3c,
}
