"""Core public command-surface action specs."""

from __future__ import annotations

from scripts.objc3c_workflow.actions.docs_public_commands import (
    BUILD_PUBLIC_COMMAND_CONTRACT_ACTION,
    BUILD_PUBLIC_COMMAND_CONTRACT_BACKEND,
    BUILD_PUBLIC_COMMAND_CONTRACT_SUMMARY,
    BUILD_PUBLIC_COMMAND_SURFACE_ACTION,
    BUILD_PUBLIC_COMMAND_SURFACE_BACKEND,
    BUILD_PUBLIC_COMMAND_SURFACE_SUMMARY,
    CHECK_PUBLIC_COMMAND_BUDGET_ACTION,
    CHECK_PUBLIC_COMMAND_BUDGET_BACKEND,
    CHECK_PUBLIC_COMMAND_BUDGET_SUMMARY,
    CHECK_PUBLIC_COMMAND_CONTRACT_ACTION,
    CHECK_PUBLIC_COMMAND_CONTRACT_BACKEND,
    CHECK_PUBLIC_COMMAND_CONTRACT_SUMMARY,
    CHECK_PUBLIC_COMMAND_SURFACE_ACTION,
    CHECK_PUBLIC_COMMAND_SURFACE_BACKEND,
    CHECK_PUBLIC_COMMAND_SURFACE_SUMMARY,
    PUBLIC_COMMAND_BUDGET_GUARANTEE_OWNER,
    PUBLIC_COMMAND_SURFACE_GUARANTEE_OWNER,
    PUBLIC_COMMAND_VALIDATION_TIER,
)

from .action_spec import ActionSpec

CORE_PUBLIC_COMMAND_ACTION_SPECS: dict[str, ActionSpec] = {
    BUILD_PUBLIC_COMMAND_SURFACE_ACTION: ActionSpec(
        BUILD_PUBLIC_COMMAND_SURFACE_ACTION,
        BUILD_PUBLIC_COMMAND_SURFACE_SUMMARY,
        BUILD_PUBLIC_COMMAND_SURFACE_BACKEND,
    ),
    CHECK_PUBLIC_COMMAND_SURFACE_ACTION: ActionSpec(
        CHECK_PUBLIC_COMMAND_SURFACE_ACTION,
        CHECK_PUBLIC_COMMAND_SURFACE_SUMMARY,
        CHECK_PUBLIC_COMMAND_SURFACE_BACKEND,
        validation_tier=PUBLIC_COMMAND_VALIDATION_TIER,
        guarantee_owner=PUBLIC_COMMAND_SURFACE_GUARANTEE_OWNER,
    ),
    BUILD_PUBLIC_COMMAND_CONTRACT_ACTION: ActionSpec(
        BUILD_PUBLIC_COMMAND_CONTRACT_ACTION,
        BUILD_PUBLIC_COMMAND_CONTRACT_SUMMARY,
        BUILD_PUBLIC_COMMAND_CONTRACT_BACKEND,
    ),
    CHECK_PUBLIC_COMMAND_CONTRACT_ACTION: ActionSpec(
        CHECK_PUBLIC_COMMAND_CONTRACT_ACTION,
        CHECK_PUBLIC_COMMAND_CONTRACT_SUMMARY,
        CHECK_PUBLIC_COMMAND_CONTRACT_BACKEND,
    ),
    CHECK_PUBLIC_COMMAND_BUDGET_ACTION: ActionSpec(
        CHECK_PUBLIC_COMMAND_BUDGET_ACTION,
        CHECK_PUBLIC_COMMAND_BUDGET_SUMMARY,
        CHECK_PUBLIC_COMMAND_BUDGET_BACKEND,
        validation_tier=PUBLIC_COMMAND_VALIDATION_TIER,
        guarantee_owner=PUBLIC_COMMAND_BUDGET_GUARANTEE_OWNER,
    ),
}

__all__ = ["CORE_PUBLIC_COMMAND_ACTION_SPECS"]
