"""Core documentation validation action specs."""

from __future__ import annotations

from scripts.objc3c_workflow.actions.docs_documentation import (
    FOUNDATIONS_UMBRELLA_SOURCE_TRUTH_GUARANTEE_OWNER,
    FOUNDATIONS_UMBRELLA_SOURCE_TRUTH_VALIDATION_TIER,
    VALIDATE_FOUNDATIONS_UMBRELLA_SOURCE_TRUTH_ACTION,
    VALIDATE_FOUNDATIONS_UMBRELLA_SOURCE_TRUTH_BACKEND,
    VALIDATE_FOUNDATIONS_UMBRELLA_SOURCE_TRUTH_SUMMARY,
    UMBRELLA_READINESS_GUARANTEE_OWNER,
    UMBRELLA_READINESS_VALIDATION_TIER,
    VALIDATE_UMBRELLA_READINESS_ACTION,
    VALIDATE_UMBRELLA_READINESS_BACKEND,
    VALIDATE_UMBRELLA_READINESS_SUMMARY,
)

from .action_spec import ActionSpec

CORE_DOCUMENTATION_VALIDATION_ACTION_SPECS: dict[str, ActionSpec] = {
    VALIDATE_UMBRELLA_READINESS_ACTION: ActionSpec(
        VALIDATE_UMBRELLA_READINESS_ACTION,
        VALIDATE_UMBRELLA_READINESS_SUMMARY,
        VALIDATE_UMBRELLA_READINESS_BACKEND,
        validation_tier=UMBRELLA_READINESS_VALIDATION_TIER,
        guarantee_owner=UMBRELLA_READINESS_GUARANTEE_OWNER,
    ),
    VALIDATE_FOUNDATIONS_UMBRELLA_SOURCE_TRUTH_ACTION: ActionSpec(
        VALIDATE_FOUNDATIONS_UMBRELLA_SOURCE_TRUTH_ACTION,
        VALIDATE_FOUNDATIONS_UMBRELLA_SOURCE_TRUTH_SUMMARY,
        VALIDATE_FOUNDATIONS_UMBRELLA_SOURCE_TRUTH_BACKEND,
        validation_tier=FOUNDATIONS_UMBRELLA_SOURCE_TRUTH_VALIDATION_TIER,
        guarantee_owner=FOUNDATIONS_UMBRELLA_SOURCE_TRUTH_GUARANTEE_OWNER,
    ),
}

__all__ = ["CORE_DOCUMENTATION_VALIDATION_ACTION_SPECS"]
