"""Action handler registry for the objc3c workflow CLI."""

from __future__ import annotations

from scripts.objc3c_workflow.action_spec import ActionHandler
from scripts.objc3c_workflow.actions import (
    application_surfaces,
    developer_tooling,
    docs,
    ecosystem_publication,
    external_validation,
    hygiene,
    native_build,
    performance,
    release_governance,
    runtime_tests,
    schema_surfaces,
    stress,
    test_orchestration,
    validation_timing,
)


def action_build_default(_: list[str]) -> int:
    return native_build.action_build_native_binaries([])


def action_test_default(_: list[str]) -> int:
    return test_orchestration.action_test_smoke([])


ACTION_HANDLERS: dict[str, ActionHandler] = {
    "build-default": action_build_default,
    "build-native-binaries": native_build.action_build_native_binaries,
    "build-native-contracts": native_build.action_build_native_contracts,
    "build-native-full": native_build.action_build_native_full,
    "build-native-reconfigure": native_build.action_build_native_reconfigure,
    "build-site": docs.action_build_site,
    "check-site": docs.action_check_site,
    "build-native-docs": docs.action_build_native_docs,
    "check-native-docs": docs.action_check_native_docs,
    "build-public-command-surface": docs.action_build_public_command_surface,
    "check-public-command-surface": docs.action_check_public_command_surface,
    "build-public-command-contract": docs.action_build_public_command_contract,
    "check-public-command-contract": docs.action_check_public_command_contract,
    "check-public-command-budget": docs.action_check_public_command_budget,
    "check-documentation-surface": docs.action_check_documentation_surface,
    "check-markdown": docs.action_check_markdown,
    "format-markdown": docs.action_format_markdown,
    "lint-markdown": docs.action_lint_markdown,
    "lint": hygiene.action_lint,
    "check-dependency-boundaries": hygiene.action_check_dependency_boundaries,
    "check-llvm-capabilities": developer_tooling.action_check_llvm_capabilities,
    "check-hosted-llvm-capabilities": developer_tooling.action_check_hosted_llvm_capabilities,
    "check-release-evidence": hygiene.action_check_release_evidence,
    "check-source-hygiene-authenticity": hygiene.action_check_source_hygiene_authenticity,
    "check-source-hygiene-hard-cutover": hygiene.action_check_source_hygiene_hard_cutover,
    "check-task-hygiene": hygiene.action_check_task_hygiene,
    "check-showcase-surface": application_surfaces.action_check_showcase_surface,
    "check-stdlib-surface": application_surfaces.action_check_stdlib_surface,
    "validate-showcase-runtime": application_surfaces.action_validate_showcase_runtime,
    "validate-showcase": application_surfaces.action_validate_showcase,
    "validate-runnable-showcase": application_surfaces.action_validate_runnable_showcase,
    "validate-getting-started": application_surfaces.action_validate_getting_started,
    "check-repo-superclean-surface": hygiene.action_check_repo_superclean_surface,
    "validate-documentation-surface": docs.action_validate_documentation_surface,
    "validate-repo-superclean": hygiene.action_validate_repo_superclean,
    "compile-objc3c": native_build.action_compile_objc3c,
    "materialize-playground-workspace": developer_tooling.action_materialize_playground_workspace,
    "materialize-stdlib-workspace": application_surfaces.action_materialize_stdlib_workspace,
    "validate-stdlib-foundation": application_surfaces.action_validate_stdlib_foundation,
    "validate-stdlib-advanced": application_surfaces.action_validate_stdlib_advanced,
    "validate-stdlib-program": application_surfaces.action_validate_stdlib_program,
    "validate-runnable-stdlib-advanced": application_surfaces.action_validate_runnable_stdlib_advanced,
    "validate-runnable-stdlib-foundation": application_surfaces.action_validate_runnable_stdlib_foundation,
    "validate-runnable-stdlib-program": application_surfaces.action_validate_runnable_stdlib_program,
    "inspect-capability-explorer": developer_tooling.action_inspect_capability_explorer,
    "inspect-playground-repro": developer_tooling.action_inspect_playground_repro,
    "inspect-compile-observability": developer_tooling.action_inspect_compile_observability,
    "inspect-runtime-inspector": developer_tooling.action_inspect_runtime_inspector,
    "inspect-editor-tooling": developer_tooling.action_inspect_editor_tooling,
    "format-objc3c": developer_tooling.action_format_objc3c,
    "benchmark-runtime-inspector": performance.action_benchmark_runtime_inspector,
    "benchmark-performance": performance.action_benchmark_performance,
    "benchmark-runtime-performance": performance.action_benchmark_runtime_performance,
    "benchmark-compiler-throughput": performance.action_benchmark_compiler_throughput,
    "validate-compiler-throughput": performance.action_validate_compiler_throughput,
    "validate-runnable-compiler-throughput": performance.action_validate_runnable_compiler_throughput,
    "validate-runtime-performance": performance.action_validate_runtime_performance,
    "validate-runnable-runtime-performance": performance.action_validate_runnable_runtime_performance,
    "benchmark-comparative-baselines": performance.action_benchmark_comparative_baselines,
    "validate-runnable-performance": performance.action_validate_runnable_performance,
    "validate-performance-foundation": performance.action_validate_performance_foundation,
    "validate-conformance-corpus": application_surfaces.action_validate_conformance_corpus,
    "check-conformance-minima": application_surfaces.action_check_conformance_minima,
    "validate-runnable-conformance-corpus": application_surfaces.action_validate_runnable_conformance_corpus,
    "check-stress-surface": stress.action_check_stress_surface,
    "test-fuzz-safety": stress.action_test_fuzz_safety,
    "test-lowering-runtime-stress": stress.action_test_lowering_runtime_stress,
    "test-mixed-module-differential": stress.action_test_mixed_module_differential,
    "test-stress-minimization": stress.action_test_stress_minimization,
    "test-stress-crash-triage": stress.action_test_stress_crash_triage,
    "validate-stress": stress.action_validate_stress,
    "validate-stress-integration": stress.action_validate_stress_integration,
    "validate-stress-end-to-end": stress.action_validate_stress_end_to_end,
    "check-external-validation-surface": external_validation.action_check_external_validation_surface,
    "test-external-validation-replay": external_validation.action_test_external_validation_replay,
    "publish-external-repro-corpus": external_validation.action_publish_external_repro_corpus,
    "validate-external-validation": external_validation.action_validate_external_validation,
    "validate-external-validation-integration": external_validation.action_validate_external_validation_integration,
    "check-public-conformance-reporting-surface": release_governance.action_check_public_conformance_reporting_surface,
    "check-public-conformance-schema-surface": schema_surfaces.action_check_public_conformance_schema_surface,
    "build-public-conformance-scorecard": release_governance.action_build_public_conformance_scorecard,
    "publish-public-conformance-report": release_governance.action_publish_public_conformance_report,
    "validate-public-conformance-reporting": release_governance.action_validate_public_conformance_reporting,
    "validate-public-conformance-reporting-integration": release_governance.action_validate_public_conformance_reporting_integration,
    "validate-public-conformance-reporting-end-to-end": release_governance.action_validate_public_conformance_reporting_end_to_end,
    "check-performance-governance-surface": performance.action_check_performance_governance_surface,
    "check-performance-governance-schema-surface": performance.action_check_performance_governance_schema_surface,
    "build-performance-dashboard": performance.action_build_performance_dashboard,
    "publish-performance-report": performance.action_publish_performance_report,
    "validate-performance-governance": performance.action_validate_performance_governance,
    "validate-performance-governance-integration": performance.action_validate_performance_governance_integration,
    "validate-performance-governance-end-to-end": performance.action_validate_performance_governance_end_to_end,
    "check-release-foundation-surface": release_governance.action_check_release_foundation_surface,
    "check-release-foundation-schema-surface": schema_surfaces.action_check_release_foundation_schema_surface,
    "build-release-manifest": release_governance.action_build_release_manifest,
    "publish-release-provenance": release_governance.action_publish_release_provenance,
    "validate-release-foundation": release_governance.action_validate_release_foundation,
    "check-packaging-channels-surface": release_governance.action_check_packaging_channels_surface,
    "check-packaging-channels-schema-surface": schema_surfaces.action_check_packaging_channels_schema_surface,
    "build-package-channels": release_governance.action_build_package_channels,
    "build-platform-support-matrix": release_governance.action_build_platform_support_matrix,
    "validate-packaging-channels": release_governance.action_validate_packaging_channels,
    "validate-packaging-channels-end-to-end": release_governance.action_validate_packaging_channels_end_to_end,
    "validate-platform-hardening": release_governance.action_validate_platform_hardening,
    "validate-platform-hardening-end-to-end": release_governance.action_validate_platform_hardening_end_to_end,
    "check-release-operations-surface": release_governance.action_check_release_operations_surface,
    "check-release-operations-schema-surface": schema_surfaces.action_check_release_operations_schema_surface,
    "build-update-manifest": release_governance.action_build_update_manifest,
    "publish-release-operations": release_governance.action_publish_release_operations,
    "validate-release-operations": release_governance.action_validate_release_operations,
    "validate-release-operations-end-to-end": release_governance.action_validate_release_operations_end_to_end,
    "check-distribution-credibility-surface": release_governance.action_check_distribution_credibility_surface,
    "check-distribution-credibility-schema-surface": schema_surfaces.action_check_distribution_credibility_schema_surface,
    "build-distribution-credibility-dashboard": release_governance.action_build_distribution_credibility_dashboard,
    "publish-distribution-credibility": release_governance.action_publish_distribution_credibility,
    "validate-distribution-credibility": release_governance.action_validate_distribution_credibility,
    "validate-distribution-credibility-end-to-end": release_governance.action_validate_distribution_credibility_end_to_end,
    "check-security-hardening-surface": release_governance.action_check_security_hardening_surface,
    "check-security-hardening-schema-surface": schema_surfaces.action_check_security_hardening_schema_surface,
    "build-security-posture": release_governance.action_build_security_posture,
    "publish-security-advisories": release_governance.action_publish_security_advisories,
    "validate-security-hardening": release_governance.action_validate_security_hardening,
    "validate-security-hardening-end-to-end": release_governance.action_validate_security_hardening_end_to_end,
    "inspect-bonus-tool-integration": developer_tooling.action_inspect_bonus_tool_integration,
    "inspect-validation-timing": validation_timing.action_inspect_validation_timing,
    "materialize-project-template": developer_tooling.action_materialize_project_template,
    "materialize-canonical-application-workspace": application_surfaces.action_materialize_canonical_application_workspace,
    "trace-compile-stages": developer_tooling.action_trace_compile_stages,
    "test-capability-routed-source-parity": developer_tooling.action_test_capability_routed_source_parity,
    "validate-developer-tooling": developer_tooling.action_validate_developer_tooling,
    "validate-runnable-developer-tooling": developer_tooling.action_validate_runnable_developer_tooling,
    "validate-bonus-experiences": developer_tooling.action_validate_bonus_experiences,
    "validate-runnable-bonus-experiences": developer_tooling.action_validate_runnable_bonus_experiences,
    "validate-application-architecture": application_surfaces.action_validate_application_architecture,
    "validate-runnable-application-architecture": application_surfaces.action_validate_runnable_application_architecture,
    "build-package-lock": ecosystem_publication.action_build_package_lock,
    "validate-package-authoring": ecosystem_publication.action_validate_package_authoring,
    "validate-package-mirror": ecosystem_publication.action_validate_package_mirror,
    "validate-package-ecosystem": ecosystem_publication.action_validate_package_ecosystem,
    "validate-runnable-package-ecosystem": ecosystem_publication.action_validate_runnable_package_ecosystem,
    "validate-long-horizon-operations": ecosystem_publication.action_validate_long_horizon_operations,
    "publish-long-horizon-operations": ecosystem_publication.action_publish_long_horizon_operations,
    "validate-adoption-legibility": ecosystem_publication.action_validate_adoption_legibility,
    "publish-adoption-legibility": ecosystem_publication.action_publish_adoption_legibility,
    "validate-governance-sustainability": ecosystem_publication.action_validate_governance_sustainability,
    "publish-governance-sustainability": ecosystem_publication.action_publish_governance_sustainability,
    "publish-planning-issues": ecosystem_publication.action_publish_planning_issues,
    "check-planning-publication-drift": ecosystem_publication.action_check_planning_publication_drift,
    "lint-spec": hygiene.action_lint_spec,
    "test-default": action_test_default,
    "test-behavior-matrix": test_orchestration.action_test_behavior_matrix,
    "test-smoke": test_orchestration.action_test_smoke,
    "test-ci": test_orchestration.action_test_ci,
    "test-recovery": test_orchestration.action_test_recovery,
    "test-compile-wrapper-self-audit": test_orchestration.action_test_compile_wrapper_self_audit,
    "test-llvm-capability-routing": test_orchestration.action_test_llvm_capability_routing,
    "test-execution-smoke": test_orchestration.action_test_execution_smoke,
    "test-execution-replay": test_orchestration.action_test_execution_replay,
    "test-execution-replay-focused": test_orchestration.action_test_execution_replay_focused,
    "test-runtime-acceptance": runtime_tests.action_test_runtime_acceptance,
    "test-runtime-acceptance-fast": runtime_tests.action_test_runtime_acceptance_fast,
    "test-runtime-acceptance-diagnostics": runtime_tests.action_test_runtime_acceptance_diagnostics,
    "test-runtime-acceptance-cross-module": runtime_tests.action_test_runtime_acceptance_cross_module,
    "test-runtime-acceptance-block-arc": runtime_tests.action_test_runtime_acceptance_block_arc,
    "test-runtime-acceptance-concurrency": runtime_tests.action_test_runtime_acceptance_concurrency,
    "proof-runtime-architecture": runtime_tests.action_proof_runtime_architecture,
    "validate-runtime-architecture": runtime_tests.action_validate_runtime_architecture,
    "validate-runnable-bootstrap": runtime_tests.action_validate_runnable_bootstrap,
    "validate-block-arc-conformance": runtime_tests.action_validate_block_arc_conformance,
    "validate-runnable-block-arc": runtime_tests.action_validate_runnable_block_arc,
    "validate-concurrency-conformance": runtime_tests.action_validate_concurrency_conformance,
    "validate-runnable-concurrency": runtime_tests.action_validate_runnable_concurrency,
    "validate-object-model-conformance": runtime_tests.action_validate_object_model_conformance,
    "validate-storage-reflection-conformance": runtime_tests.action_validate_storage_reflection_conformance,
    "validate-runnable-object-model": runtime_tests.action_validate_runnable_object_model,
    "validate-runnable-storage-reflection": runtime_tests.action_validate_runnable_storage_reflection,
    "validate-error-conformance": runtime_tests.action_validate_error_conformance,
    "validate-runnable-error": runtime_tests.action_validate_runnable_error,
    "validate-interop-conformance": runtime_tests.action_validate_interop_conformance,
    "validate-runnable-interop": runtime_tests.action_validate_runnable_interop,
    "validate-metaprogramming-conformance": runtime_tests.action_validate_metaprogramming_conformance,
    "validate-runnable-metaprogramming": runtime_tests.action_validate_runnable_metaprogramming,
    "validate-release-candidate-conformance": runtime_tests.action_validate_release_candidate_conformance,
    "validate-runnable-release-candidate": runtime_tests.action_validate_runnable_release_candidate,
    "test-fixture-matrix": test_orchestration.action_test_fixture_matrix,
    "test-negative-expectations": test_orchestration.action_test_negative_expectations,
    "test-full": test_orchestration.action_test_full,
    "test-nightly": test_orchestration.action_test_nightly,
    "package-runnable-toolchain": native_build.action_package_runnable_toolchain,
    "proof-objc3c": native_build.action_proof_objc3c,
}
