"""Direct action handler dispatch for the objc3c workflow CLI."""

from __future__ import annotations

import sys
from collections.abc import Sequence
from dataclasses import asdict

from scripts.objc3c_workflow.action_spec import ActionHandler, ActionSpec
from scripts.objc3c_workflow.actions.application_surfaces import (
    action_check_showcase_surface,
    action_check_stdlib_surface,
    action_check_conformance_minima,
    action_materialize_canonical_application_workspace,
    action_materialize_stdlib_workspace,
    action_validate_application_architecture,
    action_validate_conformance_corpus,
    action_validate_getting_started,
    action_validate_runnable_application_architecture,
    action_validate_runnable_conformance_corpus,
    action_validate_runnable_showcase,
    action_validate_runnable_stdlib_advanced,
    action_validate_runnable_stdlib_foundation,
    action_validate_runnable_stdlib_program,
    action_validate_showcase,
    action_validate_showcase_runtime,
    action_validate_stdlib_advanced,
    action_validate_stdlib_foundation,
    action_validate_stdlib_program,
)
from scripts.objc3c_workflow.actions.developer_tooling import (
    action_check_llvm_capabilities,
    action_check_hosted_llvm_capabilities,
    action_format_objc3c,
    action_inspect_bonus_tool_integration,
    action_inspect_capability_explorer,
    action_inspect_compile_observability,
    action_inspect_editor_tooling,
    action_inspect_playground_repro,
    action_inspect_runtime_inspector,
    action_materialize_playground_workspace,
    action_materialize_project_template,
    action_trace_compile_stages,
    action_test_capability_routed_source_parity,
    action_validate_bonus_experiences,
    action_validate_developer_tooling,
    action_validate_runnable_bonus_experiences,
    action_validate_runnable_developer_tooling,
)
from scripts.objc3c_workflow.actions.docs import (
    action_build_native_docs,
    action_build_public_command_contract,
    action_build_public_command_surface,
    action_build_site,
    action_check_documentation_surface,
    action_check_markdown,
    action_check_native_docs,
    action_check_public_command_budget,
    action_check_public_command_contract,
    action_check_public_command_surface,
    action_check_site,
    action_format_markdown,
    action_lint_markdown,
    action_validate_documentation_surface,
)
from scripts.objc3c_workflow.actions.ecosystem_publication import (
    action_build_package_lock,
    action_check_planning_publication_drift,
    action_publish_adoption_legibility,
    action_publish_governance_sustainability,
    action_publish_long_horizon_operations,
    action_publish_planning_issues,
    action_validate_adoption_legibility,
    action_validate_governance_sustainability,
    action_validate_long_horizon_operations,
    action_validate_package_authoring,
    action_validate_package_ecosystem,
    action_validate_package_mirror,
    action_validate_runnable_package_ecosystem,
)
from scripts.objc3c_workflow.actions.external_validation import (
    action_check_external_validation_surface,
    action_publish_external_repro_corpus,
    action_test_external_validation_replay,
    action_validate_external_validation,
    action_validate_external_validation_integration,
)
from scripts.objc3c_workflow.actions.hygiene import (
    action_check_dependency_boundaries,
    action_check_release_evidence,
    action_check_repo_superclean_surface,
    action_check_source_hygiene_authenticity,
    action_check_source_hygiene_hard_cutover,
    action_check_task_hygiene,
    action_lint,
    action_lint_spec,
    action_validate_repo_superclean,
)
from scripts.objc3c_workflow.actions.native_build import (
    action_build_native_binaries,
    action_build_native_contracts,
    action_build_native_full,
    action_build_native_reconfigure,
    action_compile_objc3c,
    action_package_runnable_toolchain,
    action_proof_objc3c,
)
from scripts.objc3c_workflow.actions.performance import (
    action_benchmark_comparative_baselines,
    action_benchmark_compiler_throughput,
    action_benchmark_performance,
    action_benchmark_runtime_inspector,
    action_benchmark_runtime_performance,
    action_build_performance_dashboard,
    action_check_performance_governance_schema_surface,
    action_check_performance_governance_surface,
    action_publish_performance_report,
    action_validate_compiler_throughput,
    action_validate_performance_foundation,
    action_validate_performance_governance,
    action_validate_performance_governance_end_to_end,
    action_validate_performance_governance_integration,
    action_validate_runnable_compiler_throughput,
    action_validate_runnable_performance,
    action_validate_runnable_runtime_performance,
    action_validate_runtime_performance,
)
from scripts.objc3c_workflow.actions.release_governance import (
    action_build_distribution_credibility_dashboard,
    action_build_package_channels,
    action_build_platform_support_matrix,
    action_build_public_conformance_scorecard,
    action_build_release_manifest,
    action_build_security_posture,
    action_build_update_manifest,
    action_check_distribution_credibility_surface,
    action_check_packaging_channels_surface,
    action_check_public_conformance_reporting_surface,
    action_check_release_foundation_surface,
    action_check_release_operations_surface,
    action_check_security_hardening_surface,
    action_publish_distribution_credibility,
    action_publish_public_conformance_report,
    action_publish_release_operations,
    action_publish_release_provenance,
    action_publish_security_advisories,
    action_validate_distribution_credibility,
    action_validate_distribution_credibility_end_to_end,
    action_validate_packaging_channels,
    action_validate_packaging_channels_end_to_end,
    action_validate_platform_hardening,
    action_validate_platform_hardening_end_to_end,
    action_validate_public_conformance_reporting,
    action_validate_public_conformance_reporting_end_to_end,
    action_validate_public_conformance_reporting_integration,
    action_validate_release_foundation,
    action_validate_release_operations,
    action_validate_release_operations_end_to_end,
    action_validate_security_hardening,
    action_validate_security_hardening_end_to_end,
)
from scripts.objc3c_workflow.actions.runtime_tests import (
    action_proof_runtime_architecture,
    action_test_runtime_acceptance,
    action_test_runtime_acceptance_block_arc,
    action_test_runtime_acceptance_concurrency,
    action_test_runtime_acceptance_cross_module,
    action_test_runtime_acceptance_diagnostics,
    action_test_runtime_acceptance_fast,
    action_validate_block_arc_conformance,
    action_validate_concurrency_conformance,
    action_validate_error_conformance,
    action_validate_interop_conformance,
    action_validate_metaprogramming_conformance,
    action_validate_object_model_conformance,
    action_validate_release_candidate_conformance,
    action_validate_runnable_block_arc,
    action_validate_runnable_bootstrap,
    action_validate_runnable_concurrency,
    action_validate_runnable_error,
    action_validate_runnable_interop,
    action_validate_runnable_metaprogramming,
    action_validate_runnable_object_model,
    action_validate_runnable_release_candidate,
    action_validate_runnable_storage_reflection,
    action_validate_runtime_architecture,
    action_validate_storage_reflection_conformance,
)
from scripts.objc3c_workflow.actions.schema_surfaces import (
    action_check_distribution_credibility_schema_surface,
    action_check_packaging_channels_schema_surface,
    action_check_public_conformance_schema_surface,
    action_check_release_foundation_schema_surface,
    action_check_release_operations_schema_surface,
    action_check_security_hardening_schema_surface,
)
from scripts.objc3c_workflow.actions.stress import (
    action_check_stress_surface,
    action_test_fuzz_safety,
    action_test_lowering_runtime_stress,
    action_test_mixed_module_differential,
    action_test_stress_crash_triage,
    action_test_stress_minimization,
    action_validate_stress,
    action_validate_stress_end_to_end,
    action_validate_stress_integration,
)
from scripts.objc3c_workflow.actions.test_orchestration import (
    action_test_behavior_matrix,
    action_test_ci,
    action_test_compile_wrapper_self_audit,
    action_test_execution_replay,
    action_test_execution_replay_focused,
    action_test_execution_smoke,
    action_test_fixture_matrix,
    action_test_llvm_capability_routing,
    action_test_full,
    action_test_negative_expectations,
    action_test_nightly,
    action_test_recovery,
    action_test_smoke,
)
from scripts.objc3c_workflow.actions.validation_timing import (
    action_inspect_validation_timing,
)
from scripts.objc3c_workflow.environment import (
    WORKFLOW_RUNNER_MODE,
    WORKFLOW_RUNNER_SURFACE,
)
from scripts.objc3c_workflow.npm_surface import describe_package_script_payload
from scripts.objc3c_workflow.registry import ACTION_SPECS


def run_registered_steps(actions: Sequence[str]) -> int:
    for action in actions:
        rc = execute_registered_action(action, [])
        if rc != 0:
            return rc
    return 0


def action_build_default(_: list[str]) -> int:
    return run_registered_steps(["build-native-binaries"])


def action_test_default(_: list[str]) -> int:
    return run_registered_steps(["test-smoke"])


ACTION_HANDLERS: dict[str, ActionHandler] = {
    "build-default": action_build_default,
    "build-native-binaries": action_build_native_binaries,
    "build-native-contracts": action_build_native_contracts,
    "build-native-full": action_build_native_full,
    "build-native-reconfigure": action_build_native_reconfigure,
    "build-site": action_build_site,
    "check-site": action_check_site,
    "build-native-docs": action_build_native_docs,
    "check-native-docs": action_check_native_docs,
    "build-public-command-surface": action_build_public_command_surface,
    "check-public-command-surface": action_check_public_command_surface,
    "build-public-command-contract": action_build_public_command_contract,
    "check-public-command-contract": action_check_public_command_contract,
    "check-public-command-budget": action_check_public_command_budget,
    "check-documentation-surface": action_check_documentation_surface,
    "check-markdown": action_check_markdown,
    "format-markdown": action_format_markdown,
    "lint-markdown": action_lint_markdown,
    "lint": action_lint,
    "check-dependency-boundaries": action_check_dependency_boundaries,
    "check-llvm-capabilities": action_check_llvm_capabilities,
    "check-hosted-llvm-capabilities": action_check_hosted_llvm_capabilities,
    "check-release-evidence": action_check_release_evidence,
    "check-source-hygiene-authenticity": action_check_source_hygiene_authenticity,
    "check-source-hygiene-hard-cutover": action_check_source_hygiene_hard_cutover,
    "check-task-hygiene": action_check_task_hygiene,
    "check-showcase-surface": action_check_showcase_surface,
    "check-stdlib-surface": action_check_stdlib_surface,
    "validate-showcase-runtime": action_validate_showcase_runtime,
    "validate-showcase": action_validate_showcase,
    "validate-runnable-showcase": action_validate_runnable_showcase,
    "validate-getting-started": action_validate_getting_started,
    "check-repo-superclean-surface": action_check_repo_superclean_surface,
    "validate-documentation-surface": action_validate_documentation_surface,
    "validate-repo-superclean": action_validate_repo_superclean,
    "compile-objc3c": action_compile_objc3c,
    "materialize-playground-workspace": action_materialize_playground_workspace,
    "materialize-stdlib-workspace": action_materialize_stdlib_workspace,
    "validate-stdlib-foundation": action_validate_stdlib_foundation,
    "validate-stdlib-advanced": action_validate_stdlib_advanced,
    "validate-stdlib-program": action_validate_stdlib_program,
    "validate-runnable-stdlib-advanced": action_validate_runnable_stdlib_advanced,
    "validate-runnable-stdlib-foundation": action_validate_runnable_stdlib_foundation,
    "validate-runnable-stdlib-program": action_validate_runnable_stdlib_program,
    "inspect-capability-explorer": action_inspect_capability_explorer,
    "inspect-playground-repro": action_inspect_playground_repro,
    "inspect-compile-observability": action_inspect_compile_observability,
    "inspect-runtime-inspector": action_inspect_runtime_inspector,
    "inspect-editor-tooling": action_inspect_editor_tooling,
    "format-objc3c": action_format_objc3c,
    "benchmark-runtime-inspector": action_benchmark_runtime_inspector,
    "benchmark-performance": action_benchmark_performance,
    "benchmark-runtime-performance": action_benchmark_runtime_performance,
    "benchmark-compiler-throughput": action_benchmark_compiler_throughput,
    "validate-compiler-throughput": action_validate_compiler_throughput,
    "validate-runnable-compiler-throughput": action_validate_runnable_compiler_throughput,
    "validate-runtime-performance": action_validate_runtime_performance,
    "validate-runnable-runtime-performance": action_validate_runnable_runtime_performance,
    "benchmark-comparative-baselines": action_benchmark_comparative_baselines,
    "validate-runnable-performance": action_validate_runnable_performance,
    "validate-performance-foundation": action_validate_performance_foundation,
    "validate-conformance-corpus": action_validate_conformance_corpus,
    "check-conformance-minima": action_check_conformance_minima,
    "validate-runnable-conformance-corpus": action_validate_runnable_conformance_corpus,
    "check-stress-surface": action_check_stress_surface,
    "test-fuzz-safety": action_test_fuzz_safety,
    "test-lowering-runtime-stress": action_test_lowering_runtime_stress,
    "test-mixed-module-differential": action_test_mixed_module_differential,
    "test-stress-minimization": action_test_stress_minimization,
    "test-stress-crash-triage": action_test_stress_crash_triage,
    "validate-stress": action_validate_stress,
    "validate-stress-integration": action_validate_stress_integration,
    "validate-stress-end-to-end": action_validate_stress_end_to_end,
    "check-external-validation-surface": action_check_external_validation_surface,
    "test-external-validation-replay": action_test_external_validation_replay,
    "publish-external-repro-corpus": action_publish_external_repro_corpus,
    "validate-external-validation": action_validate_external_validation,
    "validate-external-validation-integration": action_validate_external_validation_integration,
    "check-public-conformance-reporting-surface": action_check_public_conformance_reporting_surface,
    "check-public-conformance-schema-surface": action_check_public_conformance_schema_surface,
    "build-public-conformance-scorecard": action_build_public_conformance_scorecard,
    "publish-public-conformance-report": action_publish_public_conformance_report,
    "validate-public-conformance-reporting": action_validate_public_conformance_reporting,
    "validate-public-conformance-reporting-integration": action_validate_public_conformance_reporting_integration,
    "validate-public-conformance-reporting-end-to-end": action_validate_public_conformance_reporting_end_to_end,
    "check-performance-governance-surface": action_check_performance_governance_surface,
    "check-performance-governance-schema-surface": action_check_performance_governance_schema_surface,
    "build-performance-dashboard": action_build_performance_dashboard,
    "publish-performance-report": action_publish_performance_report,
    "validate-performance-governance": action_validate_performance_governance,
    "validate-performance-governance-integration": action_validate_performance_governance_integration,
    "validate-performance-governance-end-to-end": action_validate_performance_governance_end_to_end,
    "check-release-foundation-surface": action_check_release_foundation_surface,
    "check-release-foundation-schema-surface": action_check_release_foundation_schema_surface,
    "build-release-manifest": action_build_release_manifest,
    "publish-release-provenance": action_publish_release_provenance,
    "validate-release-foundation": action_validate_release_foundation,
    "check-packaging-channels-surface": action_check_packaging_channels_surface,
    "check-packaging-channels-schema-surface": action_check_packaging_channels_schema_surface,
    "build-package-channels": action_build_package_channels,
    "build-platform-support-matrix": action_build_platform_support_matrix,
    "validate-packaging-channels": action_validate_packaging_channels,
    "validate-packaging-channels-end-to-end": action_validate_packaging_channels_end_to_end,
    "validate-platform-hardening": action_validate_platform_hardening,
    "validate-platform-hardening-end-to-end": action_validate_platform_hardening_end_to_end,
    "check-release-operations-surface": action_check_release_operations_surface,
    "check-release-operations-schema-surface": action_check_release_operations_schema_surface,
    "build-update-manifest": action_build_update_manifest,
    "publish-release-operations": action_publish_release_operations,
    "validate-release-operations": action_validate_release_operations,
    "validate-release-operations-end-to-end": action_validate_release_operations_end_to_end,
    "check-distribution-credibility-surface": action_check_distribution_credibility_surface,
    "check-distribution-credibility-schema-surface": action_check_distribution_credibility_schema_surface,
    "build-distribution-credibility-dashboard": action_build_distribution_credibility_dashboard,
    "publish-distribution-credibility": action_publish_distribution_credibility,
    "validate-distribution-credibility": action_validate_distribution_credibility,
    "validate-distribution-credibility-end-to-end": action_validate_distribution_credibility_end_to_end,
    "check-security-hardening-surface": action_check_security_hardening_surface,
    "check-security-hardening-schema-surface": action_check_security_hardening_schema_surface,
    "build-security-posture": action_build_security_posture,
    "publish-security-advisories": action_publish_security_advisories,
    "validate-security-hardening": action_validate_security_hardening,
    "validate-security-hardening-end-to-end": action_validate_security_hardening_end_to_end,
    "inspect-bonus-tool-integration": action_inspect_bonus_tool_integration,
    "inspect-validation-timing": action_inspect_validation_timing,
    "materialize-project-template": action_materialize_project_template,
    "materialize-canonical-application-workspace": action_materialize_canonical_application_workspace,
    "trace-compile-stages": action_trace_compile_stages,
    "test-capability-routed-source-parity": action_test_capability_routed_source_parity,
    "validate-developer-tooling": action_validate_developer_tooling,
    "validate-runnable-developer-tooling": action_validate_runnable_developer_tooling,
    "validate-bonus-experiences": action_validate_bonus_experiences,
    "validate-runnable-bonus-experiences": action_validate_runnable_bonus_experiences,
    "validate-application-architecture": action_validate_application_architecture,
    "validate-runnable-application-architecture": action_validate_runnable_application_architecture,
    "build-package-lock": action_build_package_lock,
    "validate-package-authoring": action_validate_package_authoring,
    "validate-package-mirror": action_validate_package_mirror,
    "validate-package-ecosystem": action_validate_package_ecosystem,
    "validate-runnable-package-ecosystem": action_validate_runnable_package_ecosystem,
    "validate-long-horizon-operations": action_validate_long_horizon_operations,
    "publish-long-horizon-operations": action_publish_long_horizon_operations,
    "validate-adoption-legibility": action_validate_adoption_legibility,
    "publish-adoption-legibility": action_publish_adoption_legibility,
    "validate-governance-sustainability": action_validate_governance_sustainability,
    "publish-governance-sustainability": action_publish_governance_sustainability,
    "publish-planning-issues": action_publish_planning_issues,
    "check-planning-publication-drift": action_check_planning_publication_drift,
    "lint-spec": action_lint_spec,
    "test-default": action_test_default,
    "test-behavior-matrix": action_test_behavior_matrix,
    "test-smoke": action_test_smoke,
    "test-ci": action_test_ci,
    "test-recovery": action_test_recovery,
    "test-compile-wrapper-self-audit": action_test_compile_wrapper_self_audit,
    "test-llvm-capability-routing": action_test_llvm_capability_routing,
    "test-execution-smoke": action_test_execution_smoke,
    "test-execution-replay": action_test_execution_replay,
    "test-execution-replay-focused": action_test_execution_replay_focused,
    "test-runtime-acceptance": action_test_runtime_acceptance,
    "test-runtime-acceptance-fast": action_test_runtime_acceptance_fast,
    "test-runtime-acceptance-diagnostics": action_test_runtime_acceptance_diagnostics,
    "test-runtime-acceptance-cross-module": action_test_runtime_acceptance_cross_module,
    "test-runtime-acceptance-block-arc": action_test_runtime_acceptance_block_arc,
    "test-runtime-acceptance-concurrency": action_test_runtime_acceptance_concurrency,
    "proof-runtime-architecture": action_proof_runtime_architecture,
    "validate-runtime-architecture": action_validate_runtime_architecture,
    "validate-runnable-bootstrap": action_validate_runnable_bootstrap,
    "validate-block-arc-conformance": action_validate_block_arc_conformance,
    "validate-runnable-block-arc": action_validate_runnable_block_arc,
    "validate-concurrency-conformance": action_validate_concurrency_conformance,
    "validate-runnable-concurrency": action_validate_runnable_concurrency,
    "validate-object-model-conformance": action_validate_object_model_conformance,
    "validate-storage-reflection-conformance": action_validate_storage_reflection_conformance,
    "validate-runnable-object-model": action_validate_runnable_object_model,
    "validate-runnable-storage-reflection": action_validate_runnable_storage_reflection,
    "validate-error-conformance": action_validate_error_conformance,
    "validate-runnable-error": action_validate_runnable_error,
    "validate-interop-conformance": action_validate_interop_conformance,
    "validate-runnable-interop": action_validate_runnable_interop,
    "validate-metaprogramming-conformance": action_validate_metaprogramming_conformance,
    "validate-runnable-metaprogramming": action_validate_runnable_metaprogramming,
    "validate-release-candidate-conformance": action_validate_release_candidate_conformance,
    "validate-runnable-release-candidate": action_validate_runnable_release_candidate,
    "test-fixture-matrix": action_test_fixture_matrix,
    "test-negative-expectations": action_test_negative_expectations,
    "test-full": action_test_full,
    "test-nightly": action_test_nightly,
    "package-runnable-toolchain": action_package_runnable_toolchain,
    "proof-objc3c": action_proof_objc3c,
}


def enrich_action_payload(spec: ActionSpec) -> dict[str, object]:
    payload = asdict(spec)
    payload["mode"] = WORKFLOW_RUNNER_MODE
    payload["runner_path"] = WORKFLOW_RUNNER_SURFACE
    payload["category"] = spec.action.split("-", 1)[0]
    return payload


def list_actions_payload() -> dict[str, object]:
    return {
        "mode": WORKFLOW_RUNNER_MODE,
        "runner_path": WORKFLOW_RUNNER_SURFACE,
        "action_count": len(ACTION_SPECS),
        "public_action_count": len(ACTION_SPECS),
        "internal_action_count": 0,
        "package_bridge_count": 1,
        "actions": [enrich_action_payload(spec) for spec in ACTION_SPECS.values()],
    }


def describe_action_payload(action: str) -> dict[str, object]:
    return enrich_action_payload(ACTION_SPECS[action])


def execute_registered_action(action: str, rest: list[str]) -> int:
    spec = ACTION_SPECS.get(action)
    handler = ACTION_HANDLERS.get(action)
    if spec is None or handler is None:
        print(f"unknown action: {action}", file=sys.stderr)
        return 2
    if rest and not spec.pass_through_args:
        print(f"action does not accept extra arguments: {action}", file=sys.stderr)
        return 2
    return handler(rest)
