"""Conformance, stress, and external-validation action specs."""

from __future__ import annotations

from .action_spec import ActionSpec

CONFORMANCE_STRESS_ACTION_SPECS: dict[str, ActionSpec] = {
    "validate-conformance-corpus": ActionSpec("validate-conformance-corpus", "run the integrated conformance corpus taxonomy indexing and current gate-surface validation flow", "python:scripts/check_objc3c_conformance_corpus_integration.py", validation_tier="repo", guarantee_owner="conformance corpus taxonomy, retained longitudinal suites, coverage indexing, and current gate surfaces stay executable on the live public workflow"),
    "check-conformance-minima": ActionSpec("check-conformance-minima", "verify conformance suite minima and required families", "pwsh:scripts/check_conformance_suite.ps1", validation_tier="ci", guarantee_owner="conformance minima stay routed through the public workflow bridge"),
    "validate-runnable-conformance-corpus": ActionSpec("validate-runnable-conformance-corpus", "validate the staged runnable conformance corpus package surface end to end", "python:scripts/check_objc3c_runnable_conformance_corpus_end_to_end.py", validation_tier="full", guarantee_owner="packaged conformance corpus contracts, retained longitudinal suites, and current gate surfaces stay reproducible from the staged runnable toolchain bundle"),
    "check-stress-surface": ActionSpec("check-stress-surface", "validate the checked-in fuzz, stress, minimization, and triage source surface", "python:scripts/check_stress_source_surface.py", validation_tier="repo", guarantee_owner="stress source roots, machine-owned artifact boundaries, and checked-in minimization contracts stay explicit and coherent"),
    "test-fuzz-safety": ActionSpec("test-fuzz-safety", "run the deterministic malformed-input parser/sema stress gate", "python:scripts/run_objc3c_fuzz_safety.py", validation_tier="repo", guarantee_owner="malformed parser/sema inputs stay fail-closed and deterministic through the live compiler path", pass_through_args=True),
    "test-lowering-runtime-stress": ActionSpec("test-lowering-runtime-stress", "run the bounded lowering/runtime stress harness over checked-in fixtures", "python:scripts/run_objc3c_lowering_runtime_stress.py", validation_tier="repo", guarantee_owner="lowering-heavy compile paths and execution-smoke subsets stay runnable through the live compiler and runtime path", pass_through_args=True),
    "test-mixed-module-differential": ActionSpec("test-mixed-module-differential", "run mixed-module and import/export differential stress validation", "python:scripts/run_objc3c_mixed_module_differential.py", validation_tier="repo", guarantee_owner="provider-consumer import/export and mixed-image surfaces stay executable on the live runtime acceptance path", pass_through_args=True),
    "test-stress-minimization": ActionSpec("test-stress-minimization", "reduce failing checked-in malformed inputs into machine-owned replay capsules", "python:scripts/run_objc3c_stress_minimization.py", validation_tier="repo", guarantee_owner="deterministic reducer output stays tied to checked-in failing inputs and live compiler signatures", pass_through_args=True),
    "test-stress-crash-triage": ActionSpec("test-stress-crash-triage", "build crash-signature triage indexes and replay requests from minimized stress cases", "python:scripts/run_objc3c_stress_crash_triage.py", validation_tier="repo", guarantee_owner="crash-signature grouping and replay requests stay derived from machine-owned minimized stress artifacts", pass_through_args=True),
    "validate-stress": ActionSpec("validate-stress", "run the integrated fuzz, stress, reducer, and crash-triage workflow", "runner-internal stress validation child actions", validation_tier="repo", guarantee_owner="checked-in stress roots, deterministic malformed-input coverage, mixed-module differential validation, reducer output, and crash-triage indexes stay executable on the live workflow"),
    "validate-stress-integration": ActionSpec("validate-stress-integration", "validate the integrated stress workflow report and child artifact set", "python:scripts/check_objc3c_stress_integration.py", validation_tier="repo", guarantee_owner="integrated stress workflow reports stay coherent across source-surface, differential, minimization, and crash-triage outputs"),
    "validate-stress-end-to-end": ActionSpec("validate-stress-end-to-end", "validate the public end-to-end stress workflow, command appendix, and nightly wiring", "python:scripts/check_objc3c_stress_end_to_end.py", validation_tier="repo", guarantee_owner="public stress workflow entrypoints and nightly wiring stay coherent with the integrated stress report set"),
    "check-external-validation-surface": ActionSpec("check-external-validation-surface", "validate the checked-in external-validation source, trust, intake, quarantine, and artifact contracts", "python:scripts/check_external_validation_source_surface.py", validation_tier="repo", guarantee_owner="external validation stays rooted in checked-in trust, intake, quarantine, and artifact contracts"),
    "test-external-validation-replay": ActionSpec("test-external-validation-replay", "run accepted external-validation entries through the live replay proof scripts", "python:scripts/run_objc3c_external_validation_replay.py", validation_tier="repo", guarantee_owner="accepted external evidence keeps replaying through the live parser and execution proof surfaces"),
    "publish-external-repro-corpus": ActionSpec("publish-external-repro-corpus", "materialize the machine-owned external repro corpus publication artifact", "python:scripts/publish_objc3c_external_repro_corpus.py", validation_tier="repo", guarantee_owner="accepted and quarantined external evidence stays publishable as a machine-owned corpus summary rooted in the replay drill"),
    "validate-external-validation": ActionSpec("validate-external-validation", "run the integrated external-validation source, replay, and publication drill", "runner-internal external-validation child actions", validation_tier="repo", guarantee_owner="external evidence intake, replay, and publication stay executable on the live workflow"),
    "validate-external-validation-integration": ActionSpec("validate-external-validation-integration", "validate the integrated external-validation report and child artifact set", "python:scripts/check_objc3c_external_validation_integration.py", validation_tier="repo", guarantee_owner="integrated external-validation reports stay coherent across source-surface, replay, and publication outputs"),
}
