"""Core build, docs, hygiene, and command-surface action specs."""

from __future__ import annotations

from .action_spec import ActionSpec

CORE_ACTION_SPECS: dict[str, ActionSpec] = {
    "build-default": ActionSpec("build-default", "default public build entrypoint", "runner-internal"),
    "build-native-binaries": ActionSpec("build-native-binaries", "build native binaries", "pwsh:scripts/build_objc3c_native.ps1"),
    "build-native-contracts": ActionSpec("build-native-contracts", "build native contracts/binaries contract-artifact surface", "pwsh:scripts/build_objc3c_native.ps1"),
    "build-native-full": ActionSpec("build-native-full", "run full native build", "pwsh:scripts/build_objc3c_native.ps1"),
    "build-native-reconfigure": ActionSpec("build-native-reconfigure", "force native reconfigure build", "pwsh:scripts/build_objc3c_native.ps1"),
    "build-site": ActionSpec("build-site", "build published site output and format it", "python:scripts/build_site_index.py + npx prettier"),
    "check-site": ActionSpec("check-site", "check generated site output for drift", "python:scripts/build_site_index.py --check", validation_tier="docs", guarantee_owner="published site index generation stays in sync with site/src inputs"),
    "build-native-docs": ActionSpec("build-native-docs", "build the generated native implementation docs", "python:scripts/build_objc3c_native_docs.py"),
    "check-native-docs": ActionSpec("check-native-docs", "check generated native implementation docs for drift", "python:scripts/build_objc3c_native_docs.py --check", validation_tier="docs", guarantee_owner="generated native implementation documentation stays in sync with docs/objc3c-native/src inputs"),
    "build-public-command-surface": ActionSpec("build-public-command-surface", "build the generated public command-surface appendix", "python:scripts/render_objc3c_public_command_surface.py"),
    "check-public-command-surface": ActionSpec("check-public-command-surface", "check the generated public command-surface appendix for drift", "python:scripts/render_objc3c_public_command_surface.py --check", validation_tier="docs", guarantee_owner="operator-facing machine appendix stays in sync with the live workflow runner and package scripts"),
    "build-public-command-contract": ActionSpec("build-public-command-contract", "build the canonical public command contract artifact", "python:scripts/build_objc3c_public_command_contract.py"),
    "check-public-command-contract": ActionSpec("check-public-command-contract", "check the canonical public command contract artifact for drift", "python:scripts/build_objc3c_public_command_contract.py --check"),
    "check-public-command-budget": ActionSpec("check-public-command-budget", "check the public command budget and appendix sync against the canonical command contract", "python:scripts/check_objc3c_public_command_budget.py"),
    "check-documentation-surface": ActionSpec("check-documentation-surface", "check the reader-facing documentation structure and machine-appendix boundary", "python:scripts/check_documentation_surface.py", validation_tier="docs", guarantee_owner="reader-facing onboarding, site structure, and machine-appendix boundary stay accessible and explicit"),
    "check-markdown": ActionSpec("check-markdown", "check markdown formatting drift across checked-in docs", "npx prettier --check <checked-in-md-globs>"),
    "format-markdown": ActionSpec("format-markdown", "rewrite markdown formatting across checked-in docs", "npx prettier --write <checked-in-md-globs>"),
    "lint-markdown": ActionSpec("lint-markdown", "run markdownlint across checked-in docs", "npx markdownlint-cli2 <checked-in-md-globs>"),
    "lint": ActionSpec("lint", "run the canonical maintainer lint workflow", "runner-internal + task hygiene + site build + markdown format check"),
    "check-dependency-boundaries": ActionSpec("check-dependency-boundaries", "check strict objc3c dependency boundaries", "python:scripts/check_objc3c_dependency_boundaries.py --strict", validation_tier="repo", guarantee_owner="repo dependency boundaries stay explicit and strict"),
    "check-llvm-capabilities": ActionSpec("check-llvm-capabilities", "probe llvm capability availability and write the summary artifact", "python:scripts/probe_objc3c_llvm_capabilities.py --summary-out tmp/artifacts/objc3c-native/llvm_capabilities/summary.json", validation_tier="repo", guarantee_owner="llvm capability probe output stays tied to the live toolchain environment"),
    "check-hosted-llvm-capabilities": ActionSpec("check-hosted-llvm-capabilities", "probe hosted-runner llvm capability availability with llc-unavailable tolerance", "python:scripts/probe_objc3c_llvm_capabilities.py --summary-out tmp/artifacts/objc3c-native/m144/llvm_capabilities/summary.json", validation_tier="ci", guarantee_owner="hosted Windows CI distinguishes missing clang failures from tolerated llc object-emission absence"),
    "check-release-evidence": ActionSpec("check-release-evidence", "check the generated-only release evidence surface", "python:scripts/check_release_evidence.py", validation_tier="repo", guarantee_owner="release evidence indexes stay coherent and replayable from schemas plus generated tmp artifacts"),
    "check-source-hygiene-authenticity": ActionSpec("check-source-hygiene-authenticity", "check source-hygiene residue removal, authenticity labeling, and genuine-output provenance against the live enforcement contract", "python:scripts/check_source_hygiene_authenticity.py", validation_tier="repo", guarantee_owner="product truth surfaces, synthetic fixtures, and genuine generated outputs stay mechanically distinguished and fail closed when provenance drifts"),
    "check-source-hygiene-hard-cutover": ActionSpec("check-source-hygiene-hard-cutover", "scan active source roots for hard-cutover forbidden residue, direct helper exposure, adapter wording, and generated-report residue", "python -m scripts.source_hygiene", validation_tier="repo", guarantee_owner="hard-cutover forbidden strings, direct helper exposure, and tracked generated reports fail closed as active hygiene blockers"),
    "check-task-hygiene": ActionSpec("check-task-hygiene", "run the task-hygiene gate over package scripts and checked-in roots", "python:scripts/ci/run_task_hygiene_gate.py", validation_tier="repo", guarantee_owner="task hygiene gate remains executable over the live repo script and path surface"),
    "check-showcase-surface": ActionSpec("check-showcase-surface", "check the live showcase portfolio and compile its example sources through the public compiler path", "python:scripts/check_showcase_surface.py", validation_tier="repo", guarantee_owner="showcase examples stay compile-coupled, checked in, and tied to the public compiler path", pass_through_args=True),
    "check-stdlib-surface": ActionSpec("check-stdlib-surface", "check the checked-in stdlib boundary contracts, canonical module inventory, package-name mapping, and lowering/import artifact contract", "python:scripts/check_stdlib_surface.py", validation_tier="repo", guarantee_owner="stdlib roots, canonical module inventory, package-name mapping, and lowering/import artifact contract stay checked in and coherent"),
    "validate-showcase-runtime": ActionSpec("validate-showcase-runtime", "compile, link, and run the checked-in showcase examples through the live runtime launch contract", "pwsh:scripts/check_showcase_runtime.ps1", validation_tier="repo", guarantee_owner="showcase examples stay runnable through the real runtime archive and launch-contract wiring", pass_through_args=True),
    "validate-showcase": ActionSpec("validate-showcase", "run the integrated showcase compile and runtime validation flow", "python:scripts/check_showcase_integration.py", validation_tier="repo", guarantee_owner="showcase examples stay compiled, runnable, and wired into the normal repo validation path"),
    "validate-runnable-showcase": ActionSpec("validate-runnable-showcase", "run packaged showcase compile link and execution validation from the staged runnable toolchain bundle", "python:scripts/check_objc3c_runnable_showcase_end_to_end.py", validation_tier="full", guarantee_owner="showcase examples stay publishable and runnable from the staged runnable toolchain bundle"),
    "validate-getting-started": ActionSpec("validate-getting-started", "run the integrated getting-started tutorial and onboarding validation flow", "python:scripts/check_getting_started_integration.py", validation_tier="repo", guarantee_owner="getting-started tutorials stay compile-coupled, runnable, and wired into the normal repo validation path"),
    "check-repo-superclean-surface": ActionSpec("check-repo-superclean-surface", "check the build-emitted repo superclean source-of-truth artifact", "python:scripts/check_repo_superclean_surface.py", validation_tier="repo", guarantee_owner="native build emits the canonical repo-cleanup roots, outputs, and command names as one source-of-truth artifact"),
    "validate-documentation-surface": ActionSpec("validate-documentation-surface", "run the full documentation build and reader-surface validation flow", "runner-internal + generated documentation checks", validation_tier="docs", guarantee_owner="site output, native docs, command appendix, and reader-facing onboarding remain buildable, in sync, and explicit"),
    "validate-repo-superclean": ActionSpec("validate-repo-superclean", "build the canonical repo surface and run the integrated hygiene/docs/superclean checks", "runner-internal + native build contracts + task hygiene gate", validation_tier="repo", guarantee_owner="repo roots, checked-in docs, generated outputs, and machine-owned boundaries remain canonical and enforced"),
    "compile-objc3c": ActionSpec("compile-objc3c", "compile one Objective-C 3 fixture through the native compiler", "pwsh:scripts/objc3c_native_compile.ps1", pass_through_args=True),
}
