"""Public conformance reporting and performance-governance action specs."""

from __future__ import annotations

from .action_spec import ActionSpec

PUBLIC_REPORTING_AND_PERFORMANCE_ACTION_SPECS: dict[str, ActionSpec] = {
    "check-public-conformance-reporting-surface": ActionSpec("check-public-conformance-reporting-surface", "validate the checked-in public-conformance reporting source and policy contracts", "python:scripts/check_public_conformance_reporting_source_surface.py", validation_tier="repo", guarantee_owner="public conformance reporting stays rooted in checked-in source, policy, and upstream evidence boundaries"),
    "check-public-conformance-schema-surface": ActionSpec("check-public-conformance-schema-surface", "validate the checked-in public-conformance schema surface", "python:scripts/check_public_conformance_schema_surface.py", validation_tier="repo", guarantee_owner="public conformance scorecard and summary outputs stay tied to checked-in schema contracts"),
    "build-public-conformance-scorecard": ActionSpec("build-public-conformance-scorecard", "derive the live public-conformance badge and stability score from upstream reports", "python:scripts/build_objc3c_public_conformance_scorecard.py", validation_tier="repo", guarantee_owner="public conformance scoring stays derived from live conformance and external-validation reports"),
    "publish-public-conformance-report": ActionSpec("publish-public-conformance-report", "materialize the machine-owned public-conformance summary and publication artifacts", "python:scripts/publish_objc3c_public_conformance_report.py", validation_tier="repo", guarantee_owner="public conformance summary and publication artifacts stay derived from the live scorecard and checked-in schema surface"),
    "validate-public-conformance-reporting": ActionSpec("validate-public-conformance-reporting", "run the integrated public-conformance reporting workflow", "runner-internal public-reporting child actions", validation_tier="repo", guarantee_owner="public conformance reporting source policy schema scorecard and publication flows stay executable on the live workflow"),
    "validate-public-conformance-reporting-integration": ActionSpec("validate-public-conformance-reporting-integration", "validate the integrated public-conformance reporting workflow report and child artifacts", "python:scripts/check_objc3c_public_conformance_reporting_integration.py", validation_tier="repo", guarantee_owner="integrated public conformance reporting artifacts stay coherent across source, schema, scorecard, and publication outputs"),
    "validate-public-conformance-reporting-end-to-end": ActionSpec("validate-public-conformance-reporting-end-to-end", "validate public-conformance reporting entrypoints, command-surface sync, and nightly wiring", "python:scripts/check_objc3c_public_conformance_reporting_end_to_end.py", validation_tier="repo", guarantee_owner="public conformance reporting entrypoints and nightly wiring stay coherent with the integrated reporting artifacts"),
    "check-performance-governance-surface": ActionSpec("check-performance-governance-surface", "validate the checked-in performance governance source surface", "python:scripts/check_performance_governance_source_surface.py", validation_tier="repo", guarantee_owner="performance governance only publishes from the checked-in benchmark, policy, and reporting sources"),
    "check-performance-governance-schema-surface": ActionSpec("check-performance-governance-schema-surface", "validate the checked-in performance governance schema surface", "python:scripts/check_performance_governance_schema_surface.py", validation_tier="repo", guarantee_owner="performance dashboard and public report artifacts stay on checked-in schema contracts"),
    "build-performance-dashboard": ActionSpec("build-performance-dashboard", "derive the live performance governance dashboard from checked-in budgets and live benchmark summaries", "python:scripts/build_objc3c_performance_dashboard.py", validation_tier="repo", guarantee_owner="performance governance dashboard derivation stays tied to the live benchmark, throughput, and runtime summaries"),
    "publish-performance-report": ActionSpec("publish-performance-report", "publish the live performance governance report artifacts and summary", "python:scripts/publish_objc3c_performance_report.py", validation_tier="repo", guarantee_owner="performance governance publication stays traceable to the checked-in policy contracts and live dashboard summary"),
    "validate-performance-governance": ActionSpec("validate-performance-governance", "run the integrated performance governance workflow", "runner-internal performance-governance child actions", validation_tier="repo", guarantee_owner="performance governance budgets, drift diagnostics, dashboard derivation, and report publication stay executable on the live performance surfaces"),
    "validate-performance-governance-integration": ActionSpec("validate-performance-governance-integration", "validate the integrated performance governance workflow report and child artifacts", "python:scripts/check_objc3c_performance_governance_integration.py", validation_tier="repo", guarantee_owner="integrated performance governance artifacts stay coherent across source, schema, dashboard, and publication outputs"),
    "validate-performance-governance-end-to-end": ActionSpec("validate-performance-governance-end-to-end", "validate performance governance entrypoints, command-surface sync, and ci/nightly wiring", "python:scripts/check_objc3c_performance_governance_end_to_end.py", validation_tier="repo", guarantee_owner="performance governance entrypoints and ci/nightly wiring stay coherent with the integrated reporting artifacts"),
}
