"""Core documentation validation action specs."""

from __future__ import annotations

from scripts.objc3c_workflow.actions.docs_documentation import (
    DOCUMENTATION_VALIDATION_GUARANTEE_OWNER,
    DOCUMENTATION_VALIDATION_TIER,
    VALIDATE_DOCUMENTATION_SURFACE_ACTION,
    VALIDATE_DOCUMENTATION_SURFACE_BACKEND,
    VALIDATE_DOCUMENTATION_SURFACE_SUMMARY,
)

from .action_spec import ActionSpec

CORE_DOCUMENTATION_VALIDATION_ACTION_SPECS: dict[str, ActionSpec] = {
    VALIDATE_DOCUMENTATION_SURFACE_ACTION: ActionSpec(
        VALIDATE_DOCUMENTATION_SURFACE_ACTION,
        VALIDATE_DOCUMENTATION_SURFACE_SUMMARY,
        VALIDATE_DOCUMENTATION_SURFACE_BACKEND,
        validation_tier=DOCUMENTATION_VALIDATION_TIER,
        guarantee_owner=DOCUMENTATION_VALIDATION_GUARANTEE_OWNER,
    ),
}

__all__ = ["CORE_DOCUMENTATION_VALIDATION_ACTION_SPECS"]
