"""Canonical public workflow bridge constants."""

from __future__ import annotations


WORKFLOW_MODULE = "scripts.objc3c_workflow"
WORKFLOW_BRIDGE_SCRIPT = "objc3c"
WORKFLOW_PUBLIC_COMMAND_PREFIX = f"npm run {WORKFLOW_BRIDGE_SCRIPT} --"
WORKFLOW_RUNNER_SURFACE = f"package.json scripts.{WORKFLOW_BRIDGE_SCRIPT} -> {WORKFLOW_MODULE}"
WORKFLOW_RUNNER_MODE = "objc3c-workflow-action-registry-v1"
PUBLIC_ENTRYPOINT_KIND = "single-npm-bridge"
WORKFLOW_PUBLIC_ACTION_TOKEN = "<action>"
WORKFLOW_PUBLIC_COMMAND_TEMPLATE = (
    f"{WORKFLOW_PUBLIC_COMMAND_PREFIX} {WORKFLOW_PUBLIC_ACTION_TOKEN}"
)
PACKAGE_BRIDGE_IDS = (WORKFLOW_BRIDGE_SCRIPT,)
PACKAGE_BRIDGE_INVOCATIONS = (WORKFLOW_PUBLIC_COMMAND_TEMPLATE,)
PUBLIC_BRIDGE_CAPABILITY_TRUTH_SCOPE = "workflow-public-bridge"
PUBLIC_BRIDGE_CONSTANTS_OWNER_SURFACE = (
    "scripts/objc3c_workflow/public_bridge_constants.py"
)
PUBLIC_BRIDGE_INVOCATION_OWNER_SURFACE = (
    "scripts/objc3c_workflow/public_bridge_invocation.py"
)
PUBLIC_BRIDGE_PAYLOAD_OWNER_SURFACE = (
    "scripts/objc3c_workflow/public_bridge_payloads.py"
)
PUBLIC_BRIDGE_REGISTRY_OWNER_SURFACE = (
    "scripts/objc3c_workflow/public_bridge_registry.py"
)


__all__ = [
    "PACKAGE_BRIDGE_IDS",
    "PACKAGE_BRIDGE_INVOCATIONS",
    "PUBLIC_ENTRYPOINT_KIND",
    "PUBLIC_BRIDGE_CAPABILITY_TRUTH_SCOPE",
    "PUBLIC_BRIDGE_CONSTANTS_OWNER_SURFACE",
    "PUBLIC_BRIDGE_INVOCATION_OWNER_SURFACE",
    "PUBLIC_BRIDGE_PAYLOAD_OWNER_SURFACE",
    "PUBLIC_BRIDGE_REGISTRY_OWNER_SURFACE",
    "WORKFLOW_BRIDGE_SCRIPT",
    "WORKFLOW_MODULE",
    "WORKFLOW_PUBLIC_ACTION_TOKEN",
    "WORKFLOW_PUBLIC_COMMAND_PREFIX",
    "WORKFLOW_PUBLIC_COMMAND_TEMPLATE",
    "WORKFLOW_RUNNER_MODE",
    "WORKFLOW_RUNNER_SURFACE",
]
