"""Public-conformance reporting workflow paths."""

from __future__ import annotations

from ..environment import ROOT
from .release_governance_public_conformance_contracts import (
    PUBLIC_CONFORMANCE_ARTIFACT_ROOT as PUBLIC_CONFORMANCE_ARTIFACT_ROOT_REL,
    PUBLIC_CONFORMANCE_END_TO_END_SCRIPT,
    PUBLIC_CONFORMANCE_END_TO_END_SUMMARY as PUBLIC_CONFORMANCE_END_TO_END_SUMMARY_REL,
    PUBLIC_CONFORMANCE_INTEGRATION_SCRIPT,
    PUBLIC_CONFORMANCE_INTEGRATION_SUMMARY as PUBLIC_CONFORMANCE_INTEGRATION_SUMMARY_REL,
    PUBLIC_CONFORMANCE_PUBLIC_SUMMARY as PUBLIC_CONFORMANCE_PUBLIC_SUMMARY_REL,
    PUBLIC_CONFORMANCE_PUBLISHED_BADGE as PUBLIC_CONFORMANCE_PUBLISHED_BADGE_REL,
    PUBLIC_CONFORMANCE_PUBLISHED_REPORT as PUBLIC_CONFORMANCE_PUBLISHED_REPORT_REL,
    PUBLIC_CONFORMANCE_PUBLISHED_SCORECARD as PUBLIC_CONFORMANCE_PUBLISHED_SCORECARD_REL,
    PUBLIC_CONFORMANCE_REPORT_ROOT as PUBLIC_CONFORMANCE_REPORT_ROOT_REL,
    PUBLIC_CONFORMANCE_REPORT_SCRIPT,
    PUBLIC_CONFORMANCE_SCHEMA_SUMMARY as PUBLIC_CONFORMANCE_SCHEMA_SUMMARY_REL,
    PUBLIC_CONFORMANCE_SCORECARD_SCRIPT,
    PUBLIC_CONFORMANCE_SCORECARD_SUMMARY as PUBLIC_CONFORMANCE_SCORECARD_SUMMARY_REL,
    PUBLIC_CONFORMANCE_SOURCE_CHECK_SCRIPT,
    PUBLIC_CONFORMANCE_SOURCE_SUMMARY as PUBLIC_CONFORMANCE_SOURCE_SUMMARY_REL,
)

PUBLIC_CONFORMANCE_SOURCE_SURFACE_PY = (
    ROOT / PUBLIC_CONFORMANCE_SOURCE_CHECK_SCRIPT
)
PUBLIC_CONFORMANCE_SCORECARD_PY = (
    ROOT / PUBLIC_CONFORMANCE_SCORECARD_SCRIPT
)
PUBLIC_CONFORMANCE_REPORT_PY = (
    ROOT / PUBLIC_CONFORMANCE_REPORT_SCRIPT
)
PUBLIC_CONFORMANCE_INTEGRATION_PY = (
    ROOT / PUBLIC_CONFORMANCE_INTEGRATION_SCRIPT
)
PUBLIC_CONFORMANCE_END_TO_END_PY = (
    ROOT / PUBLIC_CONFORMANCE_END_TO_END_SCRIPT
)

PUBLIC_CONFORMANCE_REPORT_ROOT = ROOT / PUBLIC_CONFORMANCE_REPORT_ROOT_REL
PUBLIC_CONFORMANCE_ARTIFACT_ROOT = ROOT / PUBLIC_CONFORMANCE_ARTIFACT_ROOT_REL
PUBLIC_CONFORMANCE_SOURCE_SUMMARY = ROOT / PUBLIC_CONFORMANCE_SOURCE_SUMMARY_REL
PUBLIC_CONFORMANCE_SCHEMA_SUMMARY = ROOT / PUBLIC_CONFORMANCE_SCHEMA_SUMMARY_REL
PUBLIC_CONFORMANCE_SCORECARD_SUMMARY = ROOT / PUBLIC_CONFORMANCE_SCORECARD_SUMMARY_REL
PUBLIC_CONFORMANCE_PUBLIC_SUMMARY = ROOT / PUBLIC_CONFORMANCE_PUBLIC_SUMMARY_REL
PUBLIC_CONFORMANCE_INTEGRATION_SUMMARY = ROOT / PUBLIC_CONFORMANCE_INTEGRATION_SUMMARY_REL
PUBLIC_CONFORMANCE_END_TO_END_SUMMARY = ROOT / PUBLIC_CONFORMANCE_END_TO_END_SUMMARY_REL
PUBLIC_CONFORMANCE_PUBLISHED_SCORECARD = ROOT / PUBLIC_CONFORMANCE_PUBLISHED_SCORECARD_REL
PUBLIC_CONFORMANCE_PUBLISHED_BADGE = ROOT / PUBLIC_CONFORMANCE_PUBLISHED_BADGE_REL
PUBLIC_CONFORMANCE_PUBLISHED_REPORT = ROOT / PUBLIC_CONFORMANCE_PUBLISHED_REPORT_REL
