"""Compatibility imports for the planning publication contract helpers."""

from __future__ import annotations

try:
    from planning_issue_publication_contracts import (
        REPORT_CONTRACT_ID,
        RELATIONSHIP_END,
        RELATIONSHIP_START,
        LabelDefinition,
        PublicationError,
        apply_relationship_section,
        build_dependency_report,
        build_dry_run_report,
        build_report,
        collect_dependencies,
        collect_label_definitions,
        dependencies_by_issue,
        issue_labels,
        issue_number,
        milestone_by_title,
        prior_dependency_statuses,
        render_relationship_section,
        require_dict,
        require_list,
        require_str,
        stable_label_color,
        utc_now,
        validate_existing_report,
        validate_payload,
    )
except ModuleNotFoundError:
    from scripts.planning_issue_publication_contracts import (
        REPORT_CONTRACT_ID,
        RELATIONSHIP_END,
        RELATIONSHIP_START,
        LabelDefinition,
        PublicationError,
        apply_relationship_section,
        build_dependency_report,
        build_dry_run_report,
        build_report,
        collect_dependencies,
        collect_label_definitions,
        dependencies_by_issue,
        issue_labels,
        issue_number,
        milestone_by_title,
        prior_dependency_statuses,
        render_relationship_section,
        require_dict,
        require_list,
        require_str,
        stable_label_color,
        utc_now,
        validate_existing_report,
        validate_payload,
    )

__all__ = [
    "REPORT_CONTRACT_ID",
    "RELATIONSHIP_END",
    "RELATIONSHIP_START",
    "LabelDefinition",
    "PublicationError",
    "apply_relationship_section",
    "build_dependency_report",
    "build_dry_run_report",
    "build_report",
    "collect_dependencies",
    "collect_label_definitions",
    "dependencies_by_issue",
    "issue_labels",
    "issue_number",
    "milestone_by_title",
    "prior_dependency_statuses",
    "render_relationship_section",
    "require_dict",
    "require_list",
    "require_str",
    "stable_label_color",
    "utc_now",
    "validate_existing_report",
    "validate_payload",
]
