objc3c_apply_build_defaults(objc3c_json)
objc3c_apply_llvm_direct_config(objc3c_json)

objc3c_apply_build_defaults(objc3c_io)
objc3c_apply_llvm_direct_config(objc3c_io)

objc3c_apply_build_defaults(objc3c_runtime_abi_process)
objc3c_apply_llvm_direct_config(objc3c_runtime_abi_process)

objc3c_apply_build_defaults(objc3c_runtime_abi_release_artifacts)
objc3c_apply_llvm_direct_config(objc3c_runtime_abi_release_artifacts)

objc3c_apply_build_defaults(objc3c_runtime_abi_cross_module)
objc3c_apply_llvm_direct_config(objc3c_runtime_abi_cross_module)

objc3c_apply_build_defaults(objc3c_runtime_abi_metadata)
objc3c_apply_llvm_direct_config(objc3c_runtime_abi_metadata)
